
from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np
import pandas as pd
import os
import operator
import csv

class DmgrGFAA5M(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.dataPath = None
        self.backfill = True
        self.open = NIO_CUBE()
        self.high = NIO_CUBE()
        self.low = NIO_CUBE()
        self.close = NIO_CUBE()
        self.volume = NIO_CUBE()
        self.trade_success_count = NIO_CUBE()
        self.trade_avg_price = NIO_CUBE()
        self.trade_min_price = NIO_CUBE()
        self.trade_max_price = NIO_CUBE()
        self.trade_std_price = NIO_CUBE()
        self.trade_price_p10 = NIO_CUBE()
        self.trade_price_p20 = NIO_CUBE()
        self.trade_price_p30 = NIO_CUBE()
        self.trade_price_p40 = NIO_CUBE()
        self.trade_price_p50 = NIO_CUBE()
        self.trade_price_p60 = NIO_CUBE()
        self.trade_price_p70 = NIO_CUBE()
        self.trade_price_p80 = NIO_CUBE()
        self.trade_price_p90 = NIO_CUBE()
        self.avg_volume = NIO_CUBE()
        self.max_volume = NIO_CUBE()
        self.min_volume = NIO_CUBE()
        self.std_volume = NIO_CUBE()
        self.trade_total_money = NIO_CUBE()
        self.trade_avg_money = NIO_CUBE()
        self.trade_max_money = NIO_CUBE()
        self.trade_min_money = NIO_CUBE()
        self.trade_first_interval_seconds = NIO_CUBE()
        self.trade_last_interval_seconds = NIO_CUBE()
        self.trade_avg_offer_interval_seconds = NIO_CUBE()
        self.trade_avg_bid_interval_seconds = NIO_CUBE()
        self.avg_bid_price = NIO_CUBE()
        self.min_bid_price = NIO_CUBE()
        self.max_bid_price = NIO_CUBE()
        self.avg_offer_price = NIO_CUBE()
        self.min_offer_price = NIO_CUBE()
        self.max_offer_price = NIO_CUBE()
        self.overbuy_count = NIO_CUBE()
        self.oversell_count = NIO_CUBE()
        self.overbuy_volume = NIO_CUBE()
        self.oversell_volume = NIO_CUBE()
        self.trade_cancel_count = NIO_CUBE()
        self.cancelled_volume = NIO_CUBE()
        self.cancelled_buy_trade_count = NIO_CUBE()
        self.cancelled_sell_trade_count = NIO_CUBE()
        self.order_total_volume = NIO_CUBE()
        self.order_total_money = NIO_CUBE()
        self.order_count = NIO_CUBE()
        self.order_buy_count = NIO_CUBE()
        self.order_sell_count = NIO_CUBE()
        self.order_avg_price = NIO_CUBE()
        self.order_min_price = NIO_CUBE()
        self.order_max_price = NIO_CUBE()
        self.std_price = NIO_CUBE()
        self.order_price_p10 = NIO_CUBE()
        self.order_price_p20 = NIO_CUBE()
        self.order_price_p30 = NIO_CUBE()
        self.order_price_p40 = NIO_CUBE()
        self.order_price_p50 = NIO_CUBE()
        self.order_price_p60 = NIO_CUBE()
        self.order_price_p70 = NIO_CUBE()
        self.order_price_p80 = NIO_CUBE()
        self.order_price_p90 = NIO_CUBE()
        self.order_avg_volume = NIO_CUBE()
        self.order_max_volume = NIO_CUBE()
        self.order_min_volume = NIO_CUBE()
        self.order_std_volume = NIO_CUBE()
        self.order_avg_money = NIO_CUBE()
        self.order_max_money = NIO_CUBE()
        self.order_min_money = NIO_CUBE()
        self.order_buy_volume = NIO_CUBE()
        self.order_buy_money = NIO_CUBE()
        self.order_avg_buy_price = NIO_CUBE()
        self.order_max_buy_price = NIO_CUBE()
        self.order_min_buy_price = NIO_CUBE()
        self.order_avg_buy_volume = NIO_CUBE()
        self.order_sell_volume = NIO_CUBE()
        self.order_sell_money = NIO_CUBE()
        self.order_avg_sell_price = NIO_CUBE()
        self.order_max_sell_price = NIO_CUBE()
        self.order_min_sell_price = NIO_CUBE()
        self.order_avg_sell_volume = NIO_CUBE()
        self.order_first_interval_seconds = NIO_CUBE()
        self.order_last_interval_seconds = NIO_CUBE()
        self.cancelled_order_total_volume = NIO_CUBE()
        self.cancelled_order_total_money = NIO_CUBE()
        self.pe1 = NIO_CUBE()
        self.up_limit_px = NIO_CUBE()
        self.down_limit_px = NIO_CUBE()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.dataPath = cfg.getAttributeString('dataPath')
        self.backfill = cfg.getAttributeDefault('backfill', False)
        self.addDailyData(self.open,self.tag + '.open')
        self.addDailyData(self.high,self.tag + '.high')
        self.addDailyData(self.low,self.tag + '.low')
        self.addDailyData(self.close,self.tag + '.close')
        self.addDailyData(self.volume,self.tag + '.volume')
        self.addDailyData(self.trade_success_count,self.tag + '.trade_success_count')
        self.addDailyData(self.trade_avg_price,self.tag + '.trade_avg_price')
        self.addDailyData(self.trade_min_price,self.tag + '.trade_min_price')
        self.addDailyData(self.trade_max_price,self.tag + '.trade_max_price')
        self.addDailyData(self.trade_std_price,self.tag + '.trade_std_price')
        self.addDailyData(self.trade_price_p10,self.tag + '.trade_price_p10')
        self.addDailyData(self.trade_price_p20,self.tag + '.trade_price_p20')
        self.addDailyData(self.trade_price_p30,self.tag + '.trade_price_p30')
        self.addDailyData(self.trade_price_p40,self.tag + '.trade_price_p40')
        self.addDailyData(self.trade_price_p50,self.tag + '.trade_price_p50')
        self.addDailyData(self.trade_price_p60,self.tag + '.trade_price_p60')
        self.addDailyData(self.trade_price_p70,self.tag + '.trade_price_p70')
        self.addDailyData(self.trade_price_p80,self.tag + '.trade_price_p80')
        self.addDailyData(self.trade_price_p90,self.tag + '.trade_price_p90')
        self.addDailyData(self.avg_volume,self.tag + '.avg_volume')
        self.addDailyData(self.max_volume,self.tag + '.max_volume')
        self.addDailyData(self.min_volume,self.tag + '.min_volume')
        self.addDailyData(self.std_volume,self.tag + '.std_volume')
        self.addDailyData(self.trade_total_money,self.tag + '.trade_total_money')
        self.addDailyData(self.trade_avg_money,self.tag + '.trade_avg_money')
        self.addDailyData(self.trade_max_money,self.tag + '.trade_max_money')
        self.addDailyData(self.trade_min_money,self.tag + '.trade_min_money')
        self.addDailyData(self.trade_first_interval_seconds,self.tag + '.trade_first_interval_seconds')
        self.addDailyData(self.trade_last_interval_seconds,self.tag + '.trade_last_interval_seconds')
        self.addDailyData(self.trade_avg_offer_interval_seconds,self.tag + '.trade_avg_offer_interval_seconds')
        self.addDailyData(self.trade_avg_bid_interval_seconds,self.tag + '.trade_avg_bid_interval_seconds')
        self.addDailyData(self.avg_bid_price,self.tag + '.avg_bid_price')
        self.addDailyData(self.min_bid_price,self.tag + '.min_bid_price')
        self.addDailyData(self.max_bid_price,self.tag + '.max_bid_price')
        self.addDailyData(self.avg_offer_price,self.tag + '.avg_offer_price')
        self.addDailyData(self.min_offer_price,self.tag + '.min_offer_price')
        self.addDailyData(self.max_offer_price,self.tag + '.max_offer_price')
        self.addDailyData(self.overbuy_count,self.tag + '.overbuy_count')
        self.addDailyData(self.oversell_count,self.tag + '.oversell_count')
        self.addDailyData(self.overbuy_volume,self.tag + '.overbuy_volume')
        self.addDailyData(self.oversell_volume,self.tag + '.oversell_volume')
        self.addDailyData(self.trade_cancel_count,self.tag + '.trade_cancel_count')
        self.addDailyData(self.cancelled_volume,self.tag + '.cancelled_volume')
        self.addDailyData(self.cancelled_buy_trade_count,self.tag + '.cancelled_buy_trade_count')
        self.addDailyData(self.cancelled_sell_trade_count,self.tag + '.cancelled_sell_trade_count')
        self.addDailyData(self.order_total_volume,self.tag + '.order_total_volume')
        self.addDailyData(self.order_total_money,self.tag + '.order_total_money')
        self.addDailyData(self.order_count,self.tag + '.order_count')
        self.addDailyData(self.order_buy_count,self.tag + '.order_buy_count')
        self.addDailyData(self.order_sell_count,self.tag + '.order_sell_count')
        self.addDailyData(self.order_avg_price,self.tag + '.order_avg_price')
        self.addDailyData(self.order_min_price,self.tag + '.order_min_price')
        self.addDailyData(self.order_max_price,self.tag + '.order_max_price')
        self.addDailyData(self.std_price,self.tag + '.std_price')
        self.addDailyData(self.order_price_p10,self.tag + '.order_price_p10')
        self.addDailyData(self.order_price_p20,self.tag + '.order_price_p20')
        self.addDailyData(self.order_price_p30,self.tag + '.order_price_p30')
        self.addDailyData(self.order_price_p40,self.tag + '.order_price_p40')
        self.addDailyData(self.order_price_p50,self.tag + '.order_price_p50')
        self.addDailyData(self.order_price_p60,self.tag + '.order_price_p60')
        self.addDailyData(self.order_price_p70,self.tag + '.order_price_p70')
        self.addDailyData(self.order_price_p80,self.tag + '.order_price_p80')
        self.addDailyData(self.order_price_p90,self.tag + '.order_price_p90')
        self.addDailyData(self.order_avg_volume,self.tag + '.order_avg_volume')
        self.addDailyData(self.order_max_volume,self.tag + '.order_max_volume')
        self.addDailyData(self.order_min_volume,self.tag + '.order_min_volume')
        self.addDailyData(self.order_std_volume,self.tag + '.order_std_volume')
        self.addDailyData(self.order_avg_money,self.tag + '.order_avg_money')
        self.addDailyData(self.order_max_money,self.tag + '.order_max_money')
        self.addDailyData(self.order_min_money,self.tag + '.order_min_money')
        self.addDailyData(self.order_buy_volume,self.tag + '.order_buy_volume')
        self.addDailyData(self.order_buy_money,self.tag + '.order_buy_money')
        self.addDailyData(self.order_avg_buy_price,self.tag + '.order_avg_buy_price')
        self.addDailyData(self.order_max_buy_price,self.tag + '.order_max_buy_price')
        self.addDailyData(self.order_min_buy_price,self.tag + '.order_min_buy_price')
        self.addDailyData(self.order_avg_buy_volume,self.tag + '.order_avg_buy_volume')
        self.addDailyData(self.order_sell_volume,self.tag + '.order_sell_volume')
        self.addDailyData(self.order_sell_money,self.tag + '.order_sell_money')
        self.addDailyData(self.order_avg_sell_price,self.tag + '.order_avg_sell_price')
        self.addDailyData(self.order_max_sell_price,self.tag + '.order_max_sell_price')
        self.addDailyData(self.order_min_sell_price,self.tag + '.order_min_sell_price')
        self.addDailyData(self.order_avg_sell_volume,self.tag + '.order_avg_sell_volume')
        self.addDailyData(self.order_first_interval_seconds,self.tag + '.order_first_interval_seconds')
        self.addDailyData(self.order_last_interval_seconds,self.tag + '.order_last_interval_seconds')
        self.addDailyData(self.cancelled_order_total_volume,self.tag + '.cancelled_order_total_volume')
        self.addDailyData(self.cancelled_order_total_money,self.tag + '.cancelled_order_total_money')
        self.addDailyData(self.pe1,self.tag + '.pe1')
        self.addDailyData(self.up_limit_px,self.tag + '.up_limit_px')
        self.addDailyData(self.down_limit_px,self.tag + '.down_limit_px')
        return

    def loadDay(self, di):
        self.fillnan(di)  # set default value
        filepath = os.path.join(self.dataPath, '%d' % uv.Dates[di]+".csv")
        #filepath = os.path.join(self.dataPath, '%d' % uv.Dates[di])
        if not os.path.isfile(filepath):
            print('[ %s ] %s missing on day %d' %  (self.tag, filepath, uv.Dates[di]))
            return
        infile = open(filepath, 'r')
        header = infile.readline().strip().split(',')  # skip title line
        dayStr = str(uv.Dates[di])[0:4]+'-'+str(uv.Dates[di])[4:6]+'-'+str(uv.Dates[di])[6:8]
        print ("dayStr",dayStr)
        morning = pd.date_range(start=f'{dayStr} 9:30:00', end=f'{dayStr} 11:30:00', freq='5min')
        afternoon = pd.date_range(start=f'{dayStr} 13:05:00', end=f'{dayStr} 15:00:00', freq='5min')
        timeIdx = {j.strftime('%H:%M'):i for i, j in enumerate(morning.append(afternoon))}
        count = np.zeros(len(uv.Instruments))  ############
        infile.readline() # skip title line
        updated = 0
        for line in infile:
            linespt = line.strip('\n').split(',')
            linespt = [np.nan if x == '' else x for x in linespt]
            raw_code  = linespt[header.index('stock_symbol')]
            code = raw_code[2:]#+'.'+raw_code[0:2]
            ii = uv.Instruments.lookup(code)
            if ii < 0:
                continue
            timeStr = linespt[header.index('window_end')][11:16]
            if timeStr not in timeIdx:
                continue
            ti = timeIdx[timeStr]
            count[ii] += 1  ##############


            self.open[di,ti,ii]  = float(linespt[3])
            self.high[di,ti,ii]  = float(linespt[4])
            self.low[di,ti,ii]  = float(linespt[5])
            self.close[di,ti,ii]  = float(linespt[6])
            self.volume[di,ti,ii]  = float(linespt[7])
            self.trade_success_count[di,ti,ii]  = float(linespt[8])
            self.trade_avg_price[di,ti,ii]  = float(linespt[9])
            self.trade_min_price[di,ti,ii]  = float(linespt[10])
            self.trade_max_price[di,ti,ii]  = float(linespt[11])
            self.trade_std_price[di,ti,ii]  = float(linespt[12])
            self.trade_price_p10[di,ti,ii]  = float(linespt[13])
            self.trade_price_p20[di,ti,ii]  = float(linespt[14])
            self.trade_price_p30[di,ti,ii]  = float(linespt[15])
            self.trade_price_p40[di,ti,ii]  = float(linespt[16])
            self.trade_price_p50[di,ti,ii]  = float(linespt[17])
            self.trade_price_p60[di,ti,ii]  = float(linespt[18])
            self.trade_price_p70[di,ti,ii]  = float(linespt[19])
            self.trade_price_p80[di,ti,ii]  = float(linespt[20])
            self.trade_price_p90[di,ti,ii]  = float(linespt[21])
            self.avg_volume[di,ti,ii]  = float(linespt[22])
            self.max_volume[di,ti,ii]  = float(linespt[23])
            self.min_volume[di,ti,ii]  = float(linespt[24])
            self.std_volume[di,ti,ii]  = float(linespt[25])
            self.trade_total_money[di,ti,ii]  = float(linespt[26])
            self.trade_avg_money[di,ti,ii]  = float(linespt[27])
            self.trade_max_money[di,ti,ii]  = float(linespt[28])
            self.trade_min_money[di,ti,ii]  = float(linespt[29])
            self.trade_first_interval_seconds[di,ti,ii]  = float(linespt[30])
            self.trade_last_interval_seconds[di,ti,ii]  = float(linespt[31])
            self.trade_avg_offer_interval_seconds[di,ti,ii]  = float(linespt[32])
            self.trade_avg_bid_interval_seconds[di,ti,ii]  = float(linespt[33])
            self.avg_bid_price[di,ti,ii]  = float(linespt[34])
            self.min_bid_price[di,ti,ii]  = float(linespt[35])
            self.max_bid_price[di,ti,ii]  = float(linespt[36])
            self.avg_offer_price[di,ti,ii]  = float(linespt[37])
            self.min_offer_price[di,ti,ii]  = float(linespt[38])
            self.max_offer_price[di,ti,ii]  = float(linespt[39])
            self.overbuy_count[di,ti,ii]  = float(linespt[40])
            self.oversell_count[di,ti,ii]  = float(linespt[41])
            self.overbuy_volume[di,ti,ii]  = float(linespt[42])
            self.oversell_volume[di,ti,ii]  = float(linespt[43])
            self.trade_cancel_count[di,ti,ii]  = float(linespt[44])
            self.cancelled_volume[di,ti,ii]  = float(linespt[45])
            self.cancelled_buy_trade_count[di,ti,ii]  = float(linespt[46])
            self.cancelled_sell_trade_count[di,ti,ii]  = float(linespt[47])
            self.order_total_volume[di,ti,ii]  = float(linespt[48])
            self.order_total_money[di,ti,ii]  = float(linespt[49])
            self.order_count[di,ti,ii]  = float(linespt[50])
            self.order_buy_count[di,ti,ii]  = float(linespt[51])
            self.order_sell_count[di,ti,ii]  = float(linespt[52])
            self.order_avg_price[di,ti,ii]  = float(linespt[53])
            self.order_min_price[di,ti,ii]  = float(linespt[54])
            self.order_max_price[di,ti,ii]  = float(linespt[55])
            self.std_price[di,ti,ii]  = float(linespt[56])
            self.order_price_p10[di,ti,ii]  = float(linespt[57])
            self.order_price_p20[di,ti,ii]  = float(linespt[58])
            self.order_price_p30[di,ti,ii]  = float(linespt[59])
            self.order_price_p40[di,ti,ii]  = float(linespt[60])
            self.order_price_p50[di,ti,ii]  = float(linespt[61])
            self.order_price_p60[di,ti,ii]  = float(linespt[62])
            self.order_price_p70[di,ti,ii]  = float(linespt[63])
            self.order_price_p80[di,ti,ii]  = float(linespt[64])
            self.order_price_p90[di,ti,ii]  = float(linespt[65])
            self.order_avg_volume[di,ti,ii]  = float(linespt[66])
            self.order_max_volume[di,ti,ii]  = float(linespt[67])
            self.order_min_volume[di,ti,ii]  = float(linespt[68])
            self.order_std_volume[di,ti,ii]  = float(linespt[69])
            self.order_avg_money[di,ti,ii]  = float(linespt[70])
            self.order_max_money[di,ti,ii]  = float(linespt[71])
            self.order_min_money[di,ti,ii]  = float(linespt[72])
            self.order_buy_volume[di,ti,ii]  = float(linespt[73])
            self.order_buy_money[di,ti,ii]  = float(linespt[74])
            self.order_avg_buy_price[di,ti,ii]  = float(linespt[75])
            self.order_max_buy_price[di,ti,ii]  = float(linespt[76])
            self.order_min_buy_price[di,ti,ii]  = float(linespt[77])
            self.order_avg_buy_volume[di,ti,ii]  = float(linespt[78])
            self.order_sell_volume[di,ti,ii]  = float(linespt[79])
            self.order_sell_money[di,ti,ii]  = float(linespt[80])
            self.order_avg_sell_price[di,ti,ii]  = float(linespt[81])
            self.order_max_sell_price[di,ti,ii]  = float(linespt[82])
            self.order_min_sell_price[di,ti,ii]  = float(linespt[83])
            self.order_avg_sell_volume[di,ti,ii]  = float(linespt[84])
            self.order_first_interval_seconds[di,ti,ii]  = float(linespt[85])
            self.order_last_interval_seconds[di,ti,ii]  = float(linespt[86])
            self.cancelled_order_total_volume[di,ti,ii]  = float(linespt[87])
            self.cancelled_order_total_money[di,ti,ii]  = float(linespt[88])
            self.pe1[di,ti,ii]  = float(linespt[89])
            self.up_limit_px[di,ti,ii]  = float(linespt[90])
            self.down_limit_px[di,ti,ii]  = float(linespt[91])
            updated += 1
        infile.close()
        print('[ %s ] Updated %d stocks on day %d' %  (self.tag, updated, uv.Dates[di]))
        return

