
from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np
import pandas as pd
import os
import operator
import csv

class DmgrGFV2AA5M(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.dataPath = None
        self.backfill = False
        self.open = NIO_CUBE()
        self.close = NIO_CUBE()
        self.high = NIO_CUBE()
        self.low = NIO_CUBE()
        self.volume = NIO_CUBE()
        self.trade_success_count = NIO_CUBE()
        self.trade_avg_price = NIO_CUBE()
        self.trade_min_price = NIO_CUBE()
        self.trade_max_price = NIO_CUBE()
        self.trade_std_price = NIO_CUBE()
        self.trade_price_p10 = NIO_CUBE()
        self.trade_price_p20 = NIO_CUBE()
        self.trade_price_p30 = NIO_CUBE()
        self.trade_price_p40 = NIO_CUBE()
        self.trade_price_p50 = NIO_CUBE()
        self.trade_price_p60 = NIO_CUBE()
        self.trade_price_p70 = NIO_CUBE()
        self.trade_price_p80 = NIO_CUBE()
        self.trade_price_p90 = NIO_CUBE()
        self.avg_volume = NIO_CUBE()
        self.max_volume = NIO_CUBE()
        self.min_volume = NIO_CUBE()
        self.std_volume = NIO_CUBE()
        self.volume_median = NIO_CUBE()
        self.volume_q25 = NIO_CUBE()
        self.volume_q75 = NIO_CUBE()
        self.trade_total_money = NIO_CUBE()
        self.trade_avg_money = NIO_CUBE()
        self.trade_max_money = NIO_CUBE()
        self.trade_min_money = NIO_CUBE()
        self.trade_money_median = NIO_CUBE()
        self.trade_money_q25 = NIO_CUBE()
        self.trade_money_q75 = NIO_CUBE()
        self.trade_first_interval_seconds = NIO_CUBE()
        self.trade_last_interval_seconds = NIO_CUBE()
        self.trade_buy_count = NIO_CUBE()
        self.trade_buy_avg_money = NIO_CUBE()
        self.trade_buy_total_money = NIO_CUBE()
        self.trade_buy_avg_volume = NIO_CUBE()
        self.trade_buy_volume = NIO_CUBE()
        self.trade_buy_avg_price = NIO_CUBE()
        self.trade_buy_max_price = NIO_CUBE()
        self.trade_buy_min_price = NIO_CUBE()
        self.trade_sell_count = NIO_CUBE()
        self.trade_sell_avg_money = NIO_CUBE()
        self.trade_sell_total_money = NIO_CUBE()
        self.trade_sell_avg_volume = NIO_CUBE()
        self.trade_sell_volume = NIO_CUBE()
        self.trade_sell_avg_price = NIO_CUBE()
        self.trade_sell_max_price = NIO_CUBE()
        self.trade_sell_min_price = NIO_CUBE()
        self.seq_num_diff_mean = NIO_CUBE()
        self.seq_num_diff_std = NIO_CUBE()
        self.seq_num_diff_min = NIO_CUBE()
        self.seq_num_diff_max = NIO_CUBE()
        self.seq_num_diff_median = NIO_CUBE()
        self.seq_num_diff_q25 = NIO_CUBE()
        self.seq_num_diff_q75 = NIO_CUBE()
        self.trade_big_count_based_on_trade_money = NIO_CUBE()
        self.trade_big_avg_money_based_on_trade_money = NIO_CUBE()
        self.trade_big_total_money_based_on_trade_money = NIO_CUBE()
        self.trade_big_avg_volume_based_on_trade_money = NIO_CUBE()
        self.trade_big_volume_based_on_trade_money = NIO_CUBE()
        self.trade_big_avg_price_based_on_trade_money = NIO_CUBE()
        self.trade_big_max_price_based_on_trade_money = NIO_CUBE()
        self.trade_big_min_price_based_on_trade_money = NIO_CUBE()
        self.trade_small_count_based_on_trade_money = NIO_CUBE()
        self.trade_small_avg_money_based_on_trade_money = NIO_CUBE()
        self.trade_small_total_money_based_on_trade_money = NIO_CUBE()
        self.trade_small_avg_volume_based_on_trade_money = NIO_CUBE()
        self.trade_small_volume_based_on_trade_money = NIO_CUBE()
        self.trade_small_avg_price_based_on_trade_money = NIO_CUBE()
        self.trade_small_max_price_based_on_trade_money = NIO_CUBE()
        self.trade_small_min_price_based_on_trade_money = NIO_CUBE()
        self.trade_long_count_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_avg_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_total_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_avg_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_avg_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_max_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_min_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_count_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_avg_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_total_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_avg_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_avg_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_max_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_min_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_offer_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_avg_offer_interval_seconds = NIO_CUBE()
        self.trade_max_offer_interval_seconds = NIO_CUBE()
        self.trade_min_offer_interval_seconds = NIO_CUBE()
        self.trade_stddev_offer_interval_seconds = NIO_CUBE()
        self.trade_avg_bid_interval_seconds = NIO_CUBE()
        self.trade_max_bid_interval_seconds = NIO_CUBE()
        self.trade_min_bid_interval_seconds = NIO_CUBE()
        self.trade_stddev_bid_interval_seconds = NIO_CUBE()
        #self.avg_bid_price = NIO_CUBE()
        #self.min_bid_price = NIO_CUBE()
        #self.max_bid_price = NIO_CUBE()
        #self.stddev_bid_price = NIO_CUBE()
        #self.avg_offer_price = NIO_CUBE()
        #self.min_offer_price = NIO_CUBE()
        #self.max_offer_price = NIO_CUBE()
        #self.stddev_offer_price = NIO_CUBE()
        #self.overbuy_count = NIO_CUBE()
        #self.oversell_count = NIO_CUBE()
        #self.overbuy_volume = NIO_CUBE()
        #self.oversell_volume = NIO_CUBE()
        #self.total_trade_offer_diff = NIO_CUBE()
        #self.total_trade_bid_diff = NIO_CUBE()
        #self.trade_cancel_count = NIO_CUBE()
        #self.cancelled_volume = NIO_CUBE()
        #self.cancelled_buy_trade_count = NIO_CUBE()
        #self.cancelled_sell_trade_count = NIO_CUBE()
        #self.order_total_volume = NIO_CUBE()
        #self.order_total_money = NIO_CUBE()
        #self.order_count = NIO_CUBE()
        #self.order_avg_price = NIO_CUBE()
        #self.order_min_price = NIO_CUBE()
        #self.order_max_price = NIO_CUBE()
        #self.std_price = NIO_CUBE()
        #self.order_price_p10 = NIO_CUBE()
        #self.order_price_p20 = NIO_CUBE()
        #self.order_price_p30 = NIO_CUBE()
        #self.order_price_p40 = NIO_CUBE()
        #self.order_price_p50 = NIO_CUBE()
        #self.order_price_p60 = NIO_CUBE()
        #self.order_price_p70 = NIO_CUBE()
        #self.order_price_p80 = NIO_CUBE()
        #self.order_price_p90 = NIO_CUBE()
        #self.order_avg_volume = NIO_CUBE()
        #self.order_max_volume = NIO_CUBE()
        #self.order_min_volume = NIO_CUBE()
        #self.order_std_volume = NIO_CUBE()
        #self.order_avg_money = NIO_CUBE()
        #self.order_max_money = NIO_CUBE()
        #self.order_min_money = NIO_CUBE()
        #self.order_buy_count = NIO_CUBE()
        #self.order_buy_avg_money = NIO_CUBE()
        #self.order_buy_total_money = NIO_CUBE()
        #self.order_buy_avg_volume = NIO_CUBE()
        #self.order_buy_volume = NIO_CUBE()
        #self.order_buy_avg_price = NIO_CUBE()
        #self.order_buy_max_price = NIO_CUBE()
        #self.order_buy_min_price = NIO_CUBE()
        #self.order_sell_count = NIO_CUBE()
        #self.order_sell_avg_money = NIO_CUBE()
        #self.order_sell_total_money = NIO_CUBE()
        #self.order_sell_avg_volume = NIO_CUBE()
        #self.order_sell_volume = NIO_CUBE()
        #self.order_sell_avg_price = NIO_CUBE()
        #self.order_sell_max_price = NIO_CUBE()
        #self.order_sell_min_price = NIO_CUBE()
        #self.order_first_interval_seconds = NIO_CUBE()
        #self.order_last_interval_seconds = NIO_CUBE()
        #self.order_big_count_based_on_order_money = NIO_CUBE()
        #self.order_big_avg_money_based_on_order_money = NIO_CUBE()
        #self.order_big_total_money_based_on_order_money = NIO_CUBE()
        #self.order_big_avg_volume_based_on_order_money = NIO_CUBE()
        #self.order_big_volume_based_on_order_money = NIO_CUBE()
        #self.order_big_avg_price_based_on_order_money = NIO_CUBE()
        #self.order_big_max_price_based_on_order_money = NIO_CUBE()
        #self.order_big_min_price_based_on_order_money = NIO_CUBE()
        #self.order_small_count_based_on_order_money = NIO_CUBE()
        #self.order_small_avg_money_based_on_order_money = NIO_CUBE()
        #self.order_small_total_money_based_on_order_money = NIO_CUBE()
        #self.order_small_avg_volume_based_on_order_money = NIO_CUBE()
        #self.order_small_volume_based_on_order_money = NIO_CUBE()
        #self.order_small_avg_price_based_on_order_money = NIO_CUBE()
        #self.order_small_max_price_based_on_order_money = NIO_CUBE()
        #self.order_small_min_price_based_on_order_money = NIO_CUBE()
        #self.cancelled_order_total_volume = NIO_CUBE()
        #self.cancelled_order_total_money = NIO_CUBE()
        #self.pe1 = NIO_CUBE()
        #self.up_limit_px = NIO_CUBE()
        #self.down_limit_px = NIO_CUBE()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.dataPath = cfg.getAttributeString('dataPath')
        self.backfill = cfg.getAttributeDefault('backfill', False)
        self.addData(self.open,self.tag + '.open', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.close,self.tag + '.close', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.high,self.tag + '.high', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.low,self.tag + '.low', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.volume,self.tag + '.volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_success_count,self.tag + '.trade_success_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_avg_price,self.tag + '.trade_avg_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_min_price,self.tag + '.trade_min_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_max_price,self.tag + '.trade_max_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_std_price,self.tag + '.trade_std_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p10,self.tag + '.trade_price_p10', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p20,self.tag + '.trade_price_p20', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p30,self.tag + '.trade_price_p30', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p40,self.tag + '.trade_price_p40', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p50,self.tag + '.trade_price_p50', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p60,self.tag + '.trade_price_p60', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p70,self.tag + '.trade_price_p70', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p80,self.tag + '.trade_price_p80', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_price_p90,self.tag + '.trade_price_p90', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.avg_volume,self.tag + '.avg_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.max_volume,self.tag + '.max_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.min_volume,self.tag + '.min_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.std_volume,self.tag + '.std_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.volume_median,self.tag + '.volume_median', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.volume_q25,self.tag + '.volume_q25', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.volume_q75,self.tag + '.volume_q75', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_total_money,self.tag + '.trade_total_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_avg_money,self.tag + '.trade_avg_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_max_money,self.tag + '.trade_max_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_min_money,self.tag + '.trade_min_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_money_median,self.tag + '.trade_money_median', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_money_q25,self.tag + '.trade_money_q25', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_money_q75,self.tag + '.trade_money_q75', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_first_interval_seconds,self.tag + '.trade_first_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_last_interval_seconds,self.tag + '.trade_last_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_count,self.tag + '.trade_buy_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_avg_money,self.tag + '.trade_buy_avg_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_total_money,self.tag + '.trade_buy_total_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_avg_volume,self.tag + '.trade_buy_avg_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_volume,self.tag + '.trade_buy_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_avg_price,self.tag + '.trade_buy_avg_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_max_price,self.tag + '.trade_buy_max_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_buy_min_price,self.tag + '.trade_buy_min_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_count,self.tag + '.trade_sell_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_avg_money,self.tag + '.trade_sell_avg_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_total_money,self.tag + '.trade_sell_total_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_avg_volume,self.tag + '.trade_sell_avg_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_volume,self.tag + '.trade_sell_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_avg_price,self.tag + '.trade_sell_avg_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_max_price,self.tag + '.trade_sell_max_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_sell_min_price,self.tag + '.trade_sell_min_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.seq_num_diff_mean,self.tag + '.seq_num_diff_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.seq_num_diff_std,self.tag + '.seq_num_diff_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.seq_num_diff_min,self.tag + '.seq_num_diff_min', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.seq_num_diff_max,self.tag + '.seq_num_diff_max', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.seq_num_diff_median,self.tag + '.seq_num_diff_median', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.seq_num_diff_q25,self.tag + '.seq_num_diff_q25', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.seq_num_diff_q75,self.tag + '.seq_num_diff_q75', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_count_based_on_trade_money,self.tag + '.trade_big_count_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_avg_money_based_on_trade_money,self.tag + '.trade_big_avg_money_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_total_money_based_on_trade_money,self.tag + '.trade_big_total_money_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_avg_volume_based_on_trade_money,self.tag + '.trade_big_avg_volume_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_volume_based_on_trade_money,self.tag + '.trade_big_volume_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_avg_price_based_on_trade_money,self.tag + '.trade_big_avg_price_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_max_price_based_on_trade_money,self.tag + '.trade_big_max_price_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_big_min_price_based_on_trade_money,self.tag + '.trade_big_min_price_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_count_based_on_trade_money,self.tag + '.trade_small_count_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_avg_money_based_on_trade_money,self.tag + '.trade_small_avg_money_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_total_money_based_on_trade_money,self.tag + '.trade_small_total_money_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_avg_volume_based_on_trade_money,self.tag + '.trade_small_avg_volume_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_volume_based_on_trade_money,self.tag + '.trade_small_volume_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_avg_price_based_on_trade_money,self.tag + '.trade_small_avg_price_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_max_price_based_on_trade_money,self.tag + '.trade_small_max_price_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_small_min_price_based_on_trade_money,self.tag + '.trade_small_min_price_based_on_trade_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_count_based_on_seq_num_diff,self.tag + '.trade_long_count_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_avg_money_based_on_seq_num_diff,self.tag + '.trade_long_avg_money_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_total_money_based_on_seq_num_diff,self.tag + '.trade_long_total_money_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_avg_volume_based_on_seq_num_diff,self.tag + '.trade_long_avg_volume_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_volume_based_on_seq_num_diff,self.tag + '.trade_long_volume_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_avg_price_based_on_seq_num_diff,self.tag + '.trade_long_avg_price_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_max_price_based_on_seq_num_diff,self.tag + '.trade_long_max_price_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_min_price_based_on_seq_num_diff,self.tag + '.trade_long_min_price_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_count_based_on_seq_num_diff,self.tag + '.trade_short_count_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_avg_money_based_on_seq_num_diff,self.tag + '.trade_short_avg_money_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_total_money_based_on_seq_num_diff,self.tag + '.trade_short_total_money_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_avg_volume_based_on_seq_num_diff,self.tag + '.trade_short_avg_volume_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_volume_based_on_seq_num_diff,self.tag + '.trade_short_volume_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_avg_price_based_on_seq_num_diff,self.tag + '.trade_short_avg_price_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_max_price_based_on_seq_num_diff,self.tag + '.trade_short_max_price_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_min_price_based_on_seq_num_diff,self.tag + '.trade_short_min_price_based_on_seq_num_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_count_based_on_interval_seconds,self.tag + '.trade_long_offer_count_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_avg_money_based_on_interval_seconds,self.tag + '.trade_long_offer_avg_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_total_money_based_on_interval_seconds,self.tag + '.trade_long_offer_total_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_avg_volume_based_on_interval_seconds,self.tag + '.trade_long_offer_avg_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_volume_based_on_interval_seconds,self.tag + '.trade_long_offer_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_avg_price_based_on_interval_seconds,self.tag + '.trade_long_offer_avg_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_max_price_based_on_interval_seconds,self.tag + '.trade_long_offer_max_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_offer_min_price_based_on_interval_seconds,self.tag + '.trade_long_offer_min_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_count_based_on_interval_seconds,self.tag + '.trade_short_offer_count_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_avg_money_based_on_interval_seconds,self.tag + '.trade_short_offer_avg_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_total_money_based_on_interval_seconds,self.tag + '.trade_short_offer_total_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_avg_volume_based_on_interval_seconds,self.tag + '.trade_short_offer_avg_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_volume_based_on_interval_seconds,self.tag + '.trade_short_offer_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_avg_price_based_on_interval_seconds,self.tag + '.trade_short_offer_avg_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_max_price_based_on_interval_seconds,self.tag + '.trade_short_offer_max_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_offer_min_price_based_on_interval_seconds,self.tag + '.trade_short_offer_min_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_count_based_on_interval_seconds,self.tag + '.trade_long_bid_count_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_avg_money_based_on_interval_seconds,self.tag + '.trade_long_bid_avg_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_total_money_based_on_interval_seconds,self.tag + '.trade_long_bid_total_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_avg_volume_based_on_interval_seconds,self.tag + '.trade_long_bid_avg_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_volume_based_on_interval_seconds,self.tag + '.trade_long_bid_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_avg_price_based_on_interval_seconds,self.tag + '.trade_long_bid_avg_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_max_price_based_on_interval_seconds,self.tag + '.trade_long_bid_max_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_long_bid_min_price_based_on_interval_seconds,self.tag + '.trade_long_bid_min_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_count_based_on_interval_seconds,self.tag + '.trade_short_bid_count_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_avg_money_based_on_interval_seconds,self.tag + '.trade_short_bid_avg_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_total_money_based_on_interval_seconds,self.tag + '.trade_short_bid_total_money_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_avg_volume_based_on_interval_seconds,self.tag + '.trade_short_bid_avg_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_volume_based_on_interval_seconds,self.tag + '.trade_short_bid_volume_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_avg_price_based_on_interval_seconds,self.tag + '.trade_short_bid_avg_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_max_price_based_on_interval_seconds,self.tag + '.trade_short_bid_max_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_short_bid_min_price_based_on_interval_seconds,self.tag + '.trade_short_bid_min_price_based_on_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_avg_offer_interval_seconds,self.tag + '.trade_avg_offer_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_max_offer_interval_seconds,self.tag + '.trade_max_offer_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_min_offer_interval_seconds,self.tag + '.trade_min_offer_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_stddev_offer_interval_seconds,self.tag + '.trade_stddev_offer_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_avg_bid_interval_seconds,self.tag + '.trade_avg_bid_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_max_bid_interval_seconds,self.tag + '.trade_max_bid_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_min_bid_interval_seconds,self.tag + '.trade_min_bid_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.trade_stddev_bid_interval_seconds,self.tag + '.trade_stddev_bid_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.avg_bid_price,self.tag + '.avg_bid_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.min_bid_price,self.tag + '.min_bid_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.max_bid_price,self.tag + '.max_bid_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.stddev_bid_price,self.tag + '.stddev_bid_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.avg_offer_price,self.tag + '.avg_offer_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.min_offer_price,self.tag + '.min_offer_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.max_offer_price,self.tag + '.max_offer_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.stddev_offer_price,self.tag + '.stddev_offer_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.overbuy_count,self.tag + '.overbuy_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.oversell_count,self.tag + '.oversell_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.overbuy_volume,self.tag + '.overbuy_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.oversell_volume,self.tag + '.oversell_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.total_trade_offer_diff,self.tag + '.total_trade_offer_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.total_trade_bid_diff,self.tag + '.total_trade_bid_diff', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.trade_cancel_count,self.tag + '.trade_cancel_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.cancelled_volume,self.tag + '.cancelled_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.cancelled_buy_trade_count,self.tag + '.cancelled_buy_trade_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.cancelled_sell_trade_count,self.tag + '.cancelled_sell_trade_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_total_volume,self.tag + '.order_total_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_total_money,self.tag + '.order_total_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_count,self.tag + '.order_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_avg_price,self.tag + '.order_avg_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_min_price,self.tag + '.order_min_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_max_price,self.tag + '.order_max_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.std_price,self.tag + '.std_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p10,self.tag + '.order_price_p10', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p20,self.tag + '.order_price_p20', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p30,self.tag + '.order_price_p30', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p40,self.tag + '.order_price_p40', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p50,self.tag + '.order_price_p50', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p60,self.tag + '.order_price_p60', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p70,self.tag + '.order_price_p70', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p80,self.tag + '.order_price_p80', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_price_p90,self.tag + '.order_price_p90', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_avg_volume,self.tag + '.order_avg_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_max_volume,self.tag + '.order_max_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_min_volume,self.tag + '.order_min_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_std_volume,self.tag + '.order_std_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_avg_money,self.tag + '.order_avg_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_max_money,self.tag + '.order_max_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_min_money,self.tag + '.order_min_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_count,self.tag + '.order_buy_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_avg_money,self.tag + '.order_buy_avg_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_total_money,self.tag + '.order_buy_total_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_avg_volume,self.tag + '.order_buy_avg_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_volume,self.tag + '.order_buy_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_avg_price,self.tag + '.order_buy_avg_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_max_price,self.tag + '.order_buy_max_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_buy_min_price,self.tag + '.order_buy_min_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_count,self.tag + '.order_sell_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_avg_money,self.tag + '.order_sell_avg_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_total_money,self.tag + '.order_sell_total_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_avg_volume,self.tag + '.order_sell_avg_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_volume,self.tag + '.order_sell_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_avg_price,self.tag + '.order_sell_avg_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_max_price,self.tag + '.order_sell_max_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_sell_min_price,self.tag + '.order_sell_min_price', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_first_interval_seconds,self.tag + '.order_first_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_last_interval_seconds,self.tag + '.order_last_interval_seconds', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_count_based_on_order_money,self.tag + '.order_big_count_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_avg_money_based_on_order_money,self.tag + '.order_big_avg_money_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_total_money_based_on_order_money,self.tag + '.order_big_total_money_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_avg_volume_based_on_order_money,self.tag + '.order_big_avg_volume_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_volume_based_on_order_money,self.tag + '.order_big_volume_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_avg_price_based_on_order_money,self.tag + '.order_big_avg_price_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_max_price_based_on_order_money,self.tag + '.order_big_max_price_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_big_min_price_based_on_order_money,self.tag + '.order_big_min_price_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_count_based_on_order_money,self.tag + '.order_small_count_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_avg_money_based_on_order_money,self.tag + '.order_small_avg_money_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_total_money_based_on_order_money,self.tag + '.order_small_total_money_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_avg_volume_based_on_order_money,self.tag + '.order_small_avg_volume_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_volume_based_on_order_money,self.tag + '.order_small_volume_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_avg_price_based_on_order_money,self.tag + '.order_small_avg_price_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_max_price_based_on_order_money,self.tag + '.order_small_max_price_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.order_small_min_price_based_on_order_money,self.tag + '.order_small_min_price_based_on_order_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.cancelled_order_total_volume,self.tag + '.cancelled_order_total_volume', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.cancelled_order_total_money,self.tag + '.cancelled_order_total_money', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.pe1,self.tag + '.pe1', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.up_limit_px,self.tag + '.up_limit_px', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        #self.addData(self.down_limit_px,self.tag + '.down_limit_px', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        return

    def loadDay(self, di):
        self.fillnan(di)  # set default value


        filepath = os.path.join(self.dataPath, '%d' % uv.Dates[di]+".csv")
        #filepath = os.path.join(self.dataPath, '%d' % uv.Dates[di])
        if not os.path.isfile(filepath):
            print('[ %s ] %s missing on day %d' %  (self.tag, filepath, uv.Dates[di]))
            return
        infile = open(filepath, 'r')
        header = infile.readline().strip().split(',')  # skip title line
        dayStr = str(uv.Dates[di])[0:4]+'-'+str(uv.Dates[di])[4:6]+'-'+str(uv.Dates[di])[6:8]
        print ("dayStr",dayStr)
        morning = pd.date_range(start=f'{dayStr} 9:30:00', end=f'{dayStr} 11:30:00', freq='5min')
        afternoon = pd.date_range(start=f'{dayStr} 13:05:00', end=f'{dayStr} 15:00:00', freq='5min')
        timeIdx = {j.strftime('%H:%M'):i for i, j in enumerate(morning.append(afternoon))}
        count = np.zeros(len(uv.Instruments))  ############
        infile.readline() # skip title line
        updated = 0
        for line in infile:
            linespt = line.strip('\n').split(',')
            linespt = [np.nan if x == '' else x for x in linespt]
            raw_code  = linespt[header.index('stock_symbol')]
            code = raw_code[2:]#+'.'+raw_code[0:2]
            ii = uv.Instruments.lookup(code)
            if ii < 0:
                continue
            timeStr = linespt[header.index('window_end')][11:16]
            if timeStr not in timeIdx:
                continue
            ti = timeIdx[timeStr]
            count[ii] += 1  ##############






            self.open[di, ti, ii]  = float(linespt[3])
            self.close[di, ti, ii]  = float(linespt[4])
            self.high[di, ti, ii]  = float(linespt[5])
            self.low[di, ti, ii]  = float(linespt[6])
            self.volume[di, ti, ii]  = float(linespt[7])
            self.trade_success_count[di, ti, ii]  = float(linespt[8])
            self.trade_avg_price[di, ti, ii]  = float(linespt[9])
            self.trade_min_price[di, ti, ii]  = float(linespt[10])
            self.trade_max_price[di, ti, ii]  = float(linespt[11])
            self.trade_std_price[di, ti, ii]  = float(linespt[12])
            self.trade_price_p10[di, ti, ii]  = float(linespt[13])
            self.trade_price_p20[di, ti, ii]  = float(linespt[14])
            self.trade_price_p30[di, ti, ii]  = float(linespt[15])
            self.trade_price_p40[di, ti, ii]  = float(linespt[16])
            self.trade_price_p50[di, ti, ii]  = float(linespt[17])
            self.trade_price_p60[di, ti, ii]  = float(linespt[18])
            self.trade_price_p70[di, ti, ii]  = float(linespt[19])
            self.trade_price_p80[di, ti, ii]  = float(linespt[20])
            self.trade_price_p90[di, ti, ii]  = float(linespt[21])
            self.avg_volume[di, ti, ii]  = float(linespt[22])
            self.max_volume[di, ti, ii]  = float(linespt[23])
            self.min_volume[di, ti, ii]  = float(linespt[24])
            self.std_volume[di, ti, ii]  = float(linespt[25])
            self.volume_median[di, ti, ii]  = float(linespt[26])
            self.volume_q25[di, ti, ii]  = float(linespt[27])
            self.volume_q75[di, ti, ii]  = float(linespt[28])
            self.trade_total_money[di, ti, ii]  = float(linespt[29])
            self.trade_avg_money[di, ti, ii]  = float(linespt[30])
            self.trade_max_money[di, ti, ii]  = float(linespt[31])
            self.trade_min_money[di, ti, ii]  = float(linespt[32])
            self.trade_money_median[di, ti, ii]  = float(linespt[33])
            self.trade_money_q25[di, ti, ii]  = float(linespt[34])
            self.trade_money_q75[di, ti, ii]  = float(linespt[35])
            self.trade_first_interval_seconds[di, ti, ii]  = float(linespt[36])
            self.trade_last_interval_seconds[di, ti, ii]  = float(linespt[37])
            self.trade_buy_count[di, ti, ii]  = float(linespt[38])
            self.trade_buy_avg_money[di, ti, ii]  = float(linespt[39])
            self.trade_buy_total_money[di, ti, ii]  = float(linespt[40])
            self.trade_buy_avg_volume[di, ti, ii]  = float(linespt[41])
            self.trade_buy_volume[di, ti, ii]  = float(linespt[42])
            self.trade_buy_avg_price[di, ti, ii]  = float(linespt[43])
            self.trade_buy_max_price[di, ti, ii]  = float(linespt[44])
            self.trade_buy_min_price[di, ti, ii]  = float(linespt[45])
            self.trade_sell_count[di, ti, ii]  = float(linespt[46])
            self.trade_sell_avg_money[di, ti, ii]  = float(linespt[47])
            self.trade_sell_total_money[di, ti, ii]  = float(linespt[48])
            self.trade_sell_avg_volume[di, ti, ii]  = float(linespt[49])
            self.trade_sell_volume[di, ti, ii]  = float(linespt[50])
            self.trade_sell_avg_price[di, ti, ii]  = float(linespt[51])
            self.trade_sell_max_price[di, ti, ii]  = float(linespt[52])
            self.trade_sell_min_price[di, ti, ii]  = float(linespt[53])
            self.seq_num_diff_mean[di, ti, ii]  = float(linespt[54])
            self.seq_num_diff_std[di, ti, ii]  = float(linespt[55])
            self.seq_num_diff_min[di, ti, ii]  = float(linespt[56])
            self.seq_num_diff_max[di, ti, ii]  = float(linespt[57])
            self.seq_num_diff_median[di, ti, ii]  = float(linespt[58])
            self.seq_num_diff_q25[di, ti, ii]  = float(linespt[59])
            self.seq_num_diff_q75[di, ti, ii]  = float(linespt[60])
            self.trade_big_count_based_on_trade_money[di, ti, ii]  = float(linespt[61])
            self.trade_big_avg_money_based_on_trade_money[di, ti, ii]  = float(linespt[62])
            self.trade_big_total_money_based_on_trade_money[di, ti, ii]  = float(linespt[63])
            self.trade_big_avg_volume_based_on_trade_money[di, ti, ii]  = float(linespt[64])
            self.trade_big_volume_based_on_trade_money[di, ti, ii]  = float(linespt[65])
            self.trade_big_avg_price_based_on_trade_money[di, ti, ii]  = float(linespt[66])
            self.trade_big_max_price_based_on_trade_money[di, ti, ii]  = float(linespt[67])
            self.trade_big_min_price_based_on_trade_money[di, ti, ii]  = float(linespt[68])
            self.trade_small_count_based_on_trade_money[di, ti, ii]  = float(linespt[69])
            self.trade_small_avg_money_based_on_trade_money[di, ti, ii]  = float(linespt[70])
            self.trade_small_total_money_based_on_trade_money[di, ti, ii]  = float(linespt[71])
            self.trade_small_avg_volume_based_on_trade_money[di, ti, ii]  = float(linespt[72])
            self.trade_small_volume_based_on_trade_money[di, ti, ii]  = float(linespt[73])
            self.trade_small_avg_price_based_on_trade_money[di, ti, ii]  = float(linespt[74])
            self.trade_small_max_price_based_on_trade_money[di, ti, ii]  = float(linespt[75])
            self.trade_small_min_price_based_on_trade_money[di, ti, ii]  = float(linespt[76])
            self.trade_long_count_based_on_seq_num_diff[di, ti, ii]  = float(linespt[77])
            self.trade_long_avg_money_based_on_seq_num_diff[di, ti, ii]  = float(linespt[78])
            self.trade_long_total_money_based_on_seq_num_diff[di, ti, ii]  = float(linespt[79])
            self.trade_long_avg_volume_based_on_seq_num_diff[di, ti, ii]  = float(linespt[80])
            self.trade_long_volume_based_on_seq_num_diff[di, ti, ii]  = float(linespt[81])
            self.trade_long_avg_price_based_on_seq_num_diff[di, ti, ii]  = float(linespt[82])
            self.trade_long_max_price_based_on_seq_num_diff[di, ti, ii]  = float(linespt[83])
            self.trade_long_min_price_based_on_seq_num_diff[di, ti, ii]  = float(linespt[84])
            self.trade_short_count_based_on_seq_num_diff[di, ti, ii]  = float(linespt[85])
            self.trade_short_avg_money_based_on_seq_num_diff[di, ti, ii]  = float(linespt[86])
            self.trade_short_total_money_based_on_seq_num_diff[di, ti, ii]  = float(linespt[87])
            self.trade_short_avg_volume_based_on_seq_num_diff[di, ti, ii]  = float(linespt[88])
            self.trade_short_volume_based_on_seq_num_diff[di, ti, ii]  = float(linespt[89])
            self.trade_short_avg_price_based_on_seq_num_diff[di, ti, ii]  = float(linespt[90])
            self.trade_short_max_price_based_on_seq_num_diff[di, ti, ii]  = float(linespt[91])
            self.trade_short_min_price_based_on_seq_num_diff[di, ti, ii]  = float(linespt[92])
            self.trade_long_offer_count_based_on_interval_seconds[di, ti, ii]  = float(linespt[93])
            self.trade_long_offer_avg_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[94])
            self.trade_long_offer_total_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[95])
            self.trade_long_offer_avg_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[96])
            self.trade_long_offer_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[97])
            self.trade_long_offer_avg_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[98])
            self.trade_long_offer_max_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[99])
            self.trade_long_offer_min_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[100])
            self.trade_short_offer_count_based_on_interval_seconds[di, ti, ii]  = float(linespt[101])
            self.trade_short_offer_avg_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[102])
            self.trade_short_offer_total_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[103])
            self.trade_short_offer_avg_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[104])
            self.trade_short_offer_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[105])
            self.trade_short_offer_avg_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[106])
            self.trade_short_offer_max_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[107])
            self.trade_short_offer_min_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[108])
            self.trade_long_bid_count_based_on_interval_seconds[di, ti, ii]  = float(linespt[109])
            self.trade_long_bid_avg_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[110])
            self.trade_long_bid_total_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[111])
            self.trade_long_bid_avg_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[112])
            self.trade_long_bid_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[113])
            self.trade_long_bid_avg_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[114])
            self.trade_long_bid_max_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[115])
            self.trade_long_bid_min_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[116])
            self.trade_short_bid_count_based_on_interval_seconds[di, ti, ii]  = float(linespt[117])
            self.trade_short_bid_avg_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[118])
            self.trade_short_bid_total_money_based_on_interval_seconds[di, ti, ii]  = float(linespt[119])
            self.trade_short_bid_avg_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[120])
            self.trade_short_bid_volume_based_on_interval_seconds[di, ti, ii]  = float(linespt[121])
            self.trade_short_bid_avg_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[122])
            self.trade_short_bid_max_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[123])
            self.trade_short_bid_min_price_based_on_interval_seconds[di, ti, ii]  = float(linespt[124])
            self.trade_avg_offer_interval_seconds[di, ti, ii]  = float(linespt[125])
            self.trade_max_offer_interval_seconds[di, ti, ii]  = float(linespt[126])
            self.trade_min_offer_interval_seconds[di, ti, ii]  = float(linespt[127])
            self.trade_stddev_offer_interval_seconds[di, ti, ii]  = float(linespt[128])
            self.trade_avg_bid_interval_seconds[di, ti, ii]  = float(linespt[129])
            self.trade_max_bid_interval_seconds[di, ti, ii]  = float(linespt[130])
            self.trade_min_bid_interval_seconds[di, ti, ii]  = float(linespt[131])
            self.trade_stddev_bid_interval_seconds[di, ti, ii]  = float(linespt[132])
            #self.avg_bid_price[di, ti, ii]  = float(linespt[133])
            #self.min_bid_price[di, ti, ii]  = float(linespt[134])
            #self.max_bid_price[di, ti, ii]  = float(linespt[135])
            #self.stddev_bid_price[di, ti, ii]  = float(linespt[136])
            #self.avg_offer_price[di, ti, ii]  = float(linespt[137])
            #self.min_offer_price[di, ti, ii]  = float(linespt[138])
            #self.max_offer_price[di, ti, ii]  = float(linespt[139])
            #self.stddev_offer_price[di, ti, ii]  = float(linespt[140])
            #self.overbuy_count[di, ti, ii]  = float(linespt[141])
            #self.oversell_count[di, ti, ii]  = float(linespt[142])
            #self.overbuy_volume[di, ti, ii]  = float(linespt[143])
            #self.oversell_volume[di, ti, ii]  = float(linespt[144])
            #self.total_trade_offer_diff[di, ti, ii]  = float(linespt[145])
            #self.total_trade_bid_diff[di, ti, ii]  = float(linespt[146])
            #self.trade_cancel_count[di, ti, ii]  = float(linespt[147])
            #self.cancelled_volume[di, ti, ii]  = float(linespt[148])
            #self.cancelled_buy_trade_count[di, ti, ii]  = float(linespt[149])
            #self.cancelled_sell_trade_count[di, ti, ii]  = float(linespt[150])
            #self.order_total_volume[di, ti, ii]  = float(linespt[151])
            #self.order_total_money[di, ti, ii]  = float(linespt[152])
            #self.order_count[di, ti, ii]  = float(linespt[153])
            #self.order_avg_price[di, ti, ii]  = float(linespt[154])
            #self.order_min_price[di, ti, ii]  = float(linespt[155])
            #self.order_max_price[di, ti, ii]  = float(linespt[156])
            #self.std_price[di, ti, ii]  = float(linespt[157])
            #self.order_price_p10[di, ti, ii]  = float(linespt[158])
            #self.order_price_p20[di, ti, ii]  = float(linespt[159])
            #self.order_price_p30[di, ti, ii]  = float(linespt[160])
            #self.order_price_p40[di, ti, ii]  = float(linespt[161])
            #self.order_price_p50[di, ti, ii]  = float(linespt[162])
            #self.order_price_p60[di, ti, ii]  = float(linespt[163])
            #self.order_price_p70[di, ti, ii]  = float(linespt[164])
            #self.order_price_p80[di, ti, ii]  = float(linespt[165])
            #self.order_price_p90[di, ti, ii]  = float(linespt[166])
            #self.order_avg_volume[di, ti, ii]  = float(linespt[167])
            #self.order_max_volume[di, ti, ii]  = float(linespt[168])
            #self.order_min_volume[di, ti, ii]  = float(linespt[169])
            #self.order_std_volume[di, ti, ii]  = float(linespt[170])
            #self.order_avg_money[di, ti, ii]  = float(linespt[171])
            #self.order_max_money[di, ti, ii]  = float(linespt[172])
            #self.order_min_money[di, ti, ii]  = float(linespt[173])
            #self.order_buy_count[di, ti, ii]  = float(linespt[174])
            #self.order_buy_avg_money[di, ti, ii]  = float(linespt[175])
            #self.order_buy_total_money[di, ti, ii]  = float(linespt[176])
            #self.order_buy_avg_volume[di, ti, ii]  = float(linespt[177])
            #self.order_buy_volume[di, ti, ii]  = float(linespt[178])
            #self.order_buy_avg_price[di, ti, ii]  = float(linespt[179])
            #self.order_buy_max_price[di, ti, ii]  = float(linespt[180])
            #self.order_buy_min_price[di, ti, ii]  = float(linespt[181])
            #self.order_sell_count[di, ti, ii]  = float(linespt[182])
            #self.order_sell_avg_money[di, ti, ii]  = float(linespt[183])
            #self.order_sell_total_money[di, ti, ii]  = float(linespt[184])
            #self.order_sell_avg_volume[di, ti, ii]  = float(linespt[185])
            #self.order_sell_volume[di, ti, ii]  = float(linespt[186])
            #self.order_sell_avg_price[di, ti, ii]  = float(linespt[187])
            #self.order_sell_max_price[di, ti, ii]  = float(linespt[188])
            #self.order_sell_min_price[di, ti, ii]  = float(linespt[189])
            #self.order_first_interval_seconds[di, ti, ii]  = float(linespt[190])
            #self.order_last_interval_seconds[di, ti, ii]  = float(linespt[191])
            #self.order_big_count_based_on_order_money[di, ti, ii]  = float(linespt[192])
            #self.order_big_avg_money_based_on_order_money[di, ti, ii]  = float(linespt[193])
            #self.order_big_total_money_based_on_order_money[di, ti, ii]  = float(linespt[194])
            #self.order_big_avg_volume_based_on_order_money[di, ti, ii]  = float(linespt[195])
            #self.order_big_volume_based_on_order_money[di, ti, ii]  = float(linespt[196])
            #self.order_big_avg_price_based_on_order_money[di, ti, ii]  = float(linespt[197])
            #self.order_big_max_price_based_on_order_money[di, ti, ii]  = float(linespt[198])
            #self.order_big_min_price_based_on_order_money[di, ti, ii]  = float(linespt[199])
            #self.order_small_count_based_on_order_money[di, ti, ii]  = float(linespt[200])
            #self.order_small_avg_money_based_on_order_money[di, ti, ii]  = float(linespt[201])
            #self.order_small_total_money_based_on_order_money[di, ti, ii]  = float(linespt[202])
            #self.order_small_avg_volume_based_on_order_money[di, ti, ii]  = float(linespt[203])
            #self.order_small_volume_based_on_order_money[di, ti, ii]  = float(linespt[204])
            #self.order_small_avg_price_based_on_order_money[di, ti, ii]  = float(linespt[205])
            #self.order_small_max_price_based_on_order_money[di, ti, ii]  = float(linespt[206])
            #self.order_small_min_price_based_on_order_money[di, ti, ii]  = float(linespt[207])
            #self.cancelled_order_total_volume[di, ti, ii]  = float(linespt[208])
            #self.cancelled_order_total_money[di, ti, ii]  = float(linespt[209])
            #self.pe1[di, ti, ii]  = float(linespt[210])
            #self.up_limit_px[di, ti, ii]  = float(linespt[211])
            #self.down_limit_px[di, ti, ii]  = float(linespt[212])
            updated += 1
        infile.close()
        print('[ %s ] Updated %d stocks on day %d' %  (self.tag, updated, uv.Dates[di]))
        return


