
from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np
import pandas as pd
import os
import operator
import csv

class DmgrYF169(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.dataPath = None
        self.backfill = False
        self.log_return_5_sum = NIO_CUBE()
        self.wap_5_mean = NIO_CUBE()
        self.wap_7_sum = NIO_CUBE()
        self.wap_7_std = NIO_CUBE()
        self.log_return_offer_3_std = NIO_CUBE()
        self.log_return_offer_0_mean = NIO_CUBE()
        self.log_return_1_realized_volatility = NIO_CUBE()
        self.wap_4_mean = NIO_CUBE()
        self.wap_5_std = NIO_CUBE()
        self.wap_2_mean = NIO_CUBE()
        self.wap_5_sum = NIO_CUBE()
        self.wap_6_std = NIO_CUBE()
        self.wap_0_sum = NIO_CUBE()
        self.wap_9_sum = NIO_CUBE()
        self.wap_0_std = NIO_CUBE()
        self.wap_4_sum = NIO_CUBE()
        self.log_return_2_realized_volatility = NIO_CUBE()
        self.log_return_offer_0_sum = NIO_CUBE()
        self.log_return_0_realized_volatility = NIO_CUBE()
        self.log_return_9_sum = NIO_CUBE()
        self.wap_8_std = NIO_CUBE()
        self.log_return_2_sum = NIO_CUBE()
        self.log_return_0_sum = NIO_CUBE()
        self.log_return_offer_4_realized_volatility = NIO_CUBE()
        self.log_return_bid_4_std = NIO_CUBE()
        self.wap_1_std = NIO_CUBE()
        self.wap_4_std = NIO_CUBE()
        self.wap_2_std = NIO_CUBE()
        self.log_return_4_realized_volatility = NIO_CUBE()
        self.wap_1_mean = NIO_CUBE()
        self.wap_3_mean = NIO_CUBE()
        self.log_return_2_mean = NIO_CUBE()
        self.realized_volatility = NIO_CUBE()
        self.wap_8_sum = NIO_CUBE()
        self.log_return_offer_0_realized_volatility = NIO_CUBE()
        self.wap_1_sum = NIO_CUBE()
        self.wap_3_std = NIO_CUBE()
        self.wap_8_mean = NIO_CUBE()
        self.wap_6_mean = NIO_CUBE()
        self.log_return_7_std = NIO_CUBE()
        self.wap_3_sum = NIO_CUBE()
        self.log_return_offer_1_sum = NIO_CUBE()
        self.wap_9_mean = NIO_CUBE()
        self.log_return_7_mean = NIO_CUBE()
        self.log_return_offer_7_realized_volatility = NIO_CUBE()
        self.log_return_7_sum = NIO_CUBE()
        self.log_return_0_std = NIO_CUBE()
        self.log_return_6_sum = NIO_CUBE()
        self.log_return_4_std = NIO_CUBE()
        self.log_return_5_realized_volatility = NIO_CUBE()
        self.log_return_offer_6_std = NIO_CUBE()
        self.wap_7_mean = NIO_CUBE()
        self.log_return_4_mean = NIO_CUBE()
        self.log_return_1_mean = NIO_CUBE()
        self.log_return_1_sum = NIO_CUBE()
        self.log_return_offer_4_sum = NIO_CUBE()
        self.log_return_5_mean = NIO_CUBE()
        self.wap_9_std = NIO_CUBE()
        self.log_return_1_std = NIO_CUBE()
        self.wap_6_sum = NIO_CUBE()
        self.log_return_offer_9_sum = NIO_CUBE()
        self.wap_2_sum = NIO_CUBE()
        self.log_return_0_mean = NIO_CUBE()
        self.wap_0_mean = NIO_CUBE()
        self.log_return_bid_1_realized_volatility = NIO_CUBE()
        self.log_return_offer_3_mean = NIO_CUBE()
        self.log_return_9_mean = NIO_CUBE()
        self.log_return_6_realized_volatility = NIO_CUBE()
        self.log_return_4_sum = NIO_CUBE()
        self.log_return_offer_3_realized_volatility = NIO_CUBE()
        self.log_return_offer_2_mean = NIO_CUBE()
        self.log_return_3_std = NIO_CUBE()
        self.log_return_6_mean = NIO_CUBE()
        self.log_return_8_mean = NIO_CUBE()
        self.log_return_bid_7_realized_volatility = NIO_CUBE()
        self.log_return_offer_1_std = NIO_CUBE()
        self.log_return_offer_5_realized_volatility = NIO_CUBE()
        self.log_return_bid_8_realized_volatility = NIO_CUBE()
        self.log_return_6_std = NIO_CUBE()
        self.log_return_bid_9_std = NIO_CUBE()
        self.log_return_offer_6_realized_volatility = NIO_CUBE()
        self.log_return_9_realized_volatility = NIO_CUBE()
        self.log_return_5_std = NIO_CUBE()
        self.log_return_offer_9_std = NIO_CUBE()
        self.log_return_bid_0_realized_volatility = NIO_CUBE()
        self.total_volume_sum = NIO_CUBE()
        self.log_return_offer_2_std = NIO_CUBE()
        self.log_return_bid_6_realized_volatility = NIO_CUBE()
        self.log_return_3_mean = NIO_CUBE()
        self.log_return_8_realized_volatility = NIO_CUBE()
        self.log_return_offer_0_std = NIO_CUBE()
        self.log_return_bid_0_std = NIO_CUBE()
        self.log_return_offer_5_sum = NIO_CUBE()
        self.log_return_9_std = NIO_CUBE()
        self.log_return_bid_2_mean = NIO_CUBE()
        self.log_return_8_sum = NIO_CUBE()
        self.log_return_offer_9_mean = NIO_CUBE()
        self.log_return_bid_2_realized_volatility = NIO_CUBE()
        self.log_return_bid_1_sum = NIO_CUBE()
        self.log_return_bid_8_sum = NIO_CUBE()
        self.log_return_offer_1_realized_volatility = NIO_CUBE()
        self.log_return_bid_3_mean = NIO_CUBE()
        self.log_return_7_realized_volatility = NIO_CUBE()
        self.offer_spread_mean = NIO_CUBE()
        self.log_return_bid_3_std = NIO_CUBE()
        self.log_return_offer_6_mean = NIO_CUBE()
        self.log_return_bid_3_sum = NIO_CUBE()
        self.log_return_offer_8_mean = NIO_CUBE()
        self.wap_balance_std = NIO_CUBE()
        self.log_return_bid_2_sum = NIO_CUBE()
        self.log_return_bid_3_realized_volatility = NIO_CUBE()
        self.log_return_offer_3_sum = NIO_CUBE()
        self.log_return_offer_4_std = NIO_CUBE()
        self.log_return_bid_7_std = NIO_CUBE()
        self.log_return_offer_1_mean = NIO_CUBE()
        self.log_return_3_sum = NIO_CUBE()
        self.log_return_bid_1_std = NIO_CUBE()
        self.log_return_offer_7_mean = NIO_CUBE()
        self.log_return_offer_4_mean = NIO_CUBE()
        self.log_return_offer_8_sum = NIO_CUBE()
        self.log_return_bid_6_sum = NIO_CUBE()
        self.log_return_2_std = NIO_CUBE()
        self.total_volume_std = NIO_CUBE()
        self.log_return_3_realized_volatility = NIO_CUBE()
        self.volume_imbalance_sum = NIO_CUBE()
        self.log_return_offer_8_std = NIO_CUBE()
        self.log_return_bid_5_sum = NIO_CUBE()
        self.log_return_offer_6_sum = NIO_CUBE()
        self.log_return_offer_8_realized_volatility = NIO_CUBE()
        self.log_return_bid_1_mean = NIO_CUBE()
        self.log_return_bid_9_realized_volatility = NIO_CUBE()
        self.log_return_bid_5_std = NIO_CUBE()
        self.log_return_offer_2_sum = NIO_CUBE()
        self.log_return_offer_7_sum = NIO_CUBE()
        self.log_return_offer_5_mean = NIO_CUBE()
        self.log_return_bid_4_mean = NIO_CUBE()
        self.log_return_bid_0_mean = NIO_CUBE()
        self.log_return_8_std = NIO_CUBE()
        self.bid_spread_sum = NIO_CUBE()
        self.log_return_bid_8_mean = NIO_CUBE()
        self.log_return_bid_9_mean = NIO_CUBE()
        self.bid_spread_mean = NIO_CUBE()
        self.log_return_bid_8_std = NIO_CUBE()
        self.offer_spread_sum = NIO_CUBE()
        self.volume_imbalance_mean = NIO_CUBE()
        self.log_return_offer_5_std = NIO_CUBE()
        self.log_return_bid_7_sum = NIO_CUBE()
        self.log_return_offer_2_realized_volatility = NIO_CUBE()
        self.log_return_bid_5_realized_volatility = NIO_CUBE()
        self.offer_spread_std = NIO_CUBE()
        self.log_return_offer_7_std = NIO_CUBE()
        self.total_volume_mean = NIO_CUBE()
        self.log_return_bid_2_std = NIO_CUBE()
        self.log_return_offer_9_realized_volatility = NIO_CUBE()
        self.log_return_bid_4_realized_volatility = NIO_CUBE()
        self.log_return_bid_9_sum = NIO_CUBE()
        self.log_return_bid_0_sum = NIO_CUBE()
        self.log_return_bid_6_mean = NIO_CUBE()
        self.log_return_bid_6_std = NIO_CUBE()
        self.price_spread_std = NIO_CUBE()
        self.wap_balance_mean = NIO_CUBE()
        self.log_return_bid_4_sum = NIO_CUBE()
        self.wap_balance_sum = NIO_CUBE()
        self.log_return_bid_5_mean = NIO_CUBE()
        self.volume_imbalance_std = NIO_CUBE()
        self.price_spread_mean = NIO_CUBE()
        self.log_return_bid_7_mean = NIO_CUBE()
        self.price_spread_sum = NIO_CUBE()
        self.bid_spread_std = NIO_CUBE()
        self.date_time_count = NIO_CUBE()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.dataPath = cfg.getAttributeString('dataPath')
        self.backfill = cfg.getAttributeDefault('backfill', False)
        self.addData(self.log_return_5_sum,self.tag + '.log_return_5_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_5_mean,self.tag + '.wap_5_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_7_sum,self.tag + '.wap_7_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_7_std,self.tag + '.wap_7_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_3_std,self.tag + '.log_return_offer_3_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_0_mean,self.tag + '.log_return_offer_0_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_1_realized_volatility,self.tag + '.log_return_1_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_4_mean,self.tag + '.wap_4_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_5_std,self.tag + '.wap_5_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_2_mean,self.tag + '.wap_2_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_5_sum,self.tag + '.wap_5_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_6_std,self.tag + '.wap_6_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_0_sum,self.tag + '.wap_0_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_9_sum,self.tag + '.wap_9_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_0_std,self.tag + '.wap_0_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_4_sum,self.tag + '.wap_4_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_2_realized_volatility,self.tag + '.log_return_2_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_0_sum,self.tag + '.log_return_offer_0_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_0_realized_volatility,self.tag + '.log_return_0_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_9_sum,self.tag + '.log_return_9_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_8_std,self.tag + '.wap_8_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_2_sum,self.tag + '.log_return_2_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_0_sum,self.tag + '.log_return_0_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_4_realized_volatility,self.tag + '.log_return_offer_4_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_4_std,self.tag + '.log_return_bid_4_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_1_std,self.tag + '.wap_1_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_4_std,self.tag + '.wap_4_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_2_std,self.tag + '.wap_2_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_4_realized_volatility,self.tag + '.log_return_4_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_1_mean,self.tag + '.wap_1_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_3_mean,self.tag + '.wap_3_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_2_mean,self.tag + '.log_return_2_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.realized_volatility,self.tag + '.realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_8_sum,self.tag + '.wap_8_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_0_realized_volatility,self.tag + '.log_return_offer_0_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_1_sum,self.tag + '.wap_1_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_3_std,self.tag + '.wap_3_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_8_mean,self.tag + '.wap_8_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_6_mean,self.tag + '.wap_6_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_7_std,self.tag + '.log_return_7_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_3_sum,self.tag + '.wap_3_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_1_sum,self.tag + '.log_return_offer_1_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_9_mean,self.tag + '.wap_9_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_7_mean,self.tag + '.log_return_7_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_7_realized_volatility,self.tag + '.log_return_offer_7_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_7_sum,self.tag + '.log_return_7_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_0_std,self.tag + '.log_return_0_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_6_sum,self.tag + '.log_return_6_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_4_std,self.tag + '.log_return_4_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_5_realized_volatility,self.tag + '.log_return_5_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_6_std,self.tag + '.log_return_offer_6_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_7_mean,self.tag + '.wap_7_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_4_mean,self.tag + '.log_return_4_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_1_mean,self.tag + '.log_return_1_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_1_sum,self.tag + '.log_return_1_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_4_sum,self.tag + '.log_return_offer_4_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_5_mean,self.tag + '.log_return_5_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_9_std,self.tag + '.wap_9_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_1_std,self.tag + '.log_return_1_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_6_sum,self.tag + '.wap_6_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_9_sum,self.tag + '.log_return_offer_9_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_2_sum,self.tag + '.wap_2_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_0_mean,self.tag + '.log_return_0_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_0_mean,self.tag + '.wap_0_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_1_realized_volatility,self.tag + '.log_return_bid_1_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_3_mean,self.tag + '.log_return_offer_3_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_9_mean,self.tag + '.log_return_9_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_6_realized_volatility,self.tag + '.log_return_6_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_4_sum,self.tag + '.log_return_4_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_3_realized_volatility,self.tag + '.log_return_offer_3_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_2_mean,self.tag + '.log_return_offer_2_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_3_std,self.tag + '.log_return_3_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_6_mean,self.tag + '.log_return_6_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_8_mean,self.tag + '.log_return_8_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_7_realized_volatility,self.tag + '.log_return_bid_7_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_1_std,self.tag + '.log_return_offer_1_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_5_realized_volatility,self.tag + '.log_return_offer_5_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_8_realized_volatility,self.tag + '.log_return_bid_8_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_6_std,self.tag + '.log_return_6_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_9_std,self.tag + '.log_return_bid_9_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_6_realized_volatility,self.tag + '.log_return_offer_6_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_9_realized_volatility,self.tag + '.log_return_9_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_5_std,self.tag + '.log_return_5_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_9_std,self.tag + '.log_return_offer_9_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_0_realized_volatility,self.tag + '.log_return_bid_0_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.total_volume_sum,self.tag + '.total_volume_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_2_std,self.tag + '.log_return_offer_2_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_6_realized_volatility,self.tag + '.log_return_bid_6_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_3_mean,self.tag + '.log_return_3_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_8_realized_volatility,self.tag + '.log_return_8_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_0_std,self.tag + '.log_return_offer_0_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_0_std,self.tag + '.log_return_bid_0_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_5_sum,self.tag + '.log_return_offer_5_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_9_std,self.tag + '.log_return_9_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_2_mean,self.tag + '.log_return_bid_2_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_8_sum,self.tag + '.log_return_8_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_9_mean,self.tag + '.log_return_offer_9_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_2_realized_volatility,self.tag + '.log_return_bid_2_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_1_sum,self.tag + '.log_return_bid_1_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_8_sum,self.tag + '.log_return_bid_8_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_1_realized_volatility,self.tag + '.log_return_offer_1_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_3_mean,self.tag + '.log_return_bid_3_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_7_realized_volatility,self.tag + '.log_return_7_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.offer_spread_mean,self.tag + '.offer_spread_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_3_std,self.tag + '.log_return_bid_3_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_6_mean,self.tag + '.log_return_offer_6_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_3_sum,self.tag + '.log_return_bid_3_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_8_mean,self.tag + '.log_return_offer_8_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_balance_std,self.tag + '.wap_balance_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_2_sum,self.tag + '.log_return_bid_2_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_3_realized_volatility,self.tag + '.log_return_bid_3_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_3_sum,self.tag + '.log_return_offer_3_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_4_std,self.tag + '.log_return_offer_4_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_7_std,self.tag + '.log_return_bid_7_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_1_mean,self.tag + '.log_return_offer_1_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_3_sum,self.tag + '.log_return_3_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_1_std,self.tag + '.log_return_bid_1_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_7_mean,self.tag + '.log_return_offer_7_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_4_mean,self.tag + '.log_return_offer_4_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_8_sum,self.tag + '.log_return_offer_8_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_6_sum,self.tag + '.log_return_bid_6_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_2_std,self.tag + '.log_return_2_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.total_volume_std,self.tag + '.total_volume_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_3_realized_volatility,self.tag + '.log_return_3_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.volume_imbalance_sum,self.tag + '.volume_imbalance_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_8_std,self.tag + '.log_return_offer_8_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_5_sum,self.tag + '.log_return_bid_5_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_6_sum,self.tag + '.log_return_offer_6_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_8_realized_volatility,self.tag + '.log_return_offer_8_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_1_mean,self.tag + '.log_return_bid_1_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_9_realized_volatility,self.tag + '.log_return_bid_9_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_5_std,self.tag + '.log_return_bid_5_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_2_sum,self.tag + '.log_return_offer_2_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_7_sum,self.tag + '.log_return_offer_7_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_5_mean,self.tag + '.log_return_offer_5_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_4_mean,self.tag + '.log_return_bid_4_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_0_mean,self.tag + '.log_return_bid_0_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_8_std,self.tag + '.log_return_8_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.bid_spread_sum,self.tag + '.bid_spread_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_8_mean,self.tag + '.log_return_bid_8_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_9_mean,self.tag + '.log_return_bid_9_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.bid_spread_mean,self.tag + '.bid_spread_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_8_std,self.tag + '.log_return_bid_8_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.offer_spread_sum,self.tag + '.offer_spread_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.volume_imbalance_mean,self.tag + '.volume_imbalance_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_5_std,self.tag + '.log_return_offer_5_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_7_sum,self.tag + '.log_return_bid_7_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_2_realized_volatility,self.tag + '.log_return_offer_2_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_5_realized_volatility,self.tag + '.log_return_bid_5_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.offer_spread_std,self.tag + '.offer_spread_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_7_std,self.tag + '.log_return_offer_7_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.total_volume_mean,self.tag + '.total_volume_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_2_std,self.tag + '.log_return_bid_2_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_offer_9_realized_volatility,self.tag + '.log_return_offer_9_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_4_realized_volatility,self.tag + '.log_return_bid_4_realized_volatility', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_9_sum,self.tag + '.log_return_bid_9_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_0_sum,self.tag + '.log_return_bid_0_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_6_mean,self.tag + '.log_return_bid_6_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_6_std,self.tag + '.log_return_bid_6_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.price_spread_std,self.tag + '.price_spread_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_balance_mean,self.tag + '.wap_balance_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_4_sum,self.tag + '.log_return_bid_4_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.wap_balance_sum,self.tag + '.wap_balance_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_5_mean,self.tag + '.log_return_bid_5_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.volume_imbalance_std,self.tag + '.volume_imbalance_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.price_spread_mean,self.tag + '.price_spread_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.log_return_bid_7_mean,self.tag + '.log_return_bid_7_mean', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.price_spread_sum,self.tag + '.price_spread_sum', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.bid_spread_std,self.tag + '.bid_spread_std', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        self.addData(self.date_time_count,self.tag + '.date_time_count', len(uv.Dates), len(uv.Instruments), uv.INTRADAY_STEPS_5M) 
        return

    def loadDay(self, di):
        self.fillnan(di)  # set default value
        if di == len(uv.Dates) - 1:
            return
        if di > 1 and self.backfill:  # backfill
            self.doBackfill(di)
        filepath = os.path.join(self.dataPath, '%d' % uv.Dates[di])
        if not os.path.isfile(filepath):
            print('[ %s ] %s missing on day %d' %  (self.tag, filepath, uv.Dates[di]))
            return
        infile = open(filepath, 'r')
        infile.readline() # skip title line
        updated = 0
        for line in infile:
            linespt = line.strip('\n').split(',')
            # a field could be blank if its value is missing
            linespt = [np.nan if x == '' else x for x in linespt]
            ticker = linespt[4][0:6]
            ii = uv.Instruments.lookup(ticker)
            if ii < 0:
                continue
            self.log_return_5_sum[di, ti, ii]  = float(linespt[0])
            self.wap_5_mean[di, ti, ii]  = float(linespt[1])
            self.wap_7_sum[di, ti, ii]  = float(linespt[2])
            self.wap_7_std[di, ti, ii]  = float(linespt[3])
            self.log_return_offer_3_std[di, ti, ii]  = float(linespt[4])
            self.log_return_offer_0_mean[di, ti, ii]  = float(linespt[5])
            self.log_return_1_realized_volatility[di, ti, ii]  = float(linespt[6])
            self.wap_4_mean[di, ti, ii]  = float(linespt[7])
            self.wap_5_std[di, ti, ii]  = float(linespt[8])
            self.wap_2_mean[di, ti, ii]  = float(linespt[9])
            self.wap_5_sum[di, ti, ii]  = float(linespt[10])
            self.wap_6_std[di, ti, ii]  = float(linespt[11])
            self.wap_0_sum[di, ti, ii]  = float(linespt[12])
            self.wap_9_sum[di, ti, ii]  = float(linespt[13])
            self.wap_0_std[di, ti, ii]  = float(linespt[14])
            self.wap_4_sum[di, ti, ii]  = float(linespt[15])
            self.log_return_2_realized_volatility[di, ti, ii]  = float(linespt[16])
            self.log_return_offer_0_sum[di, ti, ii]  = float(linespt[17])
            self.log_return_0_realized_volatility[di, ti, ii]  = float(linespt[18])
            self.log_return_9_sum[di, ti, ii]  = float(linespt[19])
            self.wap_8_std[di, ti, ii]  = float(linespt[20])
            self.log_return_2_sum[di, ti, ii]  = float(linespt[21])
            self.log_return_0_sum[di, ti, ii]  = float(linespt[22])
            self.log_return_offer_4_realized_volatility[di, ti, ii]  = float(linespt[23])
            self.log_return_bid_4_std[di, ti, ii]  = float(linespt[24])
            self.wap_1_std[di, ti, ii]  = float(linespt[25])
            self.wap_4_std[di, ti, ii]  = float(linespt[26])
            self.wap_2_std[di, ti, ii]  = float(linespt[27])
            self.log_return_4_realized_volatility[di, ti, ii]  = float(linespt[28])
            self.wap_1_mean[di, ti, ii]  = float(linespt[29])
            self.wap_3_mean[di, ti, ii]  = float(linespt[30])
            self.log_return_2_mean[di, ti, ii]  = float(linespt[31])
            self.realized_volatility[di, ti, ii]  = float(linespt[32])
            self.wap_8_sum[di, ti, ii]  = float(linespt[33])
            self.log_return_offer_0_realized_volatility[di, ti, ii]  = float(linespt[34])
            self.wap_1_sum[di, ti, ii]  = float(linespt[35])
            self.wap_3_std[di, ti, ii]  = float(linespt[36])
            self.wap_8_mean[di, ti, ii]  = float(linespt[37])
            self.wap_6_mean[di, ti, ii]  = float(linespt[38])
            self.log_return_7_std[di, ti, ii]  = float(linespt[39])
            self.wap_3_sum[di, ti, ii]  = float(linespt[40])
            self.log_return_offer_1_sum[di, ti, ii]  = float(linespt[41])
            self.wap_9_mean[di, ti, ii]  = float(linespt[42])
            self.log_return_7_mean[di, ti, ii]  = float(linespt[43])
            self.log_return_offer_7_realized_volatility[di, ti, ii]  = float(linespt[44])
            self.log_return_7_sum[di, ti, ii]  = float(linespt[45])
            self.log_return_0_std[di, ti, ii]  = float(linespt[46])
            self.log_return_6_sum[di, ti, ii]  = float(linespt[47])
            self.log_return_4_std[di, ti, ii]  = float(linespt[48])
            self.log_return_5_realized_volatility[di, ti, ii]  = float(linespt[49])
            self.log_return_offer_6_std[di, ti, ii]  = float(linespt[50])
            self.wap_7_mean[di, ti, ii]  = float(linespt[51])
            self.log_return_4_mean[di, ti, ii]  = float(linespt[52])
            self.log_return_1_mean[di, ti, ii]  = float(linespt[53])
            self.log_return_1_sum[di, ti, ii]  = float(linespt[54])
            self.log_return_offer_4_sum[di, ti, ii]  = float(linespt[55])
            self.log_return_5_mean[di, ti, ii]  = float(linespt[56])
            self.wap_9_std[di, ti, ii]  = float(linespt[57])
            self.log_return_1_std[di, ti, ii]  = float(linespt[58])
            self.wap_6_sum[di, ti, ii]  = float(linespt[59])
            self.log_return_offer_9_sum[di, ti, ii]  = float(linespt[60])
            self.wap_2_sum[di, ti, ii]  = float(linespt[61])
            self.log_return_0_mean[di, ti, ii]  = float(linespt[62])
            self.wap_0_mean[di, ti, ii]  = float(linespt[63])
            self.log_return_bid_1_realized_volatility[di, ti, ii]  = float(linespt[64])
            self.log_return_offer_3_mean[di, ti, ii]  = float(linespt[65])
            self.log_return_9_mean[di, ti, ii]  = float(linespt[66])
            self.log_return_6_realized_volatility[di, ti, ii]  = float(linespt[67])
            self.log_return_4_sum[di, ti, ii]  = float(linespt[68])
            self.log_return_offer_3_realized_volatility[di, ti, ii]  = float(linespt[69])
            self.log_return_offer_2_mean[di, ti, ii]  = float(linespt[70])
            self.log_return_3_std[di, ti, ii]  = float(linespt[71])
            self.log_return_6_mean[di, ti, ii]  = float(linespt[72])
            self.log_return_8_mean[di, ti, ii]  = float(linespt[73])
            self.log_return_bid_7_realized_volatility[di, ti, ii]  = float(linespt[74])
            self.log_return_offer_1_std[di, ti, ii]  = float(linespt[75])
            self.log_return_offer_5_realized_volatility[di, ti, ii]  = float(linespt[76])
            self.log_return_bid_8_realized_volatility[di, ti, ii]  = float(linespt[77])
            self.log_return_6_std[di, ti, ii]  = float(linespt[78])
            self.log_return_bid_9_std[di, ti, ii]  = float(linespt[79])
            self.log_return_offer_6_realized_volatility[di, ti, ii]  = float(linespt[80])
            self.log_return_9_realized_volatility[di, ti, ii]  = float(linespt[81])
            self.log_return_5_std[di, ti, ii]  = float(linespt[82])
            self.log_return_offer_9_std[di, ti, ii]  = float(linespt[83])
            self.log_return_bid_0_realized_volatility[di, ti, ii]  = float(linespt[84])
            self.total_volume_sum[di, ti, ii]  = float(linespt[85])
            self.log_return_offer_2_std[di, ti, ii]  = float(linespt[86])
            self.log_return_bid_6_realized_volatility[di, ti, ii]  = float(linespt[87])
            self.log_return_3_mean[di, ti, ii]  = float(linespt[88])
            self.log_return_8_realized_volatility[di, ti, ii]  = float(linespt[89])
            self.log_return_offer_0_std[di, ti, ii]  = float(linespt[90])
            self.log_return_bid_0_std[di, ti, ii]  = float(linespt[91])
            self.log_return_offer_5_sum[di, ti, ii]  = float(linespt[92])
            self.log_return_9_std[di, ti, ii]  = float(linespt[93])
            self.log_return_bid_2_mean[di, ti, ii]  = float(linespt[94])
            self.log_return_8_sum[di, ti, ii]  = float(linespt[95])
            self.log_return_offer_9_mean[di, ti, ii]  = float(linespt[96])
            self.log_return_bid_2_realized_volatility[di, ti, ii]  = float(linespt[97])
            self.log_return_bid_1_sum[di, ti, ii]  = float(linespt[98])
            self.log_return_bid_8_sum[di, ti, ii]  = float(linespt[99])
            self.log_return_offer_1_realized_volatility[di, ti, ii]  = float(linespt[100])
            self.log_return_bid_3_mean[di, ti, ii]  = float(linespt[101])
            self.log_return_7_realized_volatility[di, ti, ii]  = float(linespt[102])
            self.offer_spread_mean[di, ti, ii]  = float(linespt[103])
            self.log_return_bid_3_std[di, ti, ii]  = float(linespt[104])
            self.log_return_offer_6_mean[di, ti, ii]  = float(linespt[105])
            self.log_return_bid_3_sum[di, ti, ii]  = float(linespt[106])
            self.log_return_offer_8_mean[di, ti, ii]  = float(linespt[107])
            self.wap_balance_std[di, ti, ii]  = float(linespt[108])
            self.log_return_bid_2_sum[di, ti, ii]  = float(linespt[109])
            self.log_return_bid_3_realized_volatility[di, ti, ii]  = float(linespt[110])
            self.log_return_offer_3_sum[di, ti, ii]  = float(linespt[111])
            self.log_return_offer_4_std[di, ti, ii]  = float(linespt[112])
            self.log_return_bid_7_std[di, ti, ii]  = float(linespt[113])
            self.log_return_offer_1_mean[di, ti, ii]  = float(linespt[114])
            self.log_return_3_sum[di, ti, ii]  = float(linespt[115])
            self.log_return_bid_1_std[di, ti, ii]  = float(linespt[116])
            self.log_return_offer_7_mean[di, ti, ii]  = float(linespt[117])
            self.log_return_offer_4_mean[di, ti, ii]  = float(linespt[118])
            self.log_return_offer_8_sum[di, ti, ii]  = float(linespt[119])
            self.log_return_bid_6_sum[di, ti, ii]  = float(linespt[120])
            self.log_return_2_std[di, ti, ii]  = float(linespt[122])
            self.total_volume_std[di, ti, ii]  = float(linespt[123])
            self.log_return_3_realized_volatility[di, ti, ii]  = float(linespt[124])
            self.volume_imbalance_sum[di, ti, ii]  = float(linespt[125])
            self.log_return_offer_8_std[di, ti, ii]  = float(linespt[126])
            self.log_return_bid_5_sum[di, ti, ii]  = float(linespt[127])
            self.log_return_offer_6_sum[di, ti, ii]  = float(linespt[128])
            self.log_return_offer_8_realized_volatility[di, ti, ii]  = float(linespt[129])
            self.log_return_bid_1_mean[di, ti, ii]  = float(linespt[130])
            self.log_return_bid_9_realized_volatility[di, ti, ii]  = float(linespt[131])
            self.log_return_bid_5_std[di, ti, ii]  = float(linespt[132])
            self.log_return_offer_2_sum[di, ti, ii]  = float(linespt[133])
            self.log_return_offer_7_sum[di, ti, ii]  = float(linespt[134])
            self.log_return_offer_5_mean[di, ti, ii]  = float(linespt[135])
            self.log_return_bid_4_mean[di, ti, ii]  = float(linespt[136])
            self.log_return_bid_0_mean[di, ti, ii]  = float(linespt[137])
            self.log_return_8_std[di, ti, ii]  = float(linespt[138])
            self.bid_spread_sum[di, ti, ii]  = float(linespt[139])
            self.log_return_bid_8_mean[di, ti, ii]  = float(linespt[140])
            self.log_return_bid_9_mean[di, ti, ii]  = float(linespt[141])
            self.bid_spread_mean[di, ti, ii]  = float(linespt[142])
            self.log_return_bid_8_std[di, ti, ii]  = float(linespt[143])
            self.offer_spread_sum[di, ti, ii]  = float(linespt[144])
            self.volume_imbalance_mean[di, ti, ii]  = float(linespt[145])
            self.log_return_offer_5_std[di, ti, ii]  = float(linespt[146])
            self.log_return_bid_7_sum[di, ti, ii]  = float(linespt[147])
            self.log_return_offer_2_realized_volatility[di, ti, ii]  = float(linespt[148])
            self.log_return_bid_5_realized_volatility[di, ti, ii]  = float(linespt[149])
            self.offer_spread_std[di, ti, ii]  = float(linespt[150])
            self.log_return_offer_7_std[di, ti, ii]  = float(linespt[151])
            self.total_volume_mean[di, ti, ii]  = float(linespt[152])
            self.log_return_bid_2_std[di, ti, ii]  = float(linespt[153])
            self.log_return_offer_9_realized_volatility[di, ti, ii]  = float(linespt[154])
            self.log_return_bid_4_realized_volatility[di, ti, ii]  = float(linespt[155])
            self.log_return_bid_9_sum[di, ti, ii]  = float(linespt[156])
            self.log_return_bid_0_sum[di, ti, ii]  = float(linespt[157])
            self.log_return_bid_6_mean[di, ti, ii]  = float(linespt[158])
            self.log_return_bid_6_std[di, ti, ii]  = float(linespt[159])
            self.price_spread_std[di, ti, ii]  = float(linespt[160])
            self.wap_balance_mean[di, ti, ii]  = float(linespt[161])
            self.log_return_bid_4_sum[di, ti, ii]  = float(linespt[162])
            self.wap_balance_sum[di, ti, ii]  = float(linespt[163])
            self.log_return_bid_5_mean[di, ti, ii]  = float(linespt[164])
            self.volume_imbalance_std[di, ti, ii]  = float(linespt[165])
            self.price_spread_mean[di, ti, ii]  = float(linespt[166])
            self.log_return_bid_7_mean[di, ti, ii]  = float(linespt[167])
            self.price_spread_sum[di, ti, ii]  = float(linespt[168])
            self.bid_spread_std[di, ti, ii]  = float(linespt[169])
            self.date_time_count[di, ti, ii]  = float(linespt[170])
            updated += 1
        infile.close()
        print('[ %s ] Updated %d stocks on day %d' %  (self.tag, updated, uv.Dates[di]))
        return


