from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrSli0206(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.high_price_range_avg_vol_per_trade_ratio_10pct = NIO_MATRIX()
        self.high_price_range_avg_vol_per_trade_ratio_20pct = NIO_MATRIX()
        self.illiquidity_improved = NIO_MATRIX()
        self.low_price_range_avg_vol_per_trade_ratio_10pct = NIO_MATRIX()
        self.low_price_range_avg_vol_per_trade_ratio_20pct = NIO_MATRIX()
        self.max_spread_absolute = NIO_MATRIX()
        self.min_spread_absolute = NIO_MATRIX()
        self.open_15m_ttrades_ratio = NIO_MATRIX()
        self.open_15m_ttv_ratio = NIO_MATRIX()
        self.open_30m_ttrades_ratio = NIO_MATRIX()
        self.open_30m_ttv_ratio = NIO_MATRIX()
        self.open_5m_ttrades_ratio = NIO_MATRIX()
        self.open_5m_ttv_ratio = NIO_MATRIX()
        self.open_60m_ttrades_ratio = NIO_MATRIX()
        self.open_60m_ttv_ratio = NIO_MATRIX()
        self.return_kurtosis = NIO_MATRIX()
        self.return_skewness = NIO_MATRIX()
        self.return_std_high_vol = NIO_MATRIX()
        self.return_std_imp = NIO_MATRIX()
        self.return_std_imp_low_vol = NIO_MATRIX()
        self.return_std_low_vol = NIO_MATRIX()
        self.return_variance = NIO_MATRIX()
        self.reverse_imp_neg = NIO_MATRIX()
        self.reverse_imp_neg_low_vol = NIO_MATRIX()
        self.reverse_imp_pos = NIO_MATRIX()
        self.reverse_imp_pos_low_vol = NIO_MATRIX()
        self.std_spread_absolute = NIO_MATRIX()
        self.ttrades_ratio_close5m = NIO_MATRIX()
        self.ttrades_ratio_tail_excl5m = NIO_MATRIX()
        self.ttv_ratio_close5m = NIO_MATRIX()
        self.ttv_ratio_tail_excl5m = NIO_MATRIX()
        self.tvol_ratio_close5m = NIO_MATRIX()
        self.tvol_ratio_tail_excl5m = NIO_MATRIX()
        self.vol_price_corr = NIO_MATRIX()
        self.vol_return_corr = NIO_MATRIX()
        self.vroc_10m = NIO_MATRIX()
        self.vroc_15m = NIO_MATRIX()
        self.vroc_1m = NIO_MATRIX()
        self.vroc_30m = NIO_MATRIX()
        self.vroc_3m = NIO_MATRIX()
        self.vroc_5m = NIO_MATRIX()
        self.vroc_60m = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.high_price_range_avg_vol_per_trade_ratio_10pct, 'sli_0206.high_price_range_avg_vol_per_trade_ratio_10pct')
        self.addDailyData(self.high_price_range_avg_vol_per_trade_ratio_20pct, 'sli_0206.high_price_range_avg_vol_per_trade_ratio_20pct')
        self.addDailyData(self.illiquidity_improved, 'sli_0206.illiquidity_improved')
        self.addDailyData(self.low_price_range_avg_vol_per_trade_ratio_10pct, 'sli_0206.low_price_range_avg_vol_per_trade_ratio_10pct')
        self.addDailyData(self.low_price_range_avg_vol_per_trade_ratio_20pct, 'sli_0206.low_price_range_avg_vol_per_trade_ratio_20pct')
        self.addDailyData(self.max_spread_absolute, 'sli_0206.max_spread_absolute')
        self.addDailyData(self.min_spread_absolute, 'sli_0206.min_spread_absolute')
        self.addDailyData(self.open_15m_ttrades_ratio, 'sli_0206.open_15m_ttrades_ratio')
        self.addDailyData(self.open_15m_ttv_ratio, 'sli_0206.open_15m_ttv_ratio')
        self.addDailyData(self.open_30m_ttrades_ratio, 'sli_0206.open_30m_ttrades_ratio')
        self.addDailyData(self.open_30m_ttv_ratio, 'sli_0206.open_30m_ttv_ratio')
        self.addDailyData(self.open_5m_ttrades_ratio, 'sli_0206.open_5m_ttrades_ratio')
        self.addDailyData(self.open_5m_ttv_ratio, 'sli_0206.open_5m_ttv_ratio')
        self.addDailyData(self.open_60m_ttrades_ratio, 'sli_0206.open_60m_ttrades_ratio')
        self.addDailyData(self.open_60m_ttv_ratio, 'sli_0206.open_60m_ttv_ratio')
        self.addDailyData(self.return_kurtosis, 'sli_0206.return_kurtosis')
        self.addDailyData(self.return_skewness, 'sli_0206.return_skewness')
        self.addDailyData(self.return_std_high_vol, 'sli_0206.return_std_high_vol')
        self.addDailyData(self.return_std_imp, 'sli_0206.return_std_imp')
        self.addDailyData(self.return_std_imp_low_vol, 'sli_0206.return_std_imp_low_vol')
        self.addDailyData(self.return_std_low_vol, 'sli_0206.return_std_low_vol')
        self.addDailyData(self.return_variance, 'sli_0206.return_variance')
        self.addDailyData(self.reverse_imp_neg, 'sli_0206.reverse_imp_neg')
        self.addDailyData(self.reverse_imp_neg_low_vol, 'sli_0206.reverse_imp_neg_low_vol')
        self.addDailyData(self.reverse_imp_pos, 'sli_0206.reverse_imp_pos')
        self.addDailyData(self.reverse_imp_pos_low_vol, 'sli_0206.reverse_imp_pos_low_vol')
        self.addDailyData(self.std_spread_absolute, 'sli_0206.std_spread_absolute')
        self.addDailyData(self.ttrades_ratio_close5m, 'sli_0206.ttrades_ratio_close5m')
        self.addDailyData(self.ttrades_ratio_tail_excl5m, 'sli_0206.ttrades_ratio_tail_excl5m')
        self.addDailyData(self.ttv_ratio_close5m, 'sli_0206.ttv_ratio_close5m')
        self.addDailyData(self.ttv_ratio_tail_excl5m, 'sli_0206.ttv_ratio_tail_excl5m')
        self.addDailyData(self.tvol_ratio_close5m, 'sli_0206.tvol_ratio_close5m')
        self.addDailyData(self.tvol_ratio_tail_excl5m, 'sli_0206.tvol_ratio_tail_excl5m')
        self.addDailyData(self.vol_price_corr, 'sli_0206.vol_price_corr')
        self.addDailyData(self.vol_return_corr, 'sli_0206.vol_return_corr')
        self.addDailyData(self.vroc_10m, 'sli_0206.vroc_10m')
        self.addDailyData(self.vroc_15m, 'sli_0206.vroc_15m')
        self.addDailyData(self.vroc_1m, 'sli_0206.vroc_1m')
        self.addDailyData(self.vroc_30m, 'sli_0206.vroc_30m')
        self.addDailyData(self.vroc_3m, 'sli_0206.vroc_3m')
        self.addDailyData(self.vroc_5m, 'sli_0206.vroc_5m')
        self.addDailyData(self.vroc_60m, 'sli_0206.vroc_60m')
        return

    def loadDay(self, di):
        pass
