from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrSli0215(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.amt_ema_15 = NIO_MATRIX()
        self.amt_ema_3 = NIO_MATRIX()
        self.amt_ema_6 = NIO_MATRIX()
        self.amt_entropy_1m = NIO_MATRIX()
        self.amt_entropy_1m_sma_15 = NIO_MATRIX()
        self.amt_entropy_1m_sma_3 = NIO_MATRIX()
        self.amt_entropy_1m_sma_6 = NIO_MATRIX()
        self.amt_gini_1m = NIO_MATRIX()
        self.amt_gini_1m_sma_15 = NIO_MATRIX()
        self.amt_gini_1m_sma_3 = NIO_MATRIX()
        self.amt_gini_1m_sma_6 = NIO_MATRIX()
        self.amt_max_15 = NIO_MATRIX()
        self.amt_max_3 = NIO_MATRIX()
        self.amt_max_6 = NIO_MATRIX()
        self.amt_median_15 = NIO_MATRIX()
        self.amt_median_3 = NIO_MATRIX()
        self.amt_median_6 = NIO_MATRIX()
        self.amt_min_15 = NIO_MATRIX()
        self.amt_min_3 = NIO_MATRIX()
        self.amt_min_6 = NIO_MATRIX()
        self.amt_q25_15 = NIO_MATRIX()
        self.amt_q25_3 = NIO_MATRIX()
        self.amt_q25_6 = NIO_MATRIX()
        self.amt_q75_15 = NIO_MATRIX()
        self.amt_q75_3 = NIO_MATRIX()
        self.amt_q75_6 = NIO_MATRIX()
        self.amt_sma_15 = NIO_MATRIX()
        self.amt_sma_3 = NIO_MATRIX()
        self.amt_sma_6 = NIO_MATRIX()
        self.amt_smma_15 = NIO_MATRIX()
        self.amt_smma_3 = NIO_MATRIX()
        self.amt_smma_6 = NIO_MATRIX()
        self.amt_std_15 = NIO_MATRIX()
        self.amt_std_3 = NIO_MATRIX()
        self.amt_std_6 = NIO_MATRIX()
        self.amt_sum_15 = NIO_MATRIX()
        self.amt_sum_3 = NIO_MATRIX()
        self.amt_sum_6 = NIO_MATRIX()
        self.amt_wma_15 = NIO_MATRIX()
        self.amt_wma_3 = NIO_MATRIX()
        self.amt_wma_6 = NIO_MATRIX()
        self.avg_trade_amt = NIO_MATRIX()
        self.avg_trade_amt_ema_15 = NIO_MATRIX()
        self.avg_trade_amt_ema_3 = NIO_MATRIX()
        self.avg_trade_amt_ema_6 = NIO_MATRIX()
        self.avg_trade_amt_sma_15 = NIO_MATRIX()
        self.avg_trade_amt_sma_3 = NIO_MATRIX()
        self.avg_trade_amt_sma_6 = NIO_MATRIX()
        self.big_amt = NIO_MATRIX()
        self.big_amt_ema_15 = NIO_MATRIX()
        self.big_amt_ema_3 = NIO_MATRIX()
        self.big_amt_ema_6 = NIO_MATRIX()
        self.big_amt_share = NIO_MATRIX()
        self.big_amt_share_ema_15 = NIO_MATRIX()
        self.big_amt_share_ema_3 = NIO_MATRIX()
        self.big_amt_share_ema_6 = NIO_MATRIX()
        self.big_amt_share_sma_15 = NIO_MATRIX()
        self.big_amt_share_sma_3 = NIO_MATRIX()
        self.big_amt_share_sma_6 = NIO_MATRIX()
        self.big_amt_sma_15 = NIO_MATRIX()
        self.big_amt_sma_3 = NIO_MATRIX()
        self.big_amt_sma_6 = NIO_MATRIX()
        self.big_cnt_share = NIO_MATRIX()
        self.big_cnt_share_ema_15 = NIO_MATRIX()
        self.big_cnt_share_ema_3 = NIO_MATRIX()
        self.big_cnt_share_ema_6 = NIO_MATRIX()
        self.big_cnt_share_sma_15 = NIO_MATRIX()
        self.big_cnt_share_sma_3 = NIO_MATRIX()
        self.big_cnt_share_sma_6 = NIO_MATRIX()
        self.big_vol = NIO_MATRIX()
        self.big_vol_ema_15 = NIO_MATRIX()
        self.big_vol_ema_3 = NIO_MATRIX()
        self.big_vol_ema_6 = NIO_MATRIX()
        self.big_vol_share = NIO_MATRIX()
        self.big_vol_share_ema_15 = NIO_MATRIX()
        self.big_vol_share_ema_3 = NIO_MATRIX()
        self.big_vol_share_ema_6 = NIO_MATRIX()
        self.big_vol_share_sma_15 = NIO_MATRIX()
        self.big_vol_share_sma_3 = NIO_MATRIX()
        self.big_vol_share_sma_6 = NIO_MATRIX()
        self.big_vol_sma_15 = NIO_MATRIX()
        self.big_vol_sma_3 = NIO_MATRIX()
        self.big_vol_sma_6 = NIO_MATRIX()
        self.small_amt = NIO_MATRIX()
        self.small_amt_ema_15 = NIO_MATRIX()
        self.small_amt_ema_3 = NIO_MATRIX()
        self.small_amt_ema_6 = NIO_MATRIX()
        self.small_amt_sma_15 = NIO_MATRIX()
        self.small_amt_sma_3 = NIO_MATRIX()
        self.small_amt_sma_6 = NIO_MATRIX()
        self.small_vol = NIO_MATRIX()
        self.small_vol_ema_15 = NIO_MATRIX()
        self.small_vol_ema_3 = NIO_MATRIX()
        self.small_vol_ema_6 = NIO_MATRIX()
        self.small_vol_sma_15 = NIO_MATRIX()
        self.small_vol_sma_3 = NIO_MATRIX()
        self.small_vol_sma_6 = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.amt_ema_15, 'sli_0215.amt_ema_15')
        self.addDailyData(self.amt_ema_3, 'sli_0215.amt_ema_3')
        self.addDailyData(self.amt_ema_6, 'sli_0215.amt_ema_6')
        self.addDailyData(self.amt_entropy_1m, 'sli_0215.amt_entropy_1m')
        self.addDailyData(self.amt_entropy_1m_sma_15, 'sli_0215.amt_entropy_1m_sma_15')
        self.addDailyData(self.amt_entropy_1m_sma_3, 'sli_0215.amt_entropy_1m_sma_3')
        self.addDailyData(self.amt_entropy_1m_sma_6, 'sli_0215.amt_entropy_1m_sma_6')
        self.addDailyData(self.amt_gini_1m, 'sli_0215.amt_gini_1m')
        self.addDailyData(self.amt_gini_1m_sma_15, 'sli_0215.amt_gini_1m_sma_15')
        self.addDailyData(self.amt_gini_1m_sma_3, 'sli_0215.amt_gini_1m_sma_3')
        self.addDailyData(self.amt_gini_1m_sma_6, 'sli_0215.amt_gini_1m_sma_6')
        self.addDailyData(self.amt_max_15, 'sli_0215.amt_max_15')
        self.addDailyData(self.amt_max_3, 'sli_0215.amt_max_3')
        self.addDailyData(self.amt_max_6, 'sli_0215.amt_max_6')
        self.addDailyData(self.amt_median_15, 'sli_0215.amt_median_15')
        self.addDailyData(self.amt_median_3, 'sli_0215.amt_median_3')
        self.addDailyData(self.amt_median_6, 'sli_0215.amt_median_6')
        self.addDailyData(self.amt_min_15, 'sli_0215.amt_min_15')
        self.addDailyData(self.amt_min_3, 'sli_0215.amt_min_3')
        self.addDailyData(self.amt_min_6, 'sli_0215.amt_min_6')
        self.addDailyData(self.amt_q25_15, 'sli_0215.amt_q25_15')
        self.addDailyData(self.amt_q25_3, 'sli_0215.amt_q25_3')
        self.addDailyData(self.amt_q25_6, 'sli_0215.amt_q25_6')
        self.addDailyData(self.amt_q75_15, 'sli_0215.amt_q75_15')
        self.addDailyData(self.amt_q75_3, 'sli_0215.amt_q75_3')
        self.addDailyData(self.amt_q75_6, 'sli_0215.amt_q75_6')
        self.addDailyData(self.amt_sma_15, 'sli_0215.amt_sma_15')
        self.addDailyData(self.amt_sma_3, 'sli_0215.amt_sma_3')
        self.addDailyData(self.amt_sma_6, 'sli_0215.amt_sma_6')
        self.addDailyData(self.amt_smma_15, 'sli_0215.amt_smma_15')
        self.addDailyData(self.amt_smma_3, 'sli_0215.amt_smma_3')
        self.addDailyData(self.amt_smma_6, 'sli_0215.amt_smma_6')
        self.addDailyData(self.amt_std_15, 'sli_0215.amt_std_15')
        self.addDailyData(self.amt_std_3, 'sli_0215.amt_std_3')
        self.addDailyData(self.amt_std_6, 'sli_0215.amt_std_6')
        self.addDailyData(self.amt_sum_15, 'sli_0215.amt_sum_15')
        self.addDailyData(self.amt_sum_3, 'sli_0215.amt_sum_3')
        self.addDailyData(self.amt_sum_6, 'sli_0215.amt_sum_6')
        self.addDailyData(self.amt_wma_15, 'sli_0215.amt_wma_15')
        self.addDailyData(self.amt_wma_3, 'sli_0215.amt_wma_3')
        self.addDailyData(self.amt_wma_6, 'sli_0215.amt_wma_6')
        self.addDailyData(self.avg_trade_amt, 'sli_0215.avg_trade_amt')
        self.addDailyData(self.avg_trade_amt_ema_15, 'sli_0215.avg_trade_amt_ema_15')
        self.addDailyData(self.avg_trade_amt_ema_3, 'sli_0215.avg_trade_amt_ema_3')
        self.addDailyData(self.avg_trade_amt_ema_6, 'sli_0215.avg_trade_amt_ema_6')
        self.addDailyData(self.avg_trade_amt_sma_15, 'sli_0215.avg_trade_amt_sma_15')
        self.addDailyData(self.avg_trade_amt_sma_3, 'sli_0215.avg_trade_amt_sma_3')
        self.addDailyData(self.avg_trade_amt_sma_6, 'sli_0215.avg_trade_amt_sma_6')
        self.addDailyData(self.big_amt, 'sli_0215.big_amt')
        self.addDailyData(self.big_amt_ema_15, 'sli_0215.big_amt_ema_15')
        self.addDailyData(self.big_amt_ema_3, 'sli_0215.big_amt_ema_3')
        self.addDailyData(self.big_amt_ema_6, 'sli_0215.big_amt_ema_6')
        self.addDailyData(self.big_amt_share, 'sli_0215.big_amt_share')
        self.addDailyData(self.big_amt_share_ema_15, 'sli_0215.big_amt_share_ema_15')
        self.addDailyData(self.big_amt_share_ema_3, 'sli_0215.big_amt_share_ema_3')
        self.addDailyData(self.big_amt_share_ema_6, 'sli_0215.big_amt_share_ema_6')
        self.addDailyData(self.big_amt_share_sma_15, 'sli_0215.big_amt_share_sma_15')
        self.addDailyData(self.big_amt_share_sma_3, 'sli_0215.big_amt_share_sma_3')
        self.addDailyData(self.big_amt_share_sma_6, 'sli_0215.big_amt_share_sma_6')
        self.addDailyData(self.big_amt_sma_15, 'sli_0215.big_amt_sma_15')
        self.addDailyData(self.big_amt_sma_3, 'sli_0215.big_amt_sma_3')
        self.addDailyData(self.big_amt_sma_6, 'sli_0215.big_amt_sma_6')
        self.addDailyData(self.big_cnt_share, 'sli_0215.big_cnt_share')
        self.addDailyData(self.big_cnt_share_ema_15, 'sli_0215.big_cnt_share_ema_15')
        self.addDailyData(self.big_cnt_share_ema_3, 'sli_0215.big_cnt_share_ema_3')
        self.addDailyData(self.big_cnt_share_ema_6, 'sli_0215.big_cnt_share_ema_6')
        self.addDailyData(self.big_cnt_share_sma_15, 'sli_0215.big_cnt_share_sma_15')
        self.addDailyData(self.big_cnt_share_sma_3, 'sli_0215.big_cnt_share_sma_3')
        self.addDailyData(self.big_cnt_share_sma_6, 'sli_0215.big_cnt_share_sma_6')
        self.addDailyData(self.big_vol, 'sli_0215.big_vol')
        self.addDailyData(self.big_vol_ema_15, 'sli_0215.big_vol_ema_15')
        self.addDailyData(self.big_vol_ema_3, 'sli_0215.big_vol_ema_3')
        self.addDailyData(self.big_vol_ema_6, 'sli_0215.big_vol_ema_6')
        self.addDailyData(self.big_vol_share, 'sli_0215.big_vol_share')
        self.addDailyData(self.big_vol_share_ema_15, 'sli_0215.big_vol_share_ema_15')
        self.addDailyData(self.big_vol_share_ema_3, 'sli_0215.big_vol_share_ema_3')
        self.addDailyData(self.big_vol_share_ema_6, 'sli_0215.big_vol_share_ema_6')
        self.addDailyData(self.big_vol_share_sma_15, 'sli_0215.big_vol_share_sma_15')
        self.addDailyData(self.big_vol_share_sma_3, 'sli_0215.big_vol_share_sma_3')
        self.addDailyData(self.big_vol_share_sma_6, 'sli_0215.big_vol_share_sma_6')
        self.addDailyData(self.big_vol_sma_15, 'sli_0215.big_vol_sma_15')
        self.addDailyData(self.big_vol_sma_3, 'sli_0215.big_vol_sma_3')
        self.addDailyData(self.big_vol_sma_6, 'sli_0215.big_vol_sma_6')
        self.addDailyData(self.small_amt, 'sli_0215.small_amt')
        self.addDailyData(self.small_amt_ema_15, 'sli_0215.small_amt_ema_15')
        self.addDailyData(self.small_amt_ema_3, 'sli_0215.small_amt_ema_3')
        self.addDailyData(self.small_amt_ema_6, 'sli_0215.small_amt_ema_6')
        self.addDailyData(self.small_amt_sma_15, 'sli_0215.small_amt_sma_15')
        self.addDailyData(self.small_amt_sma_3, 'sli_0215.small_amt_sma_3')
        self.addDailyData(self.small_amt_sma_6, 'sli_0215.small_amt_sma_6')
        self.addDailyData(self.small_vol, 'sli_0215.small_vol')
        self.addDailyData(self.small_vol_ema_15, 'sli_0215.small_vol_ema_15')
        self.addDailyData(self.small_vol_ema_3, 'sli_0215.small_vol_ema_3')
        self.addDailyData(self.small_vol_ema_6, 'sli_0215.small_vol_ema_6')
        self.addDailyData(self.small_vol_sma_15, 'sli_0215.small_vol_sma_15')
        self.addDailyData(self.small_vol_sma_3, 'sli_0215.small_vol_sma_3')
        self.addDailyData(self.small_vol_sma_6, 'sli_0215.small_vol_sma_6')
        return

    def loadDay(self, di):
        pass
