from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrFguotrade3(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.upshadow_daily_avg_1W = NIO_MATRIX()
        self.upshadow_daily_avg_1M = NIO_MATRIX()
        self.upshadow_daily_avg_3M = NIO_MATRIX()
        self.upshadow_daily_avg_6M = NIO_MATRIX()
        self.upshadow_daily_std_1W = NIO_MATRIX()
        self.upshadow_daily_std_1M = NIO_MATRIX()
        self.upshadow_daily_std_3M = NIO_MATRIX()
        self.upshadow_daily_std_6M = NIO_MATRIX()
        self.upshadow_daily_skew_1W = NIO_MATRIX()
        self.upshadow_daily_skew_1M = NIO_MATRIX()
        self.upshadow_daily_skew_3M = NIO_MATRIX()
        self.upshadow_daily_skew_6M = NIO_MATRIX()
        self.upshadow_am_avg_1W = NIO_MATRIX()
        self.upshadow_am_avg_1M = NIO_MATRIX()
        self.upshadow_am_avg_3M = NIO_MATRIX()
        self.upshadow_am_avg_6M = NIO_MATRIX()
        self.upshadow_am_std_1W = NIO_MATRIX()
        self.upshadow_am_std_1M = NIO_MATRIX()
        self.upshadow_am_std_3M = NIO_MATRIX()
        self.upshadow_am_std_6M = NIO_MATRIX()
        self.upshadow_am_skew_1W = NIO_MATRIX()
        self.upshadow_am_skew_1M = NIO_MATRIX()
        self.upshadow_am_skew_3M = NIO_MATRIX()
        self.upshadow_am_skew_6M = NIO_MATRIX()
        self.upshadow_pm_avg_1W = NIO_MATRIX()
        self.upshadow_pm_avg_1M = NIO_MATRIX()
        self.upshadow_pm_avg_3M = NIO_MATRIX()
        self.upshadow_pm_avg_6M = NIO_MATRIX()
        self.upshadow_pm_std_1W = NIO_MATRIX()
        self.upshadow_pm_std_1M = NIO_MATRIX()
        self.upshadow_pm_std_3M = NIO_MATRIX()
        self.upshadow_pm_std_6M = NIO_MATRIX()
        self.upshadow_pm_skew_1W = NIO_MATRIX()
        self.upshadow_pm_skew_1M = NIO_MATRIX()
        self.upshadow_pm_skew_3M = NIO_MATRIX()
        self.upshadow_pm_skew_6M = NIO_MATRIX()
        self.upshadow_open_30m_avg_1W = NIO_MATRIX()
        self.upshadow_open_30m_avg_1M = NIO_MATRIX()
        self.upshadow_open_30m_avg_3M = NIO_MATRIX()
        self.upshadow_open_30m_avg_6M = NIO_MATRIX()
        self.upshadow_open_30m_std_1W = NIO_MATRIX()
        self.upshadow_open_30m_std_1M = NIO_MATRIX()
        self.upshadow_open_30m_std_3M = NIO_MATRIX()
        self.upshadow_open_30m_std_6M = NIO_MATRIX()
        self.upshadow_open_30m_skew_1W = NIO_MATRIX()
        self.upshadow_open_30m_skew_1M = NIO_MATRIX()
        self.upshadow_open_30m_skew_3M = NIO_MATRIX()
        self.upshadow_open_30m_skew_6M = NIO_MATRIX()
        self.upshadow_close_30m_avg_1W = NIO_MATRIX()
        self.upshadow_close_30m_avg_1M = NIO_MATRIX()
        self.upshadow_close_30m_avg_3M = NIO_MATRIX()
        self.upshadow_close_30m_avg_6M = NIO_MATRIX()
        self.upshadow_close_30m_std_1W = NIO_MATRIX()
        self.upshadow_close_30m_std_1M = NIO_MATRIX()
        self.upshadow_close_30m_std_3M = NIO_MATRIX()
        self.upshadow_close_30m_std_6M = NIO_MATRIX()
        self.upshadow_close_30m_skew_1W = NIO_MATRIX()
        self.upshadow_close_30m_skew_1M = NIO_MATRIX()
        self.upshadow_close_30m_skew_3M = NIO_MATRIX()
        self.upshadow_close_30m_skew_6M = NIO_MATRIX()
        self.downshadow_daily_avg_1W = NIO_MATRIX()
        self.downshadow_daily_avg_1M = NIO_MATRIX()
        self.downshadow_daily_avg_3M = NIO_MATRIX()
        self.downshadow_daily_avg_6M = NIO_MATRIX()
        self.downshadow_daily_std_1W = NIO_MATRIX()
        self.downshadow_daily_std_1M = NIO_MATRIX()
        self.downshadow_daily_std_3M = NIO_MATRIX()
        self.downshadow_daily_std_6M = NIO_MATRIX()
        self.downshadow_daily_skew_1W = NIO_MATRIX()
        self.downshadow_daily_skew_1M = NIO_MATRIX()
        self.downshadow_daily_skew_3M = NIO_MATRIX()
        self.downshadow_daily_skew_6M = NIO_MATRIX()
        self.downshadow_am_avg_1W = NIO_MATRIX()
        self.downshadow_am_avg_1M = NIO_MATRIX()
        self.downshadow_am_avg_3M = NIO_MATRIX()
        self.downshadow_am_avg_6M = NIO_MATRIX()
        self.downshadow_am_std_1W = NIO_MATRIX()
        self.downshadow_am_std_1M = NIO_MATRIX()
        self.downshadow_am_std_3M = NIO_MATRIX()
        self.downshadow_am_std_6M = NIO_MATRIX()
        self.downshadow_am_skew_1W = NIO_MATRIX()
        self.downshadow_am_skew_1M = NIO_MATRIX()
        self.downshadow_am_skew_3M = NIO_MATRIX()
        self.downshadow_am_skew_6M = NIO_MATRIX()
        self.downshadow_pm_avg_1W = NIO_MATRIX()
        self.downshadow_pm_avg_1M = NIO_MATRIX()
        self.downshadow_pm_avg_3M = NIO_MATRIX()
        self.downshadow_pm_avg_6M = NIO_MATRIX()
        self.downshadow_pm_std_1W = NIO_MATRIX()
        self.downshadow_pm_std_1M = NIO_MATRIX()
        self.downshadow_pm_std_3M = NIO_MATRIX()
        self.downshadow_pm_std_6M = NIO_MATRIX()
        self.downshadow_pm_skew_1W = NIO_MATRIX()
        self.downshadow_pm_skew_1M = NIO_MATRIX()
        self.downshadow_pm_skew_3M = NIO_MATRIX()
        self.downshadow_pm_skew_6M = NIO_MATRIX()
        self.downshadow_open_30m_avg_1W = NIO_MATRIX()
        self.downshadow_open_30m_avg_1M = NIO_MATRIX()
        self.downshadow_open_30m_avg_3M = NIO_MATRIX()
        self.downshadow_open_30m_avg_6M = NIO_MATRIX()
        self.downshadow_open_30m_std_1W = NIO_MATRIX()
        self.downshadow_open_30m_std_1M = NIO_MATRIX()
        self.downshadow_open_30m_std_3M = NIO_MATRIX()
        self.downshadow_open_30m_std_6M = NIO_MATRIX()
        self.downshadow_open_30m_skew_1W = NIO_MATRIX()
        self.downshadow_open_30m_skew_1M = NIO_MATRIX()
        self.downshadow_open_30m_skew_3M = NIO_MATRIX()
        self.downshadow_open_30m_skew_6M = NIO_MATRIX()
        self.downshadow_close_30m_avg_1W = NIO_MATRIX()
        self.downshadow_close_30m_avg_1M = NIO_MATRIX()
        self.downshadow_close_30m_avg_3M = NIO_MATRIX()
        self.downshadow_close_30m_avg_6M = NIO_MATRIX()
        self.downshadow_close_30m_std_1W = NIO_MATRIX()
        self.downshadow_close_30m_std_1M = NIO_MATRIX()
        self.downshadow_close_30m_std_3M = NIO_MATRIX()
        self.downshadow_close_30m_std_6M = NIO_MATRIX()
        self.downshadow_close_30m_skew_1W = NIO_MATRIX()
        self.downshadow_close_30m_skew_1M = NIO_MATRIX()
        self.downshadow_close_30m_skew_3M = NIO_MATRIX()
        self.downshadow_close_30m_skew_6M = NIO_MATRIX()
        self.w_upshadow_daily_avg_1W = NIO_MATRIX()
        self.w_upshadow_daily_avg_1M = NIO_MATRIX()
        self.w_upshadow_daily_avg_3M = NIO_MATRIX()
        self.w_upshadow_daily_avg_6M = NIO_MATRIX()
        self.w_upshadow_daily_std_1W = NIO_MATRIX()
        self.w_upshadow_daily_std_1M = NIO_MATRIX()
        self.w_upshadow_daily_std_3M = NIO_MATRIX()
        self.w_upshadow_daily_std_6M = NIO_MATRIX()
        self.w_upshadow_daily_skew_1W = NIO_MATRIX()
        self.w_upshadow_daily_skew_1M = NIO_MATRIX()
        self.w_upshadow_daily_skew_3M = NIO_MATRIX()
        self.w_upshadow_daily_skew_6M = NIO_MATRIX()
        self.w_upshadow_am_avg_1W = NIO_MATRIX()
        self.w_upshadow_am_avg_1M = NIO_MATRIX()
        self.w_upshadow_am_avg_3M = NIO_MATRIX()
        self.w_upshadow_am_avg_6M = NIO_MATRIX()
        self.w_upshadow_am_std_1W = NIO_MATRIX()
        self.w_upshadow_am_std_1M = NIO_MATRIX()
        self.w_upshadow_am_std_3M = NIO_MATRIX()
        self.w_upshadow_am_std_6M = NIO_MATRIX()
        self.w_upshadow_am_skew_1W = NIO_MATRIX()
        self.w_upshadow_am_skew_1M = NIO_MATRIX()
        self.w_upshadow_am_skew_3M = NIO_MATRIX()
        self.w_upshadow_am_skew_6M = NIO_MATRIX()
        self.w_upshadow_pm_avg_1W = NIO_MATRIX()
        self.w_upshadow_pm_avg_1M = NIO_MATRIX()
        self.w_upshadow_pm_avg_3M = NIO_MATRIX()
        self.w_upshadow_pm_avg_6M = NIO_MATRIX()
        self.w_upshadow_pm_std_1W = NIO_MATRIX()
        self.w_upshadow_pm_std_1M = NIO_MATRIX()
        self.w_upshadow_pm_std_3M = NIO_MATRIX()
        self.w_upshadow_pm_std_6M = NIO_MATRIX()
        self.w_upshadow_pm_skew_1W = NIO_MATRIX()
        self.w_upshadow_pm_skew_1M = NIO_MATRIX()
        self.w_upshadow_pm_skew_3M = NIO_MATRIX()
        self.w_upshadow_pm_skew_6M = NIO_MATRIX()
        self.w_upshadow_open_30m_avg_1W = NIO_MATRIX()
        self.w_upshadow_open_30m_avg_1M = NIO_MATRIX()
        self.w_upshadow_open_30m_avg_3M = NIO_MATRIX()
        self.w_upshadow_open_30m_avg_6M = NIO_MATRIX()
        self.w_upshadow_open_30m_std_1W = NIO_MATRIX()
        self.w_upshadow_open_30m_std_1M = NIO_MATRIX()
        self.w_upshadow_open_30m_std_3M = NIO_MATRIX()
        self.w_upshadow_open_30m_std_6M = NIO_MATRIX()
        self.w_upshadow_open_30m_skew_1W = NIO_MATRIX()
        self.w_upshadow_open_30m_skew_1M = NIO_MATRIX()
        self.w_upshadow_open_30m_skew_3M = NIO_MATRIX()
        self.w_upshadow_open_30m_skew_6M = NIO_MATRIX()
        self.w_upshadow_close_30m_avg_1W = NIO_MATRIX()
        self.w_upshadow_close_30m_avg_1M = NIO_MATRIX()
        self.w_upshadow_close_30m_avg_3M = NIO_MATRIX()
        self.w_upshadow_close_30m_avg_6M = NIO_MATRIX()
        self.w_upshadow_close_30m_std_1W = NIO_MATRIX()
        self.w_upshadow_close_30m_std_1M = NIO_MATRIX()
        self.w_upshadow_close_30m_std_3M = NIO_MATRIX()
        self.w_upshadow_close_30m_std_6M = NIO_MATRIX()
        self.w_upshadow_close_30m_skew_1W = NIO_MATRIX()
        self.w_upshadow_close_30m_skew_1M = NIO_MATRIX()
        self.w_upshadow_close_30m_skew_3M = NIO_MATRIX()
        self.w_upshadow_close_30m_skew_6M = NIO_MATRIX()
        self.w_downshadow_daily_avg_1W = NIO_MATRIX()
        self.w_downshadow_daily_avg_1M = NIO_MATRIX()
        self.w_downshadow_daily_avg_3M = NIO_MATRIX()
        self.w_downshadow_daily_avg_6M = NIO_MATRIX()
        self.w_downshadow_daily_std_1W = NIO_MATRIX()
        self.w_downshadow_daily_std_1M = NIO_MATRIX()
        self.w_downshadow_daily_std_3M = NIO_MATRIX()
        self.w_downshadow_daily_std_6M = NIO_MATRIX()
        self.w_downshadow_daily_skew_1W = NIO_MATRIX()
        self.w_downshadow_daily_skew_1M = NIO_MATRIX()
        self.w_downshadow_daily_skew_3M = NIO_MATRIX()
        self.w_downshadow_daily_skew_6M = NIO_MATRIX()
        self.w_downshadow_am_avg_1W = NIO_MATRIX()
        self.w_downshadow_am_avg_1M = NIO_MATRIX()
        self.w_downshadow_am_avg_3M = NIO_MATRIX()
        self.w_downshadow_am_avg_6M = NIO_MATRIX()
        self.w_downshadow_am_std_1W = NIO_MATRIX()
        self.w_downshadow_am_std_1M = NIO_MATRIX()
        self.w_downshadow_am_std_3M = NIO_MATRIX()
        self.w_downshadow_am_std_6M = NIO_MATRIX()
        self.w_downshadow_am_skew_1W = NIO_MATRIX()
        self.w_downshadow_am_skew_1M = NIO_MATRIX()
        self.w_downshadow_am_skew_3M = NIO_MATRIX()
        self.w_downshadow_am_skew_6M = NIO_MATRIX()
        self.w_downshadow_pm_avg_1W = NIO_MATRIX()
        self.w_downshadow_pm_avg_1M = NIO_MATRIX()
        self.w_downshadow_pm_avg_3M = NIO_MATRIX()
        self.w_downshadow_pm_avg_6M = NIO_MATRIX()
        self.w_downshadow_pm_std_1W = NIO_MATRIX()
        self.w_downshadow_pm_std_1M = NIO_MATRIX()
        self.w_downshadow_pm_std_3M = NIO_MATRIX()
        self.w_downshadow_pm_std_6M = NIO_MATRIX()
        self.w_downshadow_pm_skew_1W = NIO_MATRIX()
        self.w_downshadow_pm_skew_1M = NIO_MATRIX()
        self.w_downshadow_pm_skew_3M = NIO_MATRIX()
        self.w_downshadow_pm_skew_6M = NIO_MATRIX()
        self.w_downshadow_open_30m_avg_1W = NIO_MATRIX()
        self.w_downshadow_open_30m_avg_1M = NIO_MATRIX()
        self.w_downshadow_open_30m_avg_3M = NIO_MATRIX()
        self.w_downshadow_open_30m_avg_6M = NIO_MATRIX()
        self.w_downshadow_open_30m_std_1W = NIO_MATRIX()
        self.w_downshadow_open_30m_std_1M = NIO_MATRIX()
        self.w_downshadow_open_30m_std_3M = NIO_MATRIX()
        self.w_downshadow_open_30m_std_6M = NIO_MATRIX()
        self.w_downshadow_open_30m_skew_1W = NIO_MATRIX()
        self.w_downshadow_open_30m_skew_1M = NIO_MATRIX()
        self.w_downshadow_open_30m_skew_3M = NIO_MATRIX()
        self.w_downshadow_open_30m_skew_6M = NIO_MATRIX()
        self.w_downshadow_close_30m_avg_1W = NIO_MATRIX()
        self.w_downshadow_close_30m_avg_1M = NIO_MATRIX()
        self.w_downshadow_close_30m_avg_3M = NIO_MATRIX()
        self.w_downshadow_close_30m_avg_6M = NIO_MATRIX()
        self.w_downshadow_close_30m_std_1W = NIO_MATRIX()
        self.w_downshadow_close_30m_std_1M = NIO_MATRIX()
        self.w_downshadow_close_30m_std_3M = NIO_MATRIX()
        self.w_downshadow_close_30m_std_6M = NIO_MATRIX()
        self.w_downshadow_close_30m_skew_1W = NIO_MATRIX()
        self.w_downshadow_close_30m_skew_1M = NIO_MATRIX()
        self.w_downshadow_close_30m_skew_3M = NIO_MATRIX()
        self.w_downshadow_close_30m_skew_6M = NIO_MATRIX()
        self.body_daily_avg_1W = NIO_MATRIX()
        self.body_daily_avg_1M = NIO_MATRIX()
        self.body_daily_avg_3M = NIO_MATRIX()
        self.body_daily_avg_6M = NIO_MATRIX()
        self.body_daily_std_1W = NIO_MATRIX()
        self.body_daily_std_1M = NIO_MATRIX()
        self.body_daily_std_3M = NIO_MATRIX()
        self.body_daily_std_6M = NIO_MATRIX()
        self.body_daily_skew_1W = NIO_MATRIX()
        self.body_daily_skew_1M = NIO_MATRIX()
        self.body_daily_skew_3M = NIO_MATRIX()
        self.body_daily_skew_6M = NIO_MATRIX()
        self.body_am_avg_1W = NIO_MATRIX()
        self.body_am_avg_1M = NIO_MATRIX()
        self.body_am_avg_3M = NIO_MATRIX()
        self.body_am_avg_6M = NIO_MATRIX()
        self.body_am_std_1W = NIO_MATRIX()
        self.body_am_std_1M = NIO_MATRIX()
        self.body_am_std_3M = NIO_MATRIX()
        self.body_am_std_6M = NIO_MATRIX()
        self.body_am_skew_1W = NIO_MATRIX()
        self.body_am_skew_1M = NIO_MATRIX()
        self.body_am_skew_3M = NIO_MATRIX()
        self.body_am_skew_6M = NIO_MATRIX()
        self.body_pm_avg_1W = NIO_MATRIX()
        self.body_pm_avg_1M = NIO_MATRIX()
        self.body_pm_avg_3M = NIO_MATRIX()
        self.body_pm_avg_6M = NIO_MATRIX()
        self.body_pm_std_1W = NIO_MATRIX()
        self.body_pm_std_1M = NIO_MATRIX()
        self.body_pm_std_3M = NIO_MATRIX()
        self.body_pm_std_6M = NIO_MATRIX()
        self.body_pm_skew_1W = NIO_MATRIX()
        self.body_pm_skew_1M = NIO_MATRIX()
        self.body_pm_skew_3M = NIO_MATRIX()
        self.body_pm_skew_6M = NIO_MATRIX()
        self.body_open_30m_avg_1W = NIO_MATRIX()
        self.body_open_30m_avg_1M = NIO_MATRIX()
        self.body_open_30m_avg_3M = NIO_MATRIX()
        self.body_open_30m_avg_6M = NIO_MATRIX()
        self.body_open_30m_std_1W = NIO_MATRIX()
        self.body_open_30m_std_1M = NIO_MATRIX()
        self.body_open_30m_std_3M = NIO_MATRIX()
        self.body_open_30m_std_6M = NIO_MATRIX()
        self.body_open_30m_skew_1W = NIO_MATRIX()
        self.body_open_30m_skew_1M = NIO_MATRIX()
        self.body_open_30m_skew_3M = NIO_MATRIX()
        self.body_open_30m_skew_6M = NIO_MATRIX()
        self.body_close_30m_avg_1W = NIO_MATRIX()
        self.body_close_30m_avg_1M = NIO_MATRIX()
        self.body_close_30m_avg_3M = NIO_MATRIX()
        self.body_close_30m_avg_6M = NIO_MATRIX()
        self.body_close_30m_std_1W = NIO_MATRIX()
        self.body_close_30m_std_1M = NIO_MATRIX()
        self.body_close_30m_std_3M = NIO_MATRIX()
        self.body_close_30m_std_6M = NIO_MATRIX()
        self.body_close_30m_skew_1W = NIO_MATRIX()
        self.body_close_30m_skew_1M = NIO_MATRIX()
        self.body_close_30m_skew_3M = NIO_MATRIX()
        self.body_close_30m_skew_6M = NIO_MATRIX()
        self.range_daily_avg_1W = NIO_MATRIX()
        self.range_daily_avg_1M = NIO_MATRIX()
        self.range_daily_avg_3M = NIO_MATRIX()
        self.range_daily_avg_6M = NIO_MATRIX()
        self.range_daily_std_1W = NIO_MATRIX()
        self.range_daily_std_1M = NIO_MATRIX()
        self.range_daily_std_3M = NIO_MATRIX()
        self.range_daily_std_6M = NIO_MATRIX()
        self.range_daily_skew_1W = NIO_MATRIX()
        self.range_daily_skew_1M = NIO_MATRIX()
        self.range_daily_skew_3M = NIO_MATRIX()
        self.range_daily_skew_6M = NIO_MATRIX()
        self.range_am_avg_1W = NIO_MATRIX()
        self.range_am_avg_1M = NIO_MATRIX()
        self.range_am_avg_3M = NIO_MATRIX()
        self.range_am_avg_6M = NIO_MATRIX()
        self.range_am_std_1W = NIO_MATRIX()
        self.range_am_std_1M = NIO_MATRIX()
        self.range_am_std_3M = NIO_MATRIX()
        self.range_am_std_6M = NIO_MATRIX()
        self.range_am_skew_1W = NIO_MATRIX()
        self.range_am_skew_1M = NIO_MATRIX()
        self.range_am_skew_3M = NIO_MATRIX()
        self.range_am_skew_6M = NIO_MATRIX()
        self.range_pm_avg_1W = NIO_MATRIX()
        self.range_pm_avg_1M = NIO_MATRIX()
        self.range_pm_avg_3M = NIO_MATRIX()
        self.range_pm_avg_6M = NIO_MATRIX()
        self.range_pm_std_1W = NIO_MATRIX()
        self.range_pm_std_1M = NIO_MATRIX()
        self.range_pm_std_3M = NIO_MATRIX()
        self.range_pm_std_6M = NIO_MATRIX()
        self.range_pm_skew_1W = NIO_MATRIX()
        self.range_pm_skew_1M = NIO_MATRIX()
        self.range_pm_skew_3M = NIO_MATRIX()
        self.range_pm_skew_6M = NIO_MATRIX()
        self.range_open_30m_avg_1W = NIO_MATRIX()
        self.range_open_30m_avg_1M = NIO_MATRIX()
        self.range_open_30m_avg_3M = NIO_MATRIX()
        self.range_open_30m_avg_6M = NIO_MATRIX()
        self.range_open_30m_std_1W = NIO_MATRIX()
        self.range_open_30m_std_1M = NIO_MATRIX()
        self.range_open_30m_std_3M = NIO_MATRIX()
        self.range_open_30m_std_6M = NIO_MATRIX()
        self.range_open_30m_skew_1W = NIO_MATRIX()
        self.range_open_30m_skew_1M = NIO_MATRIX()
        self.range_open_30m_skew_3M = NIO_MATRIX()
        self.range_open_30m_skew_6M = NIO_MATRIX()
        self.range_close_30m_avg_1W = NIO_MATRIX()
        self.range_close_30m_avg_1M = NIO_MATRIX()
        self.range_close_30m_avg_3M = NIO_MATRIX()
        self.range_close_30m_avg_6M = NIO_MATRIX()
        self.range_close_30m_std_1W = NIO_MATRIX()
        self.range_close_30m_std_1M = NIO_MATRIX()
        self.range_close_30m_std_3M = NIO_MATRIX()
        self.range_close_30m_std_6M = NIO_MATRIX()
        self.range_close_30m_skew_1W = NIO_MATRIX()
        self.range_close_30m_skew_1M = NIO_MATRIX()
        self.range_close_30m_skew_3M = NIO_MATRIX()
        self.range_close_30m_skew_6M = NIO_MATRIX()
        self.up_down_ratio_daily_avg_1W = NIO_MATRIX()
        self.up_down_ratio_daily_avg_1M = NIO_MATRIX()
        self.up_down_ratio_daily_avg_3M = NIO_MATRIX()
        self.up_down_ratio_daily_avg_6M = NIO_MATRIX()
        self.up_down_ratio_daily_std_1W = NIO_MATRIX()
        self.up_down_ratio_daily_std_1M = NIO_MATRIX()
        self.up_down_ratio_daily_std_3M = NIO_MATRIX()
        self.up_down_ratio_daily_std_6M = NIO_MATRIX()
        self.up_down_ratio_daily_skew_1W = NIO_MATRIX()
        self.up_down_ratio_daily_skew_1M = NIO_MATRIX()
        self.up_down_ratio_daily_skew_3M = NIO_MATRIX()
        self.up_down_ratio_daily_skew_6M = NIO_MATRIX()
        self.up_down_ratio_am_avg_1W = NIO_MATRIX()
        self.up_down_ratio_am_avg_1M = NIO_MATRIX()
        self.up_down_ratio_am_avg_3M = NIO_MATRIX()
        self.up_down_ratio_am_avg_6M = NIO_MATRIX()
        self.up_down_ratio_am_std_1W = NIO_MATRIX()
        self.up_down_ratio_am_std_1M = NIO_MATRIX()
        self.up_down_ratio_am_std_3M = NIO_MATRIX()
        self.up_down_ratio_am_std_6M = NIO_MATRIX()
        self.up_down_ratio_am_skew_1W = NIO_MATRIX()
        self.up_down_ratio_am_skew_1M = NIO_MATRIX()
        self.up_down_ratio_am_skew_3M = NIO_MATRIX()
        self.up_down_ratio_am_skew_6M = NIO_MATRIX()
        self.up_down_ratio_pm_avg_1W = NIO_MATRIX()
        self.up_down_ratio_pm_avg_1M = NIO_MATRIX()
        self.up_down_ratio_pm_avg_3M = NIO_MATRIX()
        self.up_down_ratio_pm_avg_6M = NIO_MATRIX()
        self.up_down_ratio_pm_std_1W = NIO_MATRIX()
        self.up_down_ratio_pm_std_1M = NIO_MATRIX()
        self.up_down_ratio_pm_std_3M = NIO_MATRIX()
        self.up_down_ratio_pm_std_6M = NIO_MATRIX()
        self.up_down_ratio_pm_skew_1W = NIO_MATRIX()
        self.up_down_ratio_pm_skew_1M = NIO_MATRIX()
        self.up_down_ratio_pm_skew_3M = NIO_MATRIX()
        self.up_down_ratio_pm_skew_6M = NIO_MATRIX()
        self.up_down_ratio_open_30m_avg_1W = NIO_MATRIX()
        self.up_down_ratio_open_30m_avg_1M = NIO_MATRIX()
        self.up_down_ratio_open_30m_avg_3M = NIO_MATRIX()
        self.up_down_ratio_open_30m_avg_6M = NIO_MATRIX()
        self.up_down_ratio_open_30m_std_1W = NIO_MATRIX()
        self.up_down_ratio_open_30m_std_1M = NIO_MATRIX()
        self.up_down_ratio_open_30m_std_3M = NIO_MATRIX()
        self.up_down_ratio_open_30m_std_6M = NIO_MATRIX()
        self.up_down_ratio_open_30m_skew_1W = NIO_MATRIX()
        self.up_down_ratio_open_30m_skew_1M = NIO_MATRIX()
        self.up_down_ratio_open_30m_skew_3M = NIO_MATRIX()
        self.up_down_ratio_open_30m_skew_6M = NIO_MATRIX()
        self.up_down_ratio_close_30m_avg_1W = NIO_MATRIX()
        self.up_down_ratio_close_30m_avg_1M = NIO_MATRIX()
        self.up_down_ratio_close_30m_avg_3M = NIO_MATRIX()
        self.up_down_ratio_close_30m_avg_6M = NIO_MATRIX()
        self.up_down_ratio_close_30m_std_1W = NIO_MATRIX()
        self.up_down_ratio_close_30m_std_1M = NIO_MATRIX()
        self.up_down_ratio_close_30m_std_3M = NIO_MATRIX()
        self.up_down_ratio_close_30m_std_6M = NIO_MATRIX()
        self.up_down_ratio_close_30m_skew_1W = NIO_MATRIX()
        self.up_down_ratio_close_30m_skew_1M = NIO_MATRIX()
        self.up_down_ratio_close_30m_skew_3M = NIO_MATRIX()
        self.up_down_ratio_close_30m_skew_6M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_avg_1W = NIO_MATRIX()
        self.upshadow_am_pm_ratio_avg_1M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_avg_3M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_avg_6M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_std_1W = NIO_MATRIX()
        self.upshadow_am_pm_ratio_std_1M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_std_3M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_std_6M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_skew_1W = NIO_MATRIX()
        self.upshadow_am_pm_ratio_skew_1M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_skew_3M = NIO_MATRIX()
        self.upshadow_am_pm_ratio_skew_6M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_avg_1W = NIO_MATRIX()
        self.downshadow_am_pm_ratio_avg_1M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_avg_3M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_avg_6M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_std_1W = NIO_MATRIX()
        self.downshadow_am_pm_ratio_std_1M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_std_3M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_std_6M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_skew_1W = NIO_MATRIX()
        self.downshadow_am_pm_ratio_skew_1M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_skew_3M = NIO_MATRIX()
        self.downshadow_am_pm_ratio_skew_6M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_avg_1W = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_avg_1M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_avg_3M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_avg_6M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_std_1W = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_std_1M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_std_3M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_std_6M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_skew_1W = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_skew_1M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_skew_3M = NIO_MATRIX()
        self.w_upshadow_am_pm_ratio_skew_6M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_avg_1W = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_avg_1M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_avg_3M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_avg_6M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_std_1W = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_std_1M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_std_3M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_std_6M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_skew_1W = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_skew_1M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_skew_3M = NIO_MATRIX()
        self.w_downshadow_am_pm_ratio_skew_6M = NIO_MATRIX()
        self.body_am_pm_ratio_avg_1W = NIO_MATRIX()
        self.body_am_pm_ratio_avg_1M = NIO_MATRIX()
        self.body_am_pm_ratio_avg_3M = NIO_MATRIX()
        self.body_am_pm_ratio_avg_6M = NIO_MATRIX()
        self.body_am_pm_ratio_std_1W = NIO_MATRIX()
        self.body_am_pm_ratio_std_1M = NIO_MATRIX()
        self.body_am_pm_ratio_std_3M = NIO_MATRIX()
        self.body_am_pm_ratio_std_6M = NIO_MATRIX()
        self.body_am_pm_ratio_skew_1W = NIO_MATRIX()
        self.body_am_pm_ratio_skew_1M = NIO_MATRIX()
        self.body_am_pm_ratio_skew_3M = NIO_MATRIX()
        self.body_am_pm_ratio_skew_6M = NIO_MATRIX()
        self.range_am_pm_ratio_avg_1W = NIO_MATRIX()
        self.range_am_pm_ratio_avg_1M = NIO_MATRIX()
        self.range_am_pm_ratio_avg_3M = NIO_MATRIX()
        self.range_am_pm_ratio_avg_6M = NIO_MATRIX()
        self.range_am_pm_ratio_std_1W = NIO_MATRIX()
        self.range_am_pm_ratio_std_1M = NIO_MATRIX()
        self.range_am_pm_ratio_std_3M = NIO_MATRIX()
        self.range_am_pm_ratio_std_6M = NIO_MATRIX()
        self.range_am_pm_ratio_skew_1W = NIO_MATRIX()
        self.range_am_pm_ratio_skew_1M = NIO_MATRIX()
        self.range_am_pm_ratio_skew_3M = NIO_MATRIX()
        self.range_am_pm_ratio_skew_6M = NIO_MATRIX()
        self.upshadow_open_close_ratio_avg_1W = NIO_MATRIX()
        self.upshadow_open_close_ratio_avg_1M = NIO_MATRIX()
        self.upshadow_open_close_ratio_avg_3M = NIO_MATRIX()
        self.upshadow_open_close_ratio_avg_6M = NIO_MATRIX()
        self.upshadow_open_close_ratio_std_1W = NIO_MATRIX()
        self.upshadow_open_close_ratio_std_1M = NIO_MATRIX()
        self.upshadow_open_close_ratio_std_3M = NIO_MATRIX()
        self.upshadow_open_close_ratio_std_6M = NIO_MATRIX()
        self.upshadow_open_close_ratio_skew_1W = NIO_MATRIX()
        self.upshadow_open_close_ratio_skew_1M = NIO_MATRIX()
        self.upshadow_open_close_ratio_skew_3M = NIO_MATRIX()
        self.upshadow_open_close_ratio_skew_6M = NIO_MATRIX()
        self.downshadow_open_close_ratio_avg_1W = NIO_MATRIX()
        self.downshadow_open_close_ratio_avg_1M = NIO_MATRIX()
        self.downshadow_open_close_ratio_avg_3M = NIO_MATRIX()
        self.downshadow_open_close_ratio_avg_6M = NIO_MATRIX()
        self.downshadow_open_close_ratio_std_1W = NIO_MATRIX()
        self.downshadow_open_close_ratio_std_1M = NIO_MATRIX()
        self.downshadow_open_close_ratio_std_3M = NIO_MATRIX()
        self.downshadow_open_close_ratio_std_6M = NIO_MATRIX()
        self.downshadow_open_close_ratio_skew_1W = NIO_MATRIX()
        self.downshadow_open_close_ratio_skew_1M = NIO_MATRIX()
        self.downshadow_open_close_ratio_skew_3M = NIO_MATRIX()
        self.downshadow_open_close_ratio_skew_6M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_avg_1W = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_avg_1M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_avg_3M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_avg_6M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_std_1W = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_std_1M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_std_3M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_std_6M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_skew_1W = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_skew_1M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_skew_3M = NIO_MATRIX()
        self.w_upshadow_open_close_ratio_skew_6M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_avg_1W = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_avg_1M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_avg_3M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_avg_6M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_std_1W = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_std_1M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_std_3M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_std_6M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_skew_1W = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_skew_1M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_skew_3M = NIO_MATRIX()
        self.w_downshadow_open_close_ratio_skew_6M = NIO_MATRIX()
        self.body_open_close_ratio_avg_1W = NIO_MATRIX()
        self.body_open_close_ratio_avg_1M = NIO_MATRIX()
        self.body_open_close_ratio_avg_3M = NIO_MATRIX()
        self.body_open_close_ratio_avg_6M = NIO_MATRIX()
        self.body_open_close_ratio_std_1W = NIO_MATRIX()
        self.body_open_close_ratio_std_1M = NIO_MATRIX()
        self.body_open_close_ratio_std_3M = NIO_MATRIX()
        self.body_open_close_ratio_std_6M = NIO_MATRIX()
        self.body_open_close_ratio_skew_1W = NIO_MATRIX()
        self.body_open_close_ratio_skew_1M = NIO_MATRIX()
        self.body_open_close_ratio_skew_3M = NIO_MATRIX()
        self.body_open_close_ratio_skew_6M = NIO_MATRIX()
        self.range_open_close_ratio_avg_1W = NIO_MATRIX()
        self.range_open_close_ratio_avg_1M = NIO_MATRIX()
        self.range_open_close_ratio_avg_3M = NIO_MATRIX()
        self.range_open_close_ratio_avg_6M = NIO_MATRIX()
        self.range_open_close_ratio_std_1W = NIO_MATRIX()
        self.range_open_close_ratio_std_1M = NIO_MATRIX()
        self.range_open_close_ratio_std_3M = NIO_MATRIX()
        self.range_open_close_ratio_std_6M = NIO_MATRIX()
        self.range_open_close_ratio_skew_1W = NIO_MATRIX()
        self.range_open_close_ratio_skew_1M = NIO_MATRIX()
        self.range_open_close_ratio_skew_3M = NIO_MATRIX()
        self.range_open_close_ratio_skew_6M = NIO_MATRIX()
        self.upshadow_range_pct_avg_1W = NIO_MATRIX()
        self.upshadow_range_pct_avg_1M = NIO_MATRIX()
        self.upshadow_range_pct_avg_3M = NIO_MATRIX()
        self.upshadow_range_pct_avg_6M = NIO_MATRIX()
        self.upshadow_range_pct_std_1W = NIO_MATRIX()
        self.upshadow_range_pct_std_1M = NIO_MATRIX()
        self.upshadow_range_pct_std_3M = NIO_MATRIX()
        self.upshadow_range_pct_std_6M = NIO_MATRIX()
        self.upshadow_range_pct_skew_1W = NIO_MATRIX()
        self.upshadow_range_pct_skew_1M = NIO_MATRIX()
        self.upshadow_range_pct_skew_3M = NIO_MATRIX()
        self.upshadow_range_pct_skew_6M = NIO_MATRIX()
        self.downshadow_range_pct_avg_1W = NIO_MATRIX()
        self.downshadow_range_pct_avg_1M = NIO_MATRIX()
        self.downshadow_range_pct_avg_3M = NIO_MATRIX()
        self.downshadow_range_pct_avg_6M = NIO_MATRIX()
        self.downshadow_range_pct_std_1W = NIO_MATRIX()
        self.downshadow_range_pct_std_1M = NIO_MATRIX()
        self.downshadow_range_pct_std_3M = NIO_MATRIX()
        self.downshadow_range_pct_std_6M = NIO_MATRIX()
        self.downshadow_range_pct_skew_1W = NIO_MATRIX()
        self.downshadow_range_pct_skew_1M = NIO_MATRIX()
        self.downshadow_range_pct_skew_3M = NIO_MATRIX()
        self.downshadow_range_pct_skew_6M = NIO_MATRIX()
        self.body_range_pct_avg_1W = NIO_MATRIX()
        self.body_range_pct_avg_1M = NIO_MATRIX()
        self.body_range_pct_avg_3M = NIO_MATRIX()
        self.body_range_pct_avg_6M = NIO_MATRIX()
        self.body_range_pct_std_1W = NIO_MATRIX()
        self.body_range_pct_std_1M = NIO_MATRIX()
        self.body_range_pct_std_3M = NIO_MATRIX()
        self.body_range_pct_std_6M = NIO_MATRIX()
        self.body_range_pct_skew_1W = NIO_MATRIX()
        self.body_range_pct_skew_1M = NIO_MATRIX()
        self.body_range_pct_skew_3M = NIO_MATRIX()
        self.body_range_pct_skew_6M = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.upshadow_daily_avg_1W, 'fguo_trade3.upshadow_daily_avg_1W')
        self.addDailyData(self.upshadow_daily_avg_1M, 'fguo_trade3.upshadow_daily_avg_1M')
        self.addDailyData(self.upshadow_daily_avg_3M, 'fguo_trade3.upshadow_daily_avg_3M')
        self.addDailyData(self.upshadow_daily_avg_6M, 'fguo_trade3.upshadow_daily_avg_6M')
        self.addDailyData(self.upshadow_daily_std_1W, 'fguo_trade3.upshadow_daily_std_1W')
        self.addDailyData(self.upshadow_daily_std_1M, 'fguo_trade3.upshadow_daily_std_1M')
        self.addDailyData(self.upshadow_daily_std_3M, 'fguo_trade3.upshadow_daily_std_3M')
        self.addDailyData(self.upshadow_daily_std_6M, 'fguo_trade3.upshadow_daily_std_6M')
        self.addDailyData(self.upshadow_daily_skew_1W, 'fguo_trade3.upshadow_daily_skew_1W')
        self.addDailyData(self.upshadow_daily_skew_1M, 'fguo_trade3.upshadow_daily_skew_1M')
        self.addDailyData(self.upshadow_daily_skew_3M, 'fguo_trade3.upshadow_daily_skew_3M')
        self.addDailyData(self.upshadow_daily_skew_6M, 'fguo_trade3.upshadow_daily_skew_6M')
        self.addDailyData(self.upshadow_am_avg_1W, 'fguo_trade3.upshadow_am_avg_1W')
        self.addDailyData(self.upshadow_am_avg_1M, 'fguo_trade3.upshadow_am_avg_1M')
        self.addDailyData(self.upshadow_am_avg_3M, 'fguo_trade3.upshadow_am_avg_3M')
        self.addDailyData(self.upshadow_am_avg_6M, 'fguo_trade3.upshadow_am_avg_6M')
        self.addDailyData(self.upshadow_am_std_1W, 'fguo_trade3.upshadow_am_std_1W')
        self.addDailyData(self.upshadow_am_std_1M, 'fguo_trade3.upshadow_am_std_1M')
        self.addDailyData(self.upshadow_am_std_3M, 'fguo_trade3.upshadow_am_std_3M')
        self.addDailyData(self.upshadow_am_std_6M, 'fguo_trade3.upshadow_am_std_6M')
        self.addDailyData(self.upshadow_am_skew_1W, 'fguo_trade3.upshadow_am_skew_1W')
        self.addDailyData(self.upshadow_am_skew_1M, 'fguo_trade3.upshadow_am_skew_1M')
        self.addDailyData(self.upshadow_am_skew_3M, 'fguo_trade3.upshadow_am_skew_3M')
        self.addDailyData(self.upshadow_am_skew_6M, 'fguo_trade3.upshadow_am_skew_6M')
        self.addDailyData(self.upshadow_pm_avg_1W, 'fguo_trade3.upshadow_pm_avg_1W')
        self.addDailyData(self.upshadow_pm_avg_1M, 'fguo_trade3.upshadow_pm_avg_1M')
        self.addDailyData(self.upshadow_pm_avg_3M, 'fguo_trade3.upshadow_pm_avg_3M')
        self.addDailyData(self.upshadow_pm_avg_6M, 'fguo_trade3.upshadow_pm_avg_6M')
        self.addDailyData(self.upshadow_pm_std_1W, 'fguo_trade3.upshadow_pm_std_1W')
        self.addDailyData(self.upshadow_pm_std_1M, 'fguo_trade3.upshadow_pm_std_1M')
        self.addDailyData(self.upshadow_pm_std_3M, 'fguo_trade3.upshadow_pm_std_3M')
        self.addDailyData(self.upshadow_pm_std_6M, 'fguo_trade3.upshadow_pm_std_6M')
        self.addDailyData(self.upshadow_pm_skew_1W, 'fguo_trade3.upshadow_pm_skew_1W')
        self.addDailyData(self.upshadow_pm_skew_1M, 'fguo_trade3.upshadow_pm_skew_1M')
        self.addDailyData(self.upshadow_pm_skew_3M, 'fguo_trade3.upshadow_pm_skew_3M')
        self.addDailyData(self.upshadow_pm_skew_6M, 'fguo_trade3.upshadow_pm_skew_6M')
        self.addDailyData(self.upshadow_open_30m_avg_1W, 'fguo_trade3.upshadow_open_30m_avg_1W')
        self.addDailyData(self.upshadow_open_30m_avg_1M, 'fguo_trade3.upshadow_open_30m_avg_1M')
        self.addDailyData(self.upshadow_open_30m_avg_3M, 'fguo_trade3.upshadow_open_30m_avg_3M')
        self.addDailyData(self.upshadow_open_30m_avg_6M, 'fguo_trade3.upshadow_open_30m_avg_6M')
        self.addDailyData(self.upshadow_open_30m_std_1W, 'fguo_trade3.upshadow_open_30m_std_1W')
        self.addDailyData(self.upshadow_open_30m_std_1M, 'fguo_trade3.upshadow_open_30m_std_1M')
        self.addDailyData(self.upshadow_open_30m_std_3M, 'fguo_trade3.upshadow_open_30m_std_3M')
        self.addDailyData(self.upshadow_open_30m_std_6M, 'fguo_trade3.upshadow_open_30m_std_6M')
        self.addDailyData(self.upshadow_open_30m_skew_1W, 'fguo_trade3.upshadow_open_30m_skew_1W')
        self.addDailyData(self.upshadow_open_30m_skew_1M, 'fguo_trade3.upshadow_open_30m_skew_1M')
        self.addDailyData(self.upshadow_open_30m_skew_3M, 'fguo_trade3.upshadow_open_30m_skew_3M')
        self.addDailyData(self.upshadow_open_30m_skew_6M, 'fguo_trade3.upshadow_open_30m_skew_6M')
        self.addDailyData(self.upshadow_close_30m_avg_1W, 'fguo_trade3.upshadow_close_30m_avg_1W')
        self.addDailyData(self.upshadow_close_30m_avg_1M, 'fguo_trade3.upshadow_close_30m_avg_1M')
        self.addDailyData(self.upshadow_close_30m_avg_3M, 'fguo_trade3.upshadow_close_30m_avg_3M')
        self.addDailyData(self.upshadow_close_30m_avg_6M, 'fguo_trade3.upshadow_close_30m_avg_6M')
        self.addDailyData(self.upshadow_close_30m_std_1W, 'fguo_trade3.upshadow_close_30m_std_1W')
        self.addDailyData(self.upshadow_close_30m_std_1M, 'fguo_trade3.upshadow_close_30m_std_1M')
        self.addDailyData(self.upshadow_close_30m_std_3M, 'fguo_trade3.upshadow_close_30m_std_3M')
        self.addDailyData(self.upshadow_close_30m_std_6M, 'fguo_trade3.upshadow_close_30m_std_6M')
        self.addDailyData(self.upshadow_close_30m_skew_1W, 'fguo_trade3.upshadow_close_30m_skew_1W')
        self.addDailyData(self.upshadow_close_30m_skew_1M, 'fguo_trade3.upshadow_close_30m_skew_1M')
        self.addDailyData(self.upshadow_close_30m_skew_3M, 'fguo_trade3.upshadow_close_30m_skew_3M')
        self.addDailyData(self.upshadow_close_30m_skew_6M, 'fguo_trade3.upshadow_close_30m_skew_6M')
        self.addDailyData(self.downshadow_daily_avg_1W, 'fguo_trade3.downshadow_daily_avg_1W')
        self.addDailyData(self.downshadow_daily_avg_1M, 'fguo_trade3.downshadow_daily_avg_1M')
        self.addDailyData(self.downshadow_daily_avg_3M, 'fguo_trade3.downshadow_daily_avg_3M')
        self.addDailyData(self.downshadow_daily_avg_6M, 'fguo_trade3.downshadow_daily_avg_6M')
        self.addDailyData(self.downshadow_daily_std_1W, 'fguo_trade3.downshadow_daily_std_1W')
        self.addDailyData(self.downshadow_daily_std_1M, 'fguo_trade3.downshadow_daily_std_1M')
        self.addDailyData(self.downshadow_daily_std_3M, 'fguo_trade3.downshadow_daily_std_3M')
        self.addDailyData(self.downshadow_daily_std_6M, 'fguo_trade3.downshadow_daily_std_6M')
        self.addDailyData(self.downshadow_daily_skew_1W, 'fguo_trade3.downshadow_daily_skew_1W')
        self.addDailyData(self.downshadow_daily_skew_1M, 'fguo_trade3.downshadow_daily_skew_1M')
        self.addDailyData(self.downshadow_daily_skew_3M, 'fguo_trade3.downshadow_daily_skew_3M')
        self.addDailyData(self.downshadow_daily_skew_6M, 'fguo_trade3.downshadow_daily_skew_6M')
        self.addDailyData(self.downshadow_am_avg_1W, 'fguo_trade3.downshadow_am_avg_1W')
        self.addDailyData(self.downshadow_am_avg_1M, 'fguo_trade3.downshadow_am_avg_1M')
        self.addDailyData(self.downshadow_am_avg_3M, 'fguo_trade3.downshadow_am_avg_3M')
        self.addDailyData(self.downshadow_am_avg_6M, 'fguo_trade3.downshadow_am_avg_6M')
        self.addDailyData(self.downshadow_am_std_1W, 'fguo_trade3.downshadow_am_std_1W')
        self.addDailyData(self.downshadow_am_std_1M, 'fguo_trade3.downshadow_am_std_1M')
        self.addDailyData(self.downshadow_am_std_3M, 'fguo_trade3.downshadow_am_std_3M')
        self.addDailyData(self.downshadow_am_std_6M, 'fguo_trade3.downshadow_am_std_6M')
        self.addDailyData(self.downshadow_am_skew_1W, 'fguo_trade3.downshadow_am_skew_1W')
        self.addDailyData(self.downshadow_am_skew_1M, 'fguo_trade3.downshadow_am_skew_1M')
        self.addDailyData(self.downshadow_am_skew_3M, 'fguo_trade3.downshadow_am_skew_3M')
        self.addDailyData(self.downshadow_am_skew_6M, 'fguo_trade3.downshadow_am_skew_6M')
        self.addDailyData(self.downshadow_pm_avg_1W, 'fguo_trade3.downshadow_pm_avg_1W')
        self.addDailyData(self.downshadow_pm_avg_1M, 'fguo_trade3.downshadow_pm_avg_1M')
        self.addDailyData(self.downshadow_pm_avg_3M, 'fguo_trade3.downshadow_pm_avg_3M')
        self.addDailyData(self.downshadow_pm_avg_6M, 'fguo_trade3.downshadow_pm_avg_6M')
        self.addDailyData(self.downshadow_pm_std_1W, 'fguo_trade3.downshadow_pm_std_1W')
        self.addDailyData(self.downshadow_pm_std_1M, 'fguo_trade3.downshadow_pm_std_1M')
        self.addDailyData(self.downshadow_pm_std_3M, 'fguo_trade3.downshadow_pm_std_3M')
        self.addDailyData(self.downshadow_pm_std_6M, 'fguo_trade3.downshadow_pm_std_6M')
        self.addDailyData(self.downshadow_pm_skew_1W, 'fguo_trade3.downshadow_pm_skew_1W')
        self.addDailyData(self.downshadow_pm_skew_1M, 'fguo_trade3.downshadow_pm_skew_1M')
        self.addDailyData(self.downshadow_pm_skew_3M, 'fguo_trade3.downshadow_pm_skew_3M')
        self.addDailyData(self.downshadow_pm_skew_6M, 'fguo_trade3.downshadow_pm_skew_6M')
        self.addDailyData(self.downshadow_open_30m_avg_1W, 'fguo_trade3.downshadow_open_30m_avg_1W')
        self.addDailyData(self.downshadow_open_30m_avg_1M, 'fguo_trade3.downshadow_open_30m_avg_1M')
        self.addDailyData(self.downshadow_open_30m_avg_3M, 'fguo_trade3.downshadow_open_30m_avg_3M')
        self.addDailyData(self.downshadow_open_30m_avg_6M, 'fguo_trade3.downshadow_open_30m_avg_6M')
        self.addDailyData(self.downshadow_open_30m_std_1W, 'fguo_trade3.downshadow_open_30m_std_1W')
        self.addDailyData(self.downshadow_open_30m_std_1M, 'fguo_trade3.downshadow_open_30m_std_1M')
        self.addDailyData(self.downshadow_open_30m_std_3M, 'fguo_trade3.downshadow_open_30m_std_3M')
        self.addDailyData(self.downshadow_open_30m_std_6M, 'fguo_trade3.downshadow_open_30m_std_6M')
        self.addDailyData(self.downshadow_open_30m_skew_1W, 'fguo_trade3.downshadow_open_30m_skew_1W')
        self.addDailyData(self.downshadow_open_30m_skew_1M, 'fguo_trade3.downshadow_open_30m_skew_1M')
        self.addDailyData(self.downshadow_open_30m_skew_3M, 'fguo_trade3.downshadow_open_30m_skew_3M')
        self.addDailyData(self.downshadow_open_30m_skew_6M, 'fguo_trade3.downshadow_open_30m_skew_6M')
        self.addDailyData(self.downshadow_close_30m_avg_1W, 'fguo_trade3.downshadow_close_30m_avg_1W')
        self.addDailyData(self.downshadow_close_30m_avg_1M, 'fguo_trade3.downshadow_close_30m_avg_1M')
        self.addDailyData(self.downshadow_close_30m_avg_3M, 'fguo_trade3.downshadow_close_30m_avg_3M')
        self.addDailyData(self.downshadow_close_30m_avg_6M, 'fguo_trade3.downshadow_close_30m_avg_6M')
        self.addDailyData(self.downshadow_close_30m_std_1W, 'fguo_trade3.downshadow_close_30m_std_1W')
        self.addDailyData(self.downshadow_close_30m_std_1M, 'fguo_trade3.downshadow_close_30m_std_1M')
        self.addDailyData(self.downshadow_close_30m_std_3M, 'fguo_trade3.downshadow_close_30m_std_3M')
        self.addDailyData(self.downshadow_close_30m_std_6M, 'fguo_trade3.downshadow_close_30m_std_6M')
        self.addDailyData(self.downshadow_close_30m_skew_1W, 'fguo_trade3.downshadow_close_30m_skew_1W')
        self.addDailyData(self.downshadow_close_30m_skew_1M, 'fguo_trade3.downshadow_close_30m_skew_1M')
        self.addDailyData(self.downshadow_close_30m_skew_3M, 'fguo_trade3.downshadow_close_30m_skew_3M')
        self.addDailyData(self.downshadow_close_30m_skew_6M, 'fguo_trade3.downshadow_close_30m_skew_6M')
        self.addDailyData(self.w_upshadow_daily_avg_1W, 'fguo_trade3.w_upshadow_daily_avg_1W')
        self.addDailyData(self.w_upshadow_daily_avg_1M, 'fguo_trade3.w_upshadow_daily_avg_1M')
        self.addDailyData(self.w_upshadow_daily_avg_3M, 'fguo_trade3.w_upshadow_daily_avg_3M')
        self.addDailyData(self.w_upshadow_daily_avg_6M, 'fguo_trade3.w_upshadow_daily_avg_6M')
        self.addDailyData(self.w_upshadow_daily_std_1W, 'fguo_trade3.w_upshadow_daily_std_1W')
        self.addDailyData(self.w_upshadow_daily_std_1M, 'fguo_trade3.w_upshadow_daily_std_1M')
        self.addDailyData(self.w_upshadow_daily_std_3M, 'fguo_trade3.w_upshadow_daily_std_3M')
        self.addDailyData(self.w_upshadow_daily_std_6M, 'fguo_trade3.w_upshadow_daily_std_6M')
        self.addDailyData(self.w_upshadow_daily_skew_1W, 'fguo_trade3.w_upshadow_daily_skew_1W')
        self.addDailyData(self.w_upshadow_daily_skew_1M, 'fguo_trade3.w_upshadow_daily_skew_1M')
        self.addDailyData(self.w_upshadow_daily_skew_3M, 'fguo_trade3.w_upshadow_daily_skew_3M')
        self.addDailyData(self.w_upshadow_daily_skew_6M, 'fguo_trade3.w_upshadow_daily_skew_6M')
        self.addDailyData(self.w_upshadow_am_avg_1W, 'fguo_trade3.w_upshadow_am_avg_1W')
        self.addDailyData(self.w_upshadow_am_avg_1M, 'fguo_trade3.w_upshadow_am_avg_1M')
        self.addDailyData(self.w_upshadow_am_avg_3M, 'fguo_trade3.w_upshadow_am_avg_3M')
        self.addDailyData(self.w_upshadow_am_avg_6M, 'fguo_trade3.w_upshadow_am_avg_6M')
        self.addDailyData(self.w_upshadow_am_std_1W, 'fguo_trade3.w_upshadow_am_std_1W')
        self.addDailyData(self.w_upshadow_am_std_1M, 'fguo_trade3.w_upshadow_am_std_1M')
        self.addDailyData(self.w_upshadow_am_std_3M, 'fguo_trade3.w_upshadow_am_std_3M')
        self.addDailyData(self.w_upshadow_am_std_6M, 'fguo_trade3.w_upshadow_am_std_6M')
        self.addDailyData(self.w_upshadow_am_skew_1W, 'fguo_trade3.w_upshadow_am_skew_1W')
        self.addDailyData(self.w_upshadow_am_skew_1M, 'fguo_trade3.w_upshadow_am_skew_1M')
        self.addDailyData(self.w_upshadow_am_skew_3M, 'fguo_trade3.w_upshadow_am_skew_3M')
        self.addDailyData(self.w_upshadow_am_skew_6M, 'fguo_trade3.w_upshadow_am_skew_6M')
        self.addDailyData(self.w_upshadow_pm_avg_1W, 'fguo_trade3.w_upshadow_pm_avg_1W')
        self.addDailyData(self.w_upshadow_pm_avg_1M, 'fguo_trade3.w_upshadow_pm_avg_1M')
        self.addDailyData(self.w_upshadow_pm_avg_3M, 'fguo_trade3.w_upshadow_pm_avg_3M')
        self.addDailyData(self.w_upshadow_pm_avg_6M, 'fguo_trade3.w_upshadow_pm_avg_6M')
        self.addDailyData(self.w_upshadow_pm_std_1W, 'fguo_trade3.w_upshadow_pm_std_1W')
        self.addDailyData(self.w_upshadow_pm_std_1M, 'fguo_trade3.w_upshadow_pm_std_1M')
        self.addDailyData(self.w_upshadow_pm_std_3M, 'fguo_trade3.w_upshadow_pm_std_3M')
        self.addDailyData(self.w_upshadow_pm_std_6M, 'fguo_trade3.w_upshadow_pm_std_6M')
        self.addDailyData(self.w_upshadow_pm_skew_1W, 'fguo_trade3.w_upshadow_pm_skew_1W')
        self.addDailyData(self.w_upshadow_pm_skew_1M, 'fguo_trade3.w_upshadow_pm_skew_1M')
        self.addDailyData(self.w_upshadow_pm_skew_3M, 'fguo_trade3.w_upshadow_pm_skew_3M')
        self.addDailyData(self.w_upshadow_pm_skew_6M, 'fguo_trade3.w_upshadow_pm_skew_6M')
        self.addDailyData(self.w_upshadow_open_30m_avg_1W, 'fguo_trade3.w_upshadow_open_30m_avg_1W')
        self.addDailyData(self.w_upshadow_open_30m_avg_1M, 'fguo_trade3.w_upshadow_open_30m_avg_1M')
        self.addDailyData(self.w_upshadow_open_30m_avg_3M, 'fguo_trade3.w_upshadow_open_30m_avg_3M')
        self.addDailyData(self.w_upshadow_open_30m_avg_6M, 'fguo_trade3.w_upshadow_open_30m_avg_6M')
        self.addDailyData(self.w_upshadow_open_30m_std_1W, 'fguo_trade3.w_upshadow_open_30m_std_1W')
        self.addDailyData(self.w_upshadow_open_30m_std_1M, 'fguo_trade3.w_upshadow_open_30m_std_1M')
        self.addDailyData(self.w_upshadow_open_30m_std_3M, 'fguo_trade3.w_upshadow_open_30m_std_3M')
        self.addDailyData(self.w_upshadow_open_30m_std_6M, 'fguo_trade3.w_upshadow_open_30m_std_6M')
        self.addDailyData(self.w_upshadow_open_30m_skew_1W, 'fguo_trade3.w_upshadow_open_30m_skew_1W')
        self.addDailyData(self.w_upshadow_open_30m_skew_1M, 'fguo_trade3.w_upshadow_open_30m_skew_1M')
        self.addDailyData(self.w_upshadow_open_30m_skew_3M, 'fguo_trade3.w_upshadow_open_30m_skew_3M')
        self.addDailyData(self.w_upshadow_open_30m_skew_6M, 'fguo_trade3.w_upshadow_open_30m_skew_6M')
        self.addDailyData(self.w_upshadow_close_30m_avg_1W, 'fguo_trade3.w_upshadow_close_30m_avg_1W')
        self.addDailyData(self.w_upshadow_close_30m_avg_1M, 'fguo_trade3.w_upshadow_close_30m_avg_1M')
        self.addDailyData(self.w_upshadow_close_30m_avg_3M, 'fguo_trade3.w_upshadow_close_30m_avg_3M')
        self.addDailyData(self.w_upshadow_close_30m_avg_6M, 'fguo_trade3.w_upshadow_close_30m_avg_6M')
        self.addDailyData(self.w_upshadow_close_30m_std_1W, 'fguo_trade3.w_upshadow_close_30m_std_1W')
        self.addDailyData(self.w_upshadow_close_30m_std_1M, 'fguo_trade3.w_upshadow_close_30m_std_1M')
        self.addDailyData(self.w_upshadow_close_30m_std_3M, 'fguo_trade3.w_upshadow_close_30m_std_3M')
        self.addDailyData(self.w_upshadow_close_30m_std_6M, 'fguo_trade3.w_upshadow_close_30m_std_6M')
        self.addDailyData(self.w_upshadow_close_30m_skew_1W, 'fguo_trade3.w_upshadow_close_30m_skew_1W')
        self.addDailyData(self.w_upshadow_close_30m_skew_1M, 'fguo_trade3.w_upshadow_close_30m_skew_1M')
        self.addDailyData(self.w_upshadow_close_30m_skew_3M, 'fguo_trade3.w_upshadow_close_30m_skew_3M')
        self.addDailyData(self.w_upshadow_close_30m_skew_6M, 'fguo_trade3.w_upshadow_close_30m_skew_6M')
        self.addDailyData(self.w_downshadow_daily_avg_1W, 'fguo_trade3.w_downshadow_daily_avg_1W')
        self.addDailyData(self.w_downshadow_daily_avg_1M, 'fguo_trade3.w_downshadow_daily_avg_1M')
        self.addDailyData(self.w_downshadow_daily_avg_3M, 'fguo_trade3.w_downshadow_daily_avg_3M')
        self.addDailyData(self.w_downshadow_daily_avg_6M, 'fguo_trade3.w_downshadow_daily_avg_6M')
        self.addDailyData(self.w_downshadow_daily_std_1W, 'fguo_trade3.w_downshadow_daily_std_1W')
        self.addDailyData(self.w_downshadow_daily_std_1M, 'fguo_trade3.w_downshadow_daily_std_1M')
        self.addDailyData(self.w_downshadow_daily_std_3M, 'fguo_trade3.w_downshadow_daily_std_3M')
        self.addDailyData(self.w_downshadow_daily_std_6M, 'fguo_trade3.w_downshadow_daily_std_6M')
        self.addDailyData(self.w_downshadow_daily_skew_1W, 'fguo_trade3.w_downshadow_daily_skew_1W')
        self.addDailyData(self.w_downshadow_daily_skew_1M, 'fguo_trade3.w_downshadow_daily_skew_1M')
        self.addDailyData(self.w_downshadow_daily_skew_3M, 'fguo_trade3.w_downshadow_daily_skew_3M')
        self.addDailyData(self.w_downshadow_daily_skew_6M, 'fguo_trade3.w_downshadow_daily_skew_6M')
        self.addDailyData(self.w_downshadow_am_avg_1W, 'fguo_trade3.w_downshadow_am_avg_1W')
        self.addDailyData(self.w_downshadow_am_avg_1M, 'fguo_trade3.w_downshadow_am_avg_1M')
        self.addDailyData(self.w_downshadow_am_avg_3M, 'fguo_trade3.w_downshadow_am_avg_3M')
        self.addDailyData(self.w_downshadow_am_avg_6M, 'fguo_trade3.w_downshadow_am_avg_6M')
        self.addDailyData(self.w_downshadow_am_std_1W, 'fguo_trade3.w_downshadow_am_std_1W')
        self.addDailyData(self.w_downshadow_am_std_1M, 'fguo_trade3.w_downshadow_am_std_1M')
        self.addDailyData(self.w_downshadow_am_std_3M, 'fguo_trade3.w_downshadow_am_std_3M')
        self.addDailyData(self.w_downshadow_am_std_6M, 'fguo_trade3.w_downshadow_am_std_6M')
        self.addDailyData(self.w_downshadow_am_skew_1W, 'fguo_trade3.w_downshadow_am_skew_1W')
        self.addDailyData(self.w_downshadow_am_skew_1M, 'fguo_trade3.w_downshadow_am_skew_1M')
        self.addDailyData(self.w_downshadow_am_skew_3M, 'fguo_trade3.w_downshadow_am_skew_3M')
        self.addDailyData(self.w_downshadow_am_skew_6M, 'fguo_trade3.w_downshadow_am_skew_6M')
        self.addDailyData(self.w_downshadow_pm_avg_1W, 'fguo_trade3.w_downshadow_pm_avg_1W')
        self.addDailyData(self.w_downshadow_pm_avg_1M, 'fguo_trade3.w_downshadow_pm_avg_1M')
        self.addDailyData(self.w_downshadow_pm_avg_3M, 'fguo_trade3.w_downshadow_pm_avg_3M')
        self.addDailyData(self.w_downshadow_pm_avg_6M, 'fguo_trade3.w_downshadow_pm_avg_6M')
        self.addDailyData(self.w_downshadow_pm_std_1W, 'fguo_trade3.w_downshadow_pm_std_1W')
        self.addDailyData(self.w_downshadow_pm_std_1M, 'fguo_trade3.w_downshadow_pm_std_1M')
        self.addDailyData(self.w_downshadow_pm_std_3M, 'fguo_trade3.w_downshadow_pm_std_3M')
        self.addDailyData(self.w_downshadow_pm_std_6M, 'fguo_trade3.w_downshadow_pm_std_6M')
        self.addDailyData(self.w_downshadow_pm_skew_1W, 'fguo_trade3.w_downshadow_pm_skew_1W')
        self.addDailyData(self.w_downshadow_pm_skew_1M, 'fguo_trade3.w_downshadow_pm_skew_1M')
        self.addDailyData(self.w_downshadow_pm_skew_3M, 'fguo_trade3.w_downshadow_pm_skew_3M')
        self.addDailyData(self.w_downshadow_pm_skew_6M, 'fguo_trade3.w_downshadow_pm_skew_6M')
        self.addDailyData(self.w_downshadow_open_30m_avg_1W, 'fguo_trade3.w_downshadow_open_30m_avg_1W')
        self.addDailyData(self.w_downshadow_open_30m_avg_1M, 'fguo_trade3.w_downshadow_open_30m_avg_1M')
        self.addDailyData(self.w_downshadow_open_30m_avg_3M, 'fguo_trade3.w_downshadow_open_30m_avg_3M')
        self.addDailyData(self.w_downshadow_open_30m_avg_6M, 'fguo_trade3.w_downshadow_open_30m_avg_6M')
        self.addDailyData(self.w_downshadow_open_30m_std_1W, 'fguo_trade3.w_downshadow_open_30m_std_1W')
        self.addDailyData(self.w_downshadow_open_30m_std_1M, 'fguo_trade3.w_downshadow_open_30m_std_1M')
        self.addDailyData(self.w_downshadow_open_30m_std_3M, 'fguo_trade3.w_downshadow_open_30m_std_3M')
        self.addDailyData(self.w_downshadow_open_30m_std_6M, 'fguo_trade3.w_downshadow_open_30m_std_6M')
        self.addDailyData(self.w_downshadow_open_30m_skew_1W, 'fguo_trade3.w_downshadow_open_30m_skew_1W')
        self.addDailyData(self.w_downshadow_open_30m_skew_1M, 'fguo_trade3.w_downshadow_open_30m_skew_1M')
        self.addDailyData(self.w_downshadow_open_30m_skew_3M, 'fguo_trade3.w_downshadow_open_30m_skew_3M')
        self.addDailyData(self.w_downshadow_open_30m_skew_6M, 'fguo_trade3.w_downshadow_open_30m_skew_6M')
        self.addDailyData(self.w_downshadow_close_30m_avg_1W, 'fguo_trade3.w_downshadow_close_30m_avg_1W')
        self.addDailyData(self.w_downshadow_close_30m_avg_1M, 'fguo_trade3.w_downshadow_close_30m_avg_1M')
        self.addDailyData(self.w_downshadow_close_30m_avg_3M, 'fguo_trade3.w_downshadow_close_30m_avg_3M')
        self.addDailyData(self.w_downshadow_close_30m_avg_6M, 'fguo_trade3.w_downshadow_close_30m_avg_6M')
        self.addDailyData(self.w_downshadow_close_30m_std_1W, 'fguo_trade3.w_downshadow_close_30m_std_1W')
        self.addDailyData(self.w_downshadow_close_30m_std_1M, 'fguo_trade3.w_downshadow_close_30m_std_1M')
        self.addDailyData(self.w_downshadow_close_30m_std_3M, 'fguo_trade3.w_downshadow_close_30m_std_3M')
        self.addDailyData(self.w_downshadow_close_30m_std_6M, 'fguo_trade3.w_downshadow_close_30m_std_6M')
        self.addDailyData(self.w_downshadow_close_30m_skew_1W, 'fguo_trade3.w_downshadow_close_30m_skew_1W')
        self.addDailyData(self.w_downshadow_close_30m_skew_1M, 'fguo_trade3.w_downshadow_close_30m_skew_1M')
        self.addDailyData(self.w_downshadow_close_30m_skew_3M, 'fguo_trade3.w_downshadow_close_30m_skew_3M')
        self.addDailyData(self.w_downshadow_close_30m_skew_6M, 'fguo_trade3.w_downshadow_close_30m_skew_6M')
        self.addDailyData(self.body_daily_avg_1W, 'fguo_trade3.body_daily_avg_1W')
        self.addDailyData(self.body_daily_avg_1M, 'fguo_trade3.body_daily_avg_1M')
        self.addDailyData(self.body_daily_avg_3M, 'fguo_trade3.body_daily_avg_3M')
        self.addDailyData(self.body_daily_avg_6M, 'fguo_trade3.body_daily_avg_6M')
        self.addDailyData(self.body_daily_std_1W, 'fguo_trade3.body_daily_std_1W')
        self.addDailyData(self.body_daily_std_1M, 'fguo_trade3.body_daily_std_1M')
        self.addDailyData(self.body_daily_std_3M, 'fguo_trade3.body_daily_std_3M')
        self.addDailyData(self.body_daily_std_6M, 'fguo_trade3.body_daily_std_6M')
        self.addDailyData(self.body_daily_skew_1W, 'fguo_trade3.body_daily_skew_1W')
        self.addDailyData(self.body_daily_skew_1M, 'fguo_trade3.body_daily_skew_1M')
        self.addDailyData(self.body_daily_skew_3M, 'fguo_trade3.body_daily_skew_3M')
        self.addDailyData(self.body_daily_skew_6M, 'fguo_trade3.body_daily_skew_6M')
        self.addDailyData(self.body_am_avg_1W, 'fguo_trade3.body_am_avg_1W')
        self.addDailyData(self.body_am_avg_1M, 'fguo_trade3.body_am_avg_1M')
        self.addDailyData(self.body_am_avg_3M, 'fguo_trade3.body_am_avg_3M')
        self.addDailyData(self.body_am_avg_6M, 'fguo_trade3.body_am_avg_6M')
        self.addDailyData(self.body_am_std_1W, 'fguo_trade3.body_am_std_1W')
        self.addDailyData(self.body_am_std_1M, 'fguo_trade3.body_am_std_1M')
        self.addDailyData(self.body_am_std_3M, 'fguo_trade3.body_am_std_3M')
        self.addDailyData(self.body_am_std_6M, 'fguo_trade3.body_am_std_6M')
        self.addDailyData(self.body_am_skew_1W, 'fguo_trade3.body_am_skew_1W')
        self.addDailyData(self.body_am_skew_1M, 'fguo_trade3.body_am_skew_1M')
        self.addDailyData(self.body_am_skew_3M, 'fguo_trade3.body_am_skew_3M')
        self.addDailyData(self.body_am_skew_6M, 'fguo_trade3.body_am_skew_6M')
        self.addDailyData(self.body_pm_avg_1W, 'fguo_trade3.body_pm_avg_1W')
        self.addDailyData(self.body_pm_avg_1M, 'fguo_trade3.body_pm_avg_1M')
        self.addDailyData(self.body_pm_avg_3M, 'fguo_trade3.body_pm_avg_3M')
        self.addDailyData(self.body_pm_avg_6M, 'fguo_trade3.body_pm_avg_6M')
        self.addDailyData(self.body_pm_std_1W, 'fguo_trade3.body_pm_std_1W')
        self.addDailyData(self.body_pm_std_1M, 'fguo_trade3.body_pm_std_1M')
        self.addDailyData(self.body_pm_std_3M, 'fguo_trade3.body_pm_std_3M')
        self.addDailyData(self.body_pm_std_6M, 'fguo_trade3.body_pm_std_6M')
        self.addDailyData(self.body_pm_skew_1W, 'fguo_trade3.body_pm_skew_1W')
        self.addDailyData(self.body_pm_skew_1M, 'fguo_trade3.body_pm_skew_1M')
        self.addDailyData(self.body_pm_skew_3M, 'fguo_trade3.body_pm_skew_3M')
        self.addDailyData(self.body_pm_skew_6M, 'fguo_trade3.body_pm_skew_6M')
        self.addDailyData(self.body_open_30m_avg_1W, 'fguo_trade3.body_open_30m_avg_1W')
        self.addDailyData(self.body_open_30m_avg_1M, 'fguo_trade3.body_open_30m_avg_1M')
        self.addDailyData(self.body_open_30m_avg_3M, 'fguo_trade3.body_open_30m_avg_3M')
        self.addDailyData(self.body_open_30m_avg_6M, 'fguo_trade3.body_open_30m_avg_6M')
        self.addDailyData(self.body_open_30m_std_1W, 'fguo_trade3.body_open_30m_std_1W')
        self.addDailyData(self.body_open_30m_std_1M, 'fguo_trade3.body_open_30m_std_1M')
        self.addDailyData(self.body_open_30m_std_3M, 'fguo_trade3.body_open_30m_std_3M')
        self.addDailyData(self.body_open_30m_std_6M, 'fguo_trade3.body_open_30m_std_6M')
        self.addDailyData(self.body_open_30m_skew_1W, 'fguo_trade3.body_open_30m_skew_1W')
        self.addDailyData(self.body_open_30m_skew_1M, 'fguo_trade3.body_open_30m_skew_1M')
        self.addDailyData(self.body_open_30m_skew_3M, 'fguo_trade3.body_open_30m_skew_3M')
        self.addDailyData(self.body_open_30m_skew_6M, 'fguo_trade3.body_open_30m_skew_6M')
        self.addDailyData(self.body_close_30m_avg_1W, 'fguo_trade3.body_close_30m_avg_1W')
        self.addDailyData(self.body_close_30m_avg_1M, 'fguo_trade3.body_close_30m_avg_1M')
        self.addDailyData(self.body_close_30m_avg_3M, 'fguo_trade3.body_close_30m_avg_3M')
        self.addDailyData(self.body_close_30m_avg_6M, 'fguo_trade3.body_close_30m_avg_6M')
        self.addDailyData(self.body_close_30m_std_1W, 'fguo_trade3.body_close_30m_std_1W')
        self.addDailyData(self.body_close_30m_std_1M, 'fguo_trade3.body_close_30m_std_1M')
        self.addDailyData(self.body_close_30m_std_3M, 'fguo_trade3.body_close_30m_std_3M')
        self.addDailyData(self.body_close_30m_std_6M, 'fguo_trade3.body_close_30m_std_6M')
        self.addDailyData(self.body_close_30m_skew_1W, 'fguo_trade3.body_close_30m_skew_1W')
        self.addDailyData(self.body_close_30m_skew_1M, 'fguo_trade3.body_close_30m_skew_1M')
        self.addDailyData(self.body_close_30m_skew_3M, 'fguo_trade3.body_close_30m_skew_3M')
        self.addDailyData(self.body_close_30m_skew_6M, 'fguo_trade3.body_close_30m_skew_6M')
        self.addDailyData(self.range_daily_avg_1W, 'fguo_trade3.range_daily_avg_1W')
        self.addDailyData(self.range_daily_avg_1M, 'fguo_trade3.range_daily_avg_1M')
        self.addDailyData(self.range_daily_avg_3M, 'fguo_trade3.range_daily_avg_3M')
        self.addDailyData(self.range_daily_avg_6M, 'fguo_trade3.range_daily_avg_6M')
        self.addDailyData(self.range_daily_std_1W, 'fguo_trade3.range_daily_std_1W')
        self.addDailyData(self.range_daily_std_1M, 'fguo_trade3.range_daily_std_1M')
        self.addDailyData(self.range_daily_std_3M, 'fguo_trade3.range_daily_std_3M')
        self.addDailyData(self.range_daily_std_6M, 'fguo_trade3.range_daily_std_6M')
        self.addDailyData(self.range_daily_skew_1W, 'fguo_trade3.range_daily_skew_1W')
        self.addDailyData(self.range_daily_skew_1M, 'fguo_trade3.range_daily_skew_1M')
        self.addDailyData(self.range_daily_skew_3M, 'fguo_trade3.range_daily_skew_3M')
        self.addDailyData(self.range_daily_skew_6M, 'fguo_trade3.range_daily_skew_6M')
        self.addDailyData(self.range_am_avg_1W, 'fguo_trade3.range_am_avg_1W')
        self.addDailyData(self.range_am_avg_1M, 'fguo_trade3.range_am_avg_1M')
        self.addDailyData(self.range_am_avg_3M, 'fguo_trade3.range_am_avg_3M')
        self.addDailyData(self.range_am_avg_6M, 'fguo_trade3.range_am_avg_6M')
        self.addDailyData(self.range_am_std_1W, 'fguo_trade3.range_am_std_1W')
        self.addDailyData(self.range_am_std_1M, 'fguo_trade3.range_am_std_1M')
        self.addDailyData(self.range_am_std_3M, 'fguo_trade3.range_am_std_3M')
        self.addDailyData(self.range_am_std_6M, 'fguo_trade3.range_am_std_6M')
        self.addDailyData(self.range_am_skew_1W, 'fguo_trade3.range_am_skew_1W')
        self.addDailyData(self.range_am_skew_1M, 'fguo_trade3.range_am_skew_1M')
        self.addDailyData(self.range_am_skew_3M, 'fguo_trade3.range_am_skew_3M')
        self.addDailyData(self.range_am_skew_6M, 'fguo_trade3.range_am_skew_6M')
        self.addDailyData(self.range_pm_avg_1W, 'fguo_trade3.range_pm_avg_1W')
        self.addDailyData(self.range_pm_avg_1M, 'fguo_trade3.range_pm_avg_1M')
        self.addDailyData(self.range_pm_avg_3M, 'fguo_trade3.range_pm_avg_3M')
        self.addDailyData(self.range_pm_avg_6M, 'fguo_trade3.range_pm_avg_6M')
        self.addDailyData(self.range_pm_std_1W, 'fguo_trade3.range_pm_std_1W')
        self.addDailyData(self.range_pm_std_1M, 'fguo_trade3.range_pm_std_1M')
        self.addDailyData(self.range_pm_std_3M, 'fguo_trade3.range_pm_std_3M')
        self.addDailyData(self.range_pm_std_6M, 'fguo_trade3.range_pm_std_6M')
        self.addDailyData(self.range_pm_skew_1W, 'fguo_trade3.range_pm_skew_1W')
        self.addDailyData(self.range_pm_skew_1M, 'fguo_trade3.range_pm_skew_1M')
        self.addDailyData(self.range_pm_skew_3M, 'fguo_trade3.range_pm_skew_3M')
        self.addDailyData(self.range_pm_skew_6M, 'fguo_trade3.range_pm_skew_6M')
        self.addDailyData(self.range_open_30m_avg_1W, 'fguo_trade3.range_open_30m_avg_1W')
        self.addDailyData(self.range_open_30m_avg_1M, 'fguo_trade3.range_open_30m_avg_1M')
        self.addDailyData(self.range_open_30m_avg_3M, 'fguo_trade3.range_open_30m_avg_3M')
        self.addDailyData(self.range_open_30m_avg_6M, 'fguo_trade3.range_open_30m_avg_6M')
        self.addDailyData(self.range_open_30m_std_1W, 'fguo_trade3.range_open_30m_std_1W')
        self.addDailyData(self.range_open_30m_std_1M, 'fguo_trade3.range_open_30m_std_1M')
        self.addDailyData(self.range_open_30m_std_3M, 'fguo_trade3.range_open_30m_std_3M')
        self.addDailyData(self.range_open_30m_std_6M, 'fguo_trade3.range_open_30m_std_6M')
        self.addDailyData(self.range_open_30m_skew_1W, 'fguo_trade3.range_open_30m_skew_1W')
        self.addDailyData(self.range_open_30m_skew_1M, 'fguo_trade3.range_open_30m_skew_1M')
        self.addDailyData(self.range_open_30m_skew_3M, 'fguo_trade3.range_open_30m_skew_3M')
        self.addDailyData(self.range_open_30m_skew_6M, 'fguo_trade3.range_open_30m_skew_6M')
        self.addDailyData(self.range_close_30m_avg_1W, 'fguo_trade3.range_close_30m_avg_1W')
        self.addDailyData(self.range_close_30m_avg_1M, 'fguo_trade3.range_close_30m_avg_1M')
        self.addDailyData(self.range_close_30m_avg_3M, 'fguo_trade3.range_close_30m_avg_3M')
        self.addDailyData(self.range_close_30m_avg_6M, 'fguo_trade3.range_close_30m_avg_6M')
        self.addDailyData(self.range_close_30m_std_1W, 'fguo_trade3.range_close_30m_std_1W')
        self.addDailyData(self.range_close_30m_std_1M, 'fguo_trade3.range_close_30m_std_1M')
        self.addDailyData(self.range_close_30m_std_3M, 'fguo_trade3.range_close_30m_std_3M')
        self.addDailyData(self.range_close_30m_std_6M, 'fguo_trade3.range_close_30m_std_6M')
        self.addDailyData(self.range_close_30m_skew_1W, 'fguo_trade3.range_close_30m_skew_1W')
        self.addDailyData(self.range_close_30m_skew_1M, 'fguo_trade3.range_close_30m_skew_1M')
        self.addDailyData(self.range_close_30m_skew_3M, 'fguo_trade3.range_close_30m_skew_3M')
        self.addDailyData(self.range_close_30m_skew_6M, 'fguo_trade3.range_close_30m_skew_6M')
        self.addDailyData(self.up_down_ratio_daily_avg_1W, 'fguo_trade3.up_down_ratio_daily_avg_1W')
        self.addDailyData(self.up_down_ratio_daily_avg_1M, 'fguo_trade3.up_down_ratio_daily_avg_1M')
        self.addDailyData(self.up_down_ratio_daily_avg_3M, 'fguo_trade3.up_down_ratio_daily_avg_3M')
        self.addDailyData(self.up_down_ratio_daily_avg_6M, 'fguo_trade3.up_down_ratio_daily_avg_6M')
        self.addDailyData(self.up_down_ratio_daily_std_1W, 'fguo_trade3.up_down_ratio_daily_std_1W')
        self.addDailyData(self.up_down_ratio_daily_std_1M, 'fguo_trade3.up_down_ratio_daily_std_1M')
        self.addDailyData(self.up_down_ratio_daily_std_3M, 'fguo_trade3.up_down_ratio_daily_std_3M')
        self.addDailyData(self.up_down_ratio_daily_std_6M, 'fguo_trade3.up_down_ratio_daily_std_6M')
        self.addDailyData(self.up_down_ratio_daily_skew_1W, 'fguo_trade3.up_down_ratio_daily_skew_1W')
        self.addDailyData(self.up_down_ratio_daily_skew_1M, 'fguo_trade3.up_down_ratio_daily_skew_1M')
        self.addDailyData(self.up_down_ratio_daily_skew_3M, 'fguo_trade3.up_down_ratio_daily_skew_3M')
        self.addDailyData(self.up_down_ratio_daily_skew_6M, 'fguo_trade3.up_down_ratio_daily_skew_6M')
        self.addDailyData(self.up_down_ratio_am_avg_1W, 'fguo_trade3.up_down_ratio_am_avg_1W')
        self.addDailyData(self.up_down_ratio_am_avg_1M, 'fguo_trade3.up_down_ratio_am_avg_1M')
        self.addDailyData(self.up_down_ratio_am_avg_3M, 'fguo_trade3.up_down_ratio_am_avg_3M')
        self.addDailyData(self.up_down_ratio_am_avg_6M, 'fguo_trade3.up_down_ratio_am_avg_6M')
        self.addDailyData(self.up_down_ratio_am_std_1W, 'fguo_trade3.up_down_ratio_am_std_1W')
        self.addDailyData(self.up_down_ratio_am_std_1M, 'fguo_trade3.up_down_ratio_am_std_1M')
        self.addDailyData(self.up_down_ratio_am_std_3M, 'fguo_trade3.up_down_ratio_am_std_3M')
        self.addDailyData(self.up_down_ratio_am_std_6M, 'fguo_trade3.up_down_ratio_am_std_6M')
        self.addDailyData(self.up_down_ratio_am_skew_1W, 'fguo_trade3.up_down_ratio_am_skew_1W')
        self.addDailyData(self.up_down_ratio_am_skew_1M, 'fguo_trade3.up_down_ratio_am_skew_1M')
        self.addDailyData(self.up_down_ratio_am_skew_3M, 'fguo_trade3.up_down_ratio_am_skew_3M')
        self.addDailyData(self.up_down_ratio_am_skew_6M, 'fguo_trade3.up_down_ratio_am_skew_6M')
        self.addDailyData(self.up_down_ratio_pm_avg_1W, 'fguo_trade3.up_down_ratio_pm_avg_1W')
        self.addDailyData(self.up_down_ratio_pm_avg_1M, 'fguo_trade3.up_down_ratio_pm_avg_1M')
        self.addDailyData(self.up_down_ratio_pm_avg_3M, 'fguo_trade3.up_down_ratio_pm_avg_3M')
        self.addDailyData(self.up_down_ratio_pm_avg_6M, 'fguo_trade3.up_down_ratio_pm_avg_6M')
        self.addDailyData(self.up_down_ratio_pm_std_1W, 'fguo_trade3.up_down_ratio_pm_std_1W')
        self.addDailyData(self.up_down_ratio_pm_std_1M, 'fguo_trade3.up_down_ratio_pm_std_1M')
        self.addDailyData(self.up_down_ratio_pm_std_3M, 'fguo_trade3.up_down_ratio_pm_std_3M')
        self.addDailyData(self.up_down_ratio_pm_std_6M, 'fguo_trade3.up_down_ratio_pm_std_6M')
        self.addDailyData(self.up_down_ratio_pm_skew_1W, 'fguo_trade3.up_down_ratio_pm_skew_1W')
        self.addDailyData(self.up_down_ratio_pm_skew_1M, 'fguo_trade3.up_down_ratio_pm_skew_1M')
        self.addDailyData(self.up_down_ratio_pm_skew_3M, 'fguo_trade3.up_down_ratio_pm_skew_3M')
        self.addDailyData(self.up_down_ratio_pm_skew_6M, 'fguo_trade3.up_down_ratio_pm_skew_6M')
        self.addDailyData(self.up_down_ratio_open_30m_avg_1W, 'fguo_trade3.up_down_ratio_open_30m_avg_1W')
        self.addDailyData(self.up_down_ratio_open_30m_avg_1M, 'fguo_trade3.up_down_ratio_open_30m_avg_1M')
        self.addDailyData(self.up_down_ratio_open_30m_avg_3M, 'fguo_trade3.up_down_ratio_open_30m_avg_3M')
        self.addDailyData(self.up_down_ratio_open_30m_avg_6M, 'fguo_trade3.up_down_ratio_open_30m_avg_6M')
        self.addDailyData(self.up_down_ratio_open_30m_std_1W, 'fguo_trade3.up_down_ratio_open_30m_std_1W')
        self.addDailyData(self.up_down_ratio_open_30m_std_1M, 'fguo_trade3.up_down_ratio_open_30m_std_1M')
        self.addDailyData(self.up_down_ratio_open_30m_std_3M, 'fguo_trade3.up_down_ratio_open_30m_std_3M')
        self.addDailyData(self.up_down_ratio_open_30m_std_6M, 'fguo_trade3.up_down_ratio_open_30m_std_6M')
        self.addDailyData(self.up_down_ratio_open_30m_skew_1W, 'fguo_trade3.up_down_ratio_open_30m_skew_1W')
        self.addDailyData(self.up_down_ratio_open_30m_skew_1M, 'fguo_trade3.up_down_ratio_open_30m_skew_1M')
        self.addDailyData(self.up_down_ratio_open_30m_skew_3M, 'fguo_trade3.up_down_ratio_open_30m_skew_3M')
        self.addDailyData(self.up_down_ratio_open_30m_skew_6M, 'fguo_trade3.up_down_ratio_open_30m_skew_6M')
        self.addDailyData(self.up_down_ratio_close_30m_avg_1W, 'fguo_trade3.up_down_ratio_close_30m_avg_1W')
        self.addDailyData(self.up_down_ratio_close_30m_avg_1M, 'fguo_trade3.up_down_ratio_close_30m_avg_1M')
        self.addDailyData(self.up_down_ratio_close_30m_avg_3M, 'fguo_trade3.up_down_ratio_close_30m_avg_3M')
        self.addDailyData(self.up_down_ratio_close_30m_avg_6M, 'fguo_trade3.up_down_ratio_close_30m_avg_6M')
        self.addDailyData(self.up_down_ratio_close_30m_std_1W, 'fguo_trade3.up_down_ratio_close_30m_std_1W')
        self.addDailyData(self.up_down_ratio_close_30m_std_1M, 'fguo_trade3.up_down_ratio_close_30m_std_1M')
        self.addDailyData(self.up_down_ratio_close_30m_std_3M, 'fguo_trade3.up_down_ratio_close_30m_std_3M')
        self.addDailyData(self.up_down_ratio_close_30m_std_6M, 'fguo_trade3.up_down_ratio_close_30m_std_6M')
        self.addDailyData(self.up_down_ratio_close_30m_skew_1W, 'fguo_trade3.up_down_ratio_close_30m_skew_1W')
        self.addDailyData(self.up_down_ratio_close_30m_skew_1M, 'fguo_trade3.up_down_ratio_close_30m_skew_1M')
        self.addDailyData(self.up_down_ratio_close_30m_skew_3M, 'fguo_trade3.up_down_ratio_close_30m_skew_3M')
        self.addDailyData(self.up_down_ratio_close_30m_skew_6M, 'fguo_trade3.up_down_ratio_close_30m_skew_6M')
        self.addDailyData(self.upshadow_am_pm_ratio_avg_1W, 'fguo_trade3.upshadow_am_pm_ratio_avg_1W')
        self.addDailyData(self.upshadow_am_pm_ratio_avg_1M, 'fguo_trade3.upshadow_am_pm_ratio_avg_1M')
        self.addDailyData(self.upshadow_am_pm_ratio_avg_3M, 'fguo_trade3.upshadow_am_pm_ratio_avg_3M')
        self.addDailyData(self.upshadow_am_pm_ratio_avg_6M, 'fguo_trade3.upshadow_am_pm_ratio_avg_6M')
        self.addDailyData(self.upshadow_am_pm_ratio_std_1W, 'fguo_trade3.upshadow_am_pm_ratio_std_1W')
        self.addDailyData(self.upshadow_am_pm_ratio_std_1M, 'fguo_trade3.upshadow_am_pm_ratio_std_1M')
        self.addDailyData(self.upshadow_am_pm_ratio_std_3M, 'fguo_trade3.upshadow_am_pm_ratio_std_3M')
        self.addDailyData(self.upshadow_am_pm_ratio_std_6M, 'fguo_trade3.upshadow_am_pm_ratio_std_6M')
        self.addDailyData(self.upshadow_am_pm_ratio_skew_1W, 'fguo_trade3.upshadow_am_pm_ratio_skew_1W')
        self.addDailyData(self.upshadow_am_pm_ratio_skew_1M, 'fguo_trade3.upshadow_am_pm_ratio_skew_1M')
        self.addDailyData(self.upshadow_am_pm_ratio_skew_3M, 'fguo_trade3.upshadow_am_pm_ratio_skew_3M')
        self.addDailyData(self.upshadow_am_pm_ratio_skew_6M, 'fguo_trade3.upshadow_am_pm_ratio_skew_6M')
        self.addDailyData(self.downshadow_am_pm_ratio_avg_1W, 'fguo_trade3.downshadow_am_pm_ratio_avg_1W')
        self.addDailyData(self.downshadow_am_pm_ratio_avg_1M, 'fguo_trade3.downshadow_am_pm_ratio_avg_1M')
        self.addDailyData(self.downshadow_am_pm_ratio_avg_3M, 'fguo_trade3.downshadow_am_pm_ratio_avg_3M')
        self.addDailyData(self.downshadow_am_pm_ratio_avg_6M, 'fguo_trade3.downshadow_am_pm_ratio_avg_6M')
        self.addDailyData(self.downshadow_am_pm_ratio_std_1W, 'fguo_trade3.downshadow_am_pm_ratio_std_1W')
        self.addDailyData(self.downshadow_am_pm_ratio_std_1M, 'fguo_trade3.downshadow_am_pm_ratio_std_1M')
        self.addDailyData(self.downshadow_am_pm_ratio_std_3M, 'fguo_trade3.downshadow_am_pm_ratio_std_3M')
        self.addDailyData(self.downshadow_am_pm_ratio_std_6M, 'fguo_trade3.downshadow_am_pm_ratio_std_6M')
        self.addDailyData(self.downshadow_am_pm_ratio_skew_1W, 'fguo_trade3.downshadow_am_pm_ratio_skew_1W')
        self.addDailyData(self.downshadow_am_pm_ratio_skew_1M, 'fguo_trade3.downshadow_am_pm_ratio_skew_1M')
        self.addDailyData(self.downshadow_am_pm_ratio_skew_3M, 'fguo_trade3.downshadow_am_pm_ratio_skew_3M')
        self.addDailyData(self.downshadow_am_pm_ratio_skew_6M, 'fguo_trade3.downshadow_am_pm_ratio_skew_6M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_avg_1W, 'fguo_trade3.w_upshadow_am_pm_ratio_avg_1W')
        self.addDailyData(self.w_upshadow_am_pm_ratio_avg_1M, 'fguo_trade3.w_upshadow_am_pm_ratio_avg_1M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_avg_3M, 'fguo_trade3.w_upshadow_am_pm_ratio_avg_3M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_avg_6M, 'fguo_trade3.w_upshadow_am_pm_ratio_avg_6M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_std_1W, 'fguo_trade3.w_upshadow_am_pm_ratio_std_1W')
        self.addDailyData(self.w_upshadow_am_pm_ratio_std_1M, 'fguo_trade3.w_upshadow_am_pm_ratio_std_1M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_std_3M, 'fguo_trade3.w_upshadow_am_pm_ratio_std_3M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_std_6M, 'fguo_trade3.w_upshadow_am_pm_ratio_std_6M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_skew_1W, 'fguo_trade3.w_upshadow_am_pm_ratio_skew_1W')
        self.addDailyData(self.w_upshadow_am_pm_ratio_skew_1M, 'fguo_trade3.w_upshadow_am_pm_ratio_skew_1M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_skew_3M, 'fguo_trade3.w_upshadow_am_pm_ratio_skew_3M')
        self.addDailyData(self.w_upshadow_am_pm_ratio_skew_6M, 'fguo_trade3.w_upshadow_am_pm_ratio_skew_6M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_avg_1W, 'fguo_trade3.w_downshadow_am_pm_ratio_avg_1W')
        self.addDailyData(self.w_downshadow_am_pm_ratio_avg_1M, 'fguo_trade3.w_downshadow_am_pm_ratio_avg_1M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_avg_3M, 'fguo_trade3.w_downshadow_am_pm_ratio_avg_3M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_avg_6M, 'fguo_trade3.w_downshadow_am_pm_ratio_avg_6M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_std_1W, 'fguo_trade3.w_downshadow_am_pm_ratio_std_1W')
        self.addDailyData(self.w_downshadow_am_pm_ratio_std_1M, 'fguo_trade3.w_downshadow_am_pm_ratio_std_1M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_std_3M, 'fguo_trade3.w_downshadow_am_pm_ratio_std_3M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_std_6M, 'fguo_trade3.w_downshadow_am_pm_ratio_std_6M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_skew_1W, 'fguo_trade3.w_downshadow_am_pm_ratio_skew_1W')
        self.addDailyData(self.w_downshadow_am_pm_ratio_skew_1M, 'fguo_trade3.w_downshadow_am_pm_ratio_skew_1M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_skew_3M, 'fguo_trade3.w_downshadow_am_pm_ratio_skew_3M')
        self.addDailyData(self.w_downshadow_am_pm_ratio_skew_6M, 'fguo_trade3.w_downshadow_am_pm_ratio_skew_6M')
        self.addDailyData(self.body_am_pm_ratio_avg_1W, 'fguo_trade3.body_am_pm_ratio_avg_1W')
        self.addDailyData(self.body_am_pm_ratio_avg_1M, 'fguo_trade3.body_am_pm_ratio_avg_1M')
        self.addDailyData(self.body_am_pm_ratio_avg_3M, 'fguo_trade3.body_am_pm_ratio_avg_3M')
        self.addDailyData(self.body_am_pm_ratio_avg_6M, 'fguo_trade3.body_am_pm_ratio_avg_6M')
        self.addDailyData(self.body_am_pm_ratio_std_1W, 'fguo_trade3.body_am_pm_ratio_std_1W')
        self.addDailyData(self.body_am_pm_ratio_std_1M, 'fguo_trade3.body_am_pm_ratio_std_1M')
        self.addDailyData(self.body_am_pm_ratio_std_3M, 'fguo_trade3.body_am_pm_ratio_std_3M')
        self.addDailyData(self.body_am_pm_ratio_std_6M, 'fguo_trade3.body_am_pm_ratio_std_6M')
        self.addDailyData(self.body_am_pm_ratio_skew_1W, 'fguo_trade3.body_am_pm_ratio_skew_1W')
        self.addDailyData(self.body_am_pm_ratio_skew_1M, 'fguo_trade3.body_am_pm_ratio_skew_1M')
        self.addDailyData(self.body_am_pm_ratio_skew_3M, 'fguo_trade3.body_am_pm_ratio_skew_3M')
        self.addDailyData(self.body_am_pm_ratio_skew_6M, 'fguo_trade3.body_am_pm_ratio_skew_6M')
        self.addDailyData(self.range_am_pm_ratio_avg_1W, 'fguo_trade3.range_am_pm_ratio_avg_1W')
        self.addDailyData(self.range_am_pm_ratio_avg_1M, 'fguo_trade3.range_am_pm_ratio_avg_1M')
        self.addDailyData(self.range_am_pm_ratio_avg_3M, 'fguo_trade3.range_am_pm_ratio_avg_3M')
        self.addDailyData(self.range_am_pm_ratio_avg_6M, 'fguo_trade3.range_am_pm_ratio_avg_6M')
        self.addDailyData(self.range_am_pm_ratio_std_1W, 'fguo_trade3.range_am_pm_ratio_std_1W')
        self.addDailyData(self.range_am_pm_ratio_std_1M, 'fguo_trade3.range_am_pm_ratio_std_1M')
        self.addDailyData(self.range_am_pm_ratio_std_3M, 'fguo_trade3.range_am_pm_ratio_std_3M')
        self.addDailyData(self.range_am_pm_ratio_std_6M, 'fguo_trade3.range_am_pm_ratio_std_6M')
        self.addDailyData(self.range_am_pm_ratio_skew_1W, 'fguo_trade3.range_am_pm_ratio_skew_1W')
        self.addDailyData(self.range_am_pm_ratio_skew_1M, 'fguo_trade3.range_am_pm_ratio_skew_1M')
        self.addDailyData(self.range_am_pm_ratio_skew_3M, 'fguo_trade3.range_am_pm_ratio_skew_3M')
        self.addDailyData(self.range_am_pm_ratio_skew_6M, 'fguo_trade3.range_am_pm_ratio_skew_6M')
        self.addDailyData(self.upshadow_open_close_ratio_avg_1W, 'fguo_trade3.upshadow_open_close_ratio_avg_1W')
        self.addDailyData(self.upshadow_open_close_ratio_avg_1M, 'fguo_trade3.upshadow_open_close_ratio_avg_1M')
        self.addDailyData(self.upshadow_open_close_ratio_avg_3M, 'fguo_trade3.upshadow_open_close_ratio_avg_3M')
        self.addDailyData(self.upshadow_open_close_ratio_avg_6M, 'fguo_trade3.upshadow_open_close_ratio_avg_6M')
        self.addDailyData(self.upshadow_open_close_ratio_std_1W, 'fguo_trade3.upshadow_open_close_ratio_std_1W')
        self.addDailyData(self.upshadow_open_close_ratio_std_1M, 'fguo_trade3.upshadow_open_close_ratio_std_1M')
        self.addDailyData(self.upshadow_open_close_ratio_std_3M, 'fguo_trade3.upshadow_open_close_ratio_std_3M')
        self.addDailyData(self.upshadow_open_close_ratio_std_6M, 'fguo_trade3.upshadow_open_close_ratio_std_6M')
        self.addDailyData(self.upshadow_open_close_ratio_skew_1W, 'fguo_trade3.upshadow_open_close_ratio_skew_1W')
        self.addDailyData(self.upshadow_open_close_ratio_skew_1M, 'fguo_trade3.upshadow_open_close_ratio_skew_1M')
        self.addDailyData(self.upshadow_open_close_ratio_skew_3M, 'fguo_trade3.upshadow_open_close_ratio_skew_3M')
        self.addDailyData(self.upshadow_open_close_ratio_skew_6M, 'fguo_trade3.upshadow_open_close_ratio_skew_6M')
        self.addDailyData(self.downshadow_open_close_ratio_avg_1W, 'fguo_trade3.downshadow_open_close_ratio_avg_1W')
        self.addDailyData(self.downshadow_open_close_ratio_avg_1M, 'fguo_trade3.downshadow_open_close_ratio_avg_1M')
        self.addDailyData(self.downshadow_open_close_ratio_avg_3M, 'fguo_trade3.downshadow_open_close_ratio_avg_3M')
        self.addDailyData(self.downshadow_open_close_ratio_avg_6M, 'fguo_trade3.downshadow_open_close_ratio_avg_6M')
        self.addDailyData(self.downshadow_open_close_ratio_std_1W, 'fguo_trade3.downshadow_open_close_ratio_std_1W')
        self.addDailyData(self.downshadow_open_close_ratio_std_1M, 'fguo_trade3.downshadow_open_close_ratio_std_1M')
        self.addDailyData(self.downshadow_open_close_ratio_std_3M, 'fguo_trade3.downshadow_open_close_ratio_std_3M')
        self.addDailyData(self.downshadow_open_close_ratio_std_6M, 'fguo_trade3.downshadow_open_close_ratio_std_6M')
        self.addDailyData(self.downshadow_open_close_ratio_skew_1W, 'fguo_trade3.downshadow_open_close_ratio_skew_1W')
        self.addDailyData(self.downshadow_open_close_ratio_skew_1M, 'fguo_trade3.downshadow_open_close_ratio_skew_1M')
        self.addDailyData(self.downshadow_open_close_ratio_skew_3M, 'fguo_trade3.downshadow_open_close_ratio_skew_3M')
        self.addDailyData(self.downshadow_open_close_ratio_skew_6M, 'fguo_trade3.downshadow_open_close_ratio_skew_6M')
        self.addDailyData(self.w_upshadow_open_close_ratio_avg_1W, 'fguo_trade3.w_upshadow_open_close_ratio_avg_1W')
        self.addDailyData(self.w_upshadow_open_close_ratio_avg_1M, 'fguo_trade3.w_upshadow_open_close_ratio_avg_1M')
        self.addDailyData(self.w_upshadow_open_close_ratio_avg_3M, 'fguo_trade3.w_upshadow_open_close_ratio_avg_3M')
        self.addDailyData(self.w_upshadow_open_close_ratio_avg_6M, 'fguo_trade3.w_upshadow_open_close_ratio_avg_6M')
        self.addDailyData(self.w_upshadow_open_close_ratio_std_1W, 'fguo_trade3.w_upshadow_open_close_ratio_std_1W')
        self.addDailyData(self.w_upshadow_open_close_ratio_std_1M, 'fguo_trade3.w_upshadow_open_close_ratio_std_1M')
        self.addDailyData(self.w_upshadow_open_close_ratio_std_3M, 'fguo_trade3.w_upshadow_open_close_ratio_std_3M')
        self.addDailyData(self.w_upshadow_open_close_ratio_std_6M, 'fguo_trade3.w_upshadow_open_close_ratio_std_6M')
        self.addDailyData(self.w_upshadow_open_close_ratio_skew_1W, 'fguo_trade3.w_upshadow_open_close_ratio_skew_1W')
        self.addDailyData(self.w_upshadow_open_close_ratio_skew_1M, 'fguo_trade3.w_upshadow_open_close_ratio_skew_1M')
        self.addDailyData(self.w_upshadow_open_close_ratio_skew_3M, 'fguo_trade3.w_upshadow_open_close_ratio_skew_3M')
        self.addDailyData(self.w_upshadow_open_close_ratio_skew_6M, 'fguo_trade3.w_upshadow_open_close_ratio_skew_6M')
        self.addDailyData(self.w_downshadow_open_close_ratio_avg_1W, 'fguo_trade3.w_downshadow_open_close_ratio_avg_1W')
        self.addDailyData(self.w_downshadow_open_close_ratio_avg_1M, 'fguo_trade3.w_downshadow_open_close_ratio_avg_1M')
        self.addDailyData(self.w_downshadow_open_close_ratio_avg_3M, 'fguo_trade3.w_downshadow_open_close_ratio_avg_3M')
        self.addDailyData(self.w_downshadow_open_close_ratio_avg_6M, 'fguo_trade3.w_downshadow_open_close_ratio_avg_6M')
        self.addDailyData(self.w_downshadow_open_close_ratio_std_1W, 'fguo_trade3.w_downshadow_open_close_ratio_std_1W')
        self.addDailyData(self.w_downshadow_open_close_ratio_std_1M, 'fguo_trade3.w_downshadow_open_close_ratio_std_1M')
        self.addDailyData(self.w_downshadow_open_close_ratio_std_3M, 'fguo_trade3.w_downshadow_open_close_ratio_std_3M')
        self.addDailyData(self.w_downshadow_open_close_ratio_std_6M, 'fguo_trade3.w_downshadow_open_close_ratio_std_6M')
        self.addDailyData(self.w_downshadow_open_close_ratio_skew_1W, 'fguo_trade3.w_downshadow_open_close_ratio_skew_1W')
        self.addDailyData(self.w_downshadow_open_close_ratio_skew_1M, 'fguo_trade3.w_downshadow_open_close_ratio_skew_1M')
        self.addDailyData(self.w_downshadow_open_close_ratio_skew_3M, 'fguo_trade3.w_downshadow_open_close_ratio_skew_3M')
        self.addDailyData(self.w_downshadow_open_close_ratio_skew_6M, 'fguo_trade3.w_downshadow_open_close_ratio_skew_6M')
        self.addDailyData(self.body_open_close_ratio_avg_1W, 'fguo_trade3.body_open_close_ratio_avg_1W')
        self.addDailyData(self.body_open_close_ratio_avg_1M, 'fguo_trade3.body_open_close_ratio_avg_1M')
        self.addDailyData(self.body_open_close_ratio_avg_3M, 'fguo_trade3.body_open_close_ratio_avg_3M')
        self.addDailyData(self.body_open_close_ratio_avg_6M, 'fguo_trade3.body_open_close_ratio_avg_6M')
        self.addDailyData(self.body_open_close_ratio_std_1W, 'fguo_trade3.body_open_close_ratio_std_1W')
        self.addDailyData(self.body_open_close_ratio_std_1M, 'fguo_trade3.body_open_close_ratio_std_1M')
        self.addDailyData(self.body_open_close_ratio_std_3M, 'fguo_trade3.body_open_close_ratio_std_3M')
        self.addDailyData(self.body_open_close_ratio_std_6M, 'fguo_trade3.body_open_close_ratio_std_6M')
        self.addDailyData(self.body_open_close_ratio_skew_1W, 'fguo_trade3.body_open_close_ratio_skew_1W')
        self.addDailyData(self.body_open_close_ratio_skew_1M, 'fguo_trade3.body_open_close_ratio_skew_1M')
        self.addDailyData(self.body_open_close_ratio_skew_3M, 'fguo_trade3.body_open_close_ratio_skew_3M')
        self.addDailyData(self.body_open_close_ratio_skew_6M, 'fguo_trade3.body_open_close_ratio_skew_6M')
        self.addDailyData(self.range_open_close_ratio_avg_1W, 'fguo_trade3.range_open_close_ratio_avg_1W')
        self.addDailyData(self.range_open_close_ratio_avg_1M, 'fguo_trade3.range_open_close_ratio_avg_1M')
        self.addDailyData(self.range_open_close_ratio_avg_3M, 'fguo_trade3.range_open_close_ratio_avg_3M')
        self.addDailyData(self.range_open_close_ratio_avg_6M, 'fguo_trade3.range_open_close_ratio_avg_6M')
        self.addDailyData(self.range_open_close_ratio_std_1W, 'fguo_trade3.range_open_close_ratio_std_1W')
        self.addDailyData(self.range_open_close_ratio_std_1M, 'fguo_trade3.range_open_close_ratio_std_1M')
        self.addDailyData(self.range_open_close_ratio_std_3M, 'fguo_trade3.range_open_close_ratio_std_3M')
        self.addDailyData(self.range_open_close_ratio_std_6M, 'fguo_trade3.range_open_close_ratio_std_6M')
        self.addDailyData(self.range_open_close_ratio_skew_1W, 'fguo_trade3.range_open_close_ratio_skew_1W')
        self.addDailyData(self.range_open_close_ratio_skew_1M, 'fguo_trade3.range_open_close_ratio_skew_1M')
        self.addDailyData(self.range_open_close_ratio_skew_3M, 'fguo_trade3.range_open_close_ratio_skew_3M')
        self.addDailyData(self.range_open_close_ratio_skew_6M, 'fguo_trade3.range_open_close_ratio_skew_6M')
        self.addDailyData(self.upshadow_range_pct_avg_1W, 'fguo_trade3.upshadow_range_pct_avg_1W')
        self.addDailyData(self.upshadow_range_pct_avg_1M, 'fguo_trade3.upshadow_range_pct_avg_1M')
        self.addDailyData(self.upshadow_range_pct_avg_3M, 'fguo_trade3.upshadow_range_pct_avg_3M')
        self.addDailyData(self.upshadow_range_pct_avg_6M, 'fguo_trade3.upshadow_range_pct_avg_6M')
        self.addDailyData(self.upshadow_range_pct_std_1W, 'fguo_trade3.upshadow_range_pct_std_1W')
        self.addDailyData(self.upshadow_range_pct_std_1M, 'fguo_trade3.upshadow_range_pct_std_1M')
        self.addDailyData(self.upshadow_range_pct_std_3M, 'fguo_trade3.upshadow_range_pct_std_3M')
        self.addDailyData(self.upshadow_range_pct_std_6M, 'fguo_trade3.upshadow_range_pct_std_6M')
        self.addDailyData(self.upshadow_range_pct_skew_1W, 'fguo_trade3.upshadow_range_pct_skew_1W')
        self.addDailyData(self.upshadow_range_pct_skew_1M, 'fguo_trade3.upshadow_range_pct_skew_1M')
        self.addDailyData(self.upshadow_range_pct_skew_3M, 'fguo_trade3.upshadow_range_pct_skew_3M')
        self.addDailyData(self.upshadow_range_pct_skew_6M, 'fguo_trade3.upshadow_range_pct_skew_6M')
        self.addDailyData(self.downshadow_range_pct_avg_1W, 'fguo_trade3.downshadow_range_pct_avg_1W')
        self.addDailyData(self.downshadow_range_pct_avg_1M, 'fguo_trade3.downshadow_range_pct_avg_1M')
        self.addDailyData(self.downshadow_range_pct_avg_3M, 'fguo_trade3.downshadow_range_pct_avg_3M')
        self.addDailyData(self.downshadow_range_pct_avg_6M, 'fguo_trade3.downshadow_range_pct_avg_6M')
        self.addDailyData(self.downshadow_range_pct_std_1W, 'fguo_trade3.downshadow_range_pct_std_1W')
        self.addDailyData(self.downshadow_range_pct_std_1M, 'fguo_trade3.downshadow_range_pct_std_1M')
        self.addDailyData(self.downshadow_range_pct_std_3M, 'fguo_trade3.downshadow_range_pct_std_3M')
        self.addDailyData(self.downshadow_range_pct_std_6M, 'fguo_trade3.downshadow_range_pct_std_6M')
        self.addDailyData(self.downshadow_range_pct_skew_1W, 'fguo_trade3.downshadow_range_pct_skew_1W')
        self.addDailyData(self.downshadow_range_pct_skew_1M, 'fguo_trade3.downshadow_range_pct_skew_1M')
        self.addDailyData(self.downshadow_range_pct_skew_3M, 'fguo_trade3.downshadow_range_pct_skew_3M')
        self.addDailyData(self.downshadow_range_pct_skew_6M, 'fguo_trade3.downshadow_range_pct_skew_6M')
        self.addDailyData(self.body_range_pct_avg_1W, 'fguo_trade3.body_range_pct_avg_1W')
        self.addDailyData(self.body_range_pct_avg_1M, 'fguo_trade3.body_range_pct_avg_1M')
        self.addDailyData(self.body_range_pct_avg_3M, 'fguo_trade3.body_range_pct_avg_3M')
        self.addDailyData(self.body_range_pct_avg_6M, 'fguo_trade3.body_range_pct_avg_6M')
        self.addDailyData(self.body_range_pct_std_1W, 'fguo_trade3.body_range_pct_std_1W')
        self.addDailyData(self.body_range_pct_std_1M, 'fguo_trade3.body_range_pct_std_1M')
        self.addDailyData(self.body_range_pct_std_3M, 'fguo_trade3.body_range_pct_std_3M')
        self.addDailyData(self.body_range_pct_std_6M, 'fguo_trade3.body_range_pct_std_6M')
        self.addDailyData(self.body_range_pct_skew_1W, 'fguo_trade3.body_range_pct_skew_1W')
        self.addDailyData(self.body_range_pct_skew_1M, 'fguo_trade3.body_range_pct_skew_1M')
        self.addDailyData(self.body_range_pct_skew_3M, 'fguo_trade3.body_range_pct_skew_3M')
        self.addDailyData(self.body_range_pct_skew_6M, 'fguo_trade3.body_range_pct_skew_6M')
        return
