from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrWbai_L2_yq_212_5min(DataManagerMapped):
    def __init__(self, ):
        self.shape = ()
        DataManagerMapped.__init__(self, )
        self.avg_bid_price = NIO_CUBE()
        self.avg_offer_price = NIO_CUBE()
        self.avg_volume = NIO_CUBE()
        self.cancelled_buy_trade_count = NIO_CUBE()
        self.cancelled_order_total_money = NIO_CUBE()
        self.cancelled_order_total_volume = NIO_CUBE()
        self.cancelled_sell_trade_count = NIO_CUBE()
        self.cancelled_volume = NIO_CUBE()
        self.close = NIO_CUBE()
        self.high = NIO_CUBE()
        self.low = NIO_CUBE()
        self.max_bid_price = NIO_CUBE()
        self.max_offer_price = NIO_CUBE()
        self.max_volume = NIO_CUBE()
        self.min_bid_price = NIO_CUBE()
        self.min_offer_price = NIO_CUBE()
        self.min_volume = NIO_CUBE()
        self.open = NIO_CUBE()
        self.order_avg_money = NIO_CUBE()
        self.order_avg_price = NIO_CUBE()
        self.order_avg_volume = NIO_CUBE()
        self.order_big_avg_money_based_on_order_money = NIO_CUBE()
        self.order_big_avg_price_based_on_order_money = NIO_CUBE()
        self.order_big_avg_volume_based_on_order_money = NIO_CUBE()
        self.order_big_count_based_on_order_money = NIO_CUBE()
        self.order_big_max_price_based_on_order_money = NIO_CUBE()
        self.order_big_min_price_based_on_order_money = NIO_CUBE()
        self.order_big_total_money_based_on_order_money = NIO_CUBE()
        self.order_big_volume_based_on_order_money = NIO_CUBE()
        self.order_buy_avg_money = NIO_CUBE()
        self.order_buy_avg_price = NIO_CUBE()
        self.order_buy_avg_volume = NIO_CUBE()
        self.order_buy_count = NIO_CUBE()
        self.order_buy_max_price = NIO_CUBE()
        self.order_buy_min_price = NIO_CUBE()
        self.order_buy_total_money = NIO_CUBE()
        self.order_buy_volume = NIO_CUBE()
        self.order_count = NIO_CUBE()
        self.order_max_money = NIO_CUBE()
        self.order_max_price = NIO_CUBE()
        self.order_max_volume = NIO_CUBE()
        self.order_min_money = NIO_CUBE()
        self.order_min_price = NIO_CUBE()
        self.order_min_volume = NIO_CUBE()
        self.order_price_p10 = NIO_CUBE()
        self.order_price_p20 = NIO_CUBE()
        self.order_price_p30 = NIO_CUBE()
        self.order_price_p40 = NIO_CUBE()
        self.order_price_p50 = NIO_CUBE()
        self.order_price_p60 = NIO_CUBE()
        self.order_price_p70 = NIO_CUBE()
        self.order_price_p80 = NIO_CUBE()
        self.order_price_p90 = NIO_CUBE()
        self.order_sell_avg_money = NIO_CUBE()
        self.order_sell_avg_price = NIO_CUBE()
        self.order_sell_avg_volume = NIO_CUBE()
        self.order_sell_count = NIO_CUBE()
        self.order_sell_max_price = NIO_CUBE()
        self.order_sell_min_price = NIO_CUBE()
        self.order_sell_total_money = NIO_CUBE()
        self.order_sell_volume = NIO_CUBE()
        self.order_small_avg_money_based_on_order_money = NIO_CUBE()
        self.order_small_avg_price_based_on_order_money = NIO_CUBE()
        self.order_small_avg_volume_based_on_order_money = NIO_CUBE()
        self.order_small_count_based_on_order_money = NIO_CUBE()
        self.order_small_max_price_based_on_order_money = NIO_CUBE()
        self.order_small_min_price_based_on_order_money = NIO_CUBE()
        self.order_small_total_money_based_on_order_money = NIO_CUBE()
        self.order_small_volume_based_on_order_money = NIO_CUBE()
        self.order_std_volume = NIO_CUBE()
        self.order_total_money = NIO_CUBE()
        self.order_total_volume = NIO_CUBE()
        self.overbuy_count = NIO_CUBE()
        self.overbuy_volume = NIO_CUBE()
        self.oversell_count = NIO_CUBE()
        self.oversell_volume = NIO_CUBE()
        self.seq_num_diff_max = NIO_CUBE()
        self.seq_num_diff_mean = NIO_CUBE()
        self.seq_num_diff_median = NIO_CUBE()
        self.seq_num_diff_min = NIO_CUBE()
        self.seq_num_diff_q25 = NIO_CUBE()
        self.seq_num_diff_q75 = NIO_CUBE()
        self.seq_num_diff_std = NIO_CUBE()
        self.stddev_bid_price = NIO_CUBE()
        self.stddev_offer_price = NIO_CUBE()
        self.std_price = NIO_CUBE()
        self.std_volume = NIO_CUBE()
        self.total_trade_bid_diff = NIO_CUBE()
        self.total_trade_offer_diff = NIO_CUBE()
        self.trade_avg_bid_interval_seconds = NIO_CUBE()
        self.trade_avg_money = NIO_CUBE()
        self.trade_avg_offer_interval_seconds = NIO_CUBE()
        self.trade_avg_price = NIO_CUBE()
        self.trade_big_avg_money_based_on_trade_money = NIO_CUBE()
        self.trade_big_avg_price_based_on_trade_money = NIO_CUBE()
        self.trade_big_avg_volume_based_on_trade_money = NIO_CUBE()
        self.trade_big_count_based_on_trade_money = NIO_CUBE()
        self.trade_big_max_price_based_on_trade_money = NIO_CUBE()
        self.trade_big_min_price_based_on_trade_money = NIO_CUBE()
        self.trade_big_total_money_based_on_trade_money = NIO_CUBE()
        self.trade_big_volume_based_on_trade_money = NIO_CUBE()
        self.trade_buy_avg_money = NIO_CUBE()
        self.trade_buy_avg_price = NIO_CUBE()
        self.trade_buy_avg_volume = NIO_CUBE()
        self.trade_buy_count = NIO_CUBE()
        self.trade_buy_max_price = NIO_CUBE()
        self.trade_buy_min_price = NIO_CUBE()
        self.trade_buy_total_money = NIO_CUBE()
        self.trade_buy_volume = NIO_CUBE()
        self.trade_cancel_count = NIO_CUBE()
        self.trade_first_interval_seconds = NIO_CUBE()
        self.trade_last_interval_seconds = NIO_CUBE()
        self.trade_long_avg_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_avg_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_avg_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_bid_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_bid_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_count_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_max_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_min_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_offer_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_offer_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_long_total_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_long_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_max_bid_interval_seconds = NIO_CUBE()
        self.trade_max_money = NIO_CUBE()
        self.trade_max_offer_interval_seconds = NIO_CUBE()
        self.trade_max_price = NIO_CUBE()
        self.trade_min_bid_interval_seconds = NIO_CUBE()
        self.trade_min_money = NIO_CUBE()
        self.trade_min_offer_interval_seconds = NIO_CUBE()
        self.trade_min_price = NIO_CUBE()
        self.trade_money_median = NIO_CUBE()
        self.trade_money_q25 = NIO_CUBE()
        self.trade_money_q75 = NIO_CUBE()
        self.trade_price_p10 = NIO_CUBE()
        self.trade_price_p20 = NIO_CUBE()
        self.trade_price_p30 = NIO_CUBE()
        self.trade_price_p40 = NIO_CUBE()
        self.trade_price_p50 = NIO_CUBE()
        self.trade_price_p60 = NIO_CUBE()
        self.trade_price_p70 = NIO_CUBE()
        self.trade_price_p80 = NIO_CUBE()
        self.trade_price_p90 = NIO_CUBE()
        self.trade_sell_avg_money = NIO_CUBE()
        self.trade_sell_avg_price = NIO_CUBE()
        self.trade_sell_avg_volume = NIO_CUBE()
        self.trade_sell_count = NIO_CUBE()
        self.trade_sell_max_price = NIO_CUBE()
        self.trade_sell_min_price = NIO_CUBE()
        self.trade_sell_total_money = NIO_CUBE()
        self.trade_sell_volume = NIO_CUBE()
        self.trade_short_avg_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_avg_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_avg_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_bid_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_bid_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_count_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_max_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_min_price_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_offer_avg_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_avg_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_avg_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_count_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_max_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_min_price_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_total_money_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_offer_volume_based_on_interval_seconds = NIO_CUBE()
        self.trade_short_total_money_based_on_seq_num_diff = NIO_CUBE()
        self.trade_short_volume_based_on_seq_num_diff = NIO_CUBE()
        self.trade_small_avg_money_based_on_trade_money = NIO_CUBE()
        self.trade_small_avg_price_based_on_trade_money = NIO_CUBE()
        self.trade_small_avg_volume_based_on_trade_money = NIO_CUBE()
        self.trade_small_count_based_on_trade_money = NIO_CUBE()
        self.trade_small_max_price_based_on_trade_money = NIO_CUBE()
        self.trade_small_min_price_based_on_trade_money = NIO_CUBE()
        self.trade_small_total_money_based_on_trade_money = NIO_CUBE()
        self.trade_small_volume_based_on_trade_money = NIO_CUBE()
        self.trade_stddev_bid_interval_seconds = NIO_CUBE()
        self.trade_stddev_offer_interval_seconds = NIO_CUBE()
        self.trade_std_price = NIO_CUBE()
        self.trade_success_count = NIO_CUBE()
        self.trade_total_money = NIO_CUBE()
        self.volume_median = NIO_CUBE()
        self.volume = NIO_CUBE()
        self.volume_q25 = NIO_CUBE()
        self.volume_q75 = NIO_CUBE()
                

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addData(self.avg_bid_price, 'yq_212_5min.avg_bid_price', 4636, 5484, 49)
        self.addData(self.avg_offer_price, 'yq_212_5min.avg_offer_price', 4636, 5484, 49)
        self.addData(self.avg_volume, 'yq_212_5min.avg_volume', 4636, 5484, 49)
        self.addData(self.cancelled_buy_trade_count, 'yq_212_5min.cancelled_buy_trade_count', 4636, 5484, 49)
        self.addData(self.cancelled_order_total_money, 'yq_212_5min.cancelled_order_total_money', 4636, 5484, 49)
        self.addData(self.cancelled_order_total_volume, 'yq_212_5min.cancelled_order_total_volume', 4636, 5484, 49)
        self.addData(self.cancelled_sell_trade_count, 'yq_212_5min.cancelled_sell_trade_count', 4636, 5484, 49)
        self.addData(self.cancelled_volume, 'yq_212_5min.cancelled_volume', 4636, 5484, 49)
        self.addData(self.close, 'yq_212_5min.close', 4636, 5484, 49)
        self.addData(self.high, 'yq_212_5min.high', 4636, 5484, 49)
        self.addData(self.low, 'yq_212_5min.low', 4636, 5484, 49)
        self.addData(self.max_bid_price, 'yq_212_5min.max_bid_price', 4636, 5484, 49)
        self.addData(self.max_offer_price, 'yq_212_5min.max_offer_price', 4636, 5484, 49)
        self.addData(self.max_volume, 'yq_212_5min.max_volume', 4636, 5484, 49)
        self.addData(self.min_bid_price, 'yq_212_5min.min_bid_price', 4636, 5484, 49)
        self.addData(self.min_offer_price, 'yq_212_5min.min_offer_price', 4636, 5484, 49)
        self.addData(self.min_volume, 'yq_212_5min.min_volume', 4636, 5484, 49)
        self.addData(self.open, 'yq_212_5min.open', 4636, 5484, 49)
        self.addData(self.order_avg_money, 'yq_212_5min.order_avg_money', 4636, 5484, 49)
        self.addData(self.order_avg_price, 'yq_212_5min.order_avg_price', 4636, 5484, 49)
        self.addData(self.order_avg_volume, 'yq_212_5min.order_avg_volume', 4636, 5484, 49)
        self.addData(self.order_big_avg_money_based_on_order_money, 'yq_212_5min.order_big_avg_money_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_big_avg_price_based_on_order_money, 'yq_212_5min.order_big_avg_price_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_big_avg_volume_based_on_order_money, 'yq_212_5min.order_big_avg_volume_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_big_count_based_on_order_money, 'yq_212_5min.order_big_count_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_big_max_price_based_on_order_money, 'yq_212_5min.order_big_max_price_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_big_min_price_based_on_order_money, 'yq_212_5min.order_big_min_price_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_big_total_money_based_on_order_money, 'yq_212_5min.order_big_total_money_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_big_volume_based_on_order_money, 'yq_212_5min.order_big_volume_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_buy_avg_money, 'yq_212_5min.order_buy_avg_money', 4636, 5484, 49)
        self.addData(self.order_buy_avg_price, 'yq_212_5min.order_buy_avg_price', 4636, 5484, 49)
        self.addData(self.order_buy_avg_volume, 'yq_212_5min.order_buy_avg_volume', 4636, 5484, 49)
        self.addData(self.order_buy_count, 'yq_212_5min.order_buy_count', 4636, 5484, 49)
        self.addData(self.order_buy_max_price, 'yq_212_5min.order_buy_max_price', 4636, 5484, 49)
        self.addData(self.order_buy_min_price, 'yq_212_5min.order_buy_min_price', 4636, 5484, 49)
        self.addData(self.order_buy_total_money, 'yq_212_5min.order_buy_total_money', 4636, 5484, 49)
        self.addData(self.order_buy_volume, 'yq_212_5min.order_buy_volume', 4636, 5484, 49)
        self.addData(self.order_count, 'yq_212_5min.order_count', 4636, 5484, 49)
        self.addData(self.order_max_money, 'yq_212_5min.order_max_money', 4636, 5484, 49)
        self.addData(self.order_max_price, 'yq_212_5min.order_max_price', 4636, 5484, 49)
        self.addData(self.order_max_volume, 'yq_212_5min.order_max_volume', 4636, 5484, 49)
        self.addData(self.order_min_money, 'yq_212_5min.order_min_money', 4636, 5484, 49)
        self.addData(self.order_min_price, 'yq_212_5min.order_min_price', 4636, 5484, 49)
        self.addData(self.order_min_volume, 'yq_212_5min.order_min_volume', 4636, 5484, 49)
        self.addData(self.order_price_p10, 'yq_212_5min.order_price_p10', 4636, 5484, 49)
        self.addData(self.order_price_p20, 'yq_212_5min.order_price_p20', 4636, 5484, 49)
        self.addData(self.order_price_p30, 'yq_212_5min.order_price_p30', 4636, 5484, 49)
        self.addData(self.order_price_p40, 'yq_212_5min.order_price_p40', 4636, 5484, 49)
        self.addData(self.order_price_p50, 'yq_212_5min.order_price_p50', 4636, 5484, 49)
        self.addData(self.order_price_p60, 'yq_212_5min.order_price_p60', 4636, 5484, 49)
        self.addData(self.order_price_p70, 'yq_212_5min.order_price_p70', 4636, 5484, 49)
        self.addData(self.order_price_p80, 'yq_212_5min.order_price_p80', 4636, 5484, 49)
        self.addData(self.order_price_p90, 'yq_212_5min.order_price_p90', 4636, 5484, 49)
        self.addData(self.order_sell_avg_money, 'yq_212_5min.order_sell_avg_money', 4636, 5484, 49)
        self.addData(self.order_sell_avg_price, 'yq_212_5min.order_sell_avg_price', 4636, 5484, 49)
        self.addData(self.order_sell_avg_volume, 'yq_212_5min.order_sell_avg_volume', 4636, 5484, 49)
        self.addData(self.order_sell_count, 'yq_212_5min.order_sell_count', 4636, 5484, 49)
        self.addData(self.order_sell_max_price, 'yq_212_5min.order_sell_max_price', 4636, 5484, 49)
        self.addData(self.order_sell_min_price, 'yq_212_5min.order_sell_min_price', 4636, 5484, 49)
        self.addData(self.order_sell_total_money, 'yq_212_5min.order_sell_total_money', 4636, 5484, 49)
        self.addData(self.order_sell_volume, 'yq_212_5min.order_sell_volume', 4636, 5484, 49)
        self.addData(self.order_small_avg_money_based_on_order_money, 'yq_212_5min.order_small_avg_money_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_small_avg_price_based_on_order_money, 'yq_212_5min.order_small_avg_price_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_small_avg_volume_based_on_order_money, 'yq_212_5min.order_small_avg_volume_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_small_count_based_on_order_money, 'yq_212_5min.order_small_count_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_small_max_price_based_on_order_money, 'yq_212_5min.order_small_max_price_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_small_min_price_based_on_order_money, 'yq_212_5min.order_small_min_price_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_small_total_money_based_on_order_money, 'yq_212_5min.order_small_total_money_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_small_volume_based_on_order_money, 'yq_212_5min.order_small_volume_based_on_order_money', 4636, 5484, 49)
        self.addData(self.order_std_volume, 'yq_212_5min.order_std_volume', 4636, 5484, 49)
        self.addData(self.order_total_money, 'yq_212_5min.order_total_money', 4636, 5484, 49)
        self.addData(self.order_total_volume, 'yq_212_5min.order_total_volume', 4636, 5484, 49)
        self.addData(self.overbuy_count, 'yq_212_5min.overbuy_count', 4636, 5484, 49)
        self.addData(self.overbuy_volume, 'yq_212_5min.overbuy_volume', 4636, 5484, 49)
        self.addData(self.oversell_count, 'yq_212_5min.oversell_count', 4636, 5484, 49)
        self.addData(self.oversell_volume, 'yq_212_5min.oversell_volume', 4636, 5484, 49)
        self.addData(self.seq_num_diff_max, 'yq_212_5min.seq_num_diff_max', 4636, 5484, 49)
        self.addData(self.seq_num_diff_mean, 'yq_212_5min.seq_num_diff_mean', 4636, 5484, 49)
        self.addData(self.seq_num_diff_median, 'yq_212_5min.seq_num_diff_median', 4636, 5484, 49)
        self.addData(self.seq_num_diff_min, 'yq_212_5min.seq_num_diff_min', 4636, 5484, 49)
        self.addData(self.seq_num_diff_q25, 'yq_212_5min.seq_num_diff_q25', 4636, 5484, 49)
        self.addData(self.seq_num_diff_q75, 'yq_212_5min.seq_num_diff_q75', 4636, 5484, 49)
        self.addData(self.seq_num_diff_std, 'yq_212_5min.seq_num_diff_std', 4636, 5484, 49)
        self.addData(self.stddev_bid_price, 'yq_212_5min.stddev_bid_price', 4636, 5484, 49)
        self.addData(self.stddev_offer_price, 'yq_212_5min.stddev_offer_price', 4636, 5484, 49)
        self.addData(self.std_price, 'yq_212_5min.std_price', 4636, 5484, 49)
        self.addData(self.std_volume, 'yq_212_5min.std_volume', 4636, 5484, 49)
        self.addData(self.total_trade_bid_diff, 'yq_212_5min.total_trade_bid_diff', 4636, 5484, 49)
        self.addData(self.total_trade_offer_diff, 'yq_212_5min.total_trade_offer_diff', 4636, 5484, 49)
        self.addData(self.trade_avg_bid_interval_seconds, 'yq_212_5min.trade_avg_bid_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_avg_money, 'yq_212_5min.trade_avg_money', 4636, 5484, 49)
        self.addData(self.trade_avg_offer_interval_seconds, 'yq_212_5min.trade_avg_offer_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_avg_price, 'yq_212_5min.trade_avg_price', 4636, 5484, 49)
        self.addData(self.trade_big_avg_money_based_on_trade_money, 'yq_212_5min.trade_big_avg_money_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_big_avg_price_based_on_trade_money, 'yq_212_5min.trade_big_avg_price_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_big_avg_volume_based_on_trade_money, 'yq_212_5min.trade_big_avg_volume_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_big_count_based_on_trade_money, 'yq_212_5min.trade_big_count_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_big_max_price_based_on_trade_money, 'yq_212_5min.trade_big_max_price_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_big_min_price_based_on_trade_money, 'yq_212_5min.trade_big_min_price_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_big_total_money_based_on_trade_money, 'yq_212_5min.trade_big_total_money_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_big_volume_based_on_trade_money, 'yq_212_5min.trade_big_volume_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_buy_avg_money, 'yq_212_5min.trade_buy_avg_money', 4636, 5484, 49)
        self.addData(self.trade_buy_avg_price, 'yq_212_5min.trade_buy_avg_price', 4636, 5484, 49)
        self.addData(self.trade_buy_avg_volume, 'yq_212_5min.trade_buy_avg_volume', 4636, 5484, 49)
        self.addData(self.trade_buy_count, 'yq_212_5min.trade_buy_count', 4636, 5484, 49)
        self.addData(self.trade_buy_max_price, 'yq_212_5min.trade_buy_max_price', 4636, 5484, 49)
        self.addData(self.trade_buy_min_price, 'yq_212_5min.trade_buy_min_price', 4636, 5484, 49)
        self.addData(self.trade_buy_total_money, 'yq_212_5min.trade_buy_total_money', 4636, 5484, 49)
        self.addData(self.trade_buy_volume, 'yq_212_5min.trade_buy_volume', 4636, 5484, 49)
        self.addData(self.trade_cancel_count, 'yq_212_5min.trade_cancel_count', 4636, 5484, 49)
        self.addData(self.trade_first_interval_seconds, 'yq_212_5min.trade_first_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_last_interval_seconds, 'yq_212_5min.trade_last_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_avg_money_based_on_seq_num_diff, 'yq_212_5min.trade_long_avg_money_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_long_avg_price_based_on_seq_num_diff, 'yq_212_5min.trade_long_avg_price_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_long_avg_volume_based_on_seq_num_diff, 'yq_212_5min.trade_long_avg_volume_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_long_bid_avg_money_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_avg_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_bid_avg_price_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_avg_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_bid_avg_volume_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_avg_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_bid_count_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_count_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_bid_max_price_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_max_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_bid_min_price_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_min_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_bid_total_money_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_total_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_bid_volume_based_on_interval_seconds, 'yq_212_5min.trade_long_bid_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_count_based_on_seq_num_diff, 'yq_212_5min.trade_long_count_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_long_max_price_based_on_seq_num_diff, 'yq_212_5min.trade_long_max_price_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_long_min_price_based_on_seq_num_diff, 'yq_212_5min.trade_long_min_price_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_long_offer_avg_money_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_avg_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_offer_avg_price_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_avg_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_offer_avg_volume_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_avg_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_offer_count_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_count_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_offer_max_price_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_max_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_offer_min_price_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_min_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_offer_total_money_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_total_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_offer_volume_based_on_interval_seconds, 'yq_212_5min.trade_long_offer_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_long_total_money_based_on_seq_num_diff, 'yq_212_5min.trade_long_total_money_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_long_volume_based_on_seq_num_diff, 'yq_212_5min.trade_long_volume_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_max_bid_interval_seconds, 'yq_212_5min.trade_max_bid_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_max_money, 'yq_212_5min.trade_max_money', 4636, 5484, 49)
        self.addData(self.trade_max_offer_interval_seconds, 'yq_212_5min.trade_max_offer_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_max_price, 'yq_212_5min.trade_max_price', 4636, 5484, 49)
        self.addData(self.trade_min_bid_interval_seconds, 'yq_212_5min.trade_min_bid_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_min_money, 'yq_212_5min.trade_min_money', 4636, 5484, 49)
        self.addData(self.trade_min_offer_interval_seconds, 'yq_212_5min.trade_min_offer_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_min_price, 'yq_212_5min.trade_min_price', 4636, 5484, 49)
        self.addData(self.trade_money_median, 'yq_212_5min.trade_money_median', 4636, 5484, 49)
        self.addData(self.trade_money_q25, 'yq_212_5min.trade_money_q25', 4636, 5484, 49)
        self.addData(self.trade_money_q75, 'yq_212_5min.trade_money_q75', 4636, 5484, 49)
        self.addData(self.trade_price_p10, 'yq_212_5min.trade_price_p10', 4636, 5484, 49)
        self.addData(self.trade_price_p20, 'yq_212_5min.trade_price_p20', 4636, 5484, 49)
        self.addData(self.trade_price_p30, 'yq_212_5min.trade_price_p30', 4636, 5484, 49)
        self.addData(self.trade_price_p40, 'yq_212_5min.trade_price_p40', 4636, 5484, 49)
        self.addData(self.trade_price_p50, 'yq_212_5min.trade_price_p50', 4636, 5484, 49)
        self.addData(self.trade_price_p60, 'yq_212_5min.trade_price_p60', 4636, 5484, 49)
        self.addData(self.trade_price_p70, 'yq_212_5min.trade_price_p70', 4636, 5484, 49)
        self.addData(self.trade_price_p80, 'yq_212_5min.trade_price_p80', 4636, 5484, 49)
        self.addData(self.trade_price_p90, 'yq_212_5min.trade_price_p90', 4636, 5484, 49)
        self.addData(self.trade_sell_avg_money, 'yq_212_5min.trade_sell_avg_money', 4636, 5484, 49)
        self.addData(self.trade_sell_avg_price, 'yq_212_5min.trade_sell_avg_price', 4636, 5484, 49)
        self.addData(self.trade_sell_avg_volume, 'yq_212_5min.trade_sell_avg_volume', 4636, 5484, 49)
        self.addData(self.trade_sell_count, 'yq_212_5min.trade_sell_count', 4636, 5484, 49)
        self.addData(self.trade_sell_max_price, 'yq_212_5min.trade_sell_max_price', 4636, 5484, 49)
        self.addData(self.trade_sell_min_price, 'yq_212_5min.trade_sell_min_price', 4636, 5484, 49)
        self.addData(self.trade_sell_total_money, 'yq_212_5min.trade_sell_total_money', 4636, 5484, 49)
        self.addData(self.trade_sell_volume, 'yq_212_5min.trade_sell_volume', 4636, 5484, 49)
        self.addData(self.trade_short_avg_money_based_on_seq_num_diff, 'yq_212_5min.trade_short_avg_money_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_short_avg_price_based_on_seq_num_diff, 'yq_212_5min.trade_short_avg_price_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_short_avg_volume_based_on_seq_num_diff, 'yq_212_5min.trade_short_avg_volume_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_short_bid_avg_money_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_avg_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_bid_avg_price_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_avg_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_bid_avg_volume_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_avg_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_bid_count_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_count_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_bid_max_price_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_max_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_bid_min_price_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_min_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_bid_total_money_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_total_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_bid_volume_based_on_interval_seconds, 'yq_212_5min.trade_short_bid_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_count_based_on_seq_num_diff, 'yq_212_5min.trade_short_count_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_short_max_price_based_on_seq_num_diff, 'yq_212_5min.trade_short_max_price_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_short_min_price_based_on_seq_num_diff, 'yq_212_5min.trade_short_min_price_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_short_offer_avg_money_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_avg_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_offer_avg_price_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_avg_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_offer_avg_volume_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_avg_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_offer_count_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_count_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_offer_max_price_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_max_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_offer_min_price_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_min_price_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_offer_total_money_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_total_money_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_offer_volume_based_on_interval_seconds, 'yq_212_5min.trade_short_offer_volume_based_on_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_short_total_money_based_on_seq_num_diff, 'yq_212_5min.trade_short_total_money_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_short_volume_based_on_seq_num_diff, 'yq_212_5min.trade_short_volume_based_on_seq_num_diff', 4636, 5484, 49)
        self.addData(self.trade_small_avg_money_based_on_trade_money, 'yq_212_5min.trade_small_avg_money_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_small_avg_price_based_on_trade_money, 'yq_212_5min.trade_small_avg_price_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_small_avg_volume_based_on_trade_money, 'yq_212_5min.trade_small_avg_volume_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_small_count_based_on_trade_money, 'yq_212_5min.trade_small_count_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_small_max_price_based_on_trade_money, 'yq_212_5min.trade_small_max_price_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_small_min_price_based_on_trade_money, 'yq_212_5min.trade_small_min_price_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_small_total_money_based_on_trade_money, 'yq_212_5min.trade_small_total_money_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_small_volume_based_on_trade_money, 'yq_212_5min.trade_small_volume_based_on_trade_money', 4636, 5484, 49)
        self.addData(self.trade_stddev_bid_interval_seconds, 'yq_212_5min.trade_stddev_bid_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_stddev_offer_interval_seconds, 'yq_212_5min.trade_stddev_offer_interval_seconds', 4636, 5484, 49)
        self.addData(self.trade_std_price, 'yq_212_5min.trade_std_price', 4636, 5484, 49)
        self.addData(self.trade_success_count, 'yq_212_5min.trade_success_count', 4636, 5484, 49)
        self.addData(self.trade_total_money, 'yq_212_5min.trade_total_money', 4636, 5484, 49)
        self.addData(self.volume_median, 'yq_212_5min.volume_median', 4636, 5484, 49)
        self.addData(self.volume, 'yq_212_5min.volume', 4636, 5484, 49)
        self.addData(self.volume_q25, 'yq_212_5min.volume_q25', 4636, 5484, 49)
        self.addData(self.volume_q75, 'yq_212_5min.volume_q75', 4636, 5484, 49)

    def loadDay(self, di):
        pass
