from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrSli0214(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.br_1m_N120 = NIO_MATRIX()
        self.br_1m_N30 = NIO_MATRIX()
        self.br_1m_N60 = NIO_MATRIX()
        self.br_1m_trim_N60 = NIO_MATRIX()
        self.br_30m_N4 = NIO_MATRIX()
        self.br_30m_N6 = NIO_MATRIX()
        self.br_30m_N8 = NIO_MATRIX()
        self.br_5m_N12 = NIO_MATRIX()
        self.br_5m_N26 = NIO_MATRIX()
        self.br_5m_N48 = NIO_MATRIX()
        self.vol_ema_15 = NIO_MATRIX()
        self.vol_ema_3 = NIO_MATRIX()
        self.vol_ema_6 = NIO_MATRIX()
        self.vol_max_15 = NIO_MATRIX()
        self.vol_max_3 = NIO_MATRIX()
        self.vol_max_6 = NIO_MATRIX()
        self.vol_median_15 = NIO_MATRIX()
        self.vol_median_3 = NIO_MATRIX()
        self.vol_median_6 = NIO_MATRIX()
        self.vol_min_15 = NIO_MATRIX()
        self.vol_min_3 = NIO_MATRIX()
        self.vol_min_6 = NIO_MATRIX()
        self.vol_q25_15 = NIO_MATRIX()
        self.vol_q25_3 = NIO_MATRIX()
        self.vol_q25_6 = NIO_MATRIX()
        self.vol_q75_15 = NIO_MATRIX()
        self.vol_q75_3 = NIO_MATRIX()
        self.vol_q75_6 = NIO_MATRIX()
        self.vol_sma_15 = NIO_MATRIX()
        self.vol_sma_3 = NIO_MATRIX()
        self.vol_sma_6 = NIO_MATRIX()
        self.vol_smma_15 = NIO_MATRIX()
        self.vol_smma_3 = NIO_MATRIX()
        self.vol_smma_6 = NIO_MATRIX()
        self.vol_std_15 = NIO_MATRIX()
        self.vol_std_3 = NIO_MATRIX()
        self.vol_std_6 = NIO_MATRIX()
        self.vol_sum_15 = NIO_MATRIX()
        self.vol_sum_3 = NIO_MATRIX()
        self.vol_sum_6 = NIO_MATRIX()
        self.vol_wma_15 = NIO_MATRIX()
        self.vol_wma_3 = NIO_MATRIX()
        self.vol_wma_6 = NIO_MATRIX()
        self.vr_1m = NIO_MATRIX()
        self.vr_1m_trim = NIO_MATRIX()
        self.vr_30m = NIO_MATRIX()
        self.vr_30m_trim = NIO_MATRIX()
        self.vr_5m = NIO_MATRIX()
        self.vr_5m_trim = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.br_1m_N120, 'sli_0214.br_1m_N120')
        self.addDailyData(self.br_1m_N30, 'sli_0214.br_1m_N30')
        self.addDailyData(self.br_1m_N60, 'sli_0214.br_1m_N60')
        self.addDailyData(self.br_1m_trim_N60, 'sli_0214.br_1m_trim_N60')
        self.addDailyData(self.br_30m_N4, 'sli_0214.br_30m_N4')
        self.addDailyData(self.br_30m_N6, 'sli_0214.br_30m_N6')
        self.addDailyData(self.br_30m_N8, 'sli_0214.br_30m_N8')
        self.addDailyData(self.br_5m_N12, 'sli_0214.br_5m_N12')
        self.addDailyData(self.br_5m_N26, 'sli_0214.br_5m_N26')
        self.addDailyData(self.br_5m_N48, 'sli_0214.br_5m_N48')
        self.addDailyData(self.vol_ema_15, 'sli_0214.vol_ema_15')
        self.addDailyData(self.vol_ema_3, 'sli_0214.vol_ema_3')
        self.addDailyData(self.vol_ema_6, 'sli_0214.vol_ema_6')
        self.addDailyData(self.vol_max_15, 'sli_0214.vol_max_15')
        self.addDailyData(self.vol_max_3, 'sli_0214.vol_max_3')
        self.addDailyData(self.vol_max_6, 'sli_0214.vol_max_6')
        self.addDailyData(self.vol_median_15, 'sli_0214.vol_median_15')
        self.addDailyData(self.vol_median_3, 'sli_0214.vol_median_3')
        self.addDailyData(self.vol_median_6, 'sli_0214.vol_median_6')
        self.addDailyData(self.vol_min_15, 'sli_0214.vol_min_15')
        self.addDailyData(self.vol_min_3, 'sli_0214.vol_min_3')
        self.addDailyData(self.vol_min_6, 'sli_0214.vol_min_6')
        self.addDailyData(self.vol_q25_15, 'sli_0214.vol_q25_15')
        self.addDailyData(self.vol_q25_3, 'sli_0214.vol_q25_3')
        self.addDailyData(self.vol_q25_6, 'sli_0214.vol_q25_6')
        self.addDailyData(self.vol_q75_15, 'sli_0214.vol_q75_15')
        self.addDailyData(self.vol_q75_3, 'sli_0214.vol_q75_3')
        self.addDailyData(self.vol_q75_6, 'sli_0214.vol_q75_6')
        self.addDailyData(self.vol_sma_15, 'sli_0214.vol_sma_15')
        self.addDailyData(self.vol_sma_3, 'sli_0214.vol_sma_3')
        self.addDailyData(self.vol_sma_6, 'sli_0214.vol_sma_6')
        self.addDailyData(self.vol_smma_15, 'sli_0214.vol_smma_15')
        self.addDailyData(self.vol_smma_3, 'sli_0214.vol_smma_3')
        self.addDailyData(self.vol_smma_6, 'sli_0214.vol_smma_6')
        self.addDailyData(self.vol_std_15, 'sli_0214.vol_std_15')
        self.addDailyData(self.vol_std_3, 'sli_0214.vol_std_3')
        self.addDailyData(self.vol_std_6, 'sli_0214.vol_std_6')
        self.addDailyData(self.vol_sum_15, 'sli_0214.vol_sum_15')
        self.addDailyData(self.vol_sum_3, 'sli_0214.vol_sum_3')
        self.addDailyData(self.vol_sum_6, 'sli_0214.vol_sum_6')
        self.addDailyData(self.vol_wma_15, 'sli_0214.vol_wma_15')
        self.addDailyData(self.vol_wma_3, 'sli_0214.vol_wma_3')
        self.addDailyData(self.vol_wma_6, 'sli_0214.vol_wma_6')
        self.addDailyData(self.vr_1m, 'sli_0214.vr_1m')
        self.addDailyData(self.vr_1m_trim, 'sli_0214.vr_1m_trim')
        self.addDailyData(self.vr_30m, 'sli_0214.vr_30m')
        self.addDailyData(self.vr_30m_trim, 'sli_0214.vr_30m_trim')
        self.addDailyData(self.vr_5m, 'sli_0214.vr_5m')
        self.addDailyData(self.vr_5m_trim, 'sli_0214.vr_5m_trim')
        return

    def loadDay(self, di):
        pass
