from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrFguo3(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.am_pm_open30_amount_ratio = NIO_MATRIX()
        self.am_pm_open30_volume_ratio = NIO_MATRIX()
        self.auction_amount_ratio = NIO_MATRIX()
        self.auction_volume_ratio = NIO_MATRIX()
        self.buy_side_illiquidity = NIO_MATRIX()
        self.close_15min_amount_ratio = NIO_MATRIX()
        self.close_15min_volume_ratio = NIO_MATRIX()
        self.close_5min_amount_ratio = NIO_MATRIX()
        self.close_5min_large_ratio = NIO_MATRIX()
        self.close_5min_net_buy = NIO_MATRIX()
        self.close_5min_volume_ratio = NIO_MATRIX()
        self.consistent_buy_count_ratio = NIO_MATRIX()
        self.consistent_buy_volume_ratio = NIO_MATRIX()
        self.consistent_sell_count_ratio = NIO_MATRIX()
        self.consistent_sell_volume_ratio = NIO_MATRIX()
        self.consistent_trade_count_ratio = NIO_MATRIX()
        self.consistent_trade_volume_ratio = NIO_MATRIX()
        self.early_buy_sell_count_ratio = NIO_MATRIX()
        self.first_last_10pct_amount_ratio = NIO_MATRIX()
        self.first_last_10pct_volume_ratio = NIO_MATRIX()
        self.hour1_amount = NIO_MATRIX()
        self.hour1_hour4_return_diff = NIO_MATRIX()
        self.hour1_hour4_volume_ratio = NIO_MATRIX()
        self.hour1_return = NIO_MATRIX()
        self.hour1_trade_count = NIO_MATRIX()
        self.hour1_volume = NIO_MATRIX()
        self.hour2_amount = NIO_MATRIX()
        self.hour2_return = NIO_MATRIX()
        self.hour2_trade_count = NIO_MATRIX()
        self.hour2_volume = NIO_MATRIX()
        self.hour3_amount = NIO_MATRIX()
        self.hour3_return = NIO_MATRIX()
        self.hour3_trade_count = NIO_MATRIX()
        self.hour3_volume = NIO_MATRIX()
        self.hour4_amount = NIO_MATRIX()
        self.hour4_return = NIO_MATRIX()
        self.hour4_trade_count = NIO_MATRIX()
        self.hour4_volume = NIO_MATRIX()
        self.illiquidity_asymmetry = NIO_MATRIX()
        self.imbalance_ratio_depth10 = NIO_MATRIX()
        self.imbalance_ratio_depth5 = NIO_MATRIX()
        self.imbalance_ratio_level1 = NIO_MATRIX()
        self.mid_price_change_max = NIO_MATRIX()
        self.mid_price_change_min = NIO_MATRIX()
        self.morning_afternoon_net_buy_diff = NIO_MATRIX()
        self.open_5min_amount_ratio = NIO_MATRIX()
        self.open_5min_large_ratio = NIO_MATRIX()
        self.open_5min_net_buy = NIO_MATRIX()
        self.open_5min_volume_ratio = NIO_MATRIX()
        self.open_close_5min_net_buy_diff = NIO_MATRIX()
        self.overnight_return = NIO_MATRIX()
        self.sell_side_illiquidity = NIO_MATRIX()
        self.spread_stability = NIO_MATRIX()
        self.tick_count = NIO_MATRIX()
        self.total_amount = NIO_MATRIX()
        self.total_volume = NIO_MATRIX()
        self.trade_count = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.am_pm_open30_amount_ratio, 'fguo_1230.am_pm_open30_amount_ratio')
        self.addDailyData(self.am_pm_open30_volume_ratio, 'fguo_1230.am_pm_open30_volume_ratio')
        self.addDailyData(self.auction_amount_ratio, 'fguo_1230.auction_amount_ratio')
        self.addDailyData(self.auction_volume_ratio, 'fguo_1230.auction_volume_ratio')
        self.addDailyData(self.buy_side_illiquidity, 'fguo_1230.buy_side_illiquidity')
        self.addDailyData(self.close_15min_amount_ratio, 'fguo_1230.close_15min_amount_ratio')
        self.addDailyData(self.close_15min_volume_ratio, 'fguo_1230.close_15min_volume_ratio')
        self.addDailyData(self.close_5min_amount_ratio, 'fguo_1230.close_5min_amount_ratio')
        self.addDailyData(self.close_5min_large_ratio, 'fguo_1230.close_5min_large_ratio')
        self.addDailyData(self.close_5min_net_buy, 'fguo_1230.close_5min_net_buy')
        self.addDailyData(self.close_5min_volume_ratio, 'fguo_1230.close_5min_volume_ratio')
        self.addDailyData(self.consistent_buy_count_ratio, 'fguo_1230.consistent_buy_count_ratio')
        self.addDailyData(self.consistent_buy_volume_ratio, 'fguo_1230.consistent_buy_volume_ratio')
        self.addDailyData(self.consistent_sell_count_ratio, 'fguo_1230.consistent_sell_count_ratio')
        self.addDailyData(self.consistent_sell_volume_ratio, 'fguo_1230.consistent_sell_volume_ratio')
        self.addDailyData(self.consistent_trade_count_ratio, 'fguo_1230.consistent_trade_count_ratio')
        self.addDailyData(self.consistent_trade_volume_ratio, 'fguo_1230.consistent_trade_volume_ratio')
        self.addDailyData(self.early_buy_sell_count_ratio, 'fguo_1230.early_buy_sell_count_ratio')
        self.addDailyData(self.first_last_10pct_amount_ratio, 'fguo_1230.first_last_10pct_amount_ratio')
        self.addDailyData(self.first_last_10pct_volume_ratio, 'fguo_1230.first_last_10pct_volume_ratio')
        self.addDailyData(self.hour1_amount, 'fguo_1230.hour1_amount')
        self.addDailyData(self.hour1_hour4_return_diff, 'fguo_1230.hour1_hour4_return_diff')
        self.addDailyData(self.hour1_hour4_volume_ratio, 'fguo_1230.hour1_hour4_volume_ratio')
        self.addDailyData(self.hour1_return, 'fguo_1230.hour1_return')
        self.addDailyData(self.hour1_trade_count, 'fguo_1230.hour1_trade_count')
        self.addDailyData(self.hour1_volume, 'fguo_1230.hour1_volume')
        self.addDailyData(self.hour2_amount, 'fguo_1230.hour2_amount')
        self.addDailyData(self.hour2_return, 'fguo_1230.hour2_return')
        self.addDailyData(self.hour2_trade_count, 'fguo_1230.hour2_trade_count')
        self.addDailyData(self.hour2_volume, 'fguo_1230.hour2_volume')
        self.addDailyData(self.hour3_amount, 'fguo_1230.hour3_amount')
        self.addDailyData(self.hour3_return, 'fguo_1230.hour3_return')
        self.addDailyData(self.hour3_trade_count, 'fguo_1230.hour3_trade_count')
        self.addDailyData(self.hour3_volume, 'fguo_1230.hour3_volume')
        self.addDailyData(self.hour4_amount, 'fguo_1230.hour4_amount')
        self.addDailyData(self.hour4_return, 'fguo_1230.hour4_return')
        self.addDailyData(self.hour4_trade_count, 'fguo_1230.hour4_trade_count')
        self.addDailyData(self.hour4_volume, 'fguo_1230.hour4_volume')
        self.addDailyData(self.illiquidity_asymmetry, 'fguo_1230.illiquidity_asymmetry')
        self.addDailyData(self.imbalance_ratio_depth10, 'fguo_1230.imbalance_ratio_depth10')
        self.addDailyData(self.imbalance_ratio_depth5, 'fguo_1230.imbalance_ratio_depth5')
        self.addDailyData(self.imbalance_ratio_level1, 'fguo_1230.imbalance_ratio_level1')
        self.addDailyData(self.mid_price_change_max, 'fguo_1230.mid_price_change_max')
        self.addDailyData(self.mid_price_change_min, 'fguo_1230.mid_price_change_min')
        self.addDailyData(self.morning_afternoon_net_buy_diff, 'fguo_1230.morning_afternoon_net_buy_diff')
        self.addDailyData(self.open_5min_amount_ratio, 'fguo_1230.open_5min_amount_ratio')
        self.addDailyData(self.open_5min_large_ratio, 'fguo_1230.open_5min_large_ratio')
        self.addDailyData(self.open_5min_net_buy, 'fguo_1230.open_5min_net_buy')
        self.addDailyData(self.open_5min_volume_ratio, 'fguo_1230.open_5min_volume_ratio')
        self.addDailyData(self.open_close_5min_net_buy_diff, 'fguo_1230.open_close_5min_net_buy_diff')
        self.addDailyData(self.overnight_return, 'fguo_1230.overnight_return')
        self.addDailyData(self.sell_side_illiquidity, 'fguo_1230.sell_side_illiquidity')
        self.addDailyData(self.spread_stability, 'fguo_1230.spread_stability')
        self.addDailyData(self.tick_count, 'fguo_1230.tick_count')
        self.addDailyData(self.total_amount, 'fguo_1230.total_amount')
        self.addDailyData(self.total_volume, 'fguo_1230.total_volume')
        self.addDailyData(self.trade_count, 'fguo_1230.trade_count')
        return

    def loadDay(self, di):
        pass
