from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrFguoywang(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.b123_vol_ratio_kurt_am = NIO_MATRIX()
        self.b123_vol_ratio_kurt_daily = NIO_MATRIX()
        self.b123_vol_ratio_kurt_pm = NIO_MATRIX()
        self.b123_vol_ratio_max_am = NIO_MATRIX()
        self.b123_vol_ratio_max_daily = NIO_MATRIX()
        self.b123_vol_ratio_max_pm = NIO_MATRIX()
        self.b123_vol_ratio_mean_am = NIO_MATRIX()
        self.b123_vol_ratio_mean_daily = NIO_MATRIX()
        self.b123_vol_ratio_mean_pm = NIO_MATRIX()
        self.b123_vol_ratio_min_am = NIO_MATRIX()
        self.b123_vol_ratio_min_daily = NIO_MATRIX()
        self.b123_vol_ratio_min_pm = NIO_MATRIX()
        self.b123_vol_ratio_skew_am = NIO_MATRIX()
        self.b123_vol_ratio_skew_daily = NIO_MATRIX()
        self.b123_vol_ratio_skew_pm = NIO_MATRIX()
        self.b123_vol_ratio_var_am = NIO_MATRIX()
        self.b123_vol_ratio_var_daily = NIO_MATRIX()
        self.b123_vol_ratio_var_pm = NIO_MATRIX()
        self.b1_vol_ratio_kurt_am = NIO_MATRIX()
        self.b1_vol_ratio_kurt_daily = NIO_MATRIX()
        self.b1_vol_ratio_kurt_pm = NIO_MATRIX()
        self.b1_vol_ratio_max_am = NIO_MATRIX()
        self.b1_vol_ratio_max_daily = NIO_MATRIX()
        self.b1_vol_ratio_max_pm = NIO_MATRIX()
        self.b1_vol_ratio_mean_am = NIO_MATRIX()
        self.b1_vol_ratio_mean_daily = NIO_MATRIX()
        self.b1_vol_ratio_mean_pm = NIO_MATRIX()
        self.b1_vol_ratio_min_am = NIO_MATRIX()
        self.b1_vol_ratio_min_daily = NIO_MATRIX()
        self.b1_vol_ratio_min_pm = NIO_MATRIX()
        self.b1_vol_ratio_skew_am = NIO_MATRIX()
        self.b1_vol_ratio_skew_daily = NIO_MATRIX()
        self.b1_vol_ratio_skew_pm = NIO_MATRIX()
        self.b1_vol_ratio_var_am = NIO_MATRIX()
        self.b1_vol_ratio_var_daily = NIO_MATRIX()
        self.b1_vol_ratio_var_pm = NIO_MATRIX()
        self.b5_s1_vol_diff_kurt_am = NIO_MATRIX()
        self.b5_s1_vol_diff_kurt_daily = NIO_MATRIX()
        self.b5_s1_vol_diff_kurt_pm = NIO_MATRIX()
        self.b5_s1_vol_diff_max_am = NIO_MATRIX()
        self.b5_s1_vol_diff_max_daily = NIO_MATRIX()
        self.b5_s1_vol_diff_max_pm = NIO_MATRIX()
        self.b5_s1_vol_diff_mean_am = NIO_MATRIX()
        self.b5_s1_vol_diff_mean_daily = NIO_MATRIX()
        self.b5_s1_vol_diff_mean_pm = NIO_MATRIX()
        self.b5_s1_vol_diff_min_am = NIO_MATRIX()
        self.b5_s1_vol_diff_min_daily = NIO_MATRIX()
        self.b5_s1_vol_diff_min_pm = NIO_MATRIX()
        self.b5_s1_vol_diff_skew_am = NIO_MATRIX()
        self.b5_s1_vol_diff_skew_daily = NIO_MATRIX()
        self.b5_s1_vol_diff_skew_pm = NIO_MATRIX()
        self.b5_s1_vol_diff_var_am = NIO_MATRIX()
        self.b5_s1_vol_diff_var_daily = NIO_MATRIX()
        self.b5_s1_vol_diff_var_pm = NIO_MATRIX()
        self.b6_s6_vol_diff_kurt_am = NIO_MATRIX()
        self.b6_s6_vol_diff_kurt_daily = NIO_MATRIX()
        self.b6_s6_vol_diff_kurt_pm = NIO_MATRIX()
        self.b6_s6_vol_diff_max_am = NIO_MATRIX()
        self.b6_s6_vol_diff_max_daily = NIO_MATRIX()
        self.b6_s6_vol_diff_max_pm = NIO_MATRIX()
        self.b6_s6_vol_diff_mean_am = NIO_MATRIX()
        self.b6_s6_vol_diff_mean_daily = NIO_MATRIX()
        self.b6_s6_vol_diff_mean_pm = NIO_MATRIX()
        self.b6_s6_vol_diff_min_am = NIO_MATRIX()
        self.b6_s6_vol_diff_min_daily = NIO_MATRIX()
        self.b6_s6_vol_diff_min_pm = NIO_MATRIX()
        self.b6_s6_vol_diff_skew_am = NIO_MATRIX()
        self.b6_s6_vol_diff_skew_daily = NIO_MATRIX()
        self.b6_s6_vol_diff_skew_pm = NIO_MATRIX()
        self.b6_s6_vol_diff_var_am = NIO_MATRIX()
        self.b6_s6_vol_diff_var_daily = NIO_MATRIX()
        self.b6_s6_vol_diff_var_pm = NIO_MATRIX()
        self.b_avg_spread_kurt_am = NIO_MATRIX()
        self.b_avg_spread_kurt_daily = NIO_MATRIX()
        self.b_avg_spread_kurt_pm = NIO_MATRIX()
        self.b_avg_spread_max_am = NIO_MATRIX()
        self.b_avg_spread_max_daily = NIO_MATRIX()
        self.b_avg_spread_max_pm = NIO_MATRIX()
        self.b_avg_spread_mean_am = NIO_MATRIX()
        self.b_avg_spread_mean_daily = NIO_MATRIX()
        self.b_avg_spread_mean_pm = NIO_MATRIX()
        self.b_avg_spread_min_am = NIO_MATRIX()
        self.b_avg_spread_min_daily = NIO_MATRIX()
        self.b_avg_spread_min_pm = NIO_MATRIX()
        self.b_avg_spread_skew_am = NIO_MATRIX()
        self.b_avg_spread_skew_daily = NIO_MATRIX()
        self.b_avg_spread_skew_pm = NIO_MATRIX()
        self.b_avg_spread_var_am = NIO_MATRIX()
        self.b_avg_spread_var_daily = NIO_MATRIX()
        self.b_avg_spread_var_pm = NIO_MATRIX()
        self.b_depth_spread_kurt_am = NIO_MATRIX()
        self.b_depth_spread_kurt_daily = NIO_MATRIX()
        self.b_depth_spread_kurt_pm = NIO_MATRIX()
        self.b_depth_spread_mean_am = NIO_MATRIX()
        self.b_depth_spread_mean_pm = NIO_MATRIX()
        self.b_depth_spread_skew_am = NIO_MATRIX()
        self.b_depth_spread_skew_daily = NIO_MATRIX()
        self.b_depth_spread_skew_pm = NIO_MATRIX()
        self.b_depth_spread_var_am = NIO_MATRIX()
        self.b_depth_spread_var_daily = NIO_MATRIX()
        self.b_depth_spread_var_pm = NIO_MATRIX()
        self.b_max_vol_price_kurt_am = NIO_MATRIX()
        self.b_max_vol_price_kurt_daily = NIO_MATRIX()
        self.b_max_vol_price_kurt_pm = NIO_MATRIX()
        self.b_max_vol_price_max_am = NIO_MATRIX()
        self.b_max_vol_price_max_daily = NIO_MATRIX()
        self.b_max_vol_price_max_pm = NIO_MATRIX()
        self.b_max_vol_price_mean_am = NIO_MATRIX()
        self.b_max_vol_price_mean_daily = NIO_MATRIX()
        self.b_max_vol_price_mean_pm = NIO_MATRIX()
        self.b_max_vol_price_min_am = NIO_MATRIX()
        self.b_max_vol_price_min_daily = NIO_MATRIX()
        self.b_max_vol_price_min_pm = NIO_MATRIX()
        self.b_max_vol_price_skew_am = NIO_MATRIX()
        self.b_max_vol_price_skew_daily = NIO_MATRIX()
        self.b_max_vol_price_skew_pm = NIO_MATRIX()
        self.b_max_vol_price_var_am = NIO_MATRIX()
        self.b_max_vol_price_var_daily = NIO_MATRIX()
        self.b_max_vol_price_var_pm = NIO_MATRIX()
        self.b_vol_disp_kurt_am = NIO_MATRIX()
        self.b_vol_disp_kurt_daily = NIO_MATRIX()
        self.b_vol_disp_kurt_pm = NIO_MATRIX()
        self.b_vol_disp_max_am = NIO_MATRIX()
        self.b_vol_disp_max_daily = NIO_MATRIX()
        self.b_vol_disp_max_pm = NIO_MATRIX()
        self.b_vol_disp_mean_am = NIO_MATRIX()
        self.b_vol_disp_mean_daily = NIO_MATRIX()
        self.b_vol_disp_mean_pm = NIO_MATRIX()
        self.b_vol_disp_min_am = NIO_MATRIX()
        self.b_vol_disp_min_daily = NIO_MATRIX()
        self.b_vol_disp_min_pm = NIO_MATRIX()
        self.b_vol_disp_skew_am = NIO_MATRIX()
        self.b_vol_disp_skew_daily = NIO_MATRIX()
        self.b_vol_disp_skew_pm = NIO_MATRIX()
        self.b_vol_disp_var_am = NIO_MATRIX()
        self.b_vol_disp_var_daily = NIO_MATRIX()
        self.b_vol_disp_var_pm = NIO_MATRIX()
        self.b_vol_price_corr_kurt_am = NIO_MATRIX()
        self.b_vol_price_corr_kurt_daily = NIO_MATRIX()
        self.b_vol_price_corr_kurt_pm = NIO_MATRIX()
        self.b_vol_price_corr_max_am = NIO_MATRIX()
        self.b_vol_price_corr_max_daily = NIO_MATRIX()
        self.b_vol_price_corr_max_pm = NIO_MATRIX()
        self.b_vol_price_corr_mean_am = NIO_MATRIX()
        self.b_vol_price_corr_mean_daily = NIO_MATRIX()
        self.b_vol_price_corr_mean_pm = NIO_MATRIX()
        self.b_vol_price_corr_min_am = NIO_MATRIX()
        self.b_vol_price_corr_min_daily = NIO_MATRIX()
        self.b_vol_price_corr_min_pm = NIO_MATRIX()
        self.b_vol_price_corr_skew_am = NIO_MATRIX()
        self.b_vol_price_corr_skew_daily = NIO_MATRIX()
        self.b_vol_price_corr_skew_pm = NIO_MATRIX()
        self.b_vol_price_corr_var_am = NIO_MATRIX()
        self.b_vol_price_corr_var_daily = NIO_MATRIX()
        self.b_vol_price_corr_var_pm = NIO_MATRIX()
        self.bs_amount_diff_kurt_am = NIO_MATRIX()
        self.bs_amount_diff_kurt_daily = NIO_MATRIX()
        self.bs_amount_diff_kurt_pm = NIO_MATRIX()
        self.bs_amount_diff_max_am = NIO_MATRIX()
        self.bs_amount_diff_max_daily = NIO_MATRIX()
        self.bs_amount_diff_max_pm = NIO_MATRIX()
        self.bs_amount_diff_mean_am = NIO_MATRIX()
        self.bs_amount_diff_mean_daily = NIO_MATRIX()
        self.bs_amount_diff_mean_pm = NIO_MATRIX()
        self.bs_amount_diff_min_am = NIO_MATRIX()
        self.bs_amount_diff_min_daily = NIO_MATRIX()
        self.bs_amount_diff_min_pm = NIO_MATRIX()
        self.bs_amount_diff_skew_am = NIO_MATRIX()
        self.bs_amount_diff_skew_daily = NIO_MATRIX()
        self.bs_amount_diff_skew_pm = NIO_MATRIX()
        self.bs_amount_diff_var_am = NIO_MATRIX()
        self.bs_amount_diff_var_daily = NIO_MATRIX()
        self.bs_amount_diff_var_pm = NIO_MATRIX()
        self.bs_vol_diff_kurt_am = NIO_MATRIX()
        self.bs_vol_diff_kurt_daily = NIO_MATRIX()
        self.bs_vol_diff_kurt_pm = NIO_MATRIX()
        self.bs_vol_diff_max_am = NIO_MATRIX()
        self.bs_vol_diff_max_daily = NIO_MATRIX()
        self.bs_vol_diff_max_pm = NIO_MATRIX()
        self.bs_vol_diff_mean_am = NIO_MATRIX()
        self.bs_vol_diff_mean_daily = NIO_MATRIX()
        self.bs_vol_diff_mean_pm = NIO_MATRIX()
        self.bs_vol_diff_min_am = NIO_MATRIX()
        self.bs_vol_diff_min_daily = NIO_MATRIX()
        self.bs_vol_diff_min_pm = NIO_MATRIX()
        self.bs_vol_diff_skew_am = NIO_MATRIX()
        self.bs_vol_diff_skew_daily = NIO_MATRIX()
        self.bs_vol_diff_skew_pm = NIO_MATRIX()
        self.bs_vol_diff_var_am = NIO_MATRIX()
        self.bs_vol_diff_var_daily = NIO_MATRIX()
        self.bs_vol_diff_var_pm = NIO_MATRIX()
        self.depth_spread_ratio_kurt_am = NIO_MATRIX()
        self.depth_spread_ratio_kurt_daily = NIO_MATRIX()
        self.depth_spread_ratio_kurt_pm = NIO_MATRIX()
        self.depth_spread_ratio_max_am = NIO_MATRIX()
        self.depth_spread_ratio_max_daily = NIO_MATRIX()
        self.depth_spread_ratio_max_pm = NIO_MATRIX()
        self.depth_spread_ratio_mean_am = NIO_MATRIX()
        self.depth_spread_ratio_mean_daily = NIO_MATRIX()
        self.depth_spread_ratio_mean_pm = NIO_MATRIX()
        self.depth_spread_ratio_min_am = NIO_MATRIX()
        self.depth_spread_ratio_min_daily = NIO_MATRIX()
        self.depth_spread_ratio_min_pm = NIO_MATRIX()
        self.depth_spread_ratio_skew_am = NIO_MATRIX()
        self.depth_spread_ratio_skew_daily = NIO_MATRIX()
        self.depth_spread_ratio_skew_pm = NIO_MATRIX()
        self.depth_spread_ratio_var_am = NIO_MATRIX()
        self.depth_spread_ratio_var_daily = NIO_MATRIX()
        self.depth_spread_ratio_var_pm = NIO_MATRIX()
        self.max_vol_price_diff_kurt_am = NIO_MATRIX()
        self.max_vol_price_diff_kurt_daily = NIO_MATRIX()
        self.max_vol_price_diff_kurt_pm = NIO_MATRIX()
        self.max_vol_price_diff_max_am = NIO_MATRIX()
        self.max_vol_price_diff_max_daily = NIO_MATRIX()
        self.max_vol_price_diff_max_pm = NIO_MATRIX()
        self.max_vol_price_diff_mean_am = NIO_MATRIX()
        self.max_vol_price_diff_mean_daily = NIO_MATRIX()
        self.max_vol_price_diff_mean_pm = NIO_MATRIX()
        self.max_vol_price_diff_min_am = NIO_MATRIX()
        self.max_vol_price_diff_min_daily = NIO_MATRIX()
        self.max_vol_price_diff_min_pm = NIO_MATRIX()
        self.max_vol_price_diff_skew_am = NIO_MATRIX()
        self.max_vol_price_diff_skew_daily = NIO_MATRIX()
        self.max_vol_price_diff_skew_pm = NIO_MATRIX()
        self.max_vol_price_diff_var_am = NIO_MATRIX()
        self.max_vol_price_diff_var_daily = NIO_MATRIX()
        self.max_vol_price_diff_var_pm = NIO_MATRIX()
        self.max_vol_price_rate_kurt_am = NIO_MATRIX()
        self.max_vol_price_rate_kurt_daily = NIO_MATRIX()
        self.max_vol_price_rate_kurt_pm = NIO_MATRIX()
        self.max_vol_price_rate_max_am = NIO_MATRIX()
        self.max_vol_price_rate_max_daily = NIO_MATRIX()
        self.max_vol_price_rate_max_pm = NIO_MATRIX()
        self.max_vol_price_rate_mean_am = NIO_MATRIX()
        self.max_vol_price_rate_mean_daily = NIO_MATRIX()
        self.max_vol_price_rate_mean_pm = NIO_MATRIX()
        self.max_vol_price_rate_min_am = NIO_MATRIX()
        self.max_vol_price_rate_min_daily = NIO_MATRIX()
        self.max_vol_price_rate_min_pm = NIO_MATRIX()
        self.max_vol_price_rate_skew_am = NIO_MATRIX()
        self.max_vol_price_rate_skew_daily = NIO_MATRIX()
        self.max_vol_price_rate_skew_pm = NIO_MATRIX()
        self.max_vol_price_rate_var_am = NIO_MATRIX()
        self.max_vol_price_rate_var_daily = NIO_MATRIX()
        self.max_vol_price_rate_var_pm = NIO_MATRIX()
        self.mid_price_kurt_am = NIO_MATRIX()
        self.mid_price_kurt_daily = NIO_MATRIX()
        self.mid_price_kurt_pm = NIO_MATRIX()
        self.mid_price_skew_am = NIO_MATRIX()
        self.mid_price_skew_daily = NIO_MATRIX()
        self.mid_price_skew_pm = NIO_MATRIX()
        self.mid_price_var_am = NIO_MATRIX()
        self.mid_price_var_daily = NIO_MATRIX()
        self.mid_price_var_pm = NIO_MATRIX()
        self.s123_vol_ratio_kurt_am = NIO_MATRIX()
        self.s123_vol_ratio_kurt_daily = NIO_MATRIX()
        self.s123_vol_ratio_kurt_pm = NIO_MATRIX()
        self.s123_vol_ratio_max_am = NIO_MATRIX()
        self.s123_vol_ratio_max_daily = NIO_MATRIX()
        self.s123_vol_ratio_max_pm = NIO_MATRIX()
        self.s123_vol_ratio_mean_am = NIO_MATRIX()
        self.s123_vol_ratio_mean_daily = NIO_MATRIX()
        self.s123_vol_ratio_mean_pm = NIO_MATRIX()
        self.s123_vol_ratio_min_am = NIO_MATRIX()
        self.s123_vol_ratio_min_daily = NIO_MATRIX()
        self.s123_vol_ratio_min_pm = NIO_MATRIX()
        self.s123_vol_ratio_skew_am = NIO_MATRIX()
        self.s123_vol_ratio_skew_daily = NIO_MATRIX()
        self.s123_vol_ratio_skew_pm = NIO_MATRIX()
        self.s123_vol_ratio_var_am = NIO_MATRIX()
        self.s123_vol_ratio_var_daily = NIO_MATRIX()
        self.s123_vol_ratio_var_pm = NIO_MATRIX()
        self.s1_vol_ratio_kurt_am = NIO_MATRIX()
        self.s1_vol_ratio_kurt_daily = NIO_MATRIX()
        self.s1_vol_ratio_kurt_pm = NIO_MATRIX()
        self.s1_vol_ratio_max_am = NIO_MATRIX()
        self.s1_vol_ratio_max_daily = NIO_MATRIX()
        self.s1_vol_ratio_max_pm = NIO_MATRIX()
        self.s1_vol_ratio_mean_am = NIO_MATRIX()
        self.s1_vol_ratio_mean_daily = NIO_MATRIX()
        self.s1_vol_ratio_mean_pm = NIO_MATRIX()
        self.s1_vol_ratio_min_am = NIO_MATRIX()
        self.s1_vol_ratio_min_daily = NIO_MATRIX()
        self.s1_vol_ratio_min_pm = NIO_MATRIX()
        self.s1_vol_ratio_skew_am = NIO_MATRIX()
        self.s1_vol_ratio_skew_daily = NIO_MATRIX()
        self.s1_vol_ratio_skew_pm = NIO_MATRIX()
        self.s1_vol_ratio_var_am = NIO_MATRIX()
        self.s1_vol_ratio_var_daily = NIO_MATRIX()
        self.s1_vol_ratio_var_pm = NIO_MATRIX()
        self.s5_b1_vol_diff_kurt_am = NIO_MATRIX()
        self.s5_b1_vol_diff_kurt_daily = NIO_MATRIX()
        self.s5_b1_vol_diff_kurt_pm = NIO_MATRIX()
        self.s5_b1_vol_diff_max_am = NIO_MATRIX()
        self.s5_b1_vol_diff_max_daily = NIO_MATRIX()
        self.s5_b1_vol_diff_max_pm = NIO_MATRIX()
        self.s5_b1_vol_diff_mean_am = NIO_MATRIX()
        self.s5_b1_vol_diff_mean_daily = NIO_MATRIX()
        self.s5_b1_vol_diff_mean_pm = NIO_MATRIX()
        self.s5_b1_vol_diff_min_am = NIO_MATRIX()
        self.s5_b1_vol_diff_min_daily = NIO_MATRIX()
        self.s5_b1_vol_diff_min_pm = NIO_MATRIX()
        self.s5_b1_vol_diff_skew_am = NIO_MATRIX()
        self.s5_b1_vol_diff_skew_daily = NIO_MATRIX()
        self.s5_b1_vol_diff_skew_pm = NIO_MATRIX()
        self.s5_b1_vol_diff_var_am = NIO_MATRIX()
        self.s5_b1_vol_diff_var_daily = NIO_MATRIX()
        self.s5_b1_vol_diff_var_pm = NIO_MATRIX()
        self.s_avg_spread_kurt_am = NIO_MATRIX()
        self.s_avg_spread_kurt_daily = NIO_MATRIX()
        self.s_avg_spread_kurt_pm = NIO_MATRIX()
        self.s_avg_spread_max_am = NIO_MATRIX()
        self.s_avg_spread_max_daily = NIO_MATRIX()
        self.s_avg_spread_max_pm = NIO_MATRIX()
        self.s_avg_spread_mean_am = NIO_MATRIX()
        self.s_avg_spread_mean_daily = NIO_MATRIX()
        self.s_avg_spread_mean_pm = NIO_MATRIX()
        self.s_avg_spread_min_am = NIO_MATRIX()
        self.s_avg_spread_min_daily = NIO_MATRIX()
        self.s_avg_spread_min_pm = NIO_MATRIX()
        self.s_avg_spread_skew_am = NIO_MATRIX()
        self.s_avg_spread_skew_daily = NIO_MATRIX()
        self.s_avg_spread_skew_pm = NIO_MATRIX()
        self.s_avg_spread_var_am = NIO_MATRIX()
        self.s_avg_spread_var_daily = NIO_MATRIX()
        self.s_avg_spread_var_pm = NIO_MATRIX()
        self.s_depth_spread_kurt_am = NIO_MATRIX()
        self.s_depth_spread_kurt_daily = NIO_MATRIX()
        self.s_depth_spread_kurt_pm = NIO_MATRIX()
        self.s_depth_spread_mean_am = NIO_MATRIX()
        self.s_depth_spread_mean_pm = NIO_MATRIX()
        self.s_depth_spread_skew_am = NIO_MATRIX()
        self.s_depth_spread_skew_daily = NIO_MATRIX()
        self.s_depth_spread_skew_pm = NIO_MATRIX()
        self.s_depth_spread_var_am = NIO_MATRIX()
        self.s_depth_spread_var_daily = NIO_MATRIX()
        self.s_depth_spread_var_pm = NIO_MATRIX()
        self.s_max_vol_price_kurt_am = NIO_MATRIX()
        self.s_max_vol_price_kurt_daily = NIO_MATRIX()
        self.s_max_vol_price_kurt_pm = NIO_MATRIX()
        self.s_max_vol_price_max_am = NIO_MATRIX()
        self.s_max_vol_price_max_daily = NIO_MATRIX()
        self.s_max_vol_price_max_pm = NIO_MATRIX()
        self.s_max_vol_price_mean_am = NIO_MATRIX()
        self.s_max_vol_price_mean_daily = NIO_MATRIX()
        self.s_max_vol_price_mean_pm = NIO_MATRIX()
        self.s_max_vol_price_min_am = NIO_MATRIX()
        self.s_max_vol_price_min_daily = NIO_MATRIX()
        self.s_max_vol_price_min_pm = NIO_MATRIX()
        self.s_max_vol_price_skew_am = NIO_MATRIX()
        self.s_max_vol_price_skew_daily = NIO_MATRIX()
        self.s_max_vol_price_skew_pm = NIO_MATRIX()
        self.s_max_vol_price_var_am = NIO_MATRIX()
        self.s_max_vol_price_var_daily = NIO_MATRIX()
        self.s_max_vol_price_var_pm = NIO_MATRIX()
        self.s_vol_disp_kurt_am = NIO_MATRIX()
        self.s_vol_disp_kurt_daily = NIO_MATRIX()
        self.s_vol_disp_kurt_pm = NIO_MATRIX()
        self.s_vol_disp_max_am = NIO_MATRIX()
        self.s_vol_disp_max_daily = NIO_MATRIX()
        self.s_vol_disp_max_pm = NIO_MATRIX()
        self.s_vol_disp_mean_am = NIO_MATRIX()
        self.s_vol_disp_mean_daily = NIO_MATRIX()
        self.s_vol_disp_mean_pm = NIO_MATRIX()
        self.s_vol_disp_min_am = NIO_MATRIX()
        self.s_vol_disp_min_daily = NIO_MATRIX()
        self.s_vol_disp_min_pm = NIO_MATRIX()
        self.s_vol_disp_skew_am = NIO_MATRIX()
        self.s_vol_disp_skew_daily = NIO_MATRIX()
        self.s_vol_disp_skew_pm = NIO_MATRIX()
        self.s_vol_disp_var_am = NIO_MATRIX()
        self.s_vol_disp_var_daily = NIO_MATRIX()
        self.s_vol_disp_var_pm = NIO_MATRIX()
        self.s_vol_price_corr_kurt_am = NIO_MATRIX()
        self.s_vol_price_corr_kurt_daily = NIO_MATRIX()
        self.s_vol_price_corr_kurt_pm = NIO_MATRIX()
        self.s_vol_price_corr_max_am = NIO_MATRIX()
        self.s_vol_price_corr_max_daily = NIO_MATRIX()
        self.s_vol_price_corr_max_pm = NIO_MATRIX()
        self.s_vol_price_corr_mean_am = NIO_MATRIX()
        self.s_vol_price_corr_mean_daily = NIO_MATRIX()
        self.s_vol_price_corr_mean_pm = NIO_MATRIX()
        self.s_vol_price_corr_min_am = NIO_MATRIX()
        self.s_vol_price_corr_min_daily = NIO_MATRIX()
        self.s_vol_price_corr_min_pm = NIO_MATRIX()
        self.s_vol_price_corr_skew_am = NIO_MATRIX()
        self.s_vol_price_corr_skew_daily = NIO_MATRIX()
        self.s_vol_price_corr_skew_pm = NIO_MATRIX()
        self.s_vol_price_corr_var_am = NIO_MATRIX()
        self.s_vol_price_corr_var_daily = NIO_MATRIX()
        self.s_vol_price_corr_var_pm = NIO_MATRIX()
        self.spread_kurt_am = NIO_MATRIX()
        self.spread_kurt_daily = NIO_MATRIX()
        self.spread_kurt_pm = NIO_MATRIX()
        self.spread_skew_am = NIO_MATRIX()
        self.spread_skew_daily = NIO_MATRIX()
        self.spread_skew_pm = NIO_MATRIX()
        self.spread_var_am = NIO_MATRIX()
        self.spread_var_daily = NIO_MATRIX()
        self.spread_var_pm = NIO_MATRIX()
        self.weighted_spread_kurt_am = NIO_MATRIX()
        self.weighted_spread_kurt_daily = NIO_MATRIX()
        self.weighted_spread_kurt_pm = NIO_MATRIX()
        self.weighted_spread_skew_am = NIO_MATRIX()
        self.weighted_spread_skew_daily = NIO_MATRIX()
        self.weighted_spread_skew_pm = NIO_MATRIX()
        self.weighted_spread_var_am = NIO_MATRIX()
        self.weighted_spread_var_daily = NIO_MATRIX()
        self.weighted_spread_var_pm = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.b123_vol_ratio_kurt_am, 'fguo_ywang.b123_vol_ratio_kurt_am')
        self.addDailyData(self.b123_vol_ratio_kurt_daily, 'fguo_ywang.b123_vol_ratio_kurt_daily')
        self.addDailyData(self.b123_vol_ratio_kurt_pm, 'fguo_ywang.b123_vol_ratio_kurt_pm')
        self.addDailyData(self.b123_vol_ratio_max_am, 'fguo_ywang.b123_vol_ratio_max_am')
        self.addDailyData(self.b123_vol_ratio_max_daily, 'fguo_ywang.b123_vol_ratio_max_daily')
        self.addDailyData(self.b123_vol_ratio_max_pm, 'fguo_ywang.b123_vol_ratio_max_pm')
        self.addDailyData(self.b123_vol_ratio_mean_am, 'fguo_ywang.b123_vol_ratio_mean_am')
        self.addDailyData(self.b123_vol_ratio_mean_daily, 'fguo_ywang.b123_vol_ratio_mean_daily')
        self.addDailyData(self.b123_vol_ratio_mean_pm, 'fguo_ywang.b123_vol_ratio_mean_pm')
        self.addDailyData(self.b123_vol_ratio_min_am, 'fguo_ywang.b123_vol_ratio_min_am')
        self.addDailyData(self.b123_vol_ratio_min_daily, 'fguo_ywang.b123_vol_ratio_min_daily')
        self.addDailyData(self.b123_vol_ratio_min_pm, 'fguo_ywang.b123_vol_ratio_min_pm')
        self.addDailyData(self.b123_vol_ratio_skew_am, 'fguo_ywang.b123_vol_ratio_skew_am')
        self.addDailyData(self.b123_vol_ratio_skew_daily, 'fguo_ywang.b123_vol_ratio_skew_daily')
        self.addDailyData(self.b123_vol_ratio_skew_pm, 'fguo_ywang.b123_vol_ratio_skew_pm')
        self.addDailyData(self.b123_vol_ratio_var_am, 'fguo_ywang.b123_vol_ratio_var_am')
        self.addDailyData(self.b123_vol_ratio_var_daily, 'fguo_ywang.b123_vol_ratio_var_daily')
        self.addDailyData(self.b123_vol_ratio_var_pm, 'fguo_ywang.b123_vol_ratio_var_pm')
        self.addDailyData(self.b1_vol_ratio_kurt_am, 'fguo_ywang.b1_vol_ratio_kurt_am')
        self.addDailyData(self.b1_vol_ratio_kurt_daily, 'fguo_ywang.b1_vol_ratio_kurt_daily')
        self.addDailyData(self.b1_vol_ratio_kurt_pm, 'fguo_ywang.b1_vol_ratio_kurt_pm')
        self.addDailyData(self.b1_vol_ratio_max_am, 'fguo_ywang.b1_vol_ratio_max_am')
        self.addDailyData(self.b1_vol_ratio_max_daily, 'fguo_ywang.b1_vol_ratio_max_daily')
        self.addDailyData(self.b1_vol_ratio_max_pm, 'fguo_ywang.b1_vol_ratio_max_pm')
        self.addDailyData(self.b1_vol_ratio_mean_am, 'fguo_ywang.b1_vol_ratio_mean_am')
        self.addDailyData(self.b1_vol_ratio_mean_daily, 'fguo_ywang.b1_vol_ratio_mean_daily')
        self.addDailyData(self.b1_vol_ratio_mean_pm, 'fguo_ywang.b1_vol_ratio_mean_pm')
        self.addDailyData(self.b1_vol_ratio_min_am, 'fguo_ywang.b1_vol_ratio_min_am')
        self.addDailyData(self.b1_vol_ratio_min_daily, 'fguo_ywang.b1_vol_ratio_min_daily')
        self.addDailyData(self.b1_vol_ratio_min_pm, 'fguo_ywang.b1_vol_ratio_min_pm')
        self.addDailyData(self.b1_vol_ratio_skew_am, 'fguo_ywang.b1_vol_ratio_skew_am')
        self.addDailyData(self.b1_vol_ratio_skew_daily, 'fguo_ywang.b1_vol_ratio_skew_daily')
        self.addDailyData(self.b1_vol_ratio_skew_pm, 'fguo_ywang.b1_vol_ratio_skew_pm')
        self.addDailyData(self.b1_vol_ratio_var_am, 'fguo_ywang.b1_vol_ratio_var_am')
        self.addDailyData(self.b1_vol_ratio_var_daily, 'fguo_ywang.b1_vol_ratio_var_daily')
        self.addDailyData(self.b1_vol_ratio_var_pm, 'fguo_ywang.b1_vol_ratio_var_pm')
        self.addDailyData(self.b5_s1_vol_diff_kurt_am, 'fguo_ywang.b5_s1_vol_diff_kurt_am')
        self.addDailyData(self.b5_s1_vol_diff_kurt_daily, 'fguo_ywang.b5_s1_vol_diff_kurt_daily')
        self.addDailyData(self.b5_s1_vol_diff_kurt_pm, 'fguo_ywang.b5_s1_vol_diff_kurt_pm')
        self.addDailyData(self.b5_s1_vol_diff_max_am, 'fguo_ywang.b5_s1_vol_diff_max_am')
        self.addDailyData(self.b5_s1_vol_diff_max_daily, 'fguo_ywang.b5_s1_vol_diff_max_daily')
        self.addDailyData(self.b5_s1_vol_diff_max_pm, 'fguo_ywang.b5_s1_vol_diff_max_pm')
        self.addDailyData(self.b5_s1_vol_diff_mean_am, 'fguo_ywang.b5_s1_vol_diff_mean_am')
        self.addDailyData(self.b5_s1_vol_diff_mean_daily, 'fguo_ywang.b5_s1_vol_diff_mean_daily')
        self.addDailyData(self.b5_s1_vol_diff_mean_pm, 'fguo_ywang.b5_s1_vol_diff_mean_pm')
        self.addDailyData(self.b5_s1_vol_diff_min_am, 'fguo_ywang.b5_s1_vol_diff_min_am')
        self.addDailyData(self.b5_s1_vol_diff_min_daily, 'fguo_ywang.b5_s1_vol_diff_min_daily')
        self.addDailyData(self.b5_s1_vol_diff_min_pm, 'fguo_ywang.b5_s1_vol_diff_min_pm')
        self.addDailyData(self.b5_s1_vol_diff_skew_am, 'fguo_ywang.b5_s1_vol_diff_skew_am')
        self.addDailyData(self.b5_s1_vol_diff_skew_daily, 'fguo_ywang.b5_s1_vol_diff_skew_daily')
        self.addDailyData(self.b5_s1_vol_diff_skew_pm, 'fguo_ywang.b5_s1_vol_diff_skew_pm')
        self.addDailyData(self.b5_s1_vol_diff_var_am, 'fguo_ywang.b5_s1_vol_diff_var_am')
        self.addDailyData(self.b5_s1_vol_diff_var_daily, 'fguo_ywang.b5_s1_vol_diff_var_daily')
        self.addDailyData(self.b5_s1_vol_diff_var_pm, 'fguo_ywang.b5_s1_vol_diff_var_pm')
        self.addDailyData(self.b6_s6_vol_diff_kurt_am, 'fguo_ywang.b6_s6_vol_diff_kurt_am')
        self.addDailyData(self.b6_s6_vol_diff_kurt_daily, 'fguo_ywang.b6_s6_vol_diff_kurt_daily')
        self.addDailyData(self.b6_s6_vol_diff_kurt_pm, 'fguo_ywang.b6_s6_vol_diff_kurt_pm')
        self.addDailyData(self.b6_s6_vol_diff_max_am, 'fguo_ywang.b6_s6_vol_diff_max_am')
        self.addDailyData(self.b6_s6_vol_diff_max_daily, 'fguo_ywang.b6_s6_vol_diff_max_daily')
        self.addDailyData(self.b6_s6_vol_diff_max_pm, 'fguo_ywang.b6_s6_vol_diff_max_pm')
        self.addDailyData(self.b6_s6_vol_diff_mean_am, 'fguo_ywang.b6_s6_vol_diff_mean_am')
        self.addDailyData(self.b6_s6_vol_diff_mean_daily, 'fguo_ywang.b6_s6_vol_diff_mean_daily')
        self.addDailyData(self.b6_s6_vol_diff_mean_pm, 'fguo_ywang.b6_s6_vol_diff_mean_pm')
        self.addDailyData(self.b6_s6_vol_diff_min_am, 'fguo_ywang.b6_s6_vol_diff_min_am')
        self.addDailyData(self.b6_s6_vol_diff_min_daily, 'fguo_ywang.b6_s6_vol_diff_min_daily')
        self.addDailyData(self.b6_s6_vol_diff_min_pm, 'fguo_ywang.b6_s6_vol_diff_min_pm')
        self.addDailyData(self.b6_s6_vol_diff_skew_am, 'fguo_ywang.b6_s6_vol_diff_skew_am')
        self.addDailyData(self.b6_s6_vol_diff_skew_daily, 'fguo_ywang.b6_s6_vol_diff_skew_daily')
        self.addDailyData(self.b6_s6_vol_diff_skew_pm, 'fguo_ywang.b6_s6_vol_diff_skew_pm')
        self.addDailyData(self.b6_s6_vol_diff_var_am, 'fguo_ywang.b6_s6_vol_diff_var_am')
        self.addDailyData(self.b6_s6_vol_diff_var_daily, 'fguo_ywang.b6_s6_vol_diff_var_daily')
        self.addDailyData(self.b6_s6_vol_diff_var_pm, 'fguo_ywang.b6_s6_vol_diff_var_pm')
        self.addDailyData(self.b_avg_spread_kurt_am, 'fguo_ywang.b_avg_spread_kurt_am')
        self.addDailyData(self.b_avg_spread_kurt_daily, 'fguo_ywang.b_avg_spread_kurt_daily')
        self.addDailyData(self.b_avg_spread_kurt_pm, 'fguo_ywang.b_avg_spread_kurt_pm')
        self.addDailyData(self.b_avg_spread_max_am, 'fguo_ywang.b_avg_spread_max_am')
        self.addDailyData(self.b_avg_spread_max_daily, 'fguo_ywang.b_avg_spread_max_daily')
        self.addDailyData(self.b_avg_spread_max_pm, 'fguo_ywang.b_avg_spread_max_pm')
        self.addDailyData(self.b_avg_spread_mean_am, 'fguo_ywang.b_avg_spread_mean_am')
        self.addDailyData(self.b_avg_spread_mean_daily, 'fguo_ywang.b_avg_spread_mean_daily')
        self.addDailyData(self.b_avg_spread_mean_pm, 'fguo_ywang.b_avg_spread_mean_pm')
        self.addDailyData(self.b_avg_spread_min_am, 'fguo_ywang.b_avg_spread_min_am')
        self.addDailyData(self.b_avg_spread_min_daily, 'fguo_ywang.b_avg_spread_min_daily')
        self.addDailyData(self.b_avg_spread_min_pm, 'fguo_ywang.b_avg_spread_min_pm')
        self.addDailyData(self.b_avg_spread_skew_am, 'fguo_ywang.b_avg_spread_skew_am')
        self.addDailyData(self.b_avg_spread_skew_daily, 'fguo_ywang.b_avg_spread_skew_daily')
        self.addDailyData(self.b_avg_spread_skew_pm, 'fguo_ywang.b_avg_spread_skew_pm')
        self.addDailyData(self.b_avg_spread_var_am, 'fguo_ywang.b_avg_spread_var_am')
        self.addDailyData(self.b_avg_spread_var_daily, 'fguo_ywang.b_avg_spread_var_daily')
        self.addDailyData(self.b_avg_spread_var_pm, 'fguo_ywang.b_avg_spread_var_pm')
        self.addDailyData(self.b_depth_spread_kurt_am, 'fguo_ywang.b_depth_spread_kurt_am')
        self.addDailyData(self.b_depth_spread_kurt_daily, 'fguo_ywang.b_depth_spread_kurt_daily')
        self.addDailyData(self.b_depth_spread_kurt_pm, 'fguo_ywang.b_depth_spread_kurt_pm')
        self.addDailyData(self.b_depth_spread_mean_am, 'fguo_ywang.b_depth_spread_mean_am')
        self.addDailyData(self.b_depth_spread_mean_pm, 'fguo_ywang.b_depth_spread_mean_pm')
        self.addDailyData(self.b_depth_spread_skew_am, 'fguo_ywang.b_depth_spread_skew_am')
        self.addDailyData(self.b_depth_spread_skew_daily, 'fguo_ywang.b_depth_spread_skew_daily')
        self.addDailyData(self.b_depth_spread_skew_pm, 'fguo_ywang.b_depth_spread_skew_pm')
        self.addDailyData(self.b_depth_spread_var_am, 'fguo_ywang.b_depth_spread_var_am')
        self.addDailyData(self.b_depth_spread_var_daily, 'fguo_ywang.b_depth_spread_var_daily')
        self.addDailyData(self.b_depth_spread_var_pm, 'fguo_ywang.b_depth_spread_var_pm')
        self.addDailyData(self.b_max_vol_price_kurt_am, 'fguo_ywang.b_max_vol_price_kurt_am')
        self.addDailyData(self.b_max_vol_price_kurt_daily, 'fguo_ywang.b_max_vol_price_kurt_daily')
        self.addDailyData(self.b_max_vol_price_kurt_pm, 'fguo_ywang.b_max_vol_price_kurt_pm')
        self.addDailyData(self.b_max_vol_price_max_am, 'fguo_ywang.b_max_vol_price_max_am')
        self.addDailyData(self.b_max_vol_price_max_daily, 'fguo_ywang.b_max_vol_price_max_daily')
        self.addDailyData(self.b_max_vol_price_max_pm, 'fguo_ywang.b_max_vol_price_max_pm')
        self.addDailyData(self.b_max_vol_price_mean_am, 'fguo_ywang.b_max_vol_price_mean_am')
        self.addDailyData(self.b_max_vol_price_mean_daily, 'fguo_ywang.b_max_vol_price_mean_daily')
        self.addDailyData(self.b_max_vol_price_mean_pm, 'fguo_ywang.b_max_vol_price_mean_pm')
        self.addDailyData(self.b_max_vol_price_min_am, 'fguo_ywang.b_max_vol_price_min_am')
        self.addDailyData(self.b_max_vol_price_min_daily, 'fguo_ywang.b_max_vol_price_min_daily')
        self.addDailyData(self.b_max_vol_price_min_pm, 'fguo_ywang.b_max_vol_price_min_pm')
        self.addDailyData(self.b_max_vol_price_skew_am, 'fguo_ywang.b_max_vol_price_skew_am')
        self.addDailyData(self.b_max_vol_price_skew_daily, 'fguo_ywang.b_max_vol_price_skew_daily')
        self.addDailyData(self.b_max_vol_price_skew_pm, 'fguo_ywang.b_max_vol_price_skew_pm')
        self.addDailyData(self.b_max_vol_price_var_am, 'fguo_ywang.b_max_vol_price_var_am')
        self.addDailyData(self.b_max_vol_price_var_daily, 'fguo_ywang.b_max_vol_price_var_daily')
        self.addDailyData(self.b_max_vol_price_var_pm, 'fguo_ywang.b_max_vol_price_var_pm')
        self.addDailyData(self.b_vol_disp_kurt_am, 'fguo_ywang.b_vol_disp_kurt_am')
        self.addDailyData(self.b_vol_disp_kurt_daily, 'fguo_ywang.b_vol_disp_kurt_daily')
        self.addDailyData(self.b_vol_disp_kurt_pm, 'fguo_ywang.b_vol_disp_kurt_pm')
        self.addDailyData(self.b_vol_disp_max_am, 'fguo_ywang.b_vol_disp_max_am')
        self.addDailyData(self.b_vol_disp_max_daily, 'fguo_ywang.b_vol_disp_max_daily')
        self.addDailyData(self.b_vol_disp_max_pm, 'fguo_ywang.b_vol_disp_max_pm')
        self.addDailyData(self.b_vol_disp_mean_am, 'fguo_ywang.b_vol_disp_mean_am')
        self.addDailyData(self.b_vol_disp_mean_daily, 'fguo_ywang.b_vol_disp_mean_daily')
        self.addDailyData(self.b_vol_disp_mean_pm, 'fguo_ywang.b_vol_disp_mean_pm')
        self.addDailyData(self.b_vol_disp_min_am, 'fguo_ywang.b_vol_disp_min_am')
        self.addDailyData(self.b_vol_disp_min_daily, 'fguo_ywang.b_vol_disp_min_daily')
        self.addDailyData(self.b_vol_disp_min_pm, 'fguo_ywang.b_vol_disp_min_pm')
        self.addDailyData(self.b_vol_disp_skew_am, 'fguo_ywang.b_vol_disp_skew_am')
        self.addDailyData(self.b_vol_disp_skew_daily, 'fguo_ywang.b_vol_disp_skew_daily')
        self.addDailyData(self.b_vol_disp_skew_pm, 'fguo_ywang.b_vol_disp_skew_pm')
        self.addDailyData(self.b_vol_disp_var_am, 'fguo_ywang.b_vol_disp_var_am')
        self.addDailyData(self.b_vol_disp_var_daily, 'fguo_ywang.b_vol_disp_var_daily')
        self.addDailyData(self.b_vol_disp_var_pm, 'fguo_ywang.b_vol_disp_var_pm')
        self.addDailyData(self.b_vol_price_corr_kurt_am, 'fguo_ywang.b_vol_price_corr_kurt_am')
        self.addDailyData(self.b_vol_price_corr_kurt_daily, 'fguo_ywang.b_vol_price_corr_kurt_daily')
        self.addDailyData(self.b_vol_price_corr_kurt_pm, 'fguo_ywang.b_vol_price_corr_kurt_pm')
        self.addDailyData(self.b_vol_price_corr_max_am, 'fguo_ywang.b_vol_price_corr_max_am')
        self.addDailyData(self.b_vol_price_corr_max_daily, 'fguo_ywang.b_vol_price_corr_max_daily')
        self.addDailyData(self.b_vol_price_corr_max_pm, 'fguo_ywang.b_vol_price_corr_max_pm')
        self.addDailyData(self.b_vol_price_corr_mean_am, 'fguo_ywang.b_vol_price_corr_mean_am')
        self.addDailyData(self.b_vol_price_corr_mean_daily, 'fguo_ywang.b_vol_price_corr_mean_daily')
        self.addDailyData(self.b_vol_price_corr_mean_pm, 'fguo_ywang.b_vol_price_corr_mean_pm')
        self.addDailyData(self.b_vol_price_corr_min_am, 'fguo_ywang.b_vol_price_corr_min_am')
        self.addDailyData(self.b_vol_price_corr_min_daily, 'fguo_ywang.b_vol_price_corr_min_daily')
        self.addDailyData(self.b_vol_price_corr_min_pm, 'fguo_ywang.b_vol_price_corr_min_pm')
        self.addDailyData(self.b_vol_price_corr_skew_am, 'fguo_ywang.b_vol_price_corr_skew_am')
        self.addDailyData(self.b_vol_price_corr_skew_daily, 'fguo_ywang.b_vol_price_corr_skew_daily')
        self.addDailyData(self.b_vol_price_corr_skew_pm, 'fguo_ywang.b_vol_price_corr_skew_pm')
        self.addDailyData(self.b_vol_price_corr_var_am, 'fguo_ywang.b_vol_price_corr_var_am')
        self.addDailyData(self.b_vol_price_corr_var_daily, 'fguo_ywang.b_vol_price_corr_var_daily')
        self.addDailyData(self.b_vol_price_corr_var_pm, 'fguo_ywang.b_vol_price_corr_var_pm')
        self.addDailyData(self.bs_amount_diff_kurt_am, 'fguo_ywang.bs_amount_diff_kurt_am')
        self.addDailyData(self.bs_amount_diff_kurt_daily, 'fguo_ywang.bs_amount_diff_kurt_daily')
        self.addDailyData(self.bs_amount_diff_kurt_pm, 'fguo_ywang.bs_amount_diff_kurt_pm')
        self.addDailyData(self.bs_amount_diff_max_am, 'fguo_ywang.bs_amount_diff_max_am')
        self.addDailyData(self.bs_amount_diff_max_daily, 'fguo_ywang.bs_amount_diff_max_daily')
        self.addDailyData(self.bs_amount_diff_max_pm, 'fguo_ywang.bs_amount_diff_max_pm')
        self.addDailyData(self.bs_amount_diff_mean_am, 'fguo_ywang.bs_amount_diff_mean_am')
        self.addDailyData(self.bs_amount_diff_mean_daily, 'fguo_ywang.bs_amount_diff_mean_daily')
        self.addDailyData(self.bs_amount_diff_mean_pm, 'fguo_ywang.bs_amount_diff_mean_pm')
        self.addDailyData(self.bs_amount_diff_min_am, 'fguo_ywang.bs_amount_diff_min_am')
        self.addDailyData(self.bs_amount_diff_min_daily, 'fguo_ywang.bs_amount_diff_min_daily')
        self.addDailyData(self.bs_amount_diff_min_pm, 'fguo_ywang.bs_amount_diff_min_pm')
        self.addDailyData(self.bs_amount_diff_skew_am, 'fguo_ywang.bs_amount_diff_skew_am')
        self.addDailyData(self.bs_amount_diff_skew_daily, 'fguo_ywang.bs_amount_diff_skew_daily')
        self.addDailyData(self.bs_amount_diff_skew_pm, 'fguo_ywang.bs_amount_diff_skew_pm')
        self.addDailyData(self.bs_amount_diff_var_am, 'fguo_ywang.bs_amount_diff_var_am')
        self.addDailyData(self.bs_amount_diff_var_daily, 'fguo_ywang.bs_amount_diff_var_daily')
        self.addDailyData(self.bs_amount_diff_var_pm, 'fguo_ywang.bs_amount_diff_var_pm')
        self.addDailyData(self.bs_vol_diff_kurt_am, 'fguo_ywang.bs_vol_diff_kurt_am')
        self.addDailyData(self.bs_vol_diff_kurt_daily, 'fguo_ywang.bs_vol_diff_kurt_daily')
        self.addDailyData(self.bs_vol_diff_kurt_pm, 'fguo_ywang.bs_vol_diff_kurt_pm')
        self.addDailyData(self.bs_vol_diff_max_am, 'fguo_ywang.bs_vol_diff_max_am')
        self.addDailyData(self.bs_vol_diff_max_daily, 'fguo_ywang.bs_vol_diff_max_daily')
        self.addDailyData(self.bs_vol_diff_max_pm, 'fguo_ywang.bs_vol_diff_max_pm')
        self.addDailyData(self.bs_vol_diff_mean_am, 'fguo_ywang.bs_vol_diff_mean_am')
        self.addDailyData(self.bs_vol_diff_mean_daily, 'fguo_ywang.bs_vol_diff_mean_daily')
        self.addDailyData(self.bs_vol_diff_mean_pm, 'fguo_ywang.bs_vol_diff_mean_pm')
        self.addDailyData(self.bs_vol_diff_min_am, 'fguo_ywang.bs_vol_diff_min_am')
        self.addDailyData(self.bs_vol_diff_min_daily, 'fguo_ywang.bs_vol_diff_min_daily')
        self.addDailyData(self.bs_vol_diff_min_pm, 'fguo_ywang.bs_vol_diff_min_pm')
        self.addDailyData(self.bs_vol_diff_skew_am, 'fguo_ywang.bs_vol_diff_skew_am')
        self.addDailyData(self.bs_vol_diff_skew_daily, 'fguo_ywang.bs_vol_diff_skew_daily')
        self.addDailyData(self.bs_vol_diff_skew_pm, 'fguo_ywang.bs_vol_diff_skew_pm')
        self.addDailyData(self.bs_vol_diff_var_am, 'fguo_ywang.bs_vol_diff_var_am')
        self.addDailyData(self.bs_vol_diff_var_daily, 'fguo_ywang.bs_vol_diff_var_daily')
        self.addDailyData(self.bs_vol_diff_var_pm, 'fguo_ywang.bs_vol_diff_var_pm')
        self.addDailyData(self.depth_spread_ratio_kurt_am, 'fguo_ywang.depth_spread_ratio_kurt_am')
        self.addDailyData(self.depth_spread_ratio_kurt_daily, 'fguo_ywang.depth_spread_ratio_kurt_daily')
        self.addDailyData(self.depth_spread_ratio_kurt_pm, 'fguo_ywang.depth_spread_ratio_kurt_pm')
        self.addDailyData(self.depth_spread_ratio_max_am, 'fguo_ywang.depth_spread_ratio_max_am')
        self.addDailyData(self.depth_spread_ratio_max_daily, 'fguo_ywang.depth_spread_ratio_max_daily')
        self.addDailyData(self.depth_spread_ratio_max_pm, 'fguo_ywang.depth_spread_ratio_max_pm')
        self.addDailyData(self.depth_spread_ratio_mean_am, 'fguo_ywang.depth_spread_ratio_mean_am')
        self.addDailyData(self.depth_spread_ratio_mean_daily, 'fguo_ywang.depth_spread_ratio_mean_daily')
        self.addDailyData(self.depth_spread_ratio_mean_pm, 'fguo_ywang.depth_spread_ratio_mean_pm')
        self.addDailyData(self.depth_spread_ratio_min_am, 'fguo_ywang.depth_spread_ratio_min_am')
        self.addDailyData(self.depth_spread_ratio_min_daily, 'fguo_ywang.depth_spread_ratio_min_daily')
        self.addDailyData(self.depth_spread_ratio_min_pm, 'fguo_ywang.depth_spread_ratio_min_pm')
        self.addDailyData(self.depth_spread_ratio_skew_am, 'fguo_ywang.depth_spread_ratio_skew_am')
        self.addDailyData(self.depth_spread_ratio_skew_daily, 'fguo_ywang.depth_spread_ratio_skew_daily')
        self.addDailyData(self.depth_spread_ratio_skew_pm, 'fguo_ywang.depth_spread_ratio_skew_pm')
        self.addDailyData(self.depth_spread_ratio_var_am, 'fguo_ywang.depth_spread_ratio_var_am')
        self.addDailyData(self.depth_spread_ratio_var_daily, 'fguo_ywang.depth_spread_ratio_var_daily')
        self.addDailyData(self.depth_spread_ratio_var_pm, 'fguo_ywang.depth_spread_ratio_var_pm')
        self.addDailyData(self.max_vol_price_diff_kurt_am, 'fguo_ywang.max_vol_price_diff_kurt_am')
        self.addDailyData(self.max_vol_price_diff_kurt_daily, 'fguo_ywang.max_vol_price_diff_kurt_daily')
        self.addDailyData(self.max_vol_price_diff_kurt_pm, 'fguo_ywang.max_vol_price_diff_kurt_pm')
        self.addDailyData(self.max_vol_price_diff_max_am, 'fguo_ywang.max_vol_price_diff_max_am')
        self.addDailyData(self.max_vol_price_diff_max_daily, 'fguo_ywang.max_vol_price_diff_max_daily')
        self.addDailyData(self.max_vol_price_diff_max_pm, 'fguo_ywang.max_vol_price_diff_max_pm')
        self.addDailyData(self.max_vol_price_diff_mean_am, 'fguo_ywang.max_vol_price_diff_mean_am')
        self.addDailyData(self.max_vol_price_diff_mean_daily, 'fguo_ywang.max_vol_price_diff_mean_daily')
        self.addDailyData(self.max_vol_price_diff_mean_pm, 'fguo_ywang.max_vol_price_diff_mean_pm')
        self.addDailyData(self.max_vol_price_diff_min_am, 'fguo_ywang.max_vol_price_diff_min_am')
        self.addDailyData(self.max_vol_price_diff_min_daily, 'fguo_ywang.max_vol_price_diff_min_daily')
        self.addDailyData(self.max_vol_price_diff_min_pm, 'fguo_ywang.max_vol_price_diff_min_pm')
        self.addDailyData(self.max_vol_price_diff_skew_am, 'fguo_ywang.max_vol_price_diff_skew_am')
        self.addDailyData(self.max_vol_price_diff_skew_daily, 'fguo_ywang.max_vol_price_diff_skew_daily')
        self.addDailyData(self.max_vol_price_diff_skew_pm, 'fguo_ywang.max_vol_price_diff_skew_pm')
        self.addDailyData(self.max_vol_price_diff_var_am, 'fguo_ywang.max_vol_price_diff_var_am')
        self.addDailyData(self.max_vol_price_diff_var_daily, 'fguo_ywang.max_vol_price_diff_var_daily')
        self.addDailyData(self.max_vol_price_diff_var_pm, 'fguo_ywang.max_vol_price_diff_var_pm')
        self.addDailyData(self.max_vol_price_rate_kurt_am, 'fguo_ywang.max_vol_price_rate_kurt_am')
        self.addDailyData(self.max_vol_price_rate_kurt_daily, 'fguo_ywang.max_vol_price_rate_kurt_daily')
        self.addDailyData(self.max_vol_price_rate_kurt_pm, 'fguo_ywang.max_vol_price_rate_kurt_pm')
        self.addDailyData(self.max_vol_price_rate_max_am, 'fguo_ywang.max_vol_price_rate_max_am')
        self.addDailyData(self.max_vol_price_rate_max_daily, 'fguo_ywang.max_vol_price_rate_max_daily')
        self.addDailyData(self.max_vol_price_rate_max_pm, 'fguo_ywang.max_vol_price_rate_max_pm')
        self.addDailyData(self.max_vol_price_rate_mean_am, 'fguo_ywang.max_vol_price_rate_mean_am')
        self.addDailyData(self.max_vol_price_rate_mean_daily, 'fguo_ywang.max_vol_price_rate_mean_daily')
        self.addDailyData(self.max_vol_price_rate_mean_pm, 'fguo_ywang.max_vol_price_rate_mean_pm')
        self.addDailyData(self.max_vol_price_rate_min_am, 'fguo_ywang.max_vol_price_rate_min_am')
        self.addDailyData(self.max_vol_price_rate_min_daily, 'fguo_ywang.max_vol_price_rate_min_daily')
        self.addDailyData(self.max_vol_price_rate_min_pm, 'fguo_ywang.max_vol_price_rate_min_pm')
        self.addDailyData(self.max_vol_price_rate_skew_am, 'fguo_ywang.max_vol_price_rate_skew_am')
        self.addDailyData(self.max_vol_price_rate_skew_daily, 'fguo_ywang.max_vol_price_rate_skew_daily')
        self.addDailyData(self.max_vol_price_rate_skew_pm, 'fguo_ywang.max_vol_price_rate_skew_pm')
        self.addDailyData(self.max_vol_price_rate_var_am, 'fguo_ywang.max_vol_price_rate_var_am')
        self.addDailyData(self.max_vol_price_rate_var_daily, 'fguo_ywang.max_vol_price_rate_var_daily')
        self.addDailyData(self.max_vol_price_rate_var_pm, 'fguo_ywang.max_vol_price_rate_var_pm')
        self.addDailyData(self.mid_price_kurt_am, 'fguo_ywang.mid_price_kurt_am')
        self.addDailyData(self.mid_price_kurt_daily, 'fguo_ywang.mid_price_kurt_daily')
        self.addDailyData(self.mid_price_kurt_pm, 'fguo_ywang.mid_price_kurt_pm')
        self.addDailyData(self.mid_price_skew_am, 'fguo_ywang.mid_price_skew_am')
        self.addDailyData(self.mid_price_skew_daily, 'fguo_ywang.mid_price_skew_daily')
        self.addDailyData(self.mid_price_skew_pm, 'fguo_ywang.mid_price_skew_pm')
        self.addDailyData(self.mid_price_var_am, 'fguo_ywang.mid_price_var_am')
        self.addDailyData(self.mid_price_var_daily, 'fguo_ywang.mid_price_var_daily')
        self.addDailyData(self.mid_price_var_pm, 'fguo_ywang.mid_price_var_pm')
        self.addDailyData(self.s123_vol_ratio_kurt_am, 'fguo_ywang.s123_vol_ratio_kurt_am')
        self.addDailyData(self.s123_vol_ratio_kurt_daily, 'fguo_ywang.s123_vol_ratio_kurt_daily')
        self.addDailyData(self.s123_vol_ratio_kurt_pm, 'fguo_ywang.s123_vol_ratio_kurt_pm')
        self.addDailyData(self.s123_vol_ratio_max_am, 'fguo_ywang.s123_vol_ratio_max_am')
        self.addDailyData(self.s123_vol_ratio_max_daily, 'fguo_ywang.s123_vol_ratio_max_daily')
        self.addDailyData(self.s123_vol_ratio_max_pm, 'fguo_ywang.s123_vol_ratio_max_pm')
        self.addDailyData(self.s123_vol_ratio_mean_am, 'fguo_ywang.s123_vol_ratio_mean_am')
        self.addDailyData(self.s123_vol_ratio_mean_daily, 'fguo_ywang.s123_vol_ratio_mean_daily')
        self.addDailyData(self.s123_vol_ratio_mean_pm, 'fguo_ywang.s123_vol_ratio_mean_pm')
        self.addDailyData(self.s123_vol_ratio_min_am, 'fguo_ywang.s123_vol_ratio_min_am')
        self.addDailyData(self.s123_vol_ratio_min_daily, 'fguo_ywang.s123_vol_ratio_min_daily')
        self.addDailyData(self.s123_vol_ratio_min_pm, 'fguo_ywang.s123_vol_ratio_min_pm')
        self.addDailyData(self.s123_vol_ratio_skew_am, 'fguo_ywang.s123_vol_ratio_skew_am')
        self.addDailyData(self.s123_vol_ratio_skew_daily, 'fguo_ywang.s123_vol_ratio_skew_daily')
        self.addDailyData(self.s123_vol_ratio_skew_pm, 'fguo_ywang.s123_vol_ratio_skew_pm')
        self.addDailyData(self.s123_vol_ratio_var_am, 'fguo_ywang.s123_vol_ratio_var_am')
        self.addDailyData(self.s123_vol_ratio_var_daily, 'fguo_ywang.s123_vol_ratio_var_daily')
        self.addDailyData(self.s123_vol_ratio_var_pm, 'fguo_ywang.s123_vol_ratio_var_pm')
        self.addDailyData(self.s1_vol_ratio_kurt_am, 'fguo_ywang.s1_vol_ratio_kurt_am')
        self.addDailyData(self.s1_vol_ratio_kurt_daily, 'fguo_ywang.s1_vol_ratio_kurt_daily')
        self.addDailyData(self.s1_vol_ratio_kurt_pm, 'fguo_ywang.s1_vol_ratio_kurt_pm')
        self.addDailyData(self.s1_vol_ratio_max_am, 'fguo_ywang.s1_vol_ratio_max_am')
        self.addDailyData(self.s1_vol_ratio_max_daily, 'fguo_ywang.s1_vol_ratio_max_daily')
        self.addDailyData(self.s1_vol_ratio_max_pm, 'fguo_ywang.s1_vol_ratio_max_pm')
        self.addDailyData(self.s1_vol_ratio_mean_am, 'fguo_ywang.s1_vol_ratio_mean_am')
        self.addDailyData(self.s1_vol_ratio_mean_daily, 'fguo_ywang.s1_vol_ratio_mean_daily')
        self.addDailyData(self.s1_vol_ratio_mean_pm, 'fguo_ywang.s1_vol_ratio_mean_pm')
        self.addDailyData(self.s1_vol_ratio_min_am, 'fguo_ywang.s1_vol_ratio_min_am')
        self.addDailyData(self.s1_vol_ratio_min_daily, 'fguo_ywang.s1_vol_ratio_min_daily')
        self.addDailyData(self.s1_vol_ratio_min_pm, 'fguo_ywang.s1_vol_ratio_min_pm')
        self.addDailyData(self.s1_vol_ratio_skew_am, 'fguo_ywang.s1_vol_ratio_skew_am')
        self.addDailyData(self.s1_vol_ratio_skew_daily, 'fguo_ywang.s1_vol_ratio_skew_daily')
        self.addDailyData(self.s1_vol_ratio_skew_pm, 'fguo_ywang.s1_vol_ratio_skew_pm')
        self.addDailyData(self.s1_vol_ratio_var_am, 'fguo_ywang.s1_vol_ratio_var_am')
        self.addDailyData(self.s1_vol_ratio_var_daily, 'fguo_ywang.s1_vol_ratio_var_daily')
        self.addDailyData(self.s1_vol_ratio_var_pm, 'fguo_ywang.s1_vol_ratio_var_pm')
        self.addDailyData(self.s5_b1_vol_diff_kurt_am, 'fguo_ywang.s5_b1_vol_diff_kurt_am')
        self.addDailyData(self.s5_b1_vol_diff_kurt_daily, 'fguo_ywang.s5_b1_vol_diff_kurt_daily')
        self.addDailyData(self.s5_b1_vol_diff_kurt_pm, 'fguo_ywang.s5_b1_vol_diff_kurt_pm')
        self.addDailyData(self.s5_b1_vol_diff_max_am, 'fguo_ywang.s5_b1_vol_diff_max_am')
        self.addDailyData(self.s5_b1_vol_diff_max_daily, 'fguo_ywang.s5_b1_vol_diff_max_daily')
        self.addDailyData(self.s5_b1_vol_diff_max_pm, 'fguo_ywang.s5_b1_vol_diff_max_pm')
        self.addDailyData(self.s5_b1_vol_diff_mean_am, 'fguo_ywang.s5_b1_vol_diff_mean_am')
        self.addDailyData(self.s5_b1_vol_diff_mean_daily, 'fguo_ywang.s5_b1_vol_diff_mean_daily')
        self.addDailyData(self.s5_b1_vol_diff_mean_pm, 'fguo_ywang.s5_b1_vol_diff_mean_pm')
        self.addDailyData(self.s5_b1_vol_diff_min_am, 'fguo_ywang.s5_b1_vol_diff_min_am')
        self.addDailyData(self.s5_b1_vol_diff_min_daily, 'fguo_ywang.s5_b1_vol_diff_min_daily')
        self.addDailyData(self.s5_b1_vol_diff_min_pm, 'fguo_ywang.s5_b1_vol_diff_min_pm')
        self.addDailyData(self.s5_b1_vol_diff_skew_am, 'fguo_ywang.s5_b1_vol_diff_skew_am')
        self.addDailyData(self.s5_b1_vol_diff_skew_daily, 'fguo_ywang.s5_b1_vol_diff_skew_daily')
        self.addDailyData(self.s5_b1_vol_diff_skew_pm, 'fguo_ywang.s5_b1_vol_diff_skew_pm')
        self.addDailyData(self.s5_b1_vol_diff_var_am, 'fguo_ywang.s5_b1_vol_diff_var_am')
        self.addDailyData(self.s5_b1_vol_diff_var_daily, 'fguo_ywang.s5_b1_vol_diff_var_daily')
        self.addDailyData(self.s5_b1_vol_diff_var_pm, 'fguo_ywang.s5_b1_vol_diff_var_pm')
        self.addDailyData(self.s_avg_spread_kurt_am, 'fguo_ywang.s_avg_spread_kurt_am')
        self.addDailyData(self.s_avg_spread_kurt_daily, 'fguo_ywang.s_avg_spread_kurt_daily')
        self.addDailyData(self.s_avg_spread_kurt_pm, 'fguo_ywang.s_avg_spread_kurt_pm')
        self.addDailyData(self.s_avg_spread_max_am, 'fguo_ywang.s_avg_spread_max_am')
        self.addDailyData(self.s_avg_spread_max_daily, 'fguo_ywang.s_avg_spread_max_daily')
        self.addDailyData(self.s_avg_spread_max_pm, 'fguo_ywang.s_avg_spread_max_pm')
        self.addDailyData(self.s_avg_spread_mean_am, 'fguo_ywang.s_avg_spread_mean_am')
        self.addDailyData(self.s_avg_spread_mean_daily, 'fguo_ywang.s_avg_spread_mean_daily')
        self.addDailyData(self.s_avg_spread_mean_pm, 'fguo_ywang.s_avg_spread_mean_pm')
        self.addDailyData(self.s_avg_spread_min_am, 'fguo_ywang.s_avg_spread_min_am')
        self.addDailyData(self.s_avg_spread_min_daily, 'fguo_ywang.s_avg_spread_min_daily')
        self.addDailyData(self.s_avg_spread_min_pm, 'fguo_ywang.s_avg_spread_min_pm')
        self.addDailyData(self.s_avg_spread_skew_am, 'fguo_ywang.s_avg_spread_skew_am')
        self.addDailyData(self.s_avg_spread_skew_daily, 'fguo_ywang.s_avg_spread_skew_daily')
        self.addDailyData(self.s_avg_spread_skew_pm, 'fguo_ywang.s_avg_spread_skew_pm')
        self.addDailyData(self.s_avg_spread_var_am, 'fguo_ywang.s_avg_spread_var_am')
        self.addDailyData(self.s_avg_spread_var_daily, 'fguo_ywang.s_avg_spread_var_daily')
        self.addDailyData(self.s_avg_spread_var_pm, 'fguo_ywang.s_avg_spread_var_pm')
        self.addDailyData(self.s_depth_spread_kurt_am, 'fguo_ywang.s_depth_spread_kurt_am')
        self.addDailyData(self.s_depth_spread_kurt_daily, 'fguo_ywang.s_depth_spread_kurt_daily')
        self.addDailyData(self.s_depth_spread_kurt_pm, 'fguo_ywang.s_depth_spread_kurt_pm')
        self.addDailyData(self.s_depth_spread_mean_am, 'fguo_ywang.s_depth_spread_mean_am')
        self.addDailyData(self.s_depth_spread_mean_pm, 'fguo_ywang.s_depth_spread_mean_pm')
        self.addDailyData(self.s_depth_spread_skew_am, 'fguo_ywang.s_depth_spread_skew_am')
        self.addDailyData(self.s_depth_spread_skew_daily, 'fguo_ywang.s_depth_spread_skew_daily')
        self.addDailyData(self.s_depth_spread_skew_pm, 'fguo_ywang.s_depth_spread_skew_pm')
        self.addDailyData(self.s_depth_spread_var_am, 'fguo_ywang.s_depth_spread_var_am')
        self.addDailyData(self.s_depth_spread_var_daily, 'fguo_ywang.s_depth_spread_var_daily')
        self.addDailyData(self.s_depth_spread_var_pm, 'fguo_ywang.s_depth_spread_var_pm')
        self.addDailyData(self.s_max_vol_price_kurt_am, 'fguo_ywang.s_max_vol_price_kurt_am')
        self.addDailyData(self.s_max_vol_price_kurt_daily, 'fguo_ywang.s_max_vol_price_kurt_daily')
        self.addDailyData(self.s_max_vol_price_kurt_pm, 'fguo_ywang.s_max_vol_price_kurt_pm')
        self.addDailyData(self.s_max_vol_price_max_am, 'fguo_ywang.s_max_vol_price_max_am')
        self.addDailyData(self.s_max_vol_price_max_daily, 'fguo_ywang.s_max_vol_price_max_daily')
        self.addDailyData(self.s_max_vol_price_max_pm, 'fguo_ywang.s_max_vol_price_max_pm')
        self.addDailyData(self.s_max_vol_price_mean_am, 'fguo_ywang.s_max_vol_price_mean_am')
        self.addDailyData(self.s_max_vol_price_mean_daily, 'fguo_ywang.s_max_vol_price_mean_daily')
        self.addDailyData(self.s_max_vol_price_mean_pm, 'fguo_ywang.s_max_vol_price_mean_pm')
        self.addDailyData(self.s_max_vol_price_min_am, 'fguo_ywang.s_max_vol_price_min_am')
        self.addDailyData(self.s_max_vol_price_min_daily, 'fguo_ywang.s_max_vol_price_min_daily')
        self.addDailyData(self.s_max_vol_price_min_pm, 'fguo_ywang.s_max_vol_price_min_pm')
        self.addDailyData(self.s_max_vol_price_skew_am, 'fguo_ywang.s_max_vol_price_skew_am')
        self.addDailyData(self.s_max_vol_price_skew_daily, 'fguo_ywang.s_max_vol_price_skew_daily')
        self.addDailyData(self.s_max_vol_price_skew_pm, 'fguo_ywang.s_max_vol_price_skew_pm')
        self.addDailyData(self.s_max_vol_price_var_am, 'fguo_ywang.s_max_vol_price_var_am')
        self.addDailyData(self.s_max_vol_price_var_daily, 'fguo_ywang.s_max_vol_price_var_daily')
        self.addDailyData(self.s_max_vol_price_var_pm, 'fguo_ywang.s_max_vol_price_var_pm')
        self.addDailyData(self.s_vol_disp_kurt_am, 'fguo_ywang.s_vol_disp_kurt_am')
        self.addDailyData(self.s_vol_disp_kurt_daily, 'fguo_ywang.s_vol_disp_kurt_daily')
        self.addDailyData(self.s_vol_disp_kurt_pm, 'fguo_ywang.s_vol_disp_kurt_pm')
        self.addDailyData(self.s_vol_disp_max_am, 'fguo_ywang.s_vol_disp_max_am')
        self.addDailyData(self.s_vol_disp_max_daily, 'fguo_ywang.s_vol_disp_max_daily')
        self.addDailyData(self.s_vol_disp_max_pm, 'fguo_ywang.s_vol_disp_max_pm')
        self.addDailyData(self.s_vol_disp_mean_am, 'fguo_ywang.s_vol_disp_mean_am')
        self.addDailyData(self.s_vol_disp_mean_daily, 'fguo_ywang.s_vol_disp_mean_daily')
        self.addDailyData(self.s_vol_disp_mean_pm, 'fguo_ywang.s_vol_disp_mean_pm')
        self.addDailyData(self.s_vol_disp_min_am, 'fguo_ywang.s_vol_disp_min_am')
        self.addDailyData(self.s_vol_disp_min_daily, 'fguo_ywang.s_vol_disp_min_daily')
        self.addDailyData(self.s_vol_disp_min_pm, 'fguo_ywang.s_vol_disp_min_pm')
        self.addDailyData(self.s_vol_disp_skew_am, 'fguo_ywang.s_vol_disp_skew_am')
        self.addDailyData(self.s_vol_disp_skew_daily, 'fguo_ywang.s_vol_disp_skew_daily')
        self.addDailyData(self.s_vol_disp_skew_pm, 'fguo_ywang.s_vol_disp_skew_pm')
        self.addDailyData(self.s_vol_disp_var_am, 'fguo_ywang.s_vol_disp_var_am')
        self.addDailyData(self.s_vol_disp_var_daily, 'fguo_ywang.s_vol_disp_var_daily')
        self.addDailyData(self.s_vol_disp_var_pm, 'fguo_ywang.s_vol_disp_var_pm')
        self.addDailyData(self.s_vol_price_corr_kurt_am, 'fguo_ywang.s_vol_price_corr_kurt_am')
        self.addDailyData(self.s_vol_price_corr_kurt_daily, 'fguo_ywang.s_vol_price_corr_kurt_daily')
        self.addDailyData(self.s_vol_price_corr_kurt_pm, 'fguo_ywang.s_vol_price_corr_kurt_pm')
        self.addDailyData(self.s_vol_price_corr_max_am, 'fguo_ywang.s_vol_price_corr_max_am')
        self.addDailyData(self.s_vol_price_corr_max_daily, 'fguo_ywang.s_vol_price_corr_max_daily')
        self.addDailyData(self.s_vol_price_corr_max_pm, 'fguo_ywang.s_vol_price_corr_max_pm')
        self.addDailyData(self.s_vol_price_corr_mean_am, 'fguo_ywang.s_vol_price_corr_mean_am')
        self.addDailyData(self.s_vol_price_corr_mean_daily, 'fguo_ywang.s_vol_price_corr_mean_daily')
        self.addDailyData(self.s_vol_price_corr_mean_pm, 'fguo_ywang.s_vol_price_corr_mean_pm')
        self.addDailyData(self.s_vol_price_corr_min_am, 'fguo_ywang.s_vol_price_corr_min_am')
        self.addDailyData(self.s_vol_price_corr_min_daily, 'fguo_ywang.s_vol_price_corr_min_daily')
        self.addDailyData(self.s_vol_price_corr_min_pm, 'fguo_ywang.s_vol_price_corr_min_pm')
        self.addDailyData(self.s_vol_price_corr_skew_am, 'fguo_ywang.s_vol_price_corr_skew_am')
        self.addDailyData(self.s_vol_price_corr_skew_daily, 'fguo_ywang.s_vol_price_corr_skew_daily')
        self.addDailyData(self.s_vol_price_corr_skew_pm, 'fguo_ywang.s_vol_price_corr_skew_pm')
        self.addDailyData(self.s_vol_price_corr_var_am, 'fguo_ywang.s_vol_price_corr_var_am')
        self.addDailyData(self.s_vol_price_corr_var_daily, 'fguo_ywang.s_vol_price_corr_var_daily')
        self.addDailyData(self.s_vol_price_corr_var_pm, 'fguo_ywang.s_vol_price_corr_var_pm')
        self.addDailyData(self.spread_kurt_am, 'fguo_ywang.spread_kurt_am')
        self.addDailyData(self.spread_kurt_daily, 'fguo_ywang.spread_kurt_daily')
        self.addDailyData(self.spread_kurt_pm, 'fguo_ywang.spread_kurt_pm')
        self.addDailyData(self.spread_skew_am, 'fguo_ywang.spread_skew_am')
        self.addDailyData(self.spread_skew_daily, 'fguo_ywang.spread_skew_daily')
        self.addDailyData(self.spread_skew_pm, 'fguo_ywang.spread_skew_pm')
        self.addDailyData(self.spread_var_am, 'fguo_ywang.spread_var_am')
        self.addDailyData(self.spread_var_daily, 'fguo_ywang.spread_var_daily')
        self.addDailyData(self.spread_var_pm, 'fguo_ywang.spread_var_pm')
        self.addDailyData(self.weighted_spread_kurt_am, 'fguo_ywang.weighted_spread_kurt_am')
        self.addDailyData(self.weighted_spread_kurt_daily, 'fguo_ywang.weighted_spread_kurt_daily')
        self.addDailyData(self.weighted_spread_kurt_pm, 'fguo_ywang.weighted_spread_kurt_pm')
        self.addDailyData(self.weighted_spread_skew_am, 'fguo_ywang.weighted_spread_skew_am')
        self.addDailyData(self.weighted_spread_skew_daily, 'fguo_ywang.weighted_spread_skew_daily')
        self.addDailyData(self.weighted_spread_skew_pm, 'fguo_ywang.weighted_spread_skew_pm')
        self.addDailyData(self.weighted_spread_var_am, 'fguo_ywang.weighted_spread_var_am')
        self.addDailyData(self.weighted_spread_var_daily, 'fguo_ywang.weighted_spread_var_daily')
        self.addDailyData(self.weighted_spread_var_pm, 'fguo_ywang.weighted_spread_var_pm')
        return

    def loadDay(self, di):
        pass

