from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrSli0211(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.kline_amp_1m = NIO_MATRIX()
        self.kline_amp_30m = NIO_MATRIX()
        self.kline_amp_5m = NIO_MATRIX()
        self.kline_body_1m = NIO_MATRIX()
        self.kline_body_30m = NIO_MATRIX()
        self.kline_body_5m = NIO_MATRIX()
        self.kline_hongsangbing_1m = NIO_MATRIX()
        self.kline_hongsangbing_1m_kurt = NIO_MATRIX()
        self.kline_hongsangbing_1m_skew = NIO_MATRIX()
        self.kline_hongsangbing_1m_var = NIO_MATRIX()
        self.kline_hongsangbing_30m = NIO_MATRIX()
        self.kline_hongsangbing_30m_kurt = NIO_MATRIX()
        self.kline_hongsangbing_30m_skew = NIO_MATRIX()
        self.kline_hongsangbing_30m_var = NIO_MATRIX()
        self.kline_hongsangbing_5m = NIO_MATRIX()
        self.kline_hongsangbing_5m_kurt = NIO_MATRIX()
        self.kline_hongsangbing_5m_skew = NIO_MATRIX()
        self.kline_hongsangbing_5m_var = NIO_MATRIX()
        self.kline_huanghun_1m = NIO_MATRIX()
        self.kline_huanghun_1m_kurt = NIO_MATRIX()
        self.kline_huanghun_1m_skew = NIO_MATRIX()
        self.kline_huanghun_1m_var = NIO_MATRIX()
        self.kline_huanghun_30m = NIO_MATRIX()
        self.kline_huanghun_30m_kurt = NIO_MATRIX()
        self.kline_huanghun_30m_skew = NIO_MATRIX()
        self.kline_huanghun_30m_var = NIO_MATRIX()
        self.kline_huanghun_5m = NIO_MATRIX()
        self.kline_huanghun_5m_kurt = NIO_MATRIX()
        self.kline_huanghun_5m_skew = NIO_MATRIX()
        self.kline_huanghun_5m_var = NIO_MATRIX()
        self.kline_jiwang_1m = NIO_MATRIX()
        self.kline_jiwang_1m_kurt = NIO_MATRIX()
        self.kline_jiwang_1m_skew = NIO_MATRIX()
        self.kline_jiwang_1m_var = NIO_MATRIX()
        self.kline_jiwang_30m = NIO_MATRIX()
        self.kline_jiwang_30m_kurt = NIO_MATRIX()
        self.kline_jiwang_30m_skew = NIO_MATRIX()
        self.kline_jiwang_30m_var = NIO_MATRIX()
        self.kline_jiwang_5m = NIO_MATRIX()
        self.kline_jiwang_5m_kurt = NIO_MATRIX()
        self.kline_jiwang_5m_skew = NIO_MATRIX()
        self.kline_jiwang_5m_var = NIO_MATRIX()
        self.kline_lower_1m = NIO_MATRIX()
        self.kline_lower_30m = NIO_MATRIX()
        self.kline_lower_5m = NIO_MATRIX()
        self.kline_poxiaoxing_1m = NIO_MATRIX()
        self.kline_poxiaoxing_1m_kurt = NIO_MATRIX()
        self.kline_poxiaoxing_1m_skew = NIO_MATRIX()
        self.kline_poxiaoxing_1m_var = NIO_MATRIX()
        self.kline_poxiaoxing_30m = NIO_MATRIX()
        self.kline_poxiaoxing_30m_kurt = NIO_MATRIX()
        self.kline_poxiaoxing_30m_skew = NIO_MATRIX()
        self.kline_poxiaoxing_30m_var = NIO_MATRIX()
        self.kline_poxiaoxing_5m = NIO_MATRIX()
        self.kline_poxiaoxing_5m_kurt = NIO_MATRIX()
        self.kline_poxiaoxing_5m_skew = NIO_MATRIX()
        self.kline_poxiaoxing_5m_var = NIO_MATRIX()
        self.kline_qingpen_1m = NIO_MATRIX()
        self.kline_qingpen_1m_kurt = NIO_MATRIX()
        self.kline_qingpen_1m_skew = NIO_MATRIX()
        self.kline_qingpen_1m_var = NIO_MATRIX()
        self.kline_qingpen_30m = NIO_MATRIX()
        self.kline_qingpen_30m_kurt = NIO_MATRIX()
        self.kline_qingpen_30m_skew = NIO_MATRIX()
        self.kline_qingpen_30m_var = NIO_MATRIX()
        self.kline_qingpen_5m = NIO_MATRIX()
        self.kline_qingpen_5m_kurt = NIO_MATRIX()
        self.kline_qingpen_5m_skew = NIO_MATRIX()
        self.kline_qingpen_5m_var = NIO_MATRIX()
        self.kline_qiying_1m = NIO_MATRIX()
        self.kline_qiying_1m_kurt = NIO_MATRIX()
        self.kline_qiying_1m_skew = NIO_MATRIX()
        self.kline_qiying_1m_var = NIO_MATRIX()
        self.kline_qiying_30m = NIO_MATRIX()
        self.kline_qiying_30m_kurt = NIO_MATRIX()
        self.kline_qiying_30m_skew = NIO_MATRIX()
        self.kline_qiying_30m_var = NIO_MATRIX()
        self.kline_qiying_5m = NIO_MATRIX()
        self.kline_qiying_5m_kurt = NIO_MATRIX()
        self.kline_qiying_5m_skew = NIO_MATRIX()
        self.kline_qiying_5m_var = NIO_MATRIX()
        self.kline_sanzhiwuyang_1m = NIO_MATRIX()
        self.kline_sanzhiwuyang_1m_kurt = NIO_MATRIX()
        self.kline_sanzhiwuyang_1m_skew = NIO_MATRIX()
        self.kline_sanzhiwuyang_1m_var = NIO_MATRIX()
        self.kline_sanzhiwuyang_30m = NIO_MATRIX()
        self.kline_sanzhiwuyang_30m_kurt = NIO_MATRIX()
        self.kline_sanzhiwuyang_30m_skew = NIO_MATRIX()
        self.kline_sanzhiwuyang_30m_var = NIO_MATRIX()
        self.kline_sanzhiwuyang_5m = NIO_MATRIX()
        self.kline_sanzhiwuyang_5m_kurt = NIO_MATRIX()
        self.kline_sanzhiwuyang_5m_skew = NIO_MATRIX()
        self.kline_sanzhiwuyang_5m_var = NIO_MATRIX()
        self.kline_shooting_1m = NIO_MATRIX()
        self.kline_shooting_1m_kurt = NIO_MATRIX()
        self.kline_shooting_1m_skew = NIO_MATRIX()
        self.kline_shooting_1m_var = NIO_MATRIX()
        self.kline_shooting_30m = NIO_MATRIX()
        self.kline_shooting_30m_kurt = NIO_MATRIX()
        self.kline_shooting_30m_skew = NIO_MATRIX()
        self.kline_shooting_30m_var = NIO_MATRIX()
        self.kline_shooting_5m = NIO_MATRIX()
        self.kline_shooting_5m_kurt = NIO_MATRIX()
        self.kline_shooting_5m_skew = NIO_MATRIX()
        self.kline_shooting_5m_var = NIO_MATRIX()
        self.kline_shuangchui_1m = NIO_MATRIX()
        self.kline_shuangchui_1m_kurt = NIO_MATRIX()
        self.kline_shuangchui_1m_skew = NIO_MATRIX()
        self.kline_shuangchui_1m_var = NIO_MATRIX()
        self.kline_shuangchui_30m = NIO_MATRIX()
        self.kline_shuangchui_30m_kurt = NIO_MATRIX()
        self.kline_shuangchui_30m_skew = NIO_MATRIX()
        self.kline_shuangchui_30m_var = NIO_MATRIX()
        self.kline_shuangchui_5m = NIO_MATRIX()
        self.kline_shuangchui_5m_kurt = NIO_MATRIX()
        self.kline_shuangchui_5m_skew = NIO_MATRIX()
        self.kline_shuangchui_5m_var = NIO_MATRIX()
        self.kline_shuguang_1m = NIO_MATRIX()
        self.kline_shuguang_1m_kurt = NIO_MATRIX()
        self.kline_shuguang_1m_skew = NIO_MATRIX()
        self.kline_shuguang_1m_var = NIO_MATRIX()
        self.kline_shuguang_30m = NIO_MATRIX()
        self.kline_shuguang_30m_kurt = NIO_MATRIX()
        self.kline_shuguang_30m_skew = NIO_MATRIX()
        self.kline_shuguang_30m_var = NIO_MATRIX()
        self.kline_shuguang_5m = NIO_MATRIX()
        self.kline_shuguang_5m_kurt = NIO_MATRIX()
        self.kline_shuguang_5m_skew = NIO_MATRIX()
        self.kline_shuguang_5m_var = NIO_MATRIX()
        self.kline_upper_1m = NIO_MATRIX()
        self.kline_upper_30m = NIO_MATRIX()
        self.kline_upper_5m = NIO_MATRIX()
        self.kline_wuyun_1m = NIO_MATRIX()
        self.kline_wuyun_1m_kurt = NIO_MATRIX()
        self.kline_wuyun_1m_skew = NIO_MATRIX()
        self.kline_wuyun_1m_var = NIO_MATRIX()
        self.kline_wuyun_30m = NIO_MATRIX()
        self.kline_wuyun_30m_kurt = NIO_MATRIX()
        self.kline_wuyun_30m_skew = NIO_MATRIX()
        self.kline_wuyun_30m_var = NIO_MATRIX()
        self.kline_wuyun_5m = NIO_MATRIX()
        self.kline_wuyun_5m_kurt = NIO_MATRIX()
        self.kline_wuyun_5m_skew = NIO_MATRIX()
        self.kline_wuyun_5m_var = NIO_MATRIX()
        self.kline_xianren_1m = NIO_MATRIX()
        self.kline_xianren_1m_kurt = NIO_MATRIX()
        self.kline_xianren_1m_skew = NIO_MATRIX()
        self.kline_xianren_1m_var = NIO_MATRIX()
        self.kline_xianren_30m = NIO_MATRIX()
        self.kline_xianren_30m_kurt = NIO_MATRIX()
        self.kline_xianren_30m_skew = NIO_MATRIX()
        self.kline_xianren_30m_var = NIO_MATRIX()
        self.kline_xianren_5m = NIO_MATRIX()
        self.kline_xianren_5m_kurt = NIO_MATRIX()
        self.kline_xianren_5m_skew = NIO_MATRIX()
        self.kline_xianren_5m_var = NIO_MATRIX()
        self.kline_xuri_1m = NIO_MATRIX()
        self.kline_xuri_1m_kurt = NIO_MATRIX()
        self.kline_xuri_1m_skew = NIO_MATRIX()
        self.kline_xuri_1m_var = NIO_MATRIX()
        self.kline_xuri_30m = NIO_MATRIX()
        self.kline_xuri_30m_kurt = NIO_MATRIX()
        self.kline_xuri_30m_skew = NIO_MATRIX()
        self.kline_xuri_30m_var = NIO_MATRIX()
        self.kline_xuri_5m = NIO_MATRIX()
        self.kline_xuri_5m_kurt = NIO_MATRIX()
        self.kline_xuri_5m_skew = NIO_MATRIX()
        self.kline_xuri_5m_var = NIO_MATRIX()
        self.kline_yangbao_1m = NIO_MATRIX()
        self.kline_yangbao_1m_kurt = NIO_MATRIX()
        self.kline_yangbao_1m_skew = NIO_MATRIX()
        self.kline_yangbao_1m_var = NIO_MATRIX()
        self.kline_yangbao_30m = NIO_MATRIX()
        self.kline_yangbao_30m_kurt = NIO_MATRIX()
        self.kline_yangbao_30m_skew = NIO_MATRIX()
        self.kline_yangbao_30m_var = NIO_MATRIX()
        self.kline_yangbao_5m = NIO_MATRIX()
        self.kline_yangbao_5m_kurt = NIO_MATRIX()
        self.kline_yangbao_5m_skew = NIO_MATRIX()
        self.kline_yangbao_5m_var = NIO_MATRIX()
        self.kline_yinbao_1m = NIO_MATRIX()
        self.kline_yinbao_1m_kurt = NIO_MATRIX()
        self.kline_yinbao_1m_skew = NIO_MATRIX()
        self.kline_yinbao_1m_var = NIO_MATRIX()
        self.kline_yinbao_30m = NIO_MATRIX()
        self.kline_yinbao_30m_kurt = NIO_MATRIX()
        self.kline_yinbao_30m_skew = NIO_MATRIX()
        self.kline_yinbao_30m_var = NIO_MATRIX()
        self.kline_yinbao_5m = NIO_MATRIX()
        self.kline_yinbao_5m_kurt = NIO_MATRIX()
        self.kline_yinbao_5m_skew = NIO_MATRIX()
        self.kline_yinbao_5m_var = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.kline_amp_1m, 'sli_0211.kline_amp_1m')
        self.addDailyData(self.kline_amp_30m, 'sli_0211.kline_amp_30m')
        self.addDailyData(self.kline_amp_5m, 'sli_0211.kline_amp_5m')
        self.addDailyData(self.kline_body_1m, 'sli_0211.kline_body_1m')
        self.addDailyData(self.kline_body_30m, 'sli_0211.kline_body_30m')
        self.addDailyData(self.kline_body_5m, 'sli_0211.kline_body_5m')
        self.addDailyData(self.kline_hongsangbing_1m, 'sli_0211.kline_hongsangbing_1m')
        self.addDailyData(self.kline_hongsangbing_1m_kurt, 'sli_0211.kline_hongsangbing_1m_kurt')
        self.addDailyData(self.kline_hongsangbing_1m_skew, 'sli_0211.kline_hongsangbing_1m_skew')
        self.addDailyData(self.kline_hongsangbing_1m_var, 'sli_0211.kline_hongsangbing_1m_var')
        self.addDailyData(self.kline_hongsangbing_30m, 'sli_0211.kline_hongsangbing_30m')
        self.addDailyData(self.kline_hongsangbing_30m_kurt, 'sli_0211.kline_hongsangbing_30m_kurt')
        self.addDailyData(self.kline_hongsangbing_30m_skew, 'sli_0211.kline_hongsangbing_30m_skew')
        self.addDailyData(self.kline_hongsangbing_30m_var, 'sli_0211.kline_hongsangbing_30m_var')
        self.addDailyData(self.kline_hongsangbing_5m, 'sli_0211.kline_hongsangbing_5m')
        self.addDailyData(self.kline_hongsangbing_5m_kurt, 'sli_0211.kline_hongsangbing_5m_kurt')
        self.addDailyData(self.kline_hongsangbing_5m_skew, 'sli_0211.kline_hongsangbing_5m_skew')
        self.addDailyData(self.kline_hongsangbing_5m_var, 'sli_0211.kline_hongsangbing_5m_var')
        self.addDailyData(self.kline_huanghun_1m, 'sli_0211.kline_huanghun_1m')
        self.addDailyData(self.kline_huanghun_1m_kurt, 'sli_0211.kline_huanghun_1m_kurt')
        self.addDailyData(self.kline_huanghun_1m_skew, 'sli_0211.kline_huanghun_1m_skew')
        self.addDailyData(self.kline_huanghun_1m_var, 'sli_0211.kline_huanghun_1m_var')
        self.addDailyData(self.kline_huanghun_30m, 'sli_0211.kline_huanghun_30m')
        self.addDailyData(self.kline_huanghun_30m_kurt, 'sli_0211.kline_huanghun_30m_kurt')
        self.addDailyData(self.kline_huanghun_30m_skew, 'sli_0211.kline_huanghun_30m_skew')
        self.addDailyData(self.kline_huanghun_30m_var, 'sli_0211.kline_huanghun_30m_var')
        self.addDailyData(self.kline_huanghun_5m, 'sli_0211.kline_huanghun_5m')
        self.addDailyData(self.kline_huanghun_5m_kurt, 'sli_0211.kline_huanghun_5m_kurt')
        self.addDailyData(self.kline_huanghun_5m_skew, 'sli_0211.kline_huanghun_5m_skew')
        self.addDailyData(self.kline_huanghun_5m_var, 'sli_0211.kline_huanghun_5m_var')
        self.addDailyData(self.kline_jiwang_1m, 'sli_0211.kline_jiwang_1m')
        self.addDailyData(self.kline_jiwang_1m_kurt, 'sli_0211.kline_jiwang_1m_kurt')
        self.addDailyData(self.kline_jiwang_1m_skew, 'sli_0211.kline_jiwang_1m_skew')
        self.addDailyData(self.kline_jiwang_1m_var, 'sli_0211.kline_jiwang_1m_var')
        self.addDailyData(self.kline_jiwang_30m, 'sli_0211.kline_jiwang_30m')
        self.addDailyData(self.kline_jiwang_30m_kurt, 'sli_0211.kline_jiwang_30m_kurt')
        self.addDailyData(self.kline_jiwang_30m_skew, 'sli_0211.kline_jiwang_30m_skew')
        self.addDailyData(self.kline_jiwang_30m_var, 'sli_0211.kline_jiwang_30m_var')
        self.addDailyData(self.kline_jiwang_5m, 'sli_0211.kline_jiwang_5m')
        self.addDailyData(self.kline_jiwang_5m_kurt, 'sli_0211.kline_jiwang_5m_kurt')
        self.addDailyData(self.kline_jiwang_5m_skew, 'sli_0211.kline_jiwang_5m_skew')
        self.addDailyData(self.kline_jiwang_5m_var, 'sli_0211.kline_jiwang_5m_var')
        self.addDailyData(self.kline_lower_1m, 'sli_0211.kline_lower_1m')
        self.addDailyData(self.kline_lower_30m, 'sli_0211.kline_lower_30m')
        self.addDailyData(self.kline_lower_5m, 'sli_0211.kline_lower_5m')
        self.addDailyData(self.kline_poxiaoxing_1m, 'sli_0211.kline_poxiaoxing_1m')
        self.addDailyData(self.kline_poxiaoxing_1m_kurt, 'sli_0211.kline_poxiaoxing_1m_kurt')
        self.addDailyData(self.kline_poxiaoxing_1m_skew, 'sli_0211.kline_poxiaoxing_1m_skew')
        self.addDailyData(self.kline_poxiaoxing_1m_var, 'sli_0211.kline_poxiaoxing_1m_var')
        self.addDailyData(self.kline_poxiaoxing_30m, 'sli_0211.kline_poxiaoxing_30m')
        self.addDailyData(self.kline_poxiaoxing_30m_kurt, 'sli_0211.kline_poxiaoxing_30m_kurt')
        self.addDailyData(self.kline_poxiaoxing_30m_skew, 'sli_0211.kline_poxiaoxing_30m_skew')
        self.addDailyData(self.kline_poxiaoxing_30m_var, 'sli_0211.kline_poxiaoxing_30m_var')
        self.addDailyData(self.kline_poxiaoxing_5m, 'sli_0211.kline_poxiaoxing_5m')
        self.addDailyData(self.kline_poxiaoxing_5m_kurt, 'sli_0211.kline_poxiaoxing_5m_kurt')
        self.addDailyData(self.kline_poxiaoxing_5m_skew, 'sli_0211.kline_poxiaoxing_5m_skew')
        self.addDailyData(self.kline_poxiaoxing_5m_var, 'sli_0211.kline_poxiaoxing_5m_var')
        self.addDailyData(self.kline_qingpen_1m, 'sli_0211.kline_qingpen_1m')
        self.addDailyData(self.kline_qingpen_1m_kurt, 'sli_0211.kline_qingpen_1m_kurt')
        self.addDailyData(self.kline_qingpen_1m_skew, 'sli_0211.kline_qingpen_1m_skew')
        self.addDailyData(self.kline_qingpen_1m_var, 'sli_0211.kline_qingpen_1m_var')
        self.addDailyData(self.kline_qingpen_30m, 'sli_0211.kline_qingpen_30m')
        self.addDailyData(self.kline_qingpen_30m_kurt, 'sli_0211.kline_qingpen_30m_kurt')
        self.addDailyData(self.kline_qingpen_30m_skew, 'sli_0211.kline_qingpen_30m_skew')
        self.addDailyData(self.kline_qingpen_30m_var, 'sli_0211.kline_qingpen_30m_var')
        self.addDailyData(self.kline_qingpen_5m, 'sli_0211.kline_qingpen_5m')
        self.addDailyData(self.kline_qingpen_5m_kurt, 'sli_0211.kline_qingpen_5m_kurt')
        self.addDailyData(self.kline_qingpen_5m_skew, 'sli_0211.kline_qingpen_5m_skew')
        self.addDailyData(self.kline_qingpen_5m_var, 'sli_0211.kline_qingpen_5m_var')
        self.addDailyData(self.kline_qiying_1m, 'sli_0211.kline_qiying_1m')
        self.addDailyData(self.kline_qiying_1m_kurt, 'sli_0211.kline_qiying_1m_kurt')
        self.addDailyData(self.kline_qiying_1m_skew, 'sli_0211.kline_qiying_1m_skew')
        self.addDailyData(self.kline_qiying_1m_var, 'sli_0211.kline_qiying_1m_var')
        self.addDailyData(self.kline_qiying_30m, 'sli_0211.kline_qiying_30m')
        self.addDailyData(self.kline_qiying_30m_kurt, 'sli_0211.kline_qiying_30m_kurt')
        self.addDailyData(self.kline_qiying_30m_skew, 'sli_0211.kline_qiying_30m_skew')
        self.addDailyData(self.kline_qiying_30m_var, 'sli_0211.kline_qiying_30m_var')
        self.addDailyData(self.kline_qiying_5m, 'sli_0211.kline_qiying_5m')
        self.addDailyData(self.kline_qiying_5m_kurt, 'sli_0211.kline_qiying_5m_kurt')
        self.addDailyData(self.kline_qiying_5m_skew, 'sli_0211.kline_qiying_5m_skew')
        self.addDailyData(self.kline_qiying_5m_var, 'sli_0211.kline_qiying_5m_var')
        self.addDailyData(self.kline_sanzhiwuyang_1m, 'sli_0211.kline_sanzhiwuyang_1m')
        self.addDailyData(self.kline_sanzhiwuyang_1m_kurt, 'sli_0211.kline_sanzhiwuyang_1m_kurt')
        self.addDailyData(self.kline_sanzhiwuyang_1m_skew, 'sli_0211.kline_sanzhiwuyang_1m_skew')
        self.addDailyData(self.kline_sanzhiwuyang_1m_var, 'sli_0211.kline_sanzhiwuyang_1m_var')
        self.addDailyData(self.kline_sanzhiwuyang_30m, 'sli_0211.kline_sanzhiwuyang_30m')
        self.addDailyData(self.kline_sanzhiwuyang_30m_kurt, 'sli_0211.kline_sanzhiwuyang_30m_kurt')
        self.addDailyData(self.kline_sanzhiwuyang_30m_skew, 'sli_0211.kline_sanzhiwuyang_30m_skew')
        self.addDailyData(self.kline_sanzhiwuyang_30m_var, 'sli_0211.kline_sanzhiwuyang_30m_var')
        self.addDailyData(self.kline_sanzhiwuyang_5m, 'sli_0211.kline_sanzhiwuyang_5m')
        self.addDailyData(self.kline_sanzhiwuyang_5m_kurt, 'sli_0211.kline_sanzhiwuyang_5m_kurt')
        self.addDailyData(self.kline_sanzhiwuyang_5m_skew, 'sli_0211.kline_sanzhiwuyang_5m_skew')
        self.addDailyData(self.kline_sanzhiwuyang_5m_var, 'sli_0211.kline_sanzhiwuyang_5m_var')
        self.addDailyData(self.kline_shooting_1m, 'sli_0211.kline_shooting_1m')
        self.addDailyData(self.kline_shooting_1m_kurt, 'sli_0211.kline_shooting_1m_kurt')
        self.addDailyData(self.kline_shooting_1m_skew, 'sli_0211.kline_shooting_1m_skew')
        self.addDailyData(self.kline_shooting_1m_var, 'sli_0211.kline_shooting_1m_var')
        self.addDailyData(self.kline_shooting_30m, 'sli_0211.kline_shooting_30m')
        self.addDailyData(self.kline_shooting_30m_kurt, 'sli_0211.kline_shooting_30m_kurt')
        self.addDailyData(self.kline_shooting_30m_skew, 'sli_0211.kline_shooting_30m_skew')
        self.addDailyData(self.kline_shooting_30m_var, 'sli_0211.kline_shooting_30m_var')
        self.addDailyData(self.kline_shooting_5m, 'sli_0211.kline_shooting_5m')
        self.addDailyData(self.kline_shooting_5m_kurt, 'sli_0211.kline_shooting_5m_kurt')
        self.addDailyData(self.kline_shooting_5m_skew, 'sli_0211.kline_shooting_5m_skew')
        self.addDailyData(self.kline_shooting_5m_var, 'sli_0211.kline_shooting_5m_var')
        self.addDailyData(self.kline_shuangchui_1m, 'sli_0211.kline_shuangchui_1m')
        self.addDailyData(self.kline_shuangchui_1m_kurt, 'sli_0211.kline_shuangchui_1m_kurt')
        self.addDailyData(self.kline_shuangchui_1m_skew, 'sli_0211.kline_shuangchui_1m_skew')
        self.addDailyData(self.kline_shuangchui_1m_var, 'sli_0211.kline_shuangchui_1m_var')
        self.addDailyData(self.kline_shuangchui_30m, 'sli_0211.kline_shuangchui_30m')
        self.addDailyData(self.kline_shuangchui_30m_kurt, 'sli_0211.kline_shuangchui_30m_kurt')
        self.addDailyData(self.kline_shuangchui_30m_skew, 'sli_0211.kline_shuangchui_30m_skew')
        self.addDailyData(self.kline_shuangchui_30m_var, 'sli_0211.kline_shuangchui_30m_var')
        self.addDailyData(self.kline_shuangchui_5m, 'sli_0211.kline_shuangchui_5m')
        self.addDailyData(self.kline_shuangchui_5m_kurt, 'sli_0211.kline_shuangchui_5m_kurt')
        self.addDailyData(self.kline_shuangchui_5m_skew, 'sli_0211.kline_shuangchui_5m_skew')
        self.addDailyData(self.kline_shuangchui_5m_var, 'sli_0211.kline_shuangchui_5m_var')
        self.addDailyData(self.kline_shuguang_1m, 'sli_0211.kline_shuguang_1m')
        self.addDailyData(self.kline_shuguang_1m_kurt, 'sli_0211.kline_shuguang_1m_kurt')
        self.addDailyData(self.kline_shuguang_1m_skew, 'sli_0211.kline_shuguang_1m_skew')
        self.addDailyData(self.kline_shuguang_1m_var, 'sli_0211.kline_shuguang_1m_var')
        self.addDailyData(self.kline_shuguang_30m, 'sli_0211.kline_shuguang_30m')
        self.addDailyData(self.kline_shuguang_30m_kurt, 'sli_0211.kline_shuguang_30m_kurt')
        self.addDailyData(self.kline_shuguang_30m_skew, 'sli_0211.kline_shuguang_30m_skew')
        self.addDailyData(self.kline_shuguang_30m_var, 'sli_0211.kline_shuguang_30m_var')
        self.addDailyData(self.kline_shuguang_5m, 'sli_0211.kline_shuguang_5m')
        self.addDailyData(self.kline_shuguang_5m_kurt, 'sli_0211.kline_shuguang_5m_kurt')
        self.addDailyData(self.kline_shuguang_5m_skew, 'sli_0211.kline_shuguang_5m_skew')
        self.addDailyData(self.kline_shuguang_5m_var, 'sli_0211.kline_shuguang_5m_var')
        self.addDailyData(self.kline_upper_1m, 'sli_0211.kline_upper_1m')
        self.addDailyData(self.kline_upper_30m, 'sli_0211.kline_upper_30m')
        self.addDailyData(self.kline_upper_5m, 'sli_0211.kline_upper_5m')
        self.addDailyData(self.kline_wuyun_1m, 'sli_0211.kline_wuyun_1m')
        self.addDailyData(self.kline_wuyun_1m_kurt, 'sli_0211.kline_wuyun_1m_kurt')
        self.addDailyData(self.kline_wuyun_1m_skew, 'sli_0211.kline_wuyun_1m_skew')
        self.addDailyData(self.kline_wuyun_1m_var, 'sli_0211.kline_wuyun_1m_var')
        self.addDailyData(self.kline_wuyun_30m, 'sli_0211.kline_wuyun_30m')
        self.addDailyData(self.kline_wuyun_30m_kurt, 'sli_0211.kline_wuyun_30m_kurt')
        self.addDailyData(self.kline_wuyun_30m_skew, 'sli_0211.kline_wuyun_30m_skew')
        self.addDailyData(self.kline_wuyun_30m_var, 'sli_0211.kline_wuyun_30m_var')
        self.addDailyData(self.kline_wuyun_5m, 'sli_0211.kline_wuyun_5m')
        self.addDailyData(self.kline_wuyun_5m_kurt, 'sli_0211.kline_wuyun_5m_kurt')
        self.addDailyData(self.kline_wuyun_5m_skew, 'sli_0211.kline_wuyun_5m_skew')
        self.addDailyData(self.kline_wuyun_5m_var, 'sli_0211.kline_wuyun_5m_var')
        self.addDailyData(self.kline_xianren_1m, 'sli_0211.kline_xianren_1m')
        self.addDailyData(self.kline_xianren_1m_kurt, 'sli_0211.kline_xianren_1m_kurt')
        self.addDailyData(self.kline_xianren_1m_skew, 'sli_0211.kline_xianren_1m_skew')
        self.addDailyData(self.kline_xianren_1m_var, 'sli_0211.kline_xianren_1m_var')
        self.addDailyData(self.kline_xianren_30m, 'sli_0211.kline_xianren_30m')
        self.addDailyData(self.kline_xianren_30m_kurt, 'sli_0211.kline_xianren_30m_kurt')
        self.addDailyData(self.kline_xianren_30m_skew, 'sli_0211.kline_xianren_30m_skew')
        self.addDailyData(self.kline_xianren_30m_var, 'sli_0211.kline_xianren_30m_var')
        self.addDailyData(self.kline_xianren_5m, 'sli_0211.kline_xianren_5m')
        self.addDailyData(self.kline_xianren_5m_kurt, 'sli_0211.kline_xianren_5m_kurt')
        self.addDailyData(self.kline_xianren_5m_skew, 'sli_0211.kline_xianren_5m_skew')
        self.addDailyData(self.kline_xianren_5m_var, 'sli_0211.kline_xianren_5m_var')
        self.addDailyData(self.kline_xuri_1m, 'sli_0211.kline_xuri_1m')
        self.addDailyData(self.kline_xuri_1m_kurt, 'sli_0211.kline_xuri_1m_kurt')
        self.addDailyData(self.kline_xuri_1m_skew, 'sli_0211.kline_xuri_1m_skew')
        self.addDailyData(self.kline_xuri_1m_var, 'sli_0211.kline_xuri_1m_var')
        self.addDailyData(self.kline_xuri_30m, 'sli_0211.kline_xuri_30m')
        self.addDailyData(self.kline_xuri_30m_kurt, 'sli_0211.kline_xuri_30m_kurt')
        self.addDailyData(self.kline_xuri_30m_skew, 'sli_0211.kline_xuri_30m_skew')
        self.addDailyData(self.kline_xuri_30m_var, 'sli_0211.kline_xuri_30m_var')
        self.addDailyData(self.kline_xuri_5m, 'sli_0211.kline_xuri_5m')
        self.addDailyData(self.kline_xuri_5m_kurt, 'sli_0211.kline_xuri_5m_kurt')
        self.addDailyData(self.kline_xuri_5m_skew, 'sli_0211.kline_xuri_5m_skew')
        self.addDailyData(self.kline_xuri_5m_var, 'sli_0211.kline_xuri_5m_var')
        self.addDailyData(self.kline_yangbao_1m, 'sli_0211.kline_yangbao_1m')
        self.addDailyData(self.kline_yangbao_1m_kurt, 'sli_0211.kline_yangbao_1m_kurt')
        self.addDailyData(self.kline_yangbao_1m_skew, 'sli_0211.kline_yangbao_1m_skew')
        self.addDailyData(self.kline_yangbao_1m_var, 'sli_0211.kline_yangbao_1m_var')
        self.addDailyData(self.kline_yangbao_30m, 'sli_0211.kline_yangbao_30m')
        self.addDailyData(self.kline_yangbao_30m_kurt, 'sli_0211.kline_yangbao_30m_kurt')
        self.addDailyData(self.kline_yangbao_30m_skew, 'sli_0211.kline_yangbao_30m_skew')
        self.addDailyData(self.kline_yangbao_30m_var, 'sli_0211.kline_yangbao_30m_var')
        self.addDailyData(self.kline_yangbao_5m, 'sli_0211.kline_yangbao_5m')
        self.addDailyData(self.kline_yangbao_5m_kurt, 'sli_0211.kline_yangbao_5m_kurt')
        self.addDailyData(self.kline_yangbao_5m_skew, 'sli_0211.kline_yangbao_5m_skew')
        self.addDailyData(self.kline_yangbao_5m_var, 'sli_0211.kline_yangbao_5m_var')
        self.addDailyData(self.kline_yinbao_1m, 'sli_0211.kline_yinbao_1m')
        self.addDailyData(self.kline_yinbao_1m_kurt, 'sli_0211.kline_yinbao_1m_kurt')
        self.addDailyData(self.kline_yinbao_1m_skew, 'sli_0211.kline_yinbao_1m_skew')
        self.addDailyData(self.kline_yinbao_1m_var, 'sli_0211.kline_yinbao_1m_var')
        self.addDailyData(self.kline_yinbao_30m, 'sli_0211.kline_yinbao_30m')
        self.addDailyData(self.kline_yinbao_30m_kurt, 'sli_0211.kline_yinbao_30m_kurt')
        self.addDailyData(self.kline_yinbao_30m_skew, 'sli_0211.kline_yinbao_30m_skew')
        self.addDailyData(self.kline_yinbao_30m_var, 'sli_0211.kline_yinbao_30m_var')
        self.addDailyData(self.kline_yinbao_5m, 'sli_0211.kline_yinbao_5m')
        self.addDailyData(self.kline_yinbao_5m_kurt, 'sli_0211.kline_yinbao_5m_kurt')
        self.addDailyData(self.kline_yinbao_5m_skew, 'sli_0211.kline_yinbao_5m_skew')
        self.addDailyData(self.kline_yinbao_5m_var, 'sli_0211.kline_yinbao_5m_var')
        return

    def loadDay(self, di):
        pass
