from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrFguo6(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.amp_std = NIO_MATRIX()
        self.apd_std = NIO_MATRIX()
        self.apt_net_inflow_ratio = NIO_MATRIX()
        self.ar_v_corr = NIO_MATRIX()
        self.arpp = NIO_MATRIX()
        self.buy_intent_power_open = NIO_MATRIX()
        self.buy_intent_ratio_open = NIO_MATRIX()
        self.cdpdp = NIO_MATRIX()
        self.cdpp = NIO_MATRIX()
        self.cdvdp_v = NIO_MATRIX()
        self.cdvdv = NIO_MATRIX()
        self.cdvv = NIO_MATRIX()
        self.corr_vpl = NIO_MATRIX()
        self.ddp = NIO_MATRIX()
        self.dpn_dpn_corr = NIO_MATRIX()
        self.dpn_p_corr = NIO_MATRIX()
        self.dpp_dpp_corr = NIO_MATRIX()
        self.dpp_p_corr = NIO_MATRIX()
        self.dvn_dpn_corr = NIO_MATRIX()
        self.dvn_dpp_corr = NIO_MATRIX()
        self.dvn_dvn_corr = NIO_MATRIX()
        self.dvn_dvp_corr = NIO_MATRIX()
        self.dvn_v_corr = NIO_MATRIX()
        self.dvp_dpn_corr = NIO_MATRIX()
        self.dvp_dpp_corr = NIO_MATRIX()
        self.dvp_dvn_corr = NIO_MATRIX()
        self.dvp_dvp_corr = NIO_MATRIX()
        self.dvp_v_corr = NIO_MATRIX()
        self.fuzzy_vov = NIO_MATRIX()
        self.gmm_dmean = NIO_MATRIX()
        self.gmm_mean = NIO_MATRIX()
        self.inf_buy_ratio_close = NIO_MATRIX()
        self.inf_sell_ratio_open = NIO_MATRIX()
        self.int_ret_de1 = NIO_MATRIX()
        self.mci_a = NIO_MATRIX()
        self.mci_b = NIO_MATRIX()
        self.mci_imb = NIO_MATRIX()
        self.mild_ret_1h = NIO_MATRIX()
        self.min_ret_kurt_ave = NIO_MATRIX()
        self.min_ret_kurt_std = NIO_MATRIX()
        self.min_ret_skew_ave = NIO_MATRIX()
        self.min_ret_skew_std = NIO_MATRIX()
        self.min_ret_std_ave = NIO_MATRIX()
        self.min_ret_std_std = NIO_MATRIX()
        self.min_vol_kurt_ave = NIO_MATRIX()
        self.min_vol_kurt_std = NIO_MATRIX()
        self.min_vol_skew_ave = NIO_MATRIX()
        self.min_vol_skew_std = NIO_MATRIX()
        self.min_vol_std_ave = NIO_MATRIX()
        self.min_vol_std_std = NIO_MATRIX()
        self.mintval_mte = NIO_MATRIX()
        self.mintval_mts = NIO_MATRIX()
        self.mintval_qua = NIO_MATRIX()
        self.mintval_skew = NIO_MATRIX()
        self.mom_l = NIO_MATRIX()
        self.mpb = NIO_MATRIX()
        self.mpc_skew = NIO_MATRIX()
        self.net_buy_power_open = NIO_MATRIX()
        self.oval_mbsr = NIO_MATRIX()
        self.ovp = NIO_MATRIX()
        self.resiliency = NIO_MATRIX()
        self.ret_apt_c = NIO_MATRIX()
        self.ret_hvol_rev = NIO_MATRIX()
        self.ret_vol_c = NIO_MATRIX()
        self.ret_vol_w = NIO_MATRIX()
        self.rev_enhance = NIO_MATRIX()
        self.rsj_ratio = NIO_MATRIX()
        self.rv_corr = NIO_MATRIX()
        self.sectval_kurt = NIO_MATRIX()
        self.tr0h = NIO_MATRIX()
        self.up_vol_ratio = NIO_MATRIX()
        self.upp = NIO_MATRIX()
        self.v_ar_corr = NIO_MATRIX()
        self.var_ratio = NIO_MATRIX()
        self.voll = NIO_MATRIX()
        self.vpc_std = NIO_MATRIX()
        self.vwce = NIO_MATRIX()
        self.vwcr = NIO_MATRIX()
        self.vwcs = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.amp_std, 'fguo_0106.amp_std')
        self.addDailyData(self.apd_std, 'fguo_0106.apd_std')
        self.addDailyData(self.apt_net_inflow_ratio, 'fguo_0106.apt_net_inflow_ratio')
        self.addDailyData(self.ar_v_corr, 'fguo_0106.ar_v_corr')
        self.addDailyData(self.arpp, 'fguo_0106.arpp')
        self.addDailyData(self.buy_intent_power_open, 'fguo_0106.buy_intent_power_open')
        self.addDailyData(self.buy_intent_ratio_open, 'fguo_0106.buy_intent_ratio_open')
        self.addDailyData(self.cdpdp, 'fguo_0106.cdpdp')
        self.addDailyData(self.cdpp, 'fguo_0106.cdpp')
        self.addDailyData(self.cdvdp_v, 'fguo_0106.cdvdp_v')
        self.addDailyData(self.cdvdv, 'fguo_0106.cdvdv')
        self.addDailyData(self.cdvv, 'fguo_0106.cdvv')
        self.addDailyData(self.corr_vpl, 'fguo_0106.corr_vpl')
        self.addDailyData(self.ddp, 'fguo_0106.ddp')
        self.addDailyData(self.dpn_dpn_corr, 'fguo_0106.dpn_dpn_corr')
        self.addDailyData(self.dpn_p_corr, 'fguo_0106.dpn_p_corr')
        self.addDailyData(self.dpp_dpp_corr, 'fguo_0106.dpp_dpp_corr')
        self.addDailyData(self.dpp_p_corr, 'fguo_0106.dpp_p_corr')
        self.addDailyData(self.dvn_dpn_corr, 'fguo_0106.dvn_dpn_corr')
        self.addDailyData(self.dvn_dpp_corr, 'fguo_0106.dvn_dpp_corr')
        self.addDailyData(self.dvn_dvn_corr, 'fguo_0106.dvn_dvn_corr')
        self.addDailyData(self.dvn_dvp_corr, 'fguo_0106.dvn_dvp_corr')
        self.addDailyData(self.dvn_v_corr, 'fguo_0106.dvn_v_corr')
        self.addDailyData(self.dvp_dpn_corr, 'fguo_0106.dvp_dpn_corr')
        self.addDailyData(self.dvp_dpp_corr, 'fguo_0106.dvp_dpp_corr')
        self.addDailyData(self.dvp_dvn_corr, 'fguo_0106.dvp_dvn_corr')
        self.addDailyData(self.dvp_dvp_corr, 'fguo_0106.dvp_dvp_corr')
        self.addDailyData(self.dvp_v_corr, 'fguo_0106.dvp_v_corr')
        self.addDailyData(self.fuzzy_vov, 'fguo_0106.fuzzy_vov')
        self.addDailyData(self.gmm_dmean, 'fguo_0106.gmm_dmean')
        self.addDailyData(self.gmm_mean, 'fguo_0106.gmm_mean')
        self.addDailyData(self.inf_buy_ratio_close, 'fguo_0106.inf_buy_ratio_close')
        self.addDailyData(self.inf_sell_ratio_open, 'fguo_0106.inf_sell_ratio_open')
        self.addDailyData(self.int_ret_de1, 'fguo_0106.int_ret_de1')
        self.addDailyData(self.mci_a, 'fguo_0106.mci_a')
        self.addDailyData(self.mci_b, 'fguo_0106.mci_b')
        self.addDailyData(self.mci_imb, 'fguo_0106.mci_imb')
        self.addDailyData(self.mild_ret_1h, 'fguo_0106.mild_ret_1h')
        self.addDailyData(self.min_ret_kurt_ave, 'fguo_0106.min_ret_kurt_ave')
        self.addDailyData(self.min_ret_kurt_std, 'fguo_0106.min_ret_kurt_std')
        self.addDailyData(self.min_ret_skew_ave, 'fguo_0106.min_ret_skew_ave')
        self.addDailyData(self.min_ret_skew_std, 'fguo_0106.min_ret_skew_std')
        self.addDailyData(self.min_ret_std_ave, 'fguo_0106.min_ret_std_ave')
        self.addDailyData(self.min_ret_std_std, 'fguo_0106.min_ret_std_std')
        self.addDailyData(self.min_vol_kurt_ave, 'fguo_0106.min_vol_kurt_ave')
        self.addDailyData(self.min_vol_kurt_std, 'fguo_0106.min_vol_kurt_std')
        self.addDailyData(self.min_vol_skew_ave, 'fguo_0106.min_vol_skew_ave')
        self.addDailyData(self.min_vol_skew_std, 'fguo_0106.min_vol_skew_std')
        self.addDailyData(self.min_vol_std_ave, 'fguo_0106.min_vol_std_ave')
        self.addDailyData(self.min_vol_std_std, 'fguo_0106.min_vol_std_std')
        self.addDailyData(self.mintval_mte, 'fguo_0106.mintval_mte')
        self.addDailyData(self.mintval_mts, 'fguo_0106.mintval_mts')
        self.addDailyData(self.mintval_qua, 'fguo_0106.mintval_qua')
        self.addDailyData(self.mintval_skew, 'fguo_0106.mintval_skew')
        self.addDailyData(self.mom_l, 'fguo_0106.mom_l')
        self.addDailyData(self.mpb, 'fguo_0106.mpb')
        self.addDailyData(self.mpc_skew, 'fguo_0106.mpc_skew')
        self.addDailyData(self.net_buy_power_open, 'fguo_0106.net_buy_power_open')
        self.addDailyData(self.oval_mbsr, 'fguo_0106.oval_mbsr')
        self.addDailyData(self.ovp, 'fguo_0106.ovp')
        self.addDailyData(self.resiliency, 'fguo_0106.resiliency')
        self.addDailyData(self.ret_apt_c, 'fguo_0106.ret_apt_c')
        self.addDailyData(self.ret_hvol_rev, 'fguo_0106.ret_hvol_rev')
        self.addDailyData(self.ret_vol_c, 'fguo_0106.ret_vol_c')
        self.addDailyData(self.ret_vol_w, 'fguo_0106.ret_vol_w')
        self.addDailyData(self.rev_enhance, 'fguo_0106.rev_enhance')
        self.addDailyData(self.rsj_ratio, 'fguo_0106.rsj_ratio')
        self.addDailyData(self.rv_corr, 'fguo_0106.rv_corr')
        self.addDailyData(self.sectval_kurt, 'fguo_0106.sectval_kurt')
        self.addDailyData(self.tr0h, 'fguo_0106.tr0h')
        self.addDailyData(self.up_vol_ratio, 'fguo_0106.up_vol_ratio')
        self.addDailyData(self.upp, 'fguo_0106.upp')
        self.addDailyData(self.v_ar_corr, 'fguo_0106.v_ar_corr')
        self.addDailyData(self.var_ratio, 'fguo_0106.var_ratio')
        self.addDailyData(self.voll, 'fguo_0106.voll')
        self.addDailyData(self.vpc_std, 'fguo_0106.vpc_std')
        self.addDailyData(self.vwce, 'fguo_0106.vwce')
        self.addDailyData(self.vwcr, 'fguo_0106.vwcr')
        self.addDailyData(self.vwcs, 'fguo_0106.vwcs')
        return

    def loadDay(self, di):
        pass
