from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrFguotrade2(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.bar_count_daily = NIO_MATRIX()
        self.corr_prvr_am = NIO_MATRIX()
        self.corr_prvr_close_30m = NIO_MATRIX()
        self.corr_prvr_daily = NIO_MATRIX()
        self.corr_prvr_h1 = NIO_MATRIX()
        self.corr_prvr_h2 = NIO_MATRIX()
        self.corr_prvr_h3 = NIO_MATRIX()
        self.corr_prvr_h4 = NIO_MATRIX()
        self.corr_prvr_open_30m = NIO_MATRIX()
        self.corr_prvr_pm = NIO_MATRIX()
        self.corr_pvd_am = NIO_MATRIX()
        self.corr_pvd_close_30m = NIO_MATRIX()
        self.corr_pvd_daily = NIO_MATRIX()
        self.corr_pvd_h1 = NIO_MATRIX()
        self.corr_pvd_h2 = NIO_MATRIX()
        self.corr_pvd_h3 = NIO_MATRIX()
        self.corr_pvd_h4 = NIO_MATRIX()
        self.corr_pvd_open_30m = NIO_MATRIX()
        self.corr_pvd_pm = NIO_MATRIX()
        self.corr_pvl_am = NIO_MATRIX()
        self.corr_pvl_close_30m = NIO_MATRIX()
        self.corr_pvl_daily = NIO_MATRIX()
        self.corr_pvl_h1 = NIO_MATRIX()
        self.corr_pvl_h2 = NIO_MATRIX()
        self.corr_pvl_h3 = NIO_MATRIX()
        self.corr_pvl_h4 = NIO_MATRIX()
        self.corr_pvl_open_30m = NIO_MATRIX()
        self.corr_pvl_pm = NIO_MATRIX()
        self.corr_pvr_am = NIO_MATRIX()
        self.corr_pvr_close_30m = NIO_MATRIX()
        self.corr_pvr_daily = NIO_MATRIX()
        self.corr_pvr_h1 = NIO_MATRIX()
        self.corr_pvr_h2 = NIO_MATRIX()
        self.corr_pvr_h3 = NIO_MATRIX()
        self.corr_pvr_h4 = NIO_MATRIX()
        self.corr_pvr_open_30m = NIO_MATRIX()
        self.corr_pvr_pm = NIO_MATRIX()
        self.doc_kurt_am = NIO_MATRIX()
        self.doc_kurt_close_30m = NIO_MATRIX()
        self.doc_kurt_daily = NIO_MATRIX()
        self.doc_kurt_h1 = NIO_MATRIX()
        self.doc_kurt_h2 = NIO_MATRIX()
        self.doc_kurt_h3 = NIO_MATRIX()
        self.doc_kurt_h4 = NIO_MATRIX()
        self.doc_kurt_open_30m = NIO_MATRIX()
        self.doc_kurt_pm = NIO_MATRIX()
        self.doc_skew_am = NIO_MATRIX()
        self.doc_skew_close_30m = NIO_MATRIX()
        self.doc_skew_daily = NIO_MATRIX()
        self.doc_skew_h1 = NIO_MATRIX()
        self.doc_skew_h2 = NIO_MATRIX()
        self.doc_skew_h3 = NIO_MATRIX()
        self.doc_skew_h4 = NIO_MATRIX()
        self.doc_skew_open_30m = NIO_MATRIX()
        self.doc_skew_pm = NIO_MATRIX()
        self.doc_std_am = NIO_MATRIX()
        self.doc_std_close_30m = NIO_MATRIX()
        self.doc_std_daily = NIO_MATRIX()
        self.doc_std_h1 = NIO_MATRIX()
        self.doc_std_h2 = NIO_MATRIX()
        self.doc_std_h3 = NIO_MATRIX()
        self.doc_std_h4 = NIO_MATRIX()
        self.doc_std_open_30m = NIO_MATRIX()
        self.doc_std_pm = NIO_MATRIX()
        self.doc_vol10_ratio_am = NIO_MATRIX()
        self.doc_vol10_ratio_close_30m = NIO_MATRIX()
        self.doc_vol10_ratio_daily = NIO_MATRIX()
        self.doc_vol10_ratio_h1 = NIO_MATRIX()
        self.doc_vol10_ratio_h2 = NIO_MATRIX()
        self.doc_vol10_ratio_h3 = NIO_MATRIX()
        self.doc_vol10_ratio_h4 = NIO_MATRIX()
        self.doc_vol10_ratio_open_30m = NIO_MATRIX()
        self.doc_vol10_ratio_pm = NIO_MATRIX()
        self.doc_vol50_ratio_am = NIO_MATRIX()
        self.doc_vol50_ratio_close_30m = NIO_MATRIX()
        self.doc_vol50_ratio_daily = NIO_MATRIX()
        self.doc_vol50_ratio_h1 = NIO_MATRIX()
        self.doc_vol50_ratio_h2 = NIO_MATRIX()
        self.doc_vol50_ratio_h3 = NIO_MATRIX()
        self.doc_vol50_ratio_h4 = NIO_MATRIX()
        self.doc_vol50_ratio_open_30m = NIO_MATRIX()
        self.doc_vol50_ratio_pm = NIO_MATRIX()
        self.doc_vol5_ratio_am = NIO_MATRIX()
        self.doc_vol5_ratio_close_30m = NIO_MATRIX()
        self.doc_vol5_ratio_daily = NIO_MATRIX()
        self.doc_vol5_ratio_h1 = NIO_MATRIX()
        self.doc_vol5_ratio_h2 = NIO_MATRIX()
        self.doc_vol5_ratio_h3 = NIO_MATRIX()
        self.doc_vol5_ratio_h4 = NIO_MATRIX()
        self.doc_vol5_ratio_open_30m = NIO_MATRIX()
        self.doc_vol5_ratio_pm = NIO_MATRIX()
        self.doc_vol_pdf60_am = NIO_MATRIX()
        self.doc_vol_pdf60_close_30m = NIO_MATRIX()
        self.doc_vol_pdf60_daily = NIO_MATRIX()
        self.doc_vol_pdf60_h1 = NIO_MATRIX()
        self.doc_vol_pdf60_h2 = NIO_MATRIX()
        self.doc_vol_pdf60_h3 = NIO_MATRIX()
        self.doc_vol_pdf60_h4 = NIO_MATRIX()
        self.doc_vol_pdf60_open_30m = NIO_MATRIX()
        self.doc_vol_pdf60_pm = NIO_MATRIX()
        self.doc_vol_pdf70_am = NIO_MATRIX()
        self.doc_vol_pdf70_close_30m = NIO_MATRIX()
        self.doc_vol_pdf70_daily = NIO_MATRIX()
        self.doc_vol_pdf70_h1 = NIO_MATRIX()
        self.doc_vol_pdf70_h2 = NIO_MATRIX()
        self.doc_vol_pdf70_h3 = NIO_MATRIX()
        self.doc_vol_pdf70_h4 = NIO_MATRIX()
        self.doc_vol_pdf70_open_30m = NIO_MATRIX()
        self.doc_vol_pdf70_pm = NIO_MATRIX()
        self.doc_vol_pdf80_am = NIO_MATRIX()
        self.doc_vol_pdf80_close_30m = NIO_MATRIX()
        self.doc_vol_pdf80_daily = NIO_MATRIX()
        self.doc_vol_pdf80_h1 = NIO_MATRIX()
        self.doc_vol_pdf80_h2 = NIO_MATRIX()
        self.doc_vol_pdf80_h3 = NIO_MATRIX()
        self.doc_vol_pdf80_h4 = NIO_MATRIX()
        self.doc_vol_pdf80_open_30m = NIO_MATRIX()
        self.doc_vol_pdf80_pm = NIO_MATRIX()
        self.doc_vol_pdf90_am = NIO_MATRIX()
        self.doc_vol_pdf90_close_30m = NIO_MATRIX()
        self.doc_vol_pdf90_daily = NIO_MATRIX()
        self.doc_vol_pdf90_h1 = NIO_MATRIX()
        self.doc_vol_pdf90_h2 = NIO_MATRIX()
        self.doc_vol_pdf90_h3 = NIO_MATRIX()
        self.doc_vol_pdf90_h4 = NIO_MATRIX()
        self.doc_vol_pdf90_open_30m = NIO_MATRIX()
        self.doc_vol_pdf90_pm = NIO_MATRIX()
        self.doc_vol_pdf90bi_am = NIO_MATRIX()
        self.doc_vol_pdf90bi_close_30m = NIO_MATRIX()
        self.doc_vol_pdf90bi_daily = NIO_MATRIX()
        self.doc_vol_pdf90bi_h1 = NIO_MATRIX()
        self.doc_vol_pdf90bi_h2 = NIO_MATRIX()
        self.doc_vol_pdf90bi_h3 = NIO_MATRIX()
        self.doc_vol_pdf90bi_h4 = NIO_MATRIX()
        self.doc_vol_pdf90bi_open_30m = NIO_MATRIX()
        self.doc_vol_pdf90bi_pm = NIO_MATRIX()
        self.doc_vol_pdf95_am = NIO_MATRIX()
        self.doc_vol_pdf95_close_30m = NIO_MATRIX()
        self.doc_vol_pdf95_daily = NIO_MATRIX()
        self.doc_vol_pdf95_h1 = NIO_MATRIX()
        self.doc_vol_pdf95_h2 = NIO_MATRIX()
        self.doc_vol_pdf95_h3 = NIO_MATRIX()
        self.doc_vol_pdf95_h4 = NIO_MATRIX()
        self.doc_vol_pdf95_open_30m = NIO_MATRIX()
        self.doc_vol_pdf95_pm = NIO_MATRIX()
        self.ols_beta_mean_am = NIO_MATRIX()
        self.ols_beta_mean_close_30m = NIO_MATRIX()
        self.ols_beta_mean_daily = NIO_MATRIX()
        self.ols_beta_mean_h1 = NIO_MATRIX()
        self.ols_beta_mean_h2 = NIO_MATRIX()
        self.ols_beta_mean_h3 = NIO_MATRIX()
        self.ols_beta_mean_h4 = NIO_MATRIX()
        self.ols_beta_mean_open_30m = NIO_MATRIX()
        self.ols_beta_mean_pm = NIO_MATRIX()
        self.ols_beta_zscore_last_am = NIO_MATRIX()
        self.ols_beta_zscore_last_close_30m = NIO_MATRIX()
        self.ols_beta_zscore_last_daily = NIO_MATRIX()
        self.ols_beta_zscore_last_h1 = NIO_MATRIX()
        self.ols_beta_zscore_last_h2 = NIO_MATRIX()
        self.ols_beta_zscore_last_h3 = NIO_MATRIX()
        self.ols_beta_zscore_last_h4 = NIO_MATRIX()
        self.ols_beta_zscore_last_open_30m = NIO_MATRIX()
        self.ols_beta_zscore_last_pm = NIO_MATRIX()
        self.ols_corr_mean_am = NIO_MATRIX()
        self.ols_corr_mean_close_30m = NIO_MATRIX()
        self.ols_corr_mean_daily = NIO_MATRIX()
        self.ols_corr_mean_h1 = NIO_MATRIX()
        self.ols_corr_mean_h2 = NIO_MATRIX()
        self.ols_corr_mean_h3 = NIO_MATRIX()
        self.ols_corr_mean_h4 = NIO_MATRIX()
        self.ols_corr_mean_open_30m = NIO_MATRIX()
        self.ols_corr_mean_pm = NIO_MATRIX()
        self.ols_corr_sq_mean_am = NIO_MATRIX()
        self.ols_corr_sq_mean_close_30m = NIO_MATRIX()
        self.ols_corr_sq_mean_daily = NIO_MATRIX()
        self.ols_corr_sq_mean_h1 = NIO_MATRIX()
        self.ols_corr_sq_mean_h2 = NIO_MATRIX()
        self.ols_corr_sq_mean_h3 = NIO_MATRIX()
        self.ols_corr_sq_mean_h4 = NIO_MATRIX()
        self.ols_corr_sq_mean_open_30m = NIO_MATRIX()
        self.ols_corr_sq_mean_pm = NIO_MATRIX()
        self.ols_qrs_am = NIO_MATRIX()
        self.ols_qrs_close_30m = NIO_MATRIX()
        self.ols_qrs_daily = NIO_MATRIX()
        self.ols_qrs_h1 = NIO_MATRIX()
        self.ols_qrs_h2 = NIO_MATRIX()
        self.ols_qrs_h3 = NIO_MATRIX()
        self.ols_qrs_h4 = NIO_MATRIX()
        self.ols_qrs_open_30m = NIO_MATRIX()
        self.ols_qrs_pm = NIO_MATRIX()
        self.shape_skratio_am = NIO_MATRIX()
        self.shape_skratio_close_30m = NIO_MATRIX()
        self.shape_skratio_daily = NIO_MATRIX()
        self.shape_skratio_h1 = NIO_MATRIX()
        self.shape_skratio_h2 = NIO_MATRIX()
        self.shape_skratio_h3 = NIO_MATRIX()
        self.shape_skratio_h4 = NIO_MATRIX()
        self.shape_skratio_open_30m = NIO_MATRIX()
        self.shape_skratio_pm = NIO_MATRIX()
        self.shape_skratio_vol_am = NIO_MATRIX()
        self.shape_skratio_vol_close_30m = NIO_MATRIX()
        self.shape_skratio_vol_daily = NIO_MATRIX()
        self.shape_skratio_vol_h1 = NIO_MATRIX()
        self.shape_skratio_vol_h2 = NIO_MATRIX()
        self.shape_skratio_vol_h3 = NIO_MATRIX()
        self.shape_skratio_vol_h4 = NIO_MATRIX()
        self.shape_skratio_vol_open_30m = NIO_MATRIX()
        self.shape_skratio_vol_pm = NIO_MATRIX()
        self.trade_bottom20ret_ratio_am = NIO_MATRIX()
        self.trade_bottom20ret_ratio_close_30m = NIO_MATRIX()
        self.trade_bottom20ret_ratio_daily = NIO_MATRIX()
        self.trade_bottom20ret_ratio_h1 = NIO_MATRIX()
        self.trade_bottom20ret_ratio_h2 = NIO_MATRIX()
        self.trade_bottom20ret_ratio_h3 = NIO_MATRIX()
        self.trade_bottom20ret_ratio_h4 = NIO_MATRIX()
        self.trade_bottom20ret_ratio_open_30m = NIO_MATRIX()
        self.trade_bottom20ret_ratio_pm = NIO_MATRIX()
        self.trade_bottom50ret_ratio_am = NIO_MATRIX()
        self.trade_bottom50ret_ratio_close_30m = NIO_MATRIX()
        self.trade_bottom50ret_ratio_daily = NIO_MATRIX()
        self.trade_bottom50ret_ratio_h1 = NIO_MATRIX()
        self.trade_bottom50ret_ratio_h2 = NIO_MATRIX()
        self.trade_bottom50ret_ratio_h3 = NIO_MATRIX()
        self.trade_bottom50ret_ratio_h4 = NIO_MATRIX()
        self.trade_bottom50ret_ratio_open_30m = NIO_MATRIX()
        self.trade_bottom50ret_ratio_pm = NIO_MATRIX()
        self.trade_top20ret_ratio_am = NIO_MATRIX()
        self.trade_top20ret_ratio_close_30m = NIO_MATRIX()
        self.trade_top20ret_ratio_daily = NIO_MATRIX()
        self.trade_top20ret_ratio_h1 = NIO_MATRIX()
        self.trade_top20ret_ratio_h2 = NIO_MATRIX()
        self.trade_top20ret_ratio_h3 = NIO_MATRIX()
        self.trade_top20ret_ratio_h4 = NIO_MATRIX()
        self.trade_top20ret_ratio_open_30m = NIO_MATRIX()
        self.trade_top20ret_ratio_pm = NIO_MATRIX()
        self.trade_top50ret_ratio_am = NIO_MATRIX()
        self.trade_top50ret_ratio_close_30m = NIO_MATRIX()
        self.trade_top50ret_ratio_daily = NIO_MATRIX()
        self.trade_top50ret_ratio_h1 = NIO_MATRIX()
        self.trade_top50ret_ratio_h2 = NIO_MATRIX()
        self.trade_top50ret_ratio_h3 = NIO_MATRIX()
        self.trade_top50ret_ratio_h4 = NIO_MATRIX()
        self.trade_top50ret_ratio_open_30m = NIO_MATRIX()
        self.trade_top50ret_ratio_pm = NIO_MATRIX()
        self.trade_topneg20ret_ratio_am = NIO_MATRIX()
        self.trade_topneg20ret_ratio_close_30m = NIO_MATRIX()
        self.trade_topneg20ret_ratio_daily = NIO_MATRIX()
        self.trade_topneg20ret_ratio_h1 = NIO_MATRIX()
        self.trade_topneg20ret_ratio_h2 = NIO_MATRIX()
        self.trade_topneg20ret_ratio_h3 = NIO_MATRIX()
        self.trade_topneg20ret_ratio_h4 = NIO_MATRIX()
        self.trade_topneg20ret_ratio_open_30m = NIO_MATRIX()
        self.trade_topneg20ret_ratio_pm = NIO_MATRIX()
        self.trade_toppos20ret_ratio_am = NIO_MATRIX()
        self.trade_toppos20ret_ratio_close_30m = NIO_MATRIX()
        self.trade_toppos20ret_ratio_daily = NIO_MATRIX()
        self.trade_toppos20ret_ratio_h1 = NIO_MATRIX()
        self.trade_toppos20ret_ratio_h2 = NIO_MATRIX()
        self.trade_toppos20ret_ratio_h3 = NIO_MATRIX()
        self.trade_toppos20ret_ratio_h4 = NIO_MATRIX()
        self.trade_toppos20ret_ratio_open_30m = NIO_MATRIX()
        self.trade_toppos20ret_ratio_pm = NIO_MATRIX()
        self.vol_std_am = NIO_MATRIX()
        self.vol_std_close_30m = NIO_MATRIX()
        self.vol_std_daily = NIO_MATRIX()
        self.vol_std_h1 = NIO_MATRIX()
        self.vol_std_h2 = NIO_MATRIX()
        self.vol_std_h3 = NIO_MATRIX()
        self.vol_std_h4 = NIO_MATRIX()
        self.vol_std_open_30m = NIO_MATRIX()
        self.vol_std_pm = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.bar_count_daily, 'fguo_trade2.bar_count_daily')
        self.addDailyData(self.corr_prvr_am, 'fguo_trade2.corr_prvr_am')
        self.addDailyData(self.corr_prvr_close_30m, 'fguo_trade2.corr_prvr_close_30m')
        self.addDailyData(self.corr_prvr_daily, 'fguo_trade2.corr_prvr_daily')
        self.addDailyData(self.corr_prvr_h1, 'fguo_trade2.corr_prvr_h1')
        self.addDailyData(self.corr_prvr_h2, 'fguo_trade2.corr_prvr_h2')
        self.addDailyData(self.corr_prvr_h3, 'fguo_trade2.corr_prvr_h3')
        self.addDailyData(self.corr_prvr_h4, 'fguo_trade2.corr_prvr_h4')
        self.addDailyData(self.corr_prvr_open_30m, 'fguo_trade2.corr_prvr_open_30m')
        self.addDailyData(self.corr_prvr_pm, 'fguo_trade2.corr_prvr_pm')
        self.addDailyData(self.corr_pvd_am, 'fguo_trade2.corr_pvd_am')
        self.addDailyData(self.corr_pvd_close_30m, 'fguo_trade2.corr_pvd_close_30m')
        self.addDailyData(self.corr_pvd_daily, 'fguo_trade2.corr_pvd_daily')
        self.addDailyData(self.corr_pvd_h1, 'fguo_trade2.corr_pvd_h1')
        self.addDailyData(self.corr_pvd_h2, 'fguo_trade2.corr_pvd_h2')
        self.addDailyData(self.corr_pvd_h3, 'fguo_trade2.corr_pvd_h3')
        self.addDailyData(self.corr_pvd_h4, 'fguo_trade2.corr_pvd_h4')
        self.addDailyData(self.corr_pvd_open_30m, 'fguo_trade2.corr_pvd_open_30m')
        self.addDailyData(self.corr_pvd_pm, 'fguo_trade2.corr_pvd_pm')
        self.addDailyData(self.corr_pvl_am, 'fguo_trade2.corr_pvl_am')
        self.addDailyData(self.corr_pvl_close_30m, 'fguo_trade2.corr_pvl_close_30m')
        self.addDailyData(self.corr_pvl_daily, 'fguo_trade2.corr_pvl_daily')
        self.addDailyData(self.corr_pvl_h1, 'fguo_trade2.corr_pvl_h1')
        self.addDailyData(self.corr_pvl_h2, 'fguo_trade2.corr_pvl_h2')
        self.addDailyData(self.corr_pvl_h3, 'fguo_trade2.corr_pvl_h3')
        self.addDailyData(self.corr_pvl_h4, 'fguo_trade2.corr_pvl_h4')
        self.addDailyData(self.corr_pvl_open_30m, 'fguo_trade2.corr_pvl_open_30m')
        self.addDailyData(self.corr_pvl_pm, 'fguo_trade2.corr_pvl_pm')
        self.addDailyData(self.corr_pvr_am, 'fguo_trade2.corr_pvr_am')
        self.addDailyData(self.corr_pvr_close_30m, 'fguo_trade2.corr_pvr_close_30m')
        self.addDailyData(self.corr_pvr_daily, 'fguo_trade2.corr_pvr_daily')
        self.addDailyData(self.corr_pvr_h1, 'fguo_trade2.corr_pvr_h1')
        self.addDailyData(self.corr_pvr_h2, 'fguo_trade2.corr_pvr_h2')
        self.addDailyData(self.corr_pvr_h3, 'fguo_trade2.corr_pvr_h3')
        self.addDailyData(self.corr_pvr_h4, 'fguo_trade2.corr_pvr_h4')
        self.addDailyData(self.corr_pvr_open_30m, 'fguo_trade2.corr_pvr_open_30m')
        self.addDailyData(self.corr_pvr_pm, 'fguo_trade2.corr_pvr_pm')
        self.addDailyData(self.doc_kurt_am, 'fguo_trade2.doc_kurt_am')
        self.addDailyData(self.doc_kurt_close_30m, 'fguo_trade2.doc_kurt_close_30m')
        self.addDailyData(self.doc_kurt_daily, 'fguo_trade2.doc_kurt_daily')
        self.addDailyData(self.doc_kurt_h1, 'fguo_trade2.doc_kurt_h1')
        self.addDailyData(self.doc_kurt_h2, 'fguo_trade2.doc_kurt_h2')
        self.addDailyData(self.doc_kurt_h3, 'fguo_trade2.doc_kurt_h3')
        self.addDailyData(self.doc_kurt_h4, 'fguo_trade2.doc_kurt_h4')
        self.addDailyData(self.doc_kurt_open_30m, 'fguo_trade2.doc_kurt_open_30m')
        self.addDailyData(self.doc_kurt_pm, 'fguo_trade2.doc_kurt_pm')
        self.addDailyData(self.doc_skew_am, 'fguo_trade2.doc_skew_am')
        self.addDailyData(self.doc_skew_close_30m, 'fguo_trade2.doc_skew_close_30m')
        self.addDailyData(self.doc_skew_daily, 'fguo_trade2.doc_skew_daily')
        self.addDailyData(self.doc_skew_h1, 'fguo_trade2.doc_skew_h1')
        self.addDailyData(self.doc_skew_h2, 'fguo_trade2.doc_skew_h2')
        self.addDailyData(self.doc_skew_h3, 'fguo_trade2.doc_skew_h3')
        self.addDailyData(self.doc_skew_h4, 'fguo_trade2.doc_skew_h4')
        self.addDailyData(self.doc_skew_open_30m, 'fguo_trade2.doc_skew_open_30m')
        self.addDailyData(self.doc_skew_pm, 'fguo_trade2.doc_skew_pm')
        self.addDailyData(self.doc_std_am, 'fguo_trade2.doc_std_am')
        self.addDailyData(self.doc_std_close_30m, 'fguo_trade2.doc_std_close_30m')
        self.addDailyData(self.doc_std_daily, 'fguo_trade2.doc_std_daily')
        self.addDailyData(self.doc_std_h1, 'fguo_trade2.doc_std_h1')
        self.addDailyData(self.doc_std_h2, 'fguo_trade2.doc_std_h2')
        self.addDailyData(self.doc_std_h3, 'fguo_trade2.doc_std_h3')
        self.addDailyData(self.doc_std_h4, 'fguo_trade2.doc_std_h4')
        self.addDailyData(self.doc_std_open_30m, 'fguo_trade2.doc_std_open_30m')
        self.addDailyData(self.doc_std_pm, 'fguo_trade2.doc_std_pm')
        self.addDailyData(self.doc_vol10_ratio_am, 'fguo_trade2.doc_vol10_ratio_am')
        self.addDailyData(self.doc_vol10_ratio_close_30m, 'fguo_trade2.doc_vol10_ratio_close_30m')
        self.addDailyData(self.doc_vol10_ratio_daily, 'fguo_trade2.doc_vol10_ratio_daily')
        self.addDailyData(self.doc_vol10_ratio_h1, 'fguo_trade2.doc_vol10_ratio_h1')
        self.addDailyData(self.doc_vol10_ratio_h2, 'fguo_trade2.doc_vol10_ratio_h2')
        self.addDailyData(self.doc_vol10_ratio_h3, 'fguo_trade2.doc_vol10_ratio_h3')
        self.addDailyData(self.doc_vol10_ratio_h4, 'fguo_trade2.doc_vol10_ratio_h4')
        self.addDailyData(self.doc_vol10_ratio_open_30m, 'fguo_trade2.doc_vol10_ratio_open_30m')
        self.addDailyData(self.doc_vol10_ratio_pm, 'fguo_trade2.doc_vol10_ratio_pm')
        self.addDailyData(self.doc_vol50_ratio_am, 'fguo_trade2.doc_vol50_ratio_am')
        self.addDailyData(self.doc_vol50_ratio_close_30m, 'fguo_trade2.doc_vol50_ratio_close_30m')
        self.addDailyData(self.doc_vol50_ratio_daily, 'fguo_trade2.doc_vol50_ratio_daily')
        self.addDailyData(self.doc_vol50_ratio_h1, 'fguo_trade2.doc_vol50_ratio_h1')
        self.addDailyData(self.doc_vol50_ratio_h2, 'fguo_trade2.doc_vol50_ratio_h2')
        self.addDailyData(self.doc_vol50_ratio_h3, 'fguo_trade2.doc_vol50_ratio_h3')
        self.addDailyData(self.doc_vol50_ratio_h4, 'fguo_trade2.doc_vol50_ratio_h4')
        self.addDailyData(self.doc_vol50_ratio_open_30m, 'fguo_trade2.doc_vol50_ratio_open_30m')
        self.addDailyData(self.doc_vol50_ratio_pm, 'fguo_trade2.doc_vol50_ratio_pm')
        self.addDailyData(self.doc_vol5_ratio_am, 'fguo_trade2.doc_vol5_ratio_am')
        self.addDailyData(self.doc_vol5_ratio_close_30m, 'fguo_trade2.doc_vol5_ratio_close_30m')
        self.addDailyData(self.doc_vol5_ratio_daily, 'fguo_trade2.doc_vol5_ratio_daily')
        self.addDailyData(self.doc_vol5_ratio_h1, 'fguo_trade2.doc_vol5_ratio_h1')
        self.addDailyData(self.doc_vol5_ratio_h2, 'fguo_trade2.doc_vol5_ratio_h2')
        self.addDailyData(self.doc_vol5_ratio_h3, 'fguo_trade2.doc_vol5_ratio_h3')
        self.addDailyData(self.doc_vol5_ratio_h4, 'fguo_trade2.doc_vol5_ratio_h4')
        self.addDailyData(self.doc_vol5_ratio_open_30m, 'fguo_trade2.doc_vol5_ratio_open_30m')
        self.addDailyData(self.doc_vol5_ratio_pm, 'fguo_trade2.doc_vol5_ratio_pm')
        self.addDailyData(self.doc_vol_pdf60_am, 'fguo_trade2.doc_vol_pdf60_am')
        self.addDailyData(self.doc_vol_pdf60_close_30m, 'fguo_trade2.doc_vol_pdf60_close_30m')
        self.addDailyData(self.doc_vol_pdf60_daily, 'fguo_trade2.doc_vol_pdf60_daily')
        self.addDailyData(self.doc_vol_pdf60_h1, 'fguo_trade2.doc_vol_pdf60_h1')
        self.addDailyData(self.doc_vol_pdf60_h2, 'fguo_trade2.doc_vol_pdf60_h2')
        self.addDailyData(self.doc_vol_pdf60_h3, 'fguo_trade2.doc_vol_pdf60_h3')
        self.addDailyData(self.doc_vol_pdf60_h4, 'fguo_trade2.doc_vol_pdf60_h4')
        self.addDailyData(self.doc_vol_pdf60_open_30m, 'fguo_trade2.doc_vol_pdf60_open_30m')
        self.addDailyData(self.doc_vol_pdf60_pm, 'fguo_trade2.doc_vol_pdf60_pm')
        self.addDailyData(self.doc_vol_pdf70_am, 'fguo_trade2.doc_vol_pdf70_am')
        self.addDailyData(self.doc_vol_pdf70_close_30m, 'fguo_trade2.doc_vol_pdf70_close_30m')
        self.addDailyData(self.doc_vol_pdf70_daily, 'fguo_trade2.doc_vol_pdf70_daily')
        self.addDailyData(self.doc_vol_pdf70_h1, 'fguo_trade2.doc_vol_pdf70_h1')
        self.addDailyData(self.doc_vol_pdf70_h2, 'fguo_trade2.doc_vol_pdf70_h2')
        self.addDailyData(self.doc_vol_pdf70_h3, 'fguo_trade2.doc_vol_pdf70_h3')
        self.addDailyData(self.doc_vol_pdf70_h4, 'fguo_trade2.doc_vol_pdf70_h4')
        self.addDailyData(self.doc_vol_pdf70_open_30m, 'fguo_trade2.doc_vol_pdf70_open_30m')
        self.addDailyData(self.doc_vol_pdf70_pm, 'fguo_trade2.doc_vol_pdf70_pm')
        self.addDailyData(self.doc_vol_pdf80_am, 'fguo_trade2.doc_vol_pdf80_am')
        self.addDailyData(self.doc_vol_pdf80_close_30m, 'fguo_trade2.doc_vol_pdf80_close_30m')
        self.addDailyData(self.doc_vol_pdf80_daily, 'fguo_trade2.doc_vol_pdf80_daily')
        self.addDailyData(self.doc_vol_pdf80_h1, 'fguo_trade2.doc_vol_pdf80_h1')
        self.addDailyData(self.doc_vol_pdf80_h2, 'fguo_trade2.doc_vol_pdf80_h2')
        self.addDailyData(self.doc_vol_pdf80_h3, 'fguo_trade2.doc_vol_pdf80_h3')
        self.addDailyData(self.doc_vol_pdf80_h4, 'fguo_trade2.doc_vol_pdf80_h4')
        self.addDailyData(self.doc_vol_pdf80_open_30m, 'fguo_trade2.doc_vol_pdf80_open_30m')
        self.addDailyData(self.doc_vol_pdf80_pm, 'fguo_trade2.doc_vol_pdf80_pm')
        self.addDailyData(self.doc_vol_pdf90_am, 'fguo_trade2.doc_vol_pdf90_am')
        self.addDailyData(self.doc_vol_pdf90_close_30m, 'fguo_trade2.doc_vol_pdf90_close_30m')
        self.addDailyData(self.doc_vol_pdf90_daily, 'fguo_trade2.doc_vol_pdf90_daily')
        self.addDailyData(self.doc_vol_pdf90_h1, 'fguo_trade2.doc_vol_pdf90_h1')
        self.addDailyData(self.doc_vol_pdf90_h2, 'fguo_trade2.doc_vol_pdf90_h2')
        self.addDailyData(self.doc_vol_pdf90_h3, 'fguo_trade2.doc_vol_pdf90_h3')
        self.addDailyData(self.doc_vol_pdf90_h4, 'fguo_trade2.doc_vol_pdf90_h4')
        self.addDailyData(self.doc_vol_pdf90_open_30m, 'fguo_trade2.doc_vol_pdf90_open_30m')
        self.addDailyData(self.doc_vol_pdf90_pm, 'fguo_trade2.doc_vol_pdf90_pm')
        self.addDailyData(self.doc_vol_pdf90bi_am, 'fguo_trade2.doc_vol_pdf90bi_am')
        self.addDailyData(self.doc_vol_pdf90bi_close_30m, 'fguo_trade2.doc_vol_pdf90bi_close_30m')
        self.addDailyData(self.doc_vol_pdf90bi_daily, 'fguo_trade2.doc_vol_pdf90bi_daily')
        self.addDailyData(self.doc_vol_pdf90bi_h1, 'fguo_trade2.doc_vol_pdf90bi_h1')
        self.addDailyData(self.doc_vol_pdf90bi_h2, 'fguo_trade2.doc_vol_pdf90bi_h2')
        self.addDailyData(self.doc_vol_pdf90bi_h3, 'fguo_trade2.doc_vol_pdf90bi_h3')
        self.addDailyData(self.doc_vol_pdf90bi_h4, 'fguo_trade2.doc_vol_pdf90bi_h4')
        self.addDailyData(self.doc_vol_pdf90bi_open_30m, 'fguo_trade2.doc_vol_pdf90bi_open_30m')
        self.addDailyData(self.doc_vol_pdf90bi_pm, 'fguo_trade2.doc_vol_pdf90bi_pm')
        self.addDailyData(self.doc_vol_pdf95_am, 'fguo_trade2.doc_vol_pdf95_am')
        self.addDailyData(self.doc_vol_pdf95_close_30m, 'fguo_trade2.doc_vol_pdf95_close_30m')
        self.addDailyData(self.doc_vol_pdf95_daily, 'fguo_trade2.doc_vol_pdf95_daily')
        self.addDailyData(self.doc_vol_pdf95_h1, 'fguo_trade2.doc_vol_pdf95_h1')
        self.addDailyData(self.doc_vol_pdf95_h2, 'fguo_trade2.doc_vol_pdf95_h2')
        self.addDailyData(self.doc_vol_pdf95_h3, 'fguo_trade2.doc_vol_pdf95_h3')
        self.addDailyData(self.doc_vol_pdf95_h4, 'fguo_trade2.doc_vol_pdf95_h4')
        self.addDailyData(self.doc_vol_pdf95_open_30m, 'fguo_trade2.doc_vol_pdf95_open_30m')
        self.addDailyData(self.doc_vol_pdf95_pm, 'fguo_trade2.doc_vol_pdf95_pm')
        self.addDailyData(self.ols_beta_mean_am, 'fguo_trade2.ols_beta_mean_am')
        self.addDailyData(self.ols_beta_mean_close_30m, 'fguo_trade2.ols_beta_mean_close_30m')
        self.addDailyData(self.ols_beta_mean_daily, 'fguo_trade2.ols_beta_mean_daily')
        self.addDailyData(self.ols_beta_mean_h1, 'fguo_trade2.ols_beta_mean_h1')
        self.addDailyData(self.ols_beta_mean_h2, 'fguo_trade2.ols_beta_mean_h2')
        self.addDailyData(self.ols_beta_mean_h3, 'fguo_trade2.ols_beta_mean_h3')
        self.addDailyData(self.ols_beta_mean_h4, 'fguo_trade2.ols_beta_mean_h4')
        self.addDailyData(self.ols_beta_mean_open_30m, 'fguo_trade2.ols_beta_mean_open_30m')
        self.addDailyData(self.ols_beta_mean_pm, 'fguo_trade2.ols_beta_mean_pm')
        self.addDailyData(self.ols_beta_zscore_last_am, 'fguo_trade2.ols_beta_zscore_last_am')
        self.addDailyData(self.ols_beta_zscore_last_close_30m, 'fguo_trade2.ols_beta_zscore_last_close_30m')
        self.addDailyData(self.ols_beta_zscore_last_daily, 'fguo_trade2.ols_beta_zscore_last_daily')
        self.addDailyData(self.ols_beta_zscore_last_h1, 'fguo_trade2.ols_beta_zscore_last_h1')
        self.addDailyData(self.ols_beta_zscore_last_h2, 'fguo_trade2.ols_beta_zscore_last_h2')
        self.addDailyData(self.ols_beta_zscore_last_h3, 'fguo_trade2.ols_beta_zscore_last_h3')
        self.addDailyData(self.ols_beta_zscore_last_h4, 'fguo_trade2.ols_beta_zscore_last_h4')
        self.addDailyData(self.ols_beta_zscore_last_open_30m, 'fguo_trade2.ols_beta_zscore_last_open_30m')
        self.addDailyData(self.ols_beta_zscore_last_pm, 'fguo_trade2.ols_beta_zscore_last_pm')
        self.addDailyData(self.ols_corr_mean_am, 'fguo_trade2.ols_corr_mean_am')
        self.addDailyData(self.ols_corr_mean_close_30m, 'fguo_trade2.ols_corr_mean_close_30m')
        self.addDailyData(self.ols_corr_mean_daily, 'fguo_trade2.ols_corr_mean_daily')
        self.addDailyData(self.ols_corr_mean_h1, 'fguo_trade2.ols_corr_mean_h1')
        self.addDailyData(self.ols_corr_mean_h2, 'fguo_trade2.ols_corr_mean_h2')
        self.addDailyData(self.ols_corr_mean_h3, 'fguo_trade2.ols_corr_mean_h3')
        self.addDailyData(self.ols_corr_mean_h4, 'fguo_trade2.ols_corr_mean_h4')
        self.addDailyData(self.ols_corr_mean_open_30m, 'fguo_trade2.ols_corr_mean_open_30m')
        self.addDailyData(self.ols_corr_mean_pm, 'fguo_trade2.ols_corr_mean_pm')
        self.addDailyData(self.ols_corr_sq_mean_am, 'fguo_trade2.ols_corr_sq_mean_am')
        self.addDailyData(self.ols_corr_sq_mean_close_30m, 'fguo_trade2.ols_corr_sq_mean_close_30m')
        self.addDailyData(self.ols_corr_sq_mean_daily, 'fguo_trade2.ols_corr_sq_mean_daily')
        self.addDailyData(self.ols_corr_sq_mean_h1, 'fguo_trade2.ols_corr_sq_mean_h1')
        self.addDailyData(self.ols_corr_sq_mean_h2, 'fguo_trade2.ols_corr_sq_mean_h2')
        self.addDailyData(self.ols_corr_sq_mean_h3, 'fguo_trade2.ols_corr_sq_mean_h3')
        self.addDailyData(self.ols_corr_sq_mean_h4, 'fguo_trade2.ols_corr_sq_mean_h4')
        self.addDailyData(self.ols_corr_sq_mean_open_30m, 'fguo_trade2.ols_corr_sq_mean_open_30m')
        self.addDailyData(self.ols_corr_sq_mean_pm, 'fguo_trade2.ols_corr_sq_mean_pm')
        self.addDailyData(self.ols_qrs_am, 'fguo_trade2.ols_qrs_am')
        self.addDailyData(self.ols_qrs_close_30m, 'fguo_trade2.ols_qrs_close_30m')
        self.addDailyData(self.ols_qrs_daily, 'fguo_trade2.ols_qrs_daily')
        self.addDailyData(self.ols_qrs_h1, 'fguo_trade2.ols_qrs_h1')
        self.addDailyData(self.ols_qrs_h2, 'fguo_trade2.ols_qrs_h2')
        self.addDailyData(self.ols_qrs_h3, 'fguo_trade2.ols_qrs_h3')
        self.addDailyData(self.ols_qrs_h4, 'fguo_trade2.ols_qrs_h4')
        self.addDailyData(self.ols_qrs_open_30m, 'fguo_trade2.ols_qrs_open_30m')
        self.addDailyData(self.ols_qrs_pm, 'fguo_trade2.ols_qrs_pm')
        self.addDailyData(self.shape_skratio_am, 'fguo_trade2.shape_skratio_am')
        self.addDailyData(self.shape_skratio_close_30m, 'fguo_trade2.shape_skratio_close_30m')
        self.addDailyData(self.shape_skratio_daily, 'fguo_trade2.shape_skratio_daily')
        self.addDailyData(self.shape_skratio_h1, 'fguo_trade2.shape_skratio_h1')
        self.addDailyData(self.shape_skratio_h2, 'fguo_trade2.shape_skratio_h2')
        self.addDailyData(self.shape_skratio_h3, 'fguo_trade2.shape_skratio_h3')
        self.addDailyData(self.shape_skratio_h4, 'fguo_trade2.shape_skratio_h4')
        self.addDailyData(self.shape_skratio_open_30m, 'fguo_trade2.shape_skratio_open_30m')
        self.addDailyData(self.shape_skratio_pm, 'fguo_trade2.shape_skratio_pm')
        self.addDailyData(self.shape_skratio_vol_am, 'fguo_trade2.shape_skratio_vol_am')
        self.addDailyData(self.shape_skratio_vol_close_30m, 'fguo_trade2.shape_skratio_vol_close_30m')
        self.addDailyData(self.shape_skratio_vol_daily, 'fguo_trade2.shape_skratio_vol_daily')
        self.addDailyData(self.shape_skratio_vol_h1, 'fguo_trade2.shape_skratio_vol_h1')
        self.addDailyData(self.shape_skratio_vol_h2, 'fguo_trade2.shape_skratio_vol_h2')
        self.addDailyData(self.shape_skratio_vol_h3, 'fguo_trade2.shape_skratio_vol_h3')
        self.addDailyData(self.shape_skratio_vol_h4, 'fguo_trade2.shape_skratio_vol_h4')
        self.addDailyData(self.shape_skratio_vol_open_30m, 'fguo_trade2.shape_skratio_vol_open_30m')
        self.addDailyData(self.shape_skratio_vol_pm, 'fguo_trade2.shape_skratio_vol_pm')
        self.addDailyData(self.trade_bottom20ret_ratio_am, 'fguo_trade2.trade_bottom20ret_ratio_am')
        self.addDailyData(self.trade_bottom20ret_ratio_close_30m, 'fguo_trade2.trade_bottom20ret_ratio_close_30m')
        self.addDailyData(self.trade_bottom20ret_ratio_daily, 'fguo_trade2.trade_bottom20ret_ratio_daily')
        self.addDailyData(self.trade_bottom20ret_ratio_h1, 'fguo_trade2.trade_bottom20ret_ratio_h1')
        self.addDailyData(self.trade_bottom20ret_ratio_h2, 'fguo_trade2.trade_bottom20ret_ratio_h2')
        self.addDailyData(self.trade_bottom20ret_ratio_h3, 'fguo_trade2.trade_bottom20ret_ratio_h3')
        self.addDailyData(self.trade_bottom20ret_ratio_h4, 'fguo_trade2.trade_bottom20ret_ratio_h4')
        self.addDailyData(self.trade_bottom20ret_ratio_open_30m, 'fguo_trade2.trade_bottom20ret_ratio_open_30m')
        self.addDailyData(self.trade_bottom20ret_ratio_pm, 'fguo_trade2.trade_bottom20ret_ratio_pm')
        self.addDailyData(self.trade_bottom50ret_ratio_am, 'fguo_trade2.trade_bottom50ret_ratio_am')
        self.addDailyData(self.trade_bottom50ret_ratio_close_30m, 'fguo_trade2.trade_bottom50ret_ratio_close_30m')
        self.addDailyData(self.trade_bottom50ret_ratio_daily, 'fguo_trade2.trade_bottom50ret_ratio_daily')
        self.addDailyData(self.trade_bottom50ret_ratio_h1, 'fguo_trade2.trade_bottom50ret_ratio_h1')
        self.addDailyData(self.trade_bottom50ret_ratio_h2, 'fguo_trade2.trade_bottom50ret_ratio_h2')
        self.addDailyData(self.trade_bottom50ret_ratio_h3, 'fguo_trade2.trade_bottom50ret_ratio_h3')
        self.addDailyData(self.trade_bottom50ret_ratio_h4, 'fguo_trade2.trade_bottom50ret_ratio_h4')
        self.addDailyData(self.trade_bottom50ret_ratio_open_30m, 'fguo_trade2.trade_bottom50ret_ratio_open_30m')
        self.addDailyData(self.trade_bottom50ret_ratio_pm, 'fguo_trade2.trade_bottom50ret_ratio_pm')
        self.addDailyData(self.trade_top20ret_ratio_am, 'fguo_trade2.trade_top20ret_ratio_am')
        self.addDailyData(self.trade_top20ret_ratio_close_30m, 'fguo_trade2.trade_top20ret_ratio_close_30m')
        self.addDailyData(self.trade_top20ret_ratio_daily, 'fguo_trade2.trade_top20ret_ratio_daily')
        self.addDailyData(self.trade_top20ret_ratio_h1, 'fguo_trade2.trade_top20ret_ratio_h1')
        self.addDailyData(self.trade_top20ret_ratio_h2, 'fguo_trade2.trade_top20ret_ratio_h2')
        self.addDailyData(self.trade_top20ret_ratio_h3, 'fguo_trade2.trade_top20ret_ratio_h3')
        self.addDailyData(self.trade_top20ret_ratio_h4, 'fguo_trade2.trade_top20ret_ratio_h4')
        self.addDailyData(self.trade_top20ret_ratio_open_30m, 'fguo_trade2.trade_top20ret_ratio_open_30m')
        self.addDailyData(self.trade_top20ret_ratio_pm, 'fguo_trade2.trade_top20ret_ratio_pm')
        self.addDailyData(self.trade_top50ret_ratio_am, 'fguo_trade2.trade_top50ret_ratio_am')
        self.addDailyData(self.trade_top50ret_ratio_close_30m, 'fguo_trade2.trade_top50ret_ratio_close_30m')
        self.addDailyData(self.trade_top50ret_ratio_daily, 'fguo_trade2.trade_top50ret_ratio_daily')
        self.addDailyData(self.trade_top50ret_ratio_h1, 'fguo_trade2.trade_top50ret_ratio_h1')
        self.addDailyData(self.trade_top50ret_ratio_h2, 'fguo_trade2.trade_top50ret_ratio_h2')
        self.addDailyData(self.trade_top50ret_ratio_h3, 'fguo_trade2.trade_top50ret_ratio_h3')
        self.addDailyData(self.trade_top50ret_ratio_h4, 'fguo_trade2.trade_top50ret_ratio_h4')
        self.addDailyData(self.trade_top50ret_ratio_open_30m, 'fguo_trade2.trade_top50ret_ratio_open_30m')
        self.addDailyData(self.trade_top50ret_ratio_pm, 'fguo_trade2.trade_top50ret_ratio_pm')
        self.addDailyData(self.trade_topneg20ret_ratio_am, 'fguo_trade2.trade_topneg20ret_ratio_am')
        self.addDailyData(self.trade_topneg20ret_ratio_close_30m, 'fguo_trade2.trade_topneg20ret_ratio_close_30m')
        self.addDailyData(self.trade_topneg20ret_ratio_daily, 'fguo_trade2.trade_topneg20ret_ratio_daily')
        self.addDailyData(self.trade_topneg20ret_ratio_h1, 'fguo_trade2.trade_topneg20ret_ratio_h1')
        self.addDailyData(self.trade_topneg20ret_ratio_h2, 'fguo_trade2.trade_topneg20ret_ratio_h2')
        self.addDailyData(self.trade_topneg20ret_ratio_h3, 'fguo_trade2.trade_topneg20ret_ratio_h3')
        self.addDailyData(self.trade_topneg20ret_ratio_h4, 'fguo_trade2.trade_topneg20ret_ratio_h4')
        self.addDailyData(self.trade_topneg20ret_ratio_open_30m, 'fguo_trade2.trade_topneg20ret_ratio_open_30m')
        self.addDailyData(self.trade_topneg20ret_ratio_pm, 'fguo_trade2.trade_topneg20ret_ratio_pm')
        self.addDailyData(self.trade_toppos20ret_ratio_am, 'fguo_trade2.trade_toppos20ret_ratio_am')
        self.addDailyData(self.trade_toppos20ret_ratio_close_30m, 'fguo_trade2.trade_toppos20ret_ratio_close_30m')
        self.addDailyData(self.trade_toppos20ret_ratio_daily, 'fguo_trade2.trade_toppos20ret_ratio_daily')
        self.addDailyData(self.trade_toppos20ret_ratio_h1, 'fguo_trade2.trade_toppos20ret_ratio_h1')
        self.addDailyData(self.trade_toppos20ret_ratio_h2, 'fguo_trade2.trade_toppos20ret_ratio_h2')
        self.addDailyData(self.trade_toppos20ret_ratio_h3, 'fguo_trade2.trade_toppos20ret_ratio_h3')
        self.addDailyData(self.trade_toppos20ret_ratio_h4, 'fguo_trade2.trade_toppos20ret_ratio_h4')
        self.addDailyData(self.trade_toppos20ret_ratio_open_30m, 'fguo_trade2.trade_toppos20ret_ratio_open_30m')
        self.addDailyData(self.trade_toppos20ret_ratio_pm, 'fguo_trade2.trade_toppos20ret_ratio_pm')
        self.addDailyData(self.vol_std_am, 'fguo_trade2.vol_std_am')
        self.addDailyData(self.vol_std_close_30m, 'fguo_trade2.vol_std_close_30m')
        self.addDailyData(self.vol_std_daily, 'fguo_trade2.vol_std_daily')
        self.addDailyData(self.vol_std_h1, 'fguo_trade2.vol_std_h1')
        self.addDailyData(self.vol_std_h2, 'fguo_trade2.vol_std_h2')
        self.addDailyData(self.vol_std_h3, 'fguo_trade2.vol_std_h3')
        self.addDailyData(self.vol_std_h4, 'fguo_trade2.vol_std_h4')
        self.addDailyData(self.vol_std_open_30m, 'fguo_trade2.vol_std_open_30m')
        self.addDailyData(self.vol_std_pm, 'fguo_trade2.vol_std_pm')
        return

    def loadDay(self, di):
        pass
