from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrSli0212(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.cumulative_amount_1m = NIO_MATRIX()
        self.cumulative_amount_30m = NIO_MATRIX()
        self.cumulative_amount_5m = NIO_MATRIX()
        self.cumulative_retained_amount_1m = NIO_MATRIX()
        self.cumulative_retained_amount_30m = NIO_MATRIX()
        self.cumulative_retained_amount_5m = NIO_MATRIX()
        self.log_agg_amt_1m_kurt = NIO_MATRIX()
        self.log_agg_amt_1m_mean = NIO_MATRIX()
        self.log_agg_amt_1m_skew = NIO_MATRIX()
        self.log_agg_amt_1m_var = NIO_MATRIX()
        self.log_agg_amt_30m_kurt = NIO_MATRIX()
        self.log_agg_amt_30m_mean = NIO_MATRIX()
        self.log_agg_amt_30m_skew = NIO_MATRIX()
        self.log_agg_amt_30m_var = NIO_MATRIX()
        self.log_agg_amt_5m_kurt = NIO_MATRIX()
        self.log_agg_amt_5m_mean = NIO_MATRIX()
        self.log_agg_amt_5m_skew = NIO_MATRIX()
        self.log_agg_amt_5m_var = NIO_MATRIX()
        self.log_agg_cnt_1m_kurt = NIO_MATRIX()
        self.log_agg_cnt_1m_mean = NIO_MATRIX()
        self.log_agg_cnt_1m_skew = NIO_MATRIX()
        self.log_agg_cnt_1m_var = NIO_MATRIX()
        self.log_agg_cnt_30m_kurt = NIO_MATRIX()
        self.log_agg_cnt_30m_mean = NIO_MATRIX()
        self.log_agg_cnt_30m_skew = NIO_MATRIX()
        self.log_agg_cnt_30m_var = NIO_MATRIX()
        self.log_agg_cnt_5m_kurt = NIO_MATRIX()
        self.log_agg_cnt_5m_mean = NIO_MATRIX()
        self.log_agg_cnt_5m_skew = NIO_MATRIX()
        self.log_agg_cnt_5m_var = NIO_MATRIX()
        self.log_agg_vol_1m_kurt = NIO_MATRIX()
        self.log_agg_vol_1m_mean = NIO_MATRIX()
        self.log_agg_vol_1m_skew = NIO_MATRIX()
        self.log_agg_vol_1m_var = NIO_MATRIX()
        self.log_agg_vol_30m_kurt = NIO_MATRIX()
        self.log_agg_vol_30m_mean = NIO_MATRIX()
        self.log_agg_vol_30m_skew = NIO_MATRIX()
        self.log_agg_vol_30m_var = NIO_MATRIX()
        self.log_agg_vol_5m_kurt = NIO_MATRIX()
        self.log_agg_vol_5m_mean = NIO_MATRIX()
        self.log_agg_vol_5m_skew = NIO_MATRIX()
        self.log_agg_vol_5m_var = NIO_MATRIX()
        self.log_ask_vol_1m_kurt = NIO_MATRIX()
        self.log_ask_vol_1m_mean = NIO_MATRIX()
        self.log_ask_vol_1m_skew = NIO_MATRIX()
        self.log_ask_vol_1m_var = NIO_MATRIX()
        self.log_ask_vol_30m_kurt = NIO_MATRIX()
        self.log_ask_vol_30m_mean = NIO_MATRIX()
        self.log_ask_vol_30m_skew = NIO_MATRIX()
        self.log_ask_vol_30m_var = NIO_MATRIX()
        self.log_ask_vol_5m_kurt = NIO_MATRIX()
        self.log_ask_vol_5m_mean = NIO_MATRIX()
        self.log_ask_vol_5m_skew = NIO_MATRIX()
        self.log_ask_vol_5m_var = NIO_MATRIX()
        self.log_bid_vol_1m_kurt = NIO_MATRIX()
        self.log_bid_vol_1m_mean = NIO_MATRIX()
        self.log_bid_vol_1m_skew = NIO_MATRIX()
        self.log_bid_vol_1m_var = NIO_MATRIX()
        self.log_bid_vol_30m_kurt = NIO_MATRIX()
        self.log_bid_vol_30m_mean = NIO_MATRIX()
        self.log_bid_vol_30m_skew = NIO_MATRIX()
        self.log_bid_vol_30m_var = NIO_MATRIX()
        self.log_bid_vol_5m_kurt = NIO_MATRIX()
        self.log_bid_vol_5m_mean = NIO_MATRIX()
        self.log_bid_vol_5m_skew = NIO_MATRIX()
        self.log_bid_vol_5m_var = NIO_MATRIX()
        self.log_depth_1m_kurt = NIO_MATRIX()
        self.log_depth_1m_mean = NIO_MATRIX()
        self.log_depth_1m_skew = NIO_MATRIX()
        self.log_depth_1m_var = NIO_MATRIX()
        self.log_depth_30m_kurt = NIO_MATRIX()
        self.log_depth_30m_mean = NIO_MATRIX()
        self.log_depth_30m_skew = NIO_MATRIX()
        self.log_depth_30m_var = NIO_MATRIX()
        self.log_depth_5m_kurt = NIO_MATRIX()
        self.log_depth_5m_mean = NIO_MATRIX()
        self.log_depth_5m_skew = NIO_MATRIX()
        self.log_depth_5m_var = NIO_MATRIX()
        self.log_imbalance_1m_kurt = NIO_MATRIX()
        self.log_imbalance_1m_mean = NIO_MATRIX()
        self.log_imbalance_1m_skew = NIO_MATRIX()
        self.log_imbalance_1m_var = NIO_MATRIX()
        self.log_imbalance_30m_kurt = NIO_MATRIX()
        self.log_imbalance_30m_mean = NIO_MATRIX()
        self.log_imbalance_30m_skew = NIO_MATRIX()
        self.log_imbalance_30m_var = NIO_MATRIX()
        self.log_imbalance_5m_kurt = NIO_MATRIX()
        self.log_imbalance_5m_mean = NIO_MATRIX()
        self.log_imbalance_5m_skew = NIO_MATRIX()
        self.log_imbalance_5m_var = NIO_MATRIX()
        self.log_spread_1m_kurt = NIO_MATRIX()
        self.log_spread_1m_mean = NIO_MATRIX()
        self.log_spread_1m_skew = NIO_MATRIX()
        self.log_spread_1m_var = NIO_MATRIX()
        self.log_spread_30m_kurt = NIO_MATRIX()
        self.log_spread_30m_mean = NIO_MATRIX()
        self.log_spread_30m_skew = NIO_MATRIX()
        self.log_spread_30m_var = NIO_MATRIX()
        self.log_spread_5m_kurt = NIO_MATRIX()
        self.log_spread_5m_mean = NIO_MATRIX()
        self.log_spread_5m_skew = NIO_MATRIX()
        self.log_spread_5m_var = NIO_MATRIX()
        self.mom_1m_kurt = NIO_MATRIX()
        self.mom_1m_mean = NIO_MATRIX()
        self.mom_1m_skew = NIO_MATRIX()
        self.mom_1m_var = NIO_MATRIX()
        self.mom_30m_kurt = NIO_MATRIX()
        self.mom_30m_mean = NIO_MATRIX()
        self.mom_30m_skew = NIO_MATRIX()
        self.mom_30m_var = NIO_MATRIX()
        self.mom_5m_kurt = NIO_MATRIX()
        self.mom_5m_mean = NIO_MATRIX()
        self.mom_5m_skew = NIO_MATRIX()
        self.mom_5m_var = NIO_MATRIX()
        self.mom_av_1m_kurt = NIO_MATRIX()
        self.mom_av_1m_mean = NIO_MATRIX()
        self.mom_av_1m_skew = NIO_MATRIX()
        self.mom_av_1m_var = NIO_MATRIX()
        self.mom_av_30m_kurt = NIO_MATRIX()
        self.mom_av_30m_mean = NIO_MATRIX()
        self.mom_av_30m_skew = NIO_MATRIX()
        self.mom_av_30m_var = NIO_MATRIX()
        self.mom_av_5m_kurt = NIO_MATRIX()
        self.mom_av_5m_mean = NIO_MATRIX()
        self.mom_av_5m_skew = NIO_MATRIX()
        self.mom_av_5m_var = NIO_MATRIX()
        self.mom_hl_1m_kurt = NIO_MATRIX()
        self.mom_hl_1m_mean = NIO_MATRIX()
        self.mom_hl_1m_skew = NIO_MATRIX()
        self.mom_hl_1m_var = NIO_MATRIX()
        self.mom_hl_30m_kurt = NIO_MATRIX()
        self.mom_hl_30m_mean = NIO_MATRIX()
        self.mom_hl_30m_skew = NIO_MATRIX()
        self.mom_hl_30m_var = NIO_MATRIX()
        self.mom_hl_5m_kurt = NIO_MATRIX()
        self.mom_hl_5m_mean = NIO_MATRIX()
        self.mom_hl_5m_skew = NIO_MATRIX()
        self.mom_hl_5m_var = NIO_MATRIX()
        self.retained_ratio_1m = NIO_MATRIX()
        self.retained_ratio_30m = NIO_MATRIX()
        self.retained_ratio_5m = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.cumulative_amount_1m, 'sli_0212.cumulative_amount_1m')
        self.addDailyData(self.cumulative_amount_30m, 'sli_0212.cumulative_amount_30m')
        self.addDailyData(self.cumulative_amount_5m, 'sli_0212.cumulative_amount_5m')
        self.addDailyData(self.cumulative_retained_amount_1m, 'sli_0212.cumulative_retained_amount_1m')
        self.addDailyData(self.cumulative_retained_amount_30m, 'sli_0212.cumulative_retained_amount_30m')
        self.addDailyData(self.cumulative_retained_amount_5m, 'sli_0212.cumulative_retained_amount_5m')
        self.addDailyData(self.log_agg_amt_1m_kurt, 'sli_0212.log_agg_amt_1m_kurt')
        self.addDailyData(self.log_agg_amt_1m_mean, 'sli_0212.log_agg_amt_1m_mean')
        self.addDailyData(self.log_agg_amt_1m_skew, 'sli_0212.log_agg_amt_1m_skew')
        self.addDailyData(self.log_agg_amt_1m_var, 'sli_0212.log_agg_amt_1m_var')
        self.addDailyData(self.log_agg_amt_30m_kurt, 'sli_0212.log_agg_amt_30m_kurt')
        self.addDailyData(self.log_agg_amt_30m_mean, 'sli_0212.log_agg_amt_30m_mean')
        self.addDailyData(self.log_agg_amt_30m_skew, 'sli_0212.log_agg_amt_30m_skew')
        self.addDailyData(self.log_agg_amt_30m_var, 'sli_0212.log_agg_amt_30m_var')
        self.addDailyData(self.log_agg_amt_5m_kurt, 'sli_0212.log_agg_amt_5m_kurt')
        self.addDailyData(self.log_agg_amt_5m_mean, 'sli_0212.log_agg_amt_5m_mean')
        self.addDailyData(self.log_agg_amt_5m_skew, 'sli_0212.log_agg_amt_5m_skew')
        self.addDailyData(self.log_agg_amt_5m_var, 'sli_0212.log_agg_amt_5m_var')
        self.addDailyData(self.log_agg_cnt_1m_kurt, 'sli_0212.log_agg_cnt_1m_kurt')
        self.addDailyData(self.log_agg_cnt_1m_mean, 'sli_0212.log_agg_cnt_1m_mean')
        self.addDailyData(self.log_agg_cnt_1m_skew, 'sli_0212.log_agg_cnt_1m_skew')
        self.addDailyData(self.log_agg_cnt_1m_var, 'sli_0212.log_agg_cnt_1m_var')
        self.addDailyData(self.log_agg_cnt_30m_kurt, 'sli_0212.log_agg_cnt_30m_kurt')
        self.addDailyData(self.log_agg_cnt_30m_mean, 'sli_0212.log_agg_cnt_30m_mean')
        self.addDailyData(self.log_agg_cnt_30m_skew, 'sli_0212.log_agg_cnt_30m_skew')
        self.addDailyData(self.log_agg_cnt_30m_var, 'sli_0212.log_agg_cnt_30m_var')
        self.addDailyData(self.log_agg_cnt_5m_kurt, 'sli_0212.log_agg_cnt_5m_kurt')
        self.addDailyData(self.log_agg_cnt_5m_mean, 'sli_0212.log_agg_cnt_5m_mean')
        self.addDailyData(self.log_agg_cnt_5m_skew, 'sli_0212.log_agg_cnt_5m_skew')
        self.addDailyData(self.log_agg_cnt_5m_var, 'sli_0212.log_agg_cnt_5m_var')
        self.addDailyData(self.log_agg_vol_1m_kurt, 'sli_0212.log_agg_vol_1m_kurt')
        self.addDailyData(self.log_agg_vol_1m_mean, 'sli_0212.log_agg_vol_1m_mean')
        self.addDailyData(self.log_agg_vol_1m_skew, 'sli_0212.log_agg_vol_1m_skew')
        self.addDailyData(self.log_agg_vol_1m_var, 'sli_0212.log_agg_vol_1m_var')
        self.addDailyData(self.log_agg_vol_30m_kurt, 'sli_0212.log_agg_vol_30m_kurt')
        self.addDailyData(self.log_agg_vol_30m_mean, 'sli_0212.log_agg_vol_30m_mean')
        self.addDailyData(self.log_agg_vol_30m_skew, 'sli_0212.log_agg_vol_30m_skew')
        self.addDailyData(self.log_agg_vol_30m_var, 'sli_0212.log_agg_vol_30m_var')
        self.addDailyData(self.log_agg_vol_5m_kurt, 'sli_0212.log_agg_vol_5m_kurt')
        self.addDailyData(self.log_agg_vol_5m_mean, 'sli_0212.log_agg_vol_5m_mean')
        self.addDailyData(self.log_agg_vol_5m_skew, 'sli_0212.log_agg_vol_5m_skew')
        self.addDailyData(self.log_agg_vol_5m_var, 'sli_0212.log_agg_vol_5m_var')
        self.addDailyData(self.log_ask_vol_1m_kurt, 'sli_0212.log_ask_vol_1m_kurt')
        self.addDailyData(self.log_ask_vol_1m_mean, 'sli_0212.log_ask_vol_1m_mean')
        self.addDailyData(self.log_ask_vol_1m_skew, 'sli_0212.log_ask_vol_1m_skew')
        self.addDailyData(self.log_ask_vol_1m_var, 'sli_0212.log_ask_vol_1m_var')
        self.addDailyData(self.log_ask_vol_30m_kurt, 'sli_0212.log_ask_vol_30m_kurt')
        self.addDailyData(self.log_ask_vol_30m_mean, 'sli_0212.log_ask_vol_30m_mean')
        self.addDailyData(self.log_ask_vol_30m_skew, 'sli_0212.log_ask_vol_30m_skew')
        self.addDailyData(self.log_ask_vol_30m_var, 'sli_0212.log_ask_vol_30m_var')
        self.addDailyData(self.log_ask_vol_5m_kurt, 'sli_0212.log_ask_vol_5m_kurt')
        self.addDailyData(self.log_ask_vol_5m_mean, 'sli_0212.log_ask_vol_5m_mean')
        self.addDailyData(self.log_ask_vol_5m_skew, 'sli_0212.log_ask_vol_5m_skew')
        self.addDailyData(self.log_ask_vol_5m_var, 'sli_0212.log_ask_vol_5m_var')
        self.addDailyData(self.log_bid_vol_1m_kurt, 'sli_0212.log_bid_vol_1m_kurt')
        self.addDailyData(self.log_bid_vol_1m_mean, 'sli_0212.log_bid_vol_1m_mean')
        self.addDailyData(self.log_bid_vol_1m_skew, 'sli_0212.log_bid_vol_1m_skew')
        self.addDailyData(self.log_bid_vol_1m_var, 'sli_0212.log_bid_vol_1m_var')
        self.addDailyData(self.log_bid_vol_30m_kurt, 'sli_0212.log_bid_vol_30m_kurt')
        self.addDailyData(self.log_bid_vol_30m_mean, 'sli_0212.log_bid_vol_30m_mean')
        self.addDailyData(self.log_bid_vol_30m_skew, 'sli_0212.log_bid_vol_30m_skew')
        self.addDailyData(self.log_bid_vol_30m_var, 'sli_0212.log_bid_vol_30m_var')
        self.addDailyData(self.log_bid_vol_5m_kurt, 'sli_0212.log_bid_vol_5m_kurt')
        self.addDailyData(self.log_bid_vol_5m_mean, 'sli_0212.log_bid_vol_5m_mean')
        self.addDailyData(self.log_bid_vol_5m_skew, 'sli_0212.log_bid_vol_5m_skew')
        self.addDailyData(self.log_bid_vol_5m_var, 'sli_0212.log_bid_vol_5m_var')
        self.addDailyData(self.log_depth_1m_kurt, 'sli_0212.log_depth_1m_kurt')
        self.addDailyData(self.log_depth_1m_mean, 'sli_0212.log_depth_1m_mean')
        self.addDailyData(self.log_depth_1m_skew, 'sli_0212.log_depth_1m_skew')
        self.addDailyData(self.log_depth_1m_var, 'sli_0212.log_depth_1m_var')
        self.addDailyData(self.log_depth_30m_kurt, 'sli_0212.log_depth_30m_kurt')
        self.addDailyData(self.log_depth_30m_mean, 'sli_0212.log_depth_30m_mean')
        self.addDailyData(self.log_depth_30m_skew, 'sli_0212.log_depth_30m_skew')
        self.addDailyData(self.log_depth_30m_var, 'sli_0212.log_depth_30m_var')
        self.addDailyData(self.log_depth_5m_kurt, 'sli_0212.log_depth_5m_kurt')
        self.addDailyData(self.log_depth_5m_mean, 'sli_0212.log_depth_5m_mean')
        self.addDailyData(self.log_depth_5m_skew, 'sli_0212.log_depth_5m_skew')
        self.addDailyData(self.log_depth_5m_var, 'sli_0212.log_depth_5m_var')
        self.addDailyData(self.log_imbalance_1m_kurt, 'sli_0212.log_imbalance_1m_kurt')
        self.addDailyData(self.log_imbalance_1m_mean, 'sli_0212.log_imbalance_1m_mean')
        self.addDailyData(self.log_imbalance_1m_skew, 'sli_0212.log_imbalance_1m_skew')
        self.addDailyData(self.log_imbalance_1m_var, 'sli_0212.log_imbalance_1m_var')
        self.addDailyData(self.log_imbalance_30m_kurt, 'sli_0212.log_imbalance_30m_kurt')
        self.addDailyData(self.log_imbalance_30m_mean, 'sli_0212.log_imbalance_30m_mean')
        self.addDailyData(self.log_imbalance_30m_skew, 'sli_0212.log_imbalance_30m_skew')
        self.addDailyData(self.log_imbalance_30m_var, 'sli_0212.log_imbalance_30m_var')
        self.addDailyData(self.log_imbalance_5m_kurt, 'sli_0212.log_imbalance_5m_kurt')
        self.addDailyData(self.log_imbalance_5m_mean, 'sli_0212.log_imbalance_5m_mean')
        self.addDailyData(self.log_imbalance_5m_skew, 'sli_0212.log_imbalance_5m_skew')
        self.addDailyData(self.log_imbalance_5m_var, 'sli_0212.log_imbalance_5m_var')
        self.addDailyData(self.log_spread_1m_kurt, 'sli_0212.log_spread_1m_kurt')
        self.addDailyData(self.log_spread_1m_mean, 'sli_0212.log_spread_1m_mean')
        self.addDailyData(self.log_spread_1m_skew, 'sli_0212.log_spread_1m_skew')
        self.addDailyData(self.log_spread_1m_var, 'sli_0212.log_spread_1m_var')
        self.addDailyData(self.log_spread_30m_kurt, 'sli_0212.log_spread_30m_kurt')
        self.addDailyData(self.log_spread_30m_mean, 'sli_0212.log_spread_30m_mean')
        self.addDailyData(self.log_spread_30m_skew, 'sli_0212.log_spread_30m_skew')
        self.addDailyData(self.log_spread_30m_var, 'sli_0212.log_spread_30m_var')
        self.addDailyData(self.log_spread_5m_kurt, 'sli_0212.log_spread_5m_kurt')
        self.addDailyData(self.log_spread_5m_mean, 'sli_0212.log_spread_5m_mean')
        self.addDailyData(self.log_spread_5m_skew, 'sli_0212.log_spread_5m_skew')
        self.addDailyData(self.log_spread_5m_var, 'sli_0212.log_spread_5m_var')
        self.addDailyData(self.mom_1m_kurt, 'sli_0212.mom_1m_kurt')
        self.addDailyData(self.mom_1m_mean, 'sli_0212.mom_1m_mean')
        self.addDailyData(self.mom_1m_skew, 'sli_0212.mom_1m_skew')
        self.addDailyData(self.mom_1m_var, 'sli_0212.mom_1m_var')
        self.addDailyData(self.mom_30m_kurt, 'sli_0212.mom_30m_kurt')
        self.addDailyData(self.mom_30m_mean, 'sli_0212.mom_30m_mean')
        self.addDailyData(self.mom_30m_skew, 'sli_0212.mom_30m_skew')
        self.addDailyData(self.mom_30m_var, 'sli_0212.mom_30m_var')
        self.addDailyData(self.mom_5m_kurt, 'sli_0212.mom_5m_kurt')
        self.addDailyData(self.mom_5m_mean, 'sli_0212.mom_5m_mean')
        self.addDailyData(self.mom_5m_skew, 'sli_0212.mom_5m_skew')
        self.addDailyData(self.mom_5m_var, 'sli_0212.mom_5m_var')
        self.addDailyData(self.mom_av_1m_kurt, 'sli_0212.mom_av_1m_kurt')
        self.addDailyData(self.mom_av_1m_mean, 'sli_0212.mom_av_1m_mean')
        self.addDailyData(self.mom_av_1m_skew, 'sli_0212.mom_av_1m_skew')
        self.addDailyData(self.mom_av_1m_var, 'sli_0212.mom_av_1m_var')
        self.addDailyData(self.mom_av_30m_kurt, 'sli_0212.mom_av_30m_kurt')
        self.addDailyData(self.mom_av_30m_mean, 'sli_0212.mom_av_30m_mean')
        self.addDailyData(self.mom_av_30m_skew, 'sli_0212.mom_av_30m_skew')
        self.addDailyData(self.mom_av_30m_var, 'sli_0212.mom_av_30m_var')
        self.addDailyData(self.mom_av_5m_kurt, 'sli_0212.mom_av_5m_kurt')
        self.addDailyData(self.mom_av_5m_mean, 'sli_0212.mom_av_5m_mean')
        self.addDailyData(self.mom_av_5m_skew, 'sli_0212.mom_av_5m_skew')
        self.addDailyData(self.mom_av_5m_var, 'sli_0212.mom_av_5m_var')
        self.addDailyData(self.mom_hl_1m_kurt, 'sli_0212.mom_hl_1m_kurt')
        self.addDailyData(self.mom_hl_1m_mean, 'sli_0212.mom_hl_1m_mean')
        self.addDailyData(self.mom_hl_1m_skew, 'sli_0212.mom_hl_1m_skew')
        self.addDailyData(self.mom_hl_1m_var, 'sli_0212.mom_hl_1m_var')
        self.addDailyData(self.mom_hl_30m_kurt, 'sli_0212.mom_hl_30m_kurt')
        self.addDailyData(self.mom_hl_30m_mean, 'sli_0212.mom_hl_30m_mean')
        self.addDailyData(self.mom_hl_30m_skew, 'sli_0212.mom_hl_30m_skew')
        self.addDailyData(self.mom_hl_30m_var, 'sli_0212.mom_hl_30m_var')
        self.addDailyData(self.mom_hl_5m_kurt, 'sli_0212.mom_hl_5m_kurt')
        self.addDailyData(self.mom_hl_5m_mean, 'sli_0212.mom_hl_5m_mean')
        self.addDailyData(self.mom_hl_5m_skew, 'sli_0212.mom_hl_5m_skew')
        self.addDailyData(self.mom_hl_5m_var, 'sli_0212.mom_hl_5m_var')
        self.addDailyData(self.retained_ratio_1m, 'sli_0212.retained_ratio_1m')
        self.addDailyData(self.retained_ratio_30m, 'sli_0212.retained_ratio_30m')
        self.addDailyData(self.retained_ratio_5m, 'sli_0212.retained_ratio_5m')
        return

    def loadDay(self, di):
        pass
