from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrSli0210(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.cvar5pct_1m = NIO_MATRIX()
        self.cvar5pct_30m = NIO_MATRIX()
        self.cvar5pct_5m = NIO_MATRIX()
        self.cvar5pct_close30_1m = NIO_MATRIX()
        self.cvar5pct_close30_5m = NIO_MATRIX()
        self.cvar5pct_open30_1m = NIO_MATRIX()
        self.cvar5pct_open30_5m = NIO_MATRIX()
        self.follow_coef_1m = NIO_MATRIX()
        self.follow_coef_30m = NIO_MATRIX()
        self.follow_coef_5m = NIO_MATRIX()
        self.herding_h = NIO_MATRIX()
        self.herding_hb = NIO_MATRIX()
        self.herding_hs = NIO_MATRIX()
        self.liq_1pct_10m = NIO_MATRIX()
        self.liq_1pct_2m = NIO_MATRIX()
        self.liq_1pct_5m = NIO_MATRIX()
        self.liq_sqrt_10m = NIO_MATRIX()
        self.liq_sqrt_2m = NIO_MATRIX()
        self.liq_sqrt_5m = NIO_MATRIX()
        self.prob_down_1m = NIO_MATRIX()
        self.prob_down_30m = NIO_MATRIX()
        self.prob_down_5m = NIO_MATRIX()
        self.prob_down_close30_1m = NIO_MATRIX()
        self.prob_down_close30_5m = NIO_MATRIX()
        self.prob_down_open30_1m = NIO_MATRIX()
        self.prob_down_open30_5m = NIO_MATRIX()
        self.prob_up_1m = NIO_MATRIX()
        self.prob_up_30m = NIO_MATRIX()
        self.prob_up_5m = NIO_MATRIX()
        self.prob_up_close30_1m = NIO_MATRIX()
        self.prob_up_close30_5m = NIO_MATRIX()
        self.prob_up_open30_1m = NIO_MATRIX()
        self.prob_up_open30_5m = NIO_MATRIX()
        self.rev_basic_1m = NIO_MATRIX()
        self.rev_basic_30m = NIO_MATRIX()
        self.rev_basic_5m = NIO_MATRIX()
        self.rev_exopen_1m = NIO_MATRIX()
        self.rev_exopen_30m = NIO_MATRIX()
        self.rev_exopen_5m = NIO_MATRIX()
        self.rev_hf_1m = NIO_MATRIX()
        self.rev_hf_30m = NIO_MATRIX()
        self.rev_hf_5m = NIO_MATRIX()
        self.rev_mom_1m = NIO_MATRIX()
        self.rev_mom_30m = NIO_MATRIX()
        self.rev_mom_5m = NIO_MATRIX()
        self.rev_open_1m = NIO_MATRIX()
        self.rev_open_30m = NIO_MATRIX()
        self.rev_open_5m = NIO_MATRIX()
        self.rev_per_1m = NIO_MATRIX()
        self.rev_per_30m = NIO_MATRIX()
        self.rev_per_5m = NIO_MATRIX()
        self.rev_per_close30_1m = NIO_MATRIX()
        self.rev_per_close30_5m = NIO_MATRIX()
        self.rev_per_open30_1m = NIO_MATRIX()
        self.rev_per_open30_5m = NIO_MATRIX()
        self.rev_rev_1m = NIO_MATRIX()
        self.rev_rev_30m = NIO_MATRIX()
        self.rev_rev_5m = NIO_MATRIX()
        self.rev_struct7_1m = NIO_MATRIX()
        self.rev_struct7_30m = NIO_MATRIX()
        self.rev_struct7_5m = NIO_MATRIX()
        self.rev_struct_10m = NIO_MATRIX()
        self.rev_struct_30m = NIO_MATRIX()
        self.rev_struct_60m = NIO_MATRIX()
        self.rev_time_10m = NIO_MATRIX()
        self.rev_time_30m = NIO_MATRIX()
        self.rev_time_60m = NIO_MATRIX()
        self.var1pct_1m = NIO_MATRIX()
        self.var1pct_30m = NIO_MATRIX()
        self.var1pct_5m = NIO_MATRIX()
        self.var1pct_close30_1m = NIO_MATRIX()
        self.var1pct_close30_5m = NIO_MATRIX()
        self.var1pct_open30_1m = NIO_MATRIX()
        self.var1pct_open30_5m = NIO_MATRIX()
        self.vol_1m = NIO_MATRIX()
        self.vol_30m = NIO_MATRIX()
        self.vol_5m = NIO_MATRIX()
        self.vol_close30_1m = NIO_MATRIX()
        self.vol_close30_5m = NIO_MATRIX()
        self.vol_open30_1m = NIO_MATRIX()
        self.vol_open30_5m = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.cvar5pct_1m, 'sli_0210.cvar5pct_1m')
        self.addDailyData(self.cvar5pct_30m, 'sli_0210.cvar5pct_30m')
        self.addDailyData(self.cvar5pct_5m, 'sli_0210.cvar5pct_5m')
        self.addDailyData(self.cvar5pct_close30_1m, 'sli_0210.cvar5pct_close30_1m')
        self.addDailyData(self.cvar5pct_close30_5m, 'sli_0210.cvar5pct_close30_5m')
        self.addDailyData(self.cvar5pct_open30_1m, 'sli_0210.cvar5pct_open30_1m')
        self.addDailyData(self.cvar5pct_open30_5m, 'sli_0210.cvar5pct_open30_5m')
        self.addDailyData(self.follow_coef_1m, 'sli_0210.follow_coef_1m')
        self.addDailyData(self.follow_coef_30m, 'sli_0210.follow_coef_30m')
        self.addDailyData(self.follow_coef_5m, 'sli_0210.follow_coef_5m')
        self.addDailyData(self.herding_h, 'sli_0210.herding_h')
        self.addDailyData(self.herding_hb, 'sli_0210.herding_hb')
        self.addDailyData(self.herding_hs, 'sli_0210.herding_hs')
        self.addDailyData(self.liq_1pct_10m, 'sli_0210.liq_1pct_10m')
        self.addDailyData(self.liq_1pct_2m, 'sli_0210.liq_1pct_2m')
        self.addDailyData(self.liq_1pct_5m, 'sli_0210.liq_1pct_5m')
        self.addDailyData(self.liq_sqrt_10m, 'sli_0210.liq_sqrt_10m')
        self.addDailyData(self.liq_sqrt_2m, 'sli_0210.liq_sqrt_2m')
        self.addDailyData(self.liq_sqrt_5m, 'sli_0210.liq_sqrt_5m')
        self.addDailyData(self.prob_down_1m, 'sli_0210.prob_down_1m')
        self.addDailyData(self.prob_down_30m, 'sli_0210.prob_down_30m')
        self.addDailyData(self.prob_down_5m, 'sli_0210.prob_down_5m')
        self.addDailyData(self.prob_down_close30_1m, 'sli_0210.prob_down_close30_1m')
        self.addDailyData(self.prob_down_close30_5m, 'sli_0210.prob_down_close30_5m')
        self.addDailyData(self.prob_down_open30_1m, 'sli_0210.prob_down_open30_1m')
        self.addDailyData(self.prob_down_open30_5m, 'sli_0210.prob_down_open30_5m')
        self.addDailyData(self.prob_up_1m, 'sli_0210.prob_up_1m')
        self.addDailyData(self.prob_up_30m, 'sli_0210.prob_up_30m')
        self.addDailyData(self.prob_up_5m, 'sli_0210.prob_up_5m')
        self.addDailyData(self.prob_up_close30_1m, 'sli_0210.prob_up_close30_1m')
        self.addDailyData(self.prob_up_close30_5m, 'sli_0210.prob_up_close30_5m')
        self.addDailyData(self.prob_up_open30_1m, 'sli_0210.prob_up_open30_1m')
        self.addDailyData(self.prob_up_open30_5m, 'sli_0210.prob_up_open30_5m')
        self.addDailyData(self.rev_basic_1m, 'sli_0210.rev_basic_1m')
        self.addDailyData(self.rev_basic_30m, 'sli_0210.rev_basic_30m')
        self.addDailyData(self.rev_basic_5m, 'sli_0210.rev_basic_5m')
        self.addDailyData(self.rev_exopen_1m, 'sli_0210.rev_exopen_1m')
        self.addDailyData(self.rev_exopen_30m, 'sli_0210.rev_exopen_30m')
        self.addDailyData(self.rev_exopen_5m, 'sli_0210.rev_exopen_5m')
        self.addDailyData(self.rev_hf_1m, 'sli_0210.rev_hf_1m')
        self.addDailyData(self.rev_hf_30m, 'sli_0210.rev_hf_30m')
        self.addDailyData(self.rev_hf_5m, 'sli_0210.rev_hf_5m')
        self.addDailyData(self.rev_mom_1m, 'sli_0210.rev_mom_1m')
        self.addDailyData(self.rev_mom_30m, 'sli_0210.rev_mom_30m')
        self.addDailyData(self.rev_mom_5m, 'sli_0210.rev_mom_5m')
        self.addDailyData(self.rev_open_1m, 'sli_0210.rev_open_1m')
        self.addDailyData(self.rev_open_30m, 'sli_0210.rev_open_30m')
        self.addDailyData(self.rev_open_5m, 'sli_0210.rev_open_5m')
        self.addDailyData(self.rev_per_1m, 'sli_0210.rev_per_1m')
        self.addDailyData(self.rev_per_30m, 'sli_0210.rev_per_30m')
        self.addDailyData(self.rev_per_5m, 'sli_0210.rev_per_5m')
        self.addDailyData(self.rev_per_close30_1m, 'sli_0210.rev_per_close30_1m')
        self.addDailyData(self.rev_per_close30_5m, 'sli_0210.rev_per_close30_5m')
        self.addDailyData(self.rev_per_open30_1m, 'sli_0210.rev_per_open30_1m')
        self.addDailyData(self.rev_per_open30_5m, 'sli_0210.rev_per_open30_5m')
        self.addDailyData(self.rev_rev_1m, 'sli_0210.rev_rev_1m')
        self.addDailyData(self.rev_rev_30m, 'sli_0210.rev_rev_30m')
        self.addDailyData(self.rev_rev_5m, 'sli_0210.rev_rev_5m')
        self.addDailyData(self.rev_struct7_1m, 'sli_0210.rev_struct7_1m')
        self.addDailyData(self.rev_struct7_30m, 'sli_0210.rev_struct7_30m')
        self.addDailyData(self.rev_struct7_5m, 'sli_0210.rev_struct7_5m')
        self.addDailyData(self.rev_struct_10m, 'sli_0210.rev_struct_10m')
        self.addDailyData(self.rev_struct_30m, 'sli_0210.rev_struct_30m')
        self.addDailyData(self.rev_struct_60m, 'sli_0210.rev_struct_60m')
        self.addDailyData(self.rev_time_10m, 'sli_0210.rev_time_10m')
        self.addDailyData(self.rev_time_30m, 'sli_0210.rev_time_30m')
        self.addDailyData(self.rev_time_60m, 'sli_0210.rev_time_60m')
        self.addDailyData(self.var1pct_1m, 'sli_0210.var1pct_1m')
        self.addDailyData(self.var1pct_30m, 'sli_0210.var1pct_30m')
        self.addDailyData(self.var1pct_5m, 'sli_0210.var1pct_5m')
        self.addDailyData(self.var1pct_close30_1m, 'sli_0210.var1pct_close30_1m')
        self.addDailyData(self.var1pct_close30_5m, 'sli_0210.var1pct_close30_5m')
        self.addDailyData(self.var1pct_open30_1m, 'sli_0210.var1pct_open30_1m')
        self.addDailyData(self.var1pct_open30_5m, 'sli_0210.var1pct_open30_5m')
        self.addDailyData(self.vol_1m, 'sli_0210.vol_1m')
        self.addDailyData(self.vol_30m, 'sli_0210.vol_30m')
        self.addDailyData(self.vol_5m, 'sli_0210.vol_5m')
        self.addDailyData(self.vol_close30_1m, 'sli_0210.vol_close30_1m')
        self.addDailyData(self.vol_close30_5m, 'sli_0210.vol_close30_5m')
        self.addDailyData(self.vol_open30_1m, 'sli_0210.vol_open30_1m')
        self.addDailyData(self.vol_open30_5m, 'sli_0210.vol_open30_5m')
        return

    def loadDay(self, di):
        pass
