from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrSli0213(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.amt_entropy_1m = NIO_MATRIX()
        self.amt_entropy_30m = NIO_MATRIX()
        self.amt_entropy_5m = NIO_MATRIX()
        self.amt_gini_1m = NIO_MATRIX()
        self.amt_gini_30m = NIO_MATRIX()
        self.amt_gini_5m = NIO_MATRIX()
        self.amt_kurt_1m = NIO_MATRIX()
        self.amt_kurt_30m = NIO_MATRIX()
        self.amt_kurt_5m = NIO_MATRIX()
        self.liq_1pct_1m_kurt = NIO_MATRIX()
        self.liq_1pct_1m_mean = NIO_MATRIX()
        self.liq_1pct_1m_skew = NIO_MATRIX()
        self.liq_1pct_1m_var = NIO_MATRIX()
        self.liq_1pct_30m_kurt = NIO_MATRIX()
        self.liq_1pct_30m_mean = NIO_MATRIX()
        self.liq_1pct_30m_skew = NIO_MATRIX()
        self.liq_1pct_30m_var = NIO_MATRIX()
        self.liq_1pct_5m_kurt = NIO_MATRIX()
        self.liq_1pct_5m_mean = NIO_MATRIX()
        self.liq_1pct_5m_skew = NIO_MATRIX()
        self.liq_1pct_5m_var = NIO_MATRIX()
        self.liq_sqrt_1m_kurt = NIO_MATRIX()
        self.liq_sqrt_1m_mean = NIO_MATRIX()
        self.liq_sqrt_1m_skew = NIO_MATRIX()
        self.liq_sqrt_1m_var = NIO_MATRIX()
        self.liq_sqrt_30m_kurt = NIO_MATRIX()
        self.liq_sqrt_30m_mean = NIO_MATRIX()
        self.liq_sqrt_30m_skew = NIO_MATRIX()
        self.liq_sqrt_30m_var = NIO_MATRIX()
        self.liq_sqrt_5m_kurt = NIO_MATRIX()
        self.liq_sqrt_5m_mean = NIO_MATRIX()
        self.liq_sqrt_5m_skew = NIO_MATRIX()
        self.liq_sqrt_5m_var = NIO_MATRIX()
        self.price_energy_1m_kurt = NIO_MATRIX()
        self.price_energy_1m_mean = NIO_MATRIX()
        self.price_energy_1m_skew = NIO_MATRIX()
        self.price_energy_1m_var = NIO_MATRIX()
        self.price_energy_30m_kurt = NIO_MATRIX()
        self.price_energy_30m_mean = NIO_MATRIX()
        self.price_energy_30m_skew = NIO_MATRIX()
        self.price_energy_30m_var = NIO_MATRIX()
        self.price_energy_5m_kurt = NIO_MATRIX()
        self.price_energy_5m_mean = NIO_MATRIX()
        self.price_energy_5m_skew = NIO_MATRIX()
        self.price_energy_5m_var = NIO_MATRIX()
        self.tvma_1m_kurt = NIO_MATRIX()
        self.tvma_1m_mean = NIO_MATRIX()
        self.tvma_1m_skew = NIO_MATRIX()
        self.tvma_1m_var = NIO_MATRIX()
        self.tvma_30m_kurt = NIO_MATRIX()
        self.tvma_30m_mean = NIO_MATRIX()
        self.tvma_30m_skew = NIO_MATRIX()
        self.tvma_30m_var = NIO_MATRIX()
        self.tvma_5m_kurt = NIO_MATRIX()
        self.tvma_5m_mean = NIO_MATRIX()
        self.tvma_5m_skew = NIO_MATRIX()
        self.tvma_5m_var = NIO_MATRIX()
        self.vol_energy_1m_kurt = NIO_MATRIX()
        self.vol_energy_1m_mean = NIO_MATRIX()
        self.vol_energy_1m_skew = NIO_MATRIX()
        self.vol_energy_1m_var = NIO_MATRIX()
        self.vol_energy_30m_kurt = NIO_MATRIX()
        self.vol_energy_30m_mean = NIO_MATRIX()
        self.vol_energy_30m_skew = NIO_MATRIX()
        self.vol_energy_30m_var = NIO_MATRIX()
        self.vol_energy_5m_kurt = NIO_MATRIX()
        self.vol_energy_5m_mean = NIO_MATRIX()
        self.vol_energy_5m_skew = NIO_MATRIX()
        self.vol_energy_5m_var = NIO_MATRIX()
        self.vwap_dev_1m_kurt = NIO_MATRIX()
        self.vwap_dev_1m_mean = NIO_MATRIX()
        self.vwap_dev_1m_skew = NIO_MATRIX()
        self.vwap_dev_1m_var = NIO_MATRIX()
        self.vwap_dev_30m_kurt = NIO_MATRIX()
        self.vwap_dev_30m_mean = NIO_MATRIX()
        self.vwap_dev_30m_skew = NIO_MATRIX()
        self.vwap_dev_30m_var = NIO_MATRIX()
        self.vwap_dev_5m_kurt = NIO_MATRIX()
        self.vwap_dev_5m_mean = NIO_MATRIX()
        self.vwap_dev_5m_skew = NIO_MATRIX()
        self.vwap_dev_5m_var = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.amt_entropy_1m, 'sli_0213.amt_entropy_1m')
        self.addDailyData(self.amt_entropy_30m, 'sli_0213.amt_entropy_30m')
        self.addDailyData(self.amt_entropy_5m, 'sli_0213.amt_entropy_5m')
        self.addDailyData(self.amt_gini_1m, 'sli_0213.amt_gini_1m')
        self.addDailyData(self.amt_gini_30m, 'sli_0213.amt_gini_30m')
        self.addDailyData(self.amt_gini_5m, 'sli_0213.amt_gini_5m')
        self.addDailyData(self.amt_kurt_1m, 'sli_0213.amt_kurt_1m')
        self.addDailyData(self.amt_kurt_30m, 'sli_0213.amt_kurt_30m')
        self.addDailyData(self.amt_kurt_5m, 'sli_0213.amt_kurt_5m')
        self.addDailyData(self.liq_1pct_1m_kurt, 'sli_0213.liq_1pct_1m_kurt')
        self.addDailyData(self.liq_1pct_1m_mean, 'sli_0213.liq_1pct_1m_mean')
        self.addDailyData(self.liq_1pct_1m_skew, 'sli_0213.liq_1pct_1m_skew')
        self.addDailyData(self.liq_1pct_1m_var, 'sli_0213.liq_1pct_1m_var')
        self.addDailyData(self.liq_1pct_30m_kurt, 'sli_0213.liq_1pct_30m_kurt')
        self.addDailyData(self.liq_1pct_30m_mean, 'sli_0213.liq_1pct_30m_mean')
        self.addDailyData(self.liq_1pct_30m_skew, 'sli_0213.liq_1pct_30m_skew')
        self.addDailyData(self.liq_1pct_30m_var, 'sli_0213.liq_1pct_30m_var')
        self.addDailyData(self.liq_1pct_5m_kurt, 'sli_0213.liq_1pct_5m_kurt')
        self.addDailyData(self.liq_1pct_5m_mean, 'sli_0213.liq_1pct_5m_mean')
        self.addDailyData(self.liq_1pct_5m_skew, 'sli_0213.liq_1pct_5m_skew')
        self.addDailyData(self.liq_1pct_5m_var, 'sli_0213.liq_1pct_5m_var')
        self.addDailyData(self.liq_sqrt_1m_kurt, 'sli_0213.liq_sqrt_1m_kurt')
        self.addDailyData(self.liq_sqrt_1m_mean, 'sli_0213.liq_sqrt_1m_mean')
        self.addDailyData(self.liq_sqrt_1m_skew, 'sli_0213.liq_sqrt_1m_skew')
        self.addDailyData(self.liq_sqrt_1m_var, 'sli_0213.liq_sqrt_1m_var')
        self.addDailyData(self.liq_sqrt_30m_kurt, 'sli_0213.liq_sqrt_30m_kurt')
        self.addDailyData(self.liq_sqrt_30m_mean, 'sli_0213.liq_sqrt_30m_mean')
        self.addDailyData(self.liq_sqrt_30m_skew, 'sli_0213.liq_sqrt_30m_skew')
        self.addDailyData(self.liq_sqrt_30m_var, 'sli_0213.liq_sqrt_30m_var')
        self.addDailyData(self.liq_sqrt_5m_kurt, 'sli_0213.liq_sqrt_5m_kurt')
        self.addDailyData(self.liq_sqrt_5m_mean, 'sli_0213.liq_sqrt_5m_mean')
        self.addDailyData(self.liq_sqrt_5m_skew, 'sli_0213.liq_sqrt_5m_skew')
        self.addDailyData(self.liq_sqrt_5m_var, 'sli_0213.liq_sqrt_5m_var')
        self.addDailyData(self.price_energy_1m_kurt, 'sli_0213.price_energy_1m_kurt')
        self.addDailyData(self.price_energy_1m_mean, 'sli_0213.price_energy_1m_mean')
        self.addDailyData(self.price_energy_1m_skew, 'sli_0213.price_energy_1m_skew')
        self.addDailyData(self.price_energy_1m_var, 'sli_0213.price_energy_1m_var')
        self.addDailyData(self.price_energy_30m_kurt, 'sli_0213.price_energy_30m_kurt')
        self.addDailyData(self.price_energy_30m_mean, 'sli_0213.price_energy_30m_mean')
        self.addDailyData(self.price_energy_30m_skew, 'sli_0213.price_energy_30m_skew')
        self.addDailyData(self.price_energy_30m_var, 'sli_0213.price_energy_30m_var')
        self.addDailyData(self.price_energy_5m_kurt, 'sli_0213.price_energy_5m_kurt')
        self.addDailyData(self.price_energy_5m_mean, 'sli_0213.price_energy_5m_mean')
        self.addDailyData(self.price_energy_5m_skew, 'sli_0213.price_energy_5m_skew')
        self.addDailyData(self.price_energy_5m_var, 'sli_0213.price_energy_5m_var')
        self.addDailyData(self.tvma_1m_kurt, 'sli_0213.tvma_1m_kurt')
        self.addDailyData(self.tvma_1m_mean, 'sli_0213.tvma_1m_mean')
        self.addDailyData(self.tvma_1m_skew, 'sli_0213.tvma_1m_skew')
        self.addDailyData(self.tvma_1m_var, 'sli_0213.tvma_1m_var')
        self.addDailyData(self.tvma_30m_kurt, 'sli_0213.tvma_30m_kurt')
        self.addDailyData(self.tvma_30m_mean, 'sli_0213.tvma_30m_mean')
        self.addDailyData(self.tvma_30m_skew, 'sli_0213.tvma_30m_skew')
        self.addDailyData(self.tvma_30m_var, 'sli_0213.tvma_30m_var')
        self.addDailyData(self.tvma_5m_kurt, 'sli_0213.tvma_5m_kurt')
        self.addDailyData(self.tvma_5m_mean, 'sli_0213.tvma_5m_mean')
        self.addDailyData(self.tvma_5m_skew, 'sli_0213.tvma_5m_skew')
        self.addDailyData(self.tvma_5m_var, 'sli_0213.tvma_5m_var')
        self.addDailyData(self.vol_energy_1m_kurt, 'sli_0213.vol_energy_1m_kurt')
        self.addDailyData(self.vol_energy_1m_mean, 'sli_0213.vol_energy_1m_mean')
        self.addDailyData(self.vol_energy_1m_skew, 'sli_0213.vol_energy_1m_skew')
        self.addDailyData(self.vol_energy_1m_var, 'sli_0213.vol_energy_1m_var')
        self.addDailyData(self.vol_energy_30m_kurt, 'sli_0213.vol_energy_30m_kurt')
        self.addDailyData(self.vol_energy_30m_mean, 'sli_0213.vol_energy_30m_mean')
        self.addDailyData(self.vol_energy_30m_skew, 'sli_0213.vol_energy_30m_skew')
        self.addDailyData(self.vol_energy_30m_var, 'sli_0213.vol_energy_30m_var')
        self.addDailyData(self.vol_energy_5m_kurt, 'sli_0213.vol_energy_5m_kurt')
        self.addDailyData(self.vol_energy_5m_mean, 'sli_0213.vol_energy_5m_mean')
        self.addDailyData(self.vol_energy_5m_skew, 'sli_0213.vol_energy_5m_skew')
        self.addDailyData(self.vol_energy_5m_var, 'sli_0213.vol_energy_5m_var')
        self.addDailyData(self.vwap_dev_1m_kurt, 'sli_0213.vwap_dev_1m_kurt')
        self.addDailyData(self.vwap_dev_1m_mean, 'sli_0213.vwap_dev_1m_mean')
        self.addDailyData(self.vwap_dev_1m_skew, 'sli_0213.vwap_dev_1m_skew')
        self.addDailyData(self.vwap_dev_1m_var, 'sli_0213.vwap_dev_1m_var')
        self.addDailyData(self.vwap_dev_30m_kurt, 'sli_0213.vwap_dev_30m_kurt')
        self.addDailyData(self.vwap_dev_30m_mean, 'sli_0213.vwap_dev_30m_mean')
        self.addDailyData(self.vwap_dev_30m_skew, 'sli_0213.vwap_dev_30m_skew')
        self.addDailyData(self.vwap_dev_30m_var, 'sli_0213.vwap_dev_30m_var')
        self.addDailyData(self.vwap_dev_5m_kurt, 'sli_0213.vwap_dev_5m_kurt')
        self.addDailyData(self.vwap_dev_5m_mean, 'sli_0213.vwap_dev_5m_mean')
        self.addDailyData(self.vwap_dev_5m_skew, 'sli_0213.vwap_dev_5m_skew')
        self.addDailyData(self.vwap_dev_5m_var, 'sli_0213.vwap_dev_5m_var')
        return

    def loadDay(self, di):
        pass
