from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrFguo2(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.afternoon_net_buy = NIO_MATRIX()
        self.amihud_illiquidity = NIO_MATRIX()
        self.amount_per_trade = NIO_MATRIX()
        self.avg_trade_amount = NIO_MATRIX()
        self.avg_trade_volume = NIO_MATRIX()
        self.buy_amount_ratio = NIO_MATRIX()
        self.buy_avg_amount = NIO_MATRIX()
        self.buy_sell_amount_ratio = NIO_MATRIX()
        self.buy_sell_avg_ratio = NIO_MATRIX()
        self.buy_sell_count_ratio = NIO_MATRIX()
        self.buy_sell_volume_ratio = NIO_MATRIX()
        self.buy_trade_count_ratio = NIO_MATRIX()
        self.cancel_ratio = NIO_MATRIX()
        self.cancel_volume_ratio = NIO_MATRIX()
        self.close_30min_large_ratio = NIO_MATRIX()
        self.close_30min_net_buy = NIO_MATRIX()
        self.close_vs_vwap = NIO_MATRIX()
        self.consecutive_buy_max = NIO_MATRIX()
        self.consecutive_sell_max = NIO_MATRIX()
        self.fill_ratio = NIO_MATRIX()
        self.high_vs_vwap = NIO_MATRIX()
        self.intraday_volatility = NIO_MATRIX()
        self.kyle_lambda = NIO_MATRIX()
        self.large_avg_vs_total = NIO_MATRIX()
        self.large_buy_ratio = NIO_MATRIX()
        self.large_net_buy = NIO_MATRIX()
        self.large_order_count = NIO_MATRIX()
        self.large_order_ratio = NIO_MATRIX()
        self.large_sell_ratio = NIO_MATRIX()
        self.large_small_amount_ratio = NIO_MATRIX()
        self.large_trade_avg_amount = NIO_MATRIX()
        self.low_vs_vwap = NIO_MATRIX()
        self.median_trade_amount = NIO_MATRIX()
        self.morning_net_buy = NIO_MATRIX()
        self.net_buy_ratio = NIO_MATRIX()
        self.net_buy_volume_ratio = NIO_MATRIX()
        self.open_30min_large_ratio = NIO_MATRIX()
        self.open_30min_net_buy = NIO_MATRIX()
        self.open_close_buy_diff = NIO_MATRIX()
        self.open_position = NIO_MATRIX()
        self.open_vs_vwap = NIO_MATRIX()
        self.price_close = NIO_MATRIX()
        self.price_high = NIO_MATRIX()
        self.price_low = NIO_MATRIX()
        self.price_open = NIO_MATRIX()
        self.price_position = NIO_MATRIX()
        self.price_range = NIO_MATRIX()
        self.retail_vs_institution = NIO_MATRIX()
        self.return_daily = NIO_MATRIX()
        self.sell_amount_ratio = NIO_MATRIX()
        self.sell_avg_amount = NIO_MATRIX()
        self.side_switch_count = NIO_MATRIX()
        self.small_avg_vs_total = NIO_MATRIX()
        self.small_order_ratio = NIO_MATRIX()
        self.small_trade_avg_amount = NIO_MATRIX()
        self.smart_money_flow = NIO_MATRIX()
        self.total_amount = NIO_MATRIX()
        self.total_volume = NIO_MATRIX()
        self.trade_amount_kurt = NIO_MATRIX()
        self.trade_amount_skew = NIO_MATRIX()
        self.trade_amount_std = NIO_MATRIX()
        self.trade_count = NIO_MATRIX()
        self.trade_size_dispersion = NIO_MATRIX()
        self.unknown_side_ratio = NIO_MATRIX()
        self.volume_concentration = NIO_MATRIX()
        self.volume_per_trade = NIO_MATRIX()
        self.volume_volatility = NIO_MATRIX()
        self.vwap = NIO_MATRIX()
        self.xlarge_order_ratio = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.afternoon_net_buy, 'fguo_1224_trade.afternoon_net_buy')
        self.addDailyData(self.amihud_illiquidity, 'fguo_1224_trade.amihud_illiquidity')
        self.addDailyData(self.amount_per_trade, 'fguo_1224_trade.amount_per_trade')
        self.addDailyData(self.avg_trade_amount, 'fguo_1224_trade.avg_trade_amount')
        self.addDailyData(self.avg_trade_volume, 'fguo_1224_trade.avg_trade_volume')
        self.addDailyData(self.buy_amount_ratio, 'fguo_1224_trade.buy_amount_ratio')
        self.addDailyData(self.buy_avg_amount, 'fguo_1224_trade.buy_avg_amount')
        self.addDailyData(self.buy_sell_amount_ratio, 'fguo_1224_trade.buy_sell_amount_ratio')
        self.addDailyData(self.buy_sell_avg_ratio, 'fguo_1224_trade.buy_sell_avg_ratio')
        self.addDailyData(self.buy_sell_count_ratio, 'fguo_1224_trade.buy_sell_count_ratio')
        self.addDailyData(self.buy_sell_volume_ratio, 'fguo_1224_trade.buy_sell_volume_ratio')
        self.addDailyData(self.buy_trade_count_ratio, 'fguo_1224_trade.buy_trade_count_ratio')
        self.addDailyData(self.cancel_ratio, 'fguo_1224_trade.cancel_ratio')
        self.addDailyData(self.cancel_volume_ratio, 'fguo_1224_trade.cancel_volume_ratio')
        self.addDailyData(self.close_30min_large_ratio, 'fguo_1224_trade.close_30min_large_ratio')
        self.addDailyData(self.close_30min_net_buy, 'fguo_1224_trade.close_30min_net_buy')
        self.addDailyData(self.close_vs_vwap, 'fguo_1224_trade.close_vs_vwap')
        self.addDailyData(self.consecutive_buy_max, 'fguo_1224_trade.consecutive_buy_max')
        self.addDailyData(self.consecutive_sell_max, 'fguo_1224_trade.consecutive_sell_max')
        self.addDailyData(self.fill_ratio, 'fguo_1224_trade.fill_ratio')
        self.addDailyData(self.high_vs_vwap, 'fguo_1224_trade.high_vs_vwap')
        self.addDailyData(self.intraday_volatility, 'fguo_1224_trade.intraday_volatility')
        self.addDailyData(self.kyle_lambda, 'fguo_1224_trade.kyle_lambda')
        self.addDailyData(self.large_avg_vs_total, 'fguo_1224_trade.large_avg_vs_total')
        self.addDailyData(self.large_buy_ratio, 'fguo_1224_trade.large_buy_ratio')
        self.addDailyData(self.large_net_buy, 'fguo_1224_trade.large_net_buy')
        self.addDailyData(self.large_order_count, 'fguo_1224_trade.large_order_count')
        self.addDailyData(self.large_order_ratio, 'fguo_1224_trade.large_order_ratio')
        self.addDailyData(self.large_sell_ratio, 'fguo_1224_trade.large_sell_ratio')
        self.addDailyData(self.large_small_amount_ratio, 'fguo_1224_trade.large_small_amount_ratio')
        self.addDailyData(self.large_trade_avg_amount, 'fguo_1224_trade.large_trade_avg_amount')
        self.addDailyData(self.low_vs_vwap, 'fguo_1224_trade.low_vs_vwap')
        self.addDailyData(self.median_trade_amount, 'fguo_1224_trade.median_trade_amount')
        self.addDailyData(self.morning_net_buy, 'fguo_1224_trade.morning_net_buy')
        self.addDailyData(self.net_buy_ratio, 'fguo_1224_trade.net_buy_ratio')
        self.addDailyData(self.net_buy_volume_ratio, 'fguo_1224_trade.net_buy_volume_ratio')
        self.addDailyData(self.open_30min_large_ratio, 'fguo_1224_trade.open_30min_large_ratio')
        self.addDailyData(self.open_30min_net_buy, 'fguo_1224_trade.open_30min_net_buy')
        self.addDailyData(self.open_close_buy_diff, 'fguo_1224_trade.open_close_buy_diff')
        self.addDailyData(self.open_position, 'fguo_1224_trade.open_position')
        self.addDailyData(self.open_vs_vwap, 'fguo_1224_trade.open_vs_vwap')
        self.addDailyData(self.price_close, 'fguo_1224_trade.price_close')
        self.addDailyData(self.price_high, 'fguo_1224_trade.price_high')
        self.addDailyData(self.price_low, 'fguo_1224_trade.price_low')
        self.addDailyData(self.price_open, 'fguo_1224_trade.price_open')
        self.addDailyData(self.price_position, 'fguo_1224_trade.price_position')
        self.addDailyData(self.price_range, 'fguo_1224_trade.price_range')
        self.addDailyData(self.retail_vs_institution, 'fguo_1224_trade.retail_vs_institution')
        self.addDailyData(self.return_daily, 'fguo_1224_trade.return_daily')
        self.addDailyData(self.sell_amount_ratio, 'fguo_1224_trade.sell_amount_ratio')
        self.addDailyData(self.sell_avg_amount, 'fguo_1224_trade.sell_avg_amount')
        self.addDailyData(self.side_switch_count, 'fguo_1224_trade.side_switch_count')
        self.addDailyData(self.small_avg_vs_total, 'fguo_1224_trade.small_avg_vs_total')
        self.addDailyData(self.small_order_ratio, 'fguo_1224_trade.small_order_ratio')
        self.addDailyData(self.small_trade_avg_amount, 'fguo_1224_trade.small_trade_avg_amount')
        self.addDailyData(self.smart_money_flow, 'fguo_1224_trade.smart_money_flow')
        self.addDailyData(self.total_amount, 'fguo_1224_trade.total_amount')
        self.addDailyData(self.total_volume, 'fguo_1224_trade.total_volume')
        self.addDailyData(self.trade_amount_kurt, 'fguo_1224_trade.trade_amount_kurt')
        self.addDailyData(self.trade_amount_skew, 'fguo_1224_trade.trade_amount_skew')
        self.addDailyData(self.trade_amount_std, 'fguo_1224_trade.trade_amount_std')
        self.addDailyData(self.trade_count, 'fguo_1224_trade.trade_count')
        self.addDailyData(self.trade_size_dispersion, 'fguo_1224_trade.trade_size_dispersion')
        self.addDailyData(self.unknown_side_ratio, 'fguo_1224_trade.unknown_side_ratio')
        self.addDailyData(self.volume_concentration, 'fguo_1224_trade.volume_concentration')
        self.addDailyData(self.volume_per_trade, 'fguo_1224_trade.volume_per_trade')
        self.addDailyData(self.volume_volatility, 'fguo_1224_trade.volume_volatility')
        self.addDailyData(self.vwap, 'fguo_1224_trade.vwap')
        self.addDailyData(self.xlarge_order_ratio, 'fguo_1224_trade.xlarge_order_ratio')
        return

    def loadDay(self, di):
        pass
