from gsim.utils.NioData import *
from gsim.data import DataManagerMapped
from gsim.data import DataRegistry as dr
from gsim.data import Universe as uv
from gsim.utils import Calendar
import numpy as np


class DmgrFguo5(DataManagerMapped):
    def __init__(self, ):
        DataManagerMapped.__init__(self, )
        self.auction_cancel_ratio = NIO_MATRIX()
        self.bb_sb_bs_ls = NIO_MATRIX()
        self.bb_sb_bs_ss = NIO_MATRIX()
        self.bb_sb_ss_ls = NIO_MATRIX()
        self.big_b_big_s_1p0_afo = NIO_MATRIX()
        self.big_b_big_s_1p0_bfc = NIO_MATRIX()
        self.bigbuy_1p0_afo = NIO_MATRIX()
        self.bigbuy_bigsell_1p0 = NIO_MATRIX()
        self.break_levels = NIO_MATRIX()
        self.buy_t_or_cp = NIO_MATRIX()
        self.buy_t_or_op1 = NIO_MATRIX()
        self.buy_t_or_op2 = NIO_MATRIX()
        self.buy_w_or_op1 = NIO_MATRIX()
        self.corr_pm = NIO_MATRIX()
        self.corr_pv = NIO_MATRIX()
        self.corr_pvpm = NIO_MATRIX()
        self.crowd_fftv_20_3s = NIO_MATRIX()
        self.crowd_fftv_5 = NIO_MATRIX()
        self.crowd_fftv_50 = NIO_MATRIX()
        self.hp_deal_ratio = NIO_MATRIX()
        self.hp_vol_ratio = NIO_MATRIX()
        self.limit_buy_limit_or = NIO_MATRIX()
        self.lp_apb_ratio = NIO_MATRIX()
        self.market_b_limit_b_or = NIO_MATRIX()
        self.market_b_limit_s_or = NIO_MATRIX()
        self.market_buy_market_or = NIO_MATRIX()
        self.market_limit_or = NIO_MATRIX()
        self.market_or = NIO_MATRIX()
        self.market_s_limit_b_or = NIO_MATRIX()
        self.market_s_limit_s_or = NIO_MATRIX()
        self.normal_big_br_open = NIO_MATRIX()
        self.normal_big_buy_ratio = NIO_MATRIX()
        self.order_island_buy_mu = NIO_MATRIX()
        self.order_island_buy_sd = NIO_MATRIX()
        self.order_island_sell_mu = NIO_MATRIX()
        self.order_island_sell_sd = NIO_MATRIX()
        self.ret_open2_al1 = NIO_MATRIX()
        self.sb_sb_bs_ls_bfc = NIO_MATRIX()
        self.sb_sb_ss_ls = NIO_MATRIX()
        self.sell_t_or_cp = NIO_MATRIX()
        self.sell_t_or_op1 = NIO_MATRIX()
        self.sell_t_or_op2 = NIO_MATRIX()
        self.sell_w_or_op1 = NIO_MATRIX()
        self.short_b_long_s_1p0 = NIO_MATRIX()
        self.t_or_cp = NIO_MATRIX()
        self.t_or_op1 = NIO_MATRIX()
        self.t_or_op2 = NIO_MATRIX()
        self.tox = NIO_MATRIX()
        self.trade_c_buy_ratio = NIO_MATRIX()
        self.trade_c_sell_ratio = NIO_MATRIX()
        self.trade_imb_follow = NIO_MATRIX()
        self.trade_imb_isolate = NIO_MATRIX()
        self.trix = NIO_MATRIX()
        self.w_or_op1 = NIO_MATRIX()
        return

    def initialize(self, id, path, cfg):
        DataManagerMapped.initialize(self, id, path, cfg)
        self.addDailyData(self.auction_cancel_ratio, 'fguo_0105.auction_cancel_ratio')
        self.addDailyData(self.bb_sb_bs_ls, 'fguo_0105.bb_sb_bs_ls')
        self.addDailyData(self.bb_sb_bs_ss, 'fguo_0105.bb_sb_bs_ss')
        self.addDailyData(self.bb_sb_ss_ls, 'fguo_0105.bb_sb_ss_ls')
        self.addDailyData(self.big_b_big_s_1p0_afo, 'fguo_0105.big_b_big_s_1p0_afo')
        self.addDailyData(self.big_b_big_s_1p0_bfc, 'fguo_0105.big_b_big_s_1p0_bfc')
        self.addDailyData(self.bigbuy_1p0_afo, 'fguo_0105.bigbuy_1p0_afo')
        self.addDailyData(self.bigbuy_bigsell_1p0, 'fguo_0105.bigbuy_bigsell_1p0')
        self.addDailyData(self.break_levels, 'fguo_0105.break_levels')
        self.addDailyData(self.buy_t_or_cp, 'fguo_0105.buy_t_or_cp')
        self.addDailyData(self.buy_t_or_op1, 'fguo_0105.buy_t_or_op1')
        self.addDailyData(self.buy_t_or_op2, 'fguo_0105.buy_t_or_op2')
        self.addDailyData(self.buy_w_or_op1, 'fguo_0105.buy_w_or_op1')
        self.addDailyData(self.corr_pm, 'fguo_0105.corr_pm')
        self.addDailyData(self.corr_pv, 'fguo_0105.corr_pv')
        self.addDailyData(self.corr_pvpm, 'fguo_0105.corr_pvpm')
        self.addDailyData(self.crowd_fftv_20_3s, 'fguo_0105.crowd_fftv_20_3s')
        self.addDailyData(self.crowd_fftv_5, 'fguo_0105.crowd_fftv_5')
        self.addDailyData(self.crowd_fftv_50, 'fguo_0105.crowd_fftv_50')
        self.addDailyData(self.hp_deal_ratio, 'fguo_0105.hp_deal_ratio')
        self.addDailyData(self.hp_vol_ratio, 'fguo_0105.hp_vol_ratio')
        self.addDailyData(self.limit_buy_limit_or, 'fguo_0105.limit_buy_limit_or')
        self.addDailyData(self.lp_apb_ratio, 'fguo_0105.lp_apb_ratio')
        self.addDailyData(self.market_b_limit_b_or, 'fguo_0105.market_b_limit_b_or')
        self.addDailyData(self.market_b_limit_s_or, 'fguo_0105.market_b_limit_s_or')
        self.addDailyData(self.market_buy_market_or, 'fguo_0105.market_buy_market_or')
        self.addDailyData(self.market_limit_or, 'fguo_0105.market_limit_or')
        self.addDailyData(self.market_or, 'fguo_0105.market_or')
        self.addDailyData(self.market_s_limit_b_or, 'fguo_0105.market_s_limit_b_or')
        self.addDailyData(self.market_s_limit_s_or, 'fguo_0105.market_s_limit_s_or')
        self.addDailyData(self.normal_big_br_open, 'fguo_0105.normal_big_br_open')
        self.addDailyData(self.normal_big_buy_ratio, 'fguo_0105.normal_big_buy_ratio')
        self.addDailyData(self.order_island_buy_mu, 'fguo_0105.order_island_buy_mu')
        self.addDailyData(self.order_island_buy_sd, 'fguo_0105.order_island_buy_sd')
        self.addDailyData(self.order_island_sell_mu, 'fguo_0105.order_island_sell_mu')
        self.addDailyData(self.order_island_sell_sd, 'fguo_0105.order_island_sell_sd')
        self.addDailyData(self.ret_open2_al1, 'fguo_0105.ret_open2_al1')
        self.addDailyData(self.sb_sb_bs_ls_bfc, 'fguo_0105.sb_sb_bs_ls_bfc')
        self.addDailyData(self.sb_sb_ss_ls, 'fguo_0105.sb_sb_ss_ls')
        self.addDailyData(self.sell_t_or_cp, 'fguo_0105.sell_t_or_cp')
        self.addDailyData(self.sell_t_or_op1, 'fguo_0105.sell_t_or_op1')
        self.addDailyData(self.sell_t_or_op2, 'fguo_0105.sell_t_or_op2')
        self.addDailyData(self.sell_w_or_op1, 'fguo_0105.sell_w_or_op1')
        self.addDailyData(self.short_b_long_s_1p0, 'fguo_0105.short_b_long_s_1p0')
        self.addDailyData(self.t_or_cp, 'fguo_0105.t_or_cp')
        self.addDailyData(self.t_or_op1, 'fguo_0105.t_or_op1')
        self.addDailyData(self.t_or_op2, 'fguo_0105.t_or_op2')
        self.addDailyData(self.tox, 'fguo_0105.tox')
        self.addDailyData(self.trade_c_buy_ratio, 'fguo_0105.trade_c_buy_ratio')
        self.addDailyData(self.trade_c_sell_ratio, 'fguo_0105.trade_c_sell_ratio')
        self.addDailyData(self.trade_imb_follow, 'fguo_0105.trade_imb_follow')
        self.addDailyData(self.trade_imb_isolate, 'fguo_0105.trade_imb_isolate')
        self.addDailyData(self.trix, 'fguo_0105.trix')
        self.addDailyData(self.w_or_op1, 'fguo_0105.w_or_op1')
        return

    def loadDay(self, di):
        pass
